"""Build source-support clocks for HVCFF-6 without post-entry outcomes."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
import numpy as np,pandas as pd
from training import build_options_crowding_deleveraging_relay_support_v4 as base
from training import build_options_led_intrahour_absorption_support as intrahour
from training import preregister_high_volatility_confirmation_fracture_fade as prereg
from training.build_binance_aggtrade_microstructure import _write_gzip_csv
CLOCK=Path("data/high_volatility_confirmation_fracture_fade_clocks_2023_2026.csv.gz");CONTROL_DIR=Path("data/high_volatility_confirmation_fracture_fade_controls_2023_2026");RESULT=Path("results/high_volatility_confirmation_fracture_fade_support_2026-08-08.json");SPLITS=base.SPLITS;MIN={"train":8,"test":12,"eval":12,"final":8};CONTROLS=("no_high_volatility","no_level_fracture","no_price_shock","direction_flip");ECONOMIC_OUTCOMES_AUTHORIZED=False
COLUMNS=("candidate","control","split","block_start_time","decision_time","feature_available_time","entry_time","exit_time","side","bvol_close","prior_bvol_q60","prior_bvol_median","dvol_close","prior_dvol_q60","prior_dvol_median","normalized_level_fracture","prior_fracture_q60","block_return","prior_abs_block_q60")
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def chash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def features()->pd.DataFrame:
 v=intrahour.features().drop(columns=["price_valid"],errors="ignore");p=pd.read_csv(intrahour.PRICE_DIR/"btc_intrahour_path.csv.gz",compression="gzip");p.decision_time=pd.to_datetime(p.decision_time,utc=True,format="mixed");p.hour_open=pd.to_numeric(p.hour_open,errors="coerce");p.hour_close=pd.to_numeric(p.hour_close,errors="coerce");p["path_valid"]=p.source_valid.astype(str).str.lower().eq("true");j=v.merge(p[["decision_time","hour_open","hour_close","path_valid"]],on="decision_time",validate="one_to_one").sort_values("decision_time").reset_index(drop=True)
 for name in ("bvol","dvol"):
  values=j[f"{name}_close"].where(j.bvol_valid&j[f"{name}_close"].gt(0));j[f"prior_{name}_q60"]=values.shift(1).rolling(720,min_periods=672).quantile(.60);j[f"prior_{name}_median"]=values.shift(1).rolling(720,min_periods=672).quantile(.50)
 vol_valid=j.bvol_valid&np.isfinite(j[["bvol_close","dvol_close"]]).all(axis=1)&j[["bvol_close","dvol_close"]].gt(0).all(axis=1);price_valid=j.path_valid&np.isfinite(j[["hour_open","hour_close"]]).all(axis=1)&j[["hour_open","hour_close"]].gt(0).all(axis=1);source_valid=vol_valid&price_valid;consecutive=j.decision_time.diff().eq(pd.Timedelta(hours=1));j["eight_valid"]=source_valid.rolling(8,min_periods=8).sum().eq(8)&consecutive.rolling(7,min_periods=7).sum().eq(7);j["endpoint_valid"]=price_valid&price_valid.shift(7,fill_value=False)&j.decision_time.diff(7).eq(pd.Timedelta(hours=7));j["vol_current_valid"]=vol_valid;j["block_return"]=j.hour_close/j.hour_open.shift(7)-1;j["normalized_level_fracture"]=(j.bvol_close/j.prior_bvol_median).div(j.dvol_close/j.prior_dvol_median).apply(np.log).abs();b=j[j.decision_time.dt.hour.mod(8).eq(0)].copy().reset_index(drop=True);b["prior_fracture_q60"]=b.normalized_level_fracture.where(b.vol_current_valid).shift(1).rolling(270,min_periods=252).quantile(.60);b["prior_abs_block_q60"]=b.block_return.abs().where(b.endpoint_valid).shift(1).rolling(270,min_periods=252).quantile(.60);vals=["bvol_close","dvol_close","prior_bvol_median","prior_dvol_median","normalized_level_fracture","block_return"];b["block_valid"]=b.eight_valid&np.isfinite(b[vals]).all(axis=1)&b[["prior_bvol_median","prior_dvol_median"]].gt(0).all(axis=1);return b
def clock(f:pd.DataFrame,control:str="primary")->pd.DataFrame:
 vol=pd.Series(True,index=f.index) if control=="no_high_volatility" else f.bvol_close.ge(f.prior_bvol_q60)&f.dvol_close.ge(f.prior_dvol_q60);fracture=f.prior_fracture_q60.notna();fracture&=True if control=="no_level_fracture" else f.normalized_level_fracture.ge(f.prior_fracture_q60);shock=f.block_return.ne(0)&f.prior_abs_block_q60.notna();shock&=True if control=="no_price_shock" else f.block_return.abs().ge(f.prior_abs_block_q60);active=f.block_valid&vol&fracture&shock;rows=[]
 for i in f.index[active]:
  decision=pd.Timestamp(f.at[i,"decision_time"]);entry=decision+pd.Timedelta(minutes=5);exit_=entry+pd.Timedelta(hours=6);split=next((n for n,(s,e) in SPLITS.items() if entry>=s and exit_<=e),None)
  if split is None:continue
  side=-int(np.sign(f.at[i,"block_return"]));side=-side if control=="direction_flip" else side;rows.append({"candidate":"HVCFF-6","control":control,"split":split,"block_start_time":decision-pd.Timedelta(hours=8),"decision_time":decision,"feature_available_time":decision,"entry_time":entry,"exit_time":exit_,"side":side,"bvol_close":float(f.at[i,"bvol_close"]),"prior_bvol_q60":float(f.at[i,"prior_bvol_q60"]),"prior_bvol_median":float(f.at[i,"prior_bvol_median"]),"dvol_close":float(f.at[i,"dvol_close"]),"prior_dvol_q60":float(f.at[i,"prior_dvol_q60"]),"prior_dvol_median":float(f.at[i,"prior_dvol_median"]),"normalized_level_fracture":float(f.at[i,"normalized_level_fracture"]),"prior_fracture_q60":float(f.at[i,"prior_fracture_q60"]),"block_return":float(f.at[i,"block_return"]),"prior_abs_block_q60":float(f.at[i,"prior_abs_block_q60"])})
 return pd.DataFrame(rows,columns=COLUMNS)
def stats(c:pd.DataFrame,n:str)->dict:
 x=c[c.split.eq(n)]
 if x.empty:return {"events":0,"longs":0,"shorts":0,"minority_side_share":0.,"max_month_share":0.}
 lo=int(x.side.eq(1).sum());sh=int(x.side.eq(-1).sum());m=x.entry_time.dt.strftime("%Y-%m").value_counts();return {"events":len(x),"longs":lo,"shorts":sh,"minority_side_share":min(lo,sh)/len(x),"max_month_share":int(m.max())/len(x)}
def run()->dict:
 f=features();primary=clock(f);controls={n:clock(f,n) for n in CONTROLS};CLOCK.parent.mkdir(parents=True,exist_ok=True);CONTROL_DIR.mkdir(parents=True,exist_ok=True);_write_gzip_csv(primary,CLOCK)
 for n,x in controls.items():_write_gzip_csv(x,CONTROL_DIR/f"{n}.csv.gz")
 support={n:stats(primary,n) for n in SPLITS};checks={}
 for n,x in support.items():checks[f"{n}_minimum_events"]=x["events"]>=MIN[n];checks[f"{n}_side_balance"]=x["minority_side_share"]>=.2;checks[f"{n}_month_concentration"]=x["max_month_share"]<=.45
 reg=json.loads(prereg.DEFAULT_OUTPUT.read_text());vm=intrahour.NONPRICE_DIR/"manifest.json";pm=intrahour.PRICE_DIR/"manifest.json";passed=all(checks.values());core={"protocol_version":"hvcff_6_source_support_v1","policy_id":"HVCFF-6","preregistration":{"path":str(prereg.DEFAULT_OUTPUT),"sha256":sha(prereg.DEFAULT_OUTPUT),"manifest_hash":reg["manifest_hash"]},"source_manifests":{"volatility":{"path":str(vm),"sha256":sha(vm)},"completed_price":{"path":str(pm),"sha256":sha(pm)}},"completed_preentry_sources_opened":True,"postentry_return_pnl_execution_price_opened":False,"gross9_rows_opened":False,"clock":{"path":str(CLOCK),"sha256":sha(CLOCK),"rows":len(primary)},"controls":{n:{"path":str(CONTROL_DIR/f"{n}.csv.gz"),"sha256":sha(CONTROL_DIR/f"{n}.csv.gz"),"rows":len(x)} for n,x in controls.items()},"support":support,"support_checks":checks,"support_passed":passed,"advance_to_gross9_novelty":passed,"advance_to_economic_outcomes":ECONOMIC_OUTCOMES_AUTHORIZED,"decision":"pass_to_novelty" if passed else "terminal_source_support_reject"};r={**core,"manifest_hash":chash(core)};RESULT.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");return r
if __name__=="__main__":argparse.ArgumentParser().parse_args();r=run();print(json.dumps({"passed":r["support_passed"],"support":r["support"]},indent=2))
