"""Outcome-blind preregistration for HVERF-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVERF-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_roofing_filter_zero_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_roofing_filter_zero_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a canonical Ehlers 48/10 Roofing Filter crossing its nominal zero mean on completed four-hour BTC auctions marks a tradable cyclic upswing or downswing; follow the crossing direction for twenty-four hours.","side":"long on a strict nonpositive-to-positive filtered crossing; short on a strict nonnegative-to-negative crossing","why_distinct":"A two-pole high-pass removes slow trend and a two-pole Super Smoother removes aliasing noise before the zero crossing. It is not a moving-average crossover, bounded return or range oscillator, prior control, volume, flow, OI, funding, fitted outcome, or reused event set.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"band-limited four-hour price-cycle zero crossings are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Predictive And Successful Indicators (2013)","source":"https://easylanguagemastery.com/indicators/predictive-indicators/","fixed_definition":"close input; two-pole high-pass critical period 48 bars with 0.707 damping; two-pole Super Smoother period 10 bars with 1.414 damping; published coefficients and recursions; zero line","selection_use":"published input, periods, coefficients, recursion, and zero reference only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","high_pass":"published two-pole second-difference recursion, period 48","roofing_filter":"published period-10 Super Smoother applied to current and prior high-pass values","initialization":"after a gap, first two valid observations set high-pass and filter to zero; require 48 uninterrupted valid observations before eligibility","event":"strict crossing of the finite Roofing Filter through zero from the immediately prior finite value","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"high_pass_period":48,"super_smoother_period":10,"warmup_observations":48,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","raw_high_pass_cross","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_roofing_filter_definition_read":True,"repository_roofing_filter_candidate_found":False,"prior_filter_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Ehlers 48/10 Roofing Filter zero crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no periods, coefficients, initialization, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVERF preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
