"""Outcome-blind preregistration for HVVSR-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID='HVVSR-24';DEFAULT_OUTPUT=Path('results/high_volatility_variance_signature_reversal_relay_preregistration_2026-08-11.json')
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop('manifest_hash')
 c.update(protocol_version='high_volatility_variance_signature_reversal_relay_v1',policy_id=POLICY_ID,as_of_date='2026-08-11',
 mechanism={'claim':'When completed one-minute realized variance is unusually large relative to nonoverlapping five-minute realized variance during an already volatile BTC day, the excess high-frequency variation identifies short-horizon reversal noise rather than persistent displacement; fade the completed four-hour return for twenty-four hours.','side':'short a strictly positive completed four-hour return and long a strictly negative return, only on a fresh joint signature-and-variation tail onset','why_distinct':'HVVSR compares identical-price realized variance at two fixed sampling frequencies. It is not a single-scale volatility level, jump/bipower statistic, OHLC range estimator, sign-count metric, volume/flow/OI/funding feature, fitted outcome, reused event set, prior repair, or promoted control.','why_suited_to_volatile_regimes':'both five-minute trailing realized variation and the one-minute/five-minute variance signature ratio must occupy causal upper tails','why_low_gross9_overlap_is_plausible':'a sparse dual-tail multiscale sampling-frequency diagnostic at four-hour boundaries is absent from Gross9 primitives'},
 external_basis={'origin':'Hansen and Lunde, Realized Variance and Market Microstructure Noise','paper':'https://w4.stern.nyu.edu/salomon/docs/Hansen-Lunde.pdf','paper_sha256':'d745ba595974cc95c44e7c9752aa5bf0409e5c6eed274e0da1469b357ed0a2f4','support':'the volatility signature plot diagnoses sampling-frequency dependence and high-frequency microstructure contamination','selection_use':'fixed one-minute versus five-minute signature construction only; BTC direction, tails, onset, and holding application are untested; no incidence or outcomes'},
 features={'decision_grid':'every completed four-hour BTCUSDT boundary','window':'exact 1,440 coherent one-minute bars [T-24h,T)','one_minute_rv':'sum squared one-minute close-to-previous-close log returns, excluding the unavailable return before the window','five_minute_rv':'sum squared close-to-previous-close log returns of 288 exact nonoverlapping five-minute closes, excluding the unavailable return before the window','signature_ratio':'one_minute_rv/five_minute_rv, finite strict positive','realized_variation':'sqrt(five_minute_rv), finite strict positive','four_hour_return':'log(last one-minute close / first one-minute open over [T-4h,T)), finite strict nonzero','prior_ranks':'strict-prior midranks over at most 270 earlier source-valid decisions, minimum 180, current excluded','event':'signature rank>=0.80 and variation rank>=0.65 now, while immediately prior source-valid decision was not jointly eligible','recursive_reset':'all rolling windows, rank histories, and onset state reset after any invalid four-hour source block','no_imputation':True},
 clock={'feature_available':'completed four-hour boundary','entry':'exact BTCUSDT boundary+5m open','hold':'24 elapsed hours','reservation':'global half-open; exit first on equal open','gross_exposure':.5,'funding':'not a signal input; exact settlements only after novelty passes'},
 policy={'window_hours':24,'signature_rank_min':.80,'variation_rank_min':.65,'rank_history_decisions':270,'minimum_rank_history_decisions':180,'entry_delay_minutes':5,'hold_hours':24,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 diagnostic_controls={'names':['no_signature_gate','no_variation_gate','five_minute_return_continuation','one_bar_stale_onset','direction_flip','forced_long'],'cannot_be_promoted':True},
 source_plan={'bars':{'table':'bars_binance','symbol':'BTCUSDT','interval':'1m','columns':['ts','open','high','low','close'],'window':['2023-04-01T00:00:00Z','2026-08-01T00:00:00Z'],'read_after_preregistration':True},'execution_price':'sealed until source support and Gross9 novelty pass'},
 research_boundary={'variance_signature_definition_read':True,'repository_variance_signature_candidate_found':False,'prior_multiscale_volatility_outcomes_known':True,'prior_event_sets_reused':False,'prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock':False,'candidate_incidence_opened':False,'postentry_return_or_pnl_opened':False,'gross9_rows_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False,'promoted_prior_control':False,'selection_basis':'published variance-signature sampling-frequency diagnostic under the requested high-variation regime'},
 stopping_rule='Terminal first failure; no sampling frequencies, window, formula, ranks, onset, side, hold, clock, subset, control, or other repair.')
 return {**c,'manifest_hash':canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!='manifest_hash'}
 if v.get('manifest_hash')!=canonical_hash(core) or v!=build():raise RuntimeError('HVVSR-24 preregistration drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+'\n');print(a.output)
