"""Outcome-blind preregistration for HVCKS-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVCKS-24";DEFAULT_OUTPUT=Path("results/high_volatility_chande_kroll_stop_breakout_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_chande_kroll_stop_breakout_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a completed four-hour BTC close crossing outside both canonical Chande Kroll Stop lines confirms a volatility-adjusted trend breakout; follow the breakout side for twenty-four hours.","side":"long when close newly becomes strictly above both stop lines; short when close newly becomes strictly below both stop lines","why_distinct":"Chande Kroll Stop applies Wilder ATR to ten-bar extrema and then a second nine-bar extremum to two preliminary stop paths. It is not the single-stage Chandelier Exit, recursive Supertrend band, fixed channel, moving-average crossover, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the dual stop distance scales with causal true range and the completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse four-hour dual-stop exterior crossings are absent from Gross9 primitives"},
 external_basis={"origin":"Tushar Chande and Stanley Kroll; QuantConnect LEAN canonical implementation and TradingView interpretation","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/ChandeKrollStop.cs","signal_source":"https://www.tradingview.com/support/solutions/43000589105-chande-kroll-stop/","fixed_definition":"parameters 10,1,9; Wilder ATR(10); highStop=highestHigh(10)-ATR; lowStop=lowestLow(10)+ATR; ShortStop=highest(highStop,9); LongStop=lowest(lowStop,9); warmup 18 bars","selection_use":"published parameters, Wilder smoothing, two-stage stops, and close outside both lines direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","true_range":"max(high-low,abs(high-prior_close),abs(low-prior_close)) on uninterrupted valid bars","atr":"Wilder ATR(10), seeded by the simple mean of the first ten true ranges then recursively updated with alpha=1/10","preliminary_stops":"highest high over ten bars minus ATR, and lowest low over ten bars plus ATR","final_stops":"nine-bar rolling maximum of preliminary high stop and nine-bar rolling minimum of preliminary low stop","event":"current close newly strictly above both final stops from not above both, or newly strictly below both from not below both","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"atr_periods":10,"atr_multiplier":1.0,"stop_periods":9,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","preliminary_stop_cross","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_chande_kroll_stop_definition_read":True,"repository_chande_kroll_stop_candidate_found":False,"prior_chandelier_supertrend_channel_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Chande Kroll Stop(10,1,9) dual-line breakout under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no ATR/stop period, multiplier, smoothing, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVCKS preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
