"""Outcome-blind preregistration for HVSAUDCA-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_cross_structure_action_vote as gates
POLICY_ID="HVSAUDCA-8";DEFAULT_OUTPUT=Path("results/high_volatility_spot_underwater_causal_sign_adapter_preregistration_2026-08-18.json")
BASE={"preregistration":{"path":"results/high_volatility_spot_adverse_underwater_duration_relay_preregistration_2026-08-18.json","sha256":"6f65fe4632da0c714cf971a95d1be98fb28bb8ef2a4926188656ff58af676446"},"support":{"path":"results/high_volatility_spot_adverse_underwater_duration_relay_support_2026-08-18.json","sha256":"1fc578d0c95d12c4f9cea7da4ee0f712fc0546573c2e334011eb19e2ee55b27a"},"gross9":{"path":"results/high_volatility_spot_adverse_underwater_duration_relay_gross9_novelty_2026-08-18.json","sha256":"77a222777e6baf434260657baf9b1768745b42f0ac02bcc6b9ae321b028edc6c"},"clock":{"path":"data/high_volatility_spot_adverse_underwater_duration_relay_clocks_2023_2026.csv.gz","sha256":"2a7a893cdc2026227c00ba0a7622f35277c149498cd8413dd21e2d286eaf38d9"}}
def sha256(p:str|Path)->str:return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 g=gates.build();core={"protocol_version":"high_volatility_spot_underwater_causal_sign_adapter_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-18","singleton":True,"candidate_family":[POLICY_ID],"candidate_family_size":1,"source_incidence_opened":False,"current_candidate_outcomes_opened":False,"gross9_rows_opened":False,"base_artifacts":BASE,
 "mechanism":{"claim":"The predictive sign of spot directional-underwater events can change across volatile regimes. Use only fully matured prior base-event directional returns to causally decide whether the current immutable spot-duration side should be followed or inverted.","side":"base side multiplied by strict sign of the arithmetic mean of the latest at most 12 fully matured base-event gross log returns","why_distinct":"HVOER rotates generic 4h/12h experts only on winner changes. HVSAUDCA adapts the sign of a sparse path-duration event family at every eligible event using its own causally matured event labels, without future labels, stage resets, costs, funding, OI, premium, options, fitted thresholds, or promoted controls.","why_low_gross9_overlap_is_plausible":"immutable sparse HVSAUD event times retain passed Gross9 clock geometry while causal sign adaptation changes exposure"},
 "causal_label":{"value":"immutable base side times log(perpetual exit_open/entry_open)","maturity":"label may enter memory only when base exit_time<=current decision_time","memory":"latest at most 12 mature labels in global chronological order","minimum_labels":8,"score":"arithmetic mean gross log label; strict nonzero required","routing":"score>0 keeps base side; score<0 inverts base side; zero or insufficient memory is cash","forbidden":"current or immature label, costs, funding, equity, PnL, CAGR, MDD, stage reset, future-stage fit"},
 "policy":{"memory_labels":12,"minimum_mature_labels":8,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},"clock":{"event_times":"immutable HVSAUD-8 decisions, entries, exits","entry":"immutable D+5m","hold":"8 elapsed hours","funding":"not signal input; exact settlements after Gross9"},
 "stages":g["stages"],"source_support_gates":g["source_support_gates"],"gross9_novelty_gates":g["gross9_novelty_gates"],"economic_gates":g["economic_gates"],"source_plan":{"label_prices":"bars_binance BTCUSDT exact five-minute opens at base entry/exit timestamps, read after preregistration","current_candidate_execution_prices":"sealed until source and Gross9 pass"},
 "research_boundary":{"base_train_pass_test_failure_known":True,"base_event_level_trade_returns_opened":False,"exact_adapter_incidence_or_outcomes_known":False,"mature_counterfactual_labels_explicitly_authorized":True,"current_candidate_postentry_return_or_pnl_opened":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"classification":"exploratory causal online adaptation; not fresh confirmatory evidence","selection_basis":"regime-robust causal sign adaptation with fixed event memory"},
 "stopping_rule":"source including mature-label causality, Gross9, train/test/eval/final; terminal first failure; no base event, memory, minimum labels, label, maturity, score, tie, side, clock, hold, subset, threshold, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x!=build():raise RuntimeError("HVSAUDCA prereg drift")
 for a in BASE.values():
  if sha256(a["path"])!=a["sha256"]:raise RuntimeError("HVSAUDCA base drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
