"""Outcome-blind preregistration for HVBSRT-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVBSRT-8";DEFAULT_OUTPUT=Path("results/high_volatility_basis_regime_transition_relay_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c={"protocol_version":"high_volatility_basis_regime_transition_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"A completed hourly Binance perpetual-versus-spot basis residual crossing its causal seven-day center identifies a change in which venue is paying for immediacy. During elevated BTC variation, an unusually large crossing should relay in the new leveraged-demand direction for eight hours.","side":"strict sign of the new hourly mean log-basis residual","external_basis":{"perpetual_mechanics":"He, Manela, Ross and von Wachter, Fundamentals of Perpetual Futures (arXiv:2212.06888)","claim_used":"funding and arbitrage tether perpetuals to spot while demand shocks create basis deviations","adaptation":"causal hourly basis-center crossing and BTC high-variation gate are transparent unfitted implementation choices"},"why_distinct":"HVCBR ranks the final-two-hour basis change at three daily boundaries and trades convergence. HVCBFC ranks lagged spot-return to next-basis-change correlation and follows the eight-hour spot return. Premium candidates use the exchange premium-index candle. HVBSRT uses the sign transition of the directly aligned one-hour mean cash-perpetual price basis relative to its own strictly prior seven-day median, with no endpoint basis change, lead correlation, premium-index input, prior event set or promoted control.","why_suited_to_volatile_regimes":"completed prior-24h BTC variation must occupy its causal upper 35%","why_low_gross9_overlap_is_plausible":"fresh endogenous cash-perpetual basis regime transitions with eight-hour reservation are absent from Gross9"},
 "features":{"decision_grid":"every exact UTC hour H","aligned_hour":"60 exact timestamp-aligned coherent BTCUSDT bars_binance and bars_binance_spot one-minute rows [H-1h,H)","minute_log_basis":"log(perpetual close/spot close), finite","hourly_basis":"arithmetic mean of 60 minute log bases, finite strict nonzero","causal_center":"median hourly basis over the 168 exact source-valid hours ending strictly before [H-1h,H); minimum 144; current hour excluded","basis_residual":"hourly_basis minus causal center, finite strict nonzero","transition":"current residual sign differs from immediately previous consecutive source-valid hourly residual sign; missing previous rejects","residual_magnitude_rank":"strict-prior midrank of absolute residual over at most 2160 earlier source-valid hours, minimum 1440, current excluded; rank>=0.75","btc_variation":"sqrt(sum squared exact perpetual one-minute open-to-close log returns over [H-24h,H)), finite strict positive","variation_rank":"strict-prior midrank over at most 2160 earlier source-valid hours, minimum 1440, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"feature_available":"H after all completed source rows","entry":"exact BTCUSDT perpetual H+5m open","side":"new basis-residual sign","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements only after novelty","rv20":"q90 only after unchanged all-stage pass"},
 "policy":{"center_hours":168,"minimum_center_hours":144,"history_hours":2160,"minimum_history_hours":1440,"residual_rank_min":.75,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, held 5m favorable-then-adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_residual_tail","no_variation_gate","raw_basis_zero_cross","one_hour_stale_transition","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"tables":["bars_binance","bars_binance_spot"],"symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"perpetual_basis_mechanics_read":True,"repository_exact_causal_basis_center_transition_found":False,"prior_cash_basis_family_outcomes_known":True,"prior_event_sets_or_controls_reused":False,"prior_outcomes_used_to_set_formula_rank_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent basis-regime transition mechanism"},
 "stopping_rule":"terminal first failure; no source, center, transition, history, rank, variation, side, delay, hold, clock, subset, threshold, comparator, or control repair"};return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build() or x["outcomes_opened"] or x["source_incidence_opened"] or x["gross9_rows_opened"]:raise RuntimeError("HVBSRT prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
