"""Outcome-blind preregistration for HVPOCR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVPOCR-8";DEFAULT_OUTPUT=Path("results/high_volatility_premium_occupation_crowding_reversal_preregistration_2026-08-12.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_premium_occupation_crowding_reversal_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-12","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"During elevated BTC realized variation, a completed eight-hour Binance premium-index path that spends at least three quarters of its minutes strictly on one side of its causal historical baseline represents persistent leveraged crowding rather than a transient premium impulse. Fade an upper-tail occupied premium and buy a lower-tail occupied discount for eight hours.","side":"negative strict sign of current eight-hour mean premium minus the causal median of prior block means","why_distinct":"Premium catchup uses premium displacement opposite BTC return; premium-change autocorrelation uses changes; premium acceleration compares intrahour halves; premium snapback uses a 30-minute high-turn path that already recenters; the funding/premium classifier fits a multivariate score. HVPOCR uses the duration-like occupation of a fixed eight-hour path above or below a causal block-mean baseline plus a two-sided deviation tail. It uses no BTC return direction, funding, OI, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"BTC trailing twenty-four-hour realized variation must rank in its causal upper 35%, targeting July-like unstable markets","why_low_gross9_overlap_is_plausible":"new onsets of offset eight-hour premium occupation tails at 05:05/13:05/21:05 UTC are absent from Gross9 primitives"},
 "features":{"premium_block":"exact 480 bars_binance_premium BTCUSDT one-minute closes [D-8h,D), finite signed values with complete unique grid","block_mean":"arithmetic mean of the 480 signed premium closes","causal_baseline":"median of at most 270 strictly prior source-valid block means; minimum 180; current excluded","deviation":"block mean minus causal baseline, strict nonzero","occupation_share":"fraction of current 480 premium closes strictly above the causal baseline","persistent_side":"upper when occupation share>=0.75; lower when occupation share<=0.25; middle ineligible","deviation_magnitude_rank":"strict-prior midrank of absolute deviation against at most 270 prior deviations; minimum 180; current excluded; rank at least 0.70","btc_variation":"sum squared log(close/open) over exact 1440 BTCUSDT one-minute bars [D-24h,D)","variation_rank":"strict-prior midrank against at most 270 prior source-valid decisions; minimum 180; current excluded; rank at least 0.65","trigger":"false-to-true onset of persistent side, deviation tail, and variation gate against previous source-valid decision","invalid":"missing, duplicate, nonfinite premium, incomplete or incoherent/nonpositive BTC OHLC, or sign disagreement between deviation and persistent side; no imputation"},
 "clock":{"decision":"exact 05:00, 13:00, and 21:00 UTC","entry":"exact BTCUSDT open five elapsed minutes after decision","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 "policy":{"block_minutes":480,"history_decisions":270,"minimum_history_decisions":180,"upper_occupation_min":.75,"lower_occupation_max":.25,"deviation_magnitude_rank_min":.70,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, and final","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_occupation_requirement","no_variation_gate","premium_displacement_side","one_block_stale_features","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"premium":{"table":"bars_binance_premium","symbol":"BTCUSDT","interval":"1m","columns":["ts","close"]},"btc":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"]},"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_only":True,"execution_price":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"repository_collision_search_opened":True,"exact_premium_occupation_candidate_found":False,"prior_premium_candidate_outcomes_known":True,"prior_event_sets_reused":False,"prior_controls_promoted":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"selection_basis":"independent duration-like premium occupation crowding mechanism"},
 "stopping_rule":"terminal first-failure sequence: source support, Gross9 novelty, train/test/eval/final strict economics, then RV20 q90 audit; no baseline, block, occupation, deviation, history, rank, variation, onset, side, hold, clock, subset, threshold, source, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def main()->None:
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();b=(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_bytes(b);print(json.dumps({"policy_id":POLICY_ID,"output":str(a.output),"sha256":hashlib.sha256(b).hexdigest()}))
if __name__=="__main__":main()
