"""Outcome-blind preregistration for CVEH-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any

POLICY_ID="CVEH-6"
DEFAULT_OUTPUT=Path("results/cross_venue_efficiency_handoff_relay_preregistration_2026-08-10.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"cross_venue_efficiency_handoff_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-10","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
  "mechanism":{"claim":"During a completed high-variation eight-hour BTC block, accelerating BTC-denominated cash volume plus an efficient same-direction Spot path, while the perpetual path remains less efficient, marks incomplete transfer of clean cash price discovery. Follow the common late return direction for six hours.","side":"common strict sign of completed final-two-hour Spot and perpetual returns","why_distinct":"CVEH uses the conjunction of cross-venue path-efficiency asymmetry and change in relative base-volume sponsorship. CLASP used five-minute centroids, ticket surprise, basis lag, and forward response; SLVCR used price under-transmission and implied volatility; SPVIR used an hourly participation level. CVEH uses none of their event rows, price-gap rules, flow fields, tickets, implied volatility, or controls.","why_suited_to_volatile_regimes":"completed perpetual eight-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"three fixed UTC cross-venue efficiency-handoff onsets are absent from Gross9 primitives"},
  "features":{"decision_grid":"exact 00:00/08:00/16:00 UTC boundaries","block":"480 exact aligned coherent BTCUSDT bars_binance_spot and bars_binance interval=1m rows [D-8h,D)","early_volume":"sum BTC base volume [D-4h,D-2h), separately by venue","late_volume":"sum BTC base volume [D-2h,D), separately by venue","volume_acceleration":"log(late_volume/early_volume), separately by venue","cash_handoff":"spot volume acceleration minus perpetual volume acceleration","late_return":"log(last close/first open) over [D-2h,D), separately by venue","late_total_variation":"sum absolute one-minute close-to-close log returns over [D-2h,D), separately by venue","path_efficiency":"abs(late_return)/late_total_variation, separately by venue","realized_variation":"sum squared perpetual one-minute close-to-close log returns over [D-8h,D)","ranks":"each of realized variation, Spot efficiency, perpetual efficiency, and cash handoff uses a separate strict-prior midrank over at most 270 valid decisions, minimum 180, current excluded","eligibility":"variation rank>=0.65; Spot/perpetual late returns have one strict sign; Spot efficiency rank>=0.80; perpetual efficiency rank<=0.50; cash-handoff rank>=0.75","onset":"eligible now and immediately prior exact boundary ineligible; missing prior boundary cannot trigger","no_imputation":True},
  "clock":{"decision":"completed eight-hour boundary","entry":"exact BTCUSDT perpetual D+5m open","side":"common strict late-return sign","hold":"6 elapsed hours","reservation":"global half-open; exit first on equal open","funding":"not a signal input; exact settlements only after novelty passes"},
  "policy":{"history_blocks":270,"minimum_history_blocks":180,"variation_rank_min":.65,"spot_efficiency_rank_min":.80,"perpetual_efficiency_rank_max":.50,"cash_handoff_rank_min":.75,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
  "diagnostic_controls":{"names":["no_volume_handoff","no_efficiency_asymmetry","spot_efficiency_only","one_boundary_stale_geometry","direction_flip","forced_long","forced_short"],"cannot_be_promoted":True},
  "source_plan":{"spot":{"table":"bars_binance_spot","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","volume"]},"perpetual":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","volume"]},"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True,"execution_prices":"sealed until source support and Gross9 novelty pass"},
  "research_boundary":{"prior_cross_venue_efficiency_and_participation_family_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_cveh_ranks_direction_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"source-complete cross-venue efficiency plus volume-sponsorship migration"},
  "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no feature, rank, side, hold, clock, subset, or control repair."
 }
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2)+"\n");print(a.output)
