"""Outcome-blind preregistration for HVDTCAR-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVDTCAR-8";DEFAULT_OUTPUT=Path("results/high_volatility_directional_turnover_concentration_asymmetry_relay_preregistration_2026-08-10.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_directional_turnover_concentration_asymmetry_relay_v1",policy_id=POLICY_ID,
 mechanism={"claim":"Within a volatile completed BTC block, turnover concentrated into a few auctions on only one return side reflects episodic sponsored price discovery in that direction. Follow the side with the greater count-normalized within-side turnover concentration for eight hours.","side":"strict sign of normalized up-bar turnover concentration minus normalized down-bar turnover concentration","why_distinct":"Unsigned turnover HHI pools all auctions, sign entropy and run asymmetry ignore turnover, return-volume covariance measures linear co-movement, and range-participation polarity weights directional mass. HVDTCAR compares two separately normalized within-side turnover distributions and uses no endpoint gate, flow classification, funding, OI, cross-asset, prior event, fitted outcome, or control.","why_suited_to_volatile_regimes":"completed realized variation must rank in its causal upper 35% while directional concentration separation enters its upper 30%","why_low_gross9_overlap_is_plausible":"offset three-daily side-conditioned turnover-concentration onsets are absent from Gross9 primitives"},
 features={"decision_grid":"exact 02:00/10:00/18:00 UTC boundaries","block":"96 exact coherent five-minute groups from 480 bars_binance BTCUSDT one-minute rows [D-8h,D)","five_minute_return":"log(group close/group open), finite and strict nonzero for classified bars","five_minute_turnover":"sum quote_asset_volume in group, finite nonnegative","side_partition":"strict positive-return and strict negative-return groups; each side requires at least two groups and strict positive turnover","within_side_hhi":"sum((turnover_i/side_turnover)^2) separately by side","count_normalized_concentration":"(n*HHI-1)/(n-1), separately by side, finite in [0,1]","directional_concentration_contrast":"normalized up concentration minus normalized down concentration, finite strict nonzero","concentration_rank":"strict-prior midrank of abs(directional_concentration_contrast) over at most 270 earlier source-valid blocks, minimum 180, current excluded; rank>=0.70","realized_variation":"sqrt(sum squared one-minute log(close/open) returns), finite strict positive","variation_rank":"strict-prior 270/180 midrank, current excluded; rank>=0.65","eligible_state":"concentration and variation gates pass","onset":"eligible now and immediately previous exact source-valid block ineligible; missing prior cannot trigger","no_imputation":True},
 clock={"decision":"completed eight-hour boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_blocks":270,"minimum_history_blocks":180,"concentration_rank_min":.70,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_concentration_tail","no_variation_gate","directional_turnover_mass_asymmetry","one_block_stale_concentration","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"prior_unsigned_turnover_hhi_sign_structure_covariance_and_range_participation_outcomes_known":True,"repository_directional_turnover_concentration_asymmetry_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_rank_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"separate count-normalized concentration of turnover within positive and negative auctions"},
 stopping_rule="Terminal first failure; no partition, concentration normalization, rank, onset, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVDTCAR preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
