"""Outcome-blind preregistration for HVNVI-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVNVI-24";DEFAULT_OUTPUT=Path("results/high_volatility_negative_volume_index_signal_crossover_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_negative_volume_index_signal_crossover_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a canonical Negative Volume Index crossing its 255-period exponential signal on completed four-hour BTC auctions identifies a change in the price path formed specifically during declining-volume auctions; follow the new relation for twenty-four hours.","side":"long when NVI crosses strictly above its signal EMA; short on the strict reverse crossover","why_distinct":"HVNVI updates a multiplicative price index only when completed base volume declines versus the prior bar and otherwise carries its prior state. It is not a continuously weighted volume oscillator, Force Index, taker flow, OI, funding, premium, or Gross9 primitive.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%, restricting low-participation path regime changes to July-like volatile conditions","why_low_gross9_overlap_is_plausible":"sparse stateful declining-volume price-index signal crossings are absent from Gross9 primitives"},
 external_basis={"origin":"Paul Dysart / Norman Fosback canonical Negative Volume Index convention","fixed_definition":"initialize NVI at 1000; when current completed volume is below prior completed volume, NVI=current prior NVI*(current close/prior close), otherwise unchanged; 255-period EMA signal with adjust=false; strict line crossover","selection_use":"published state update, initial value, signal period, and direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T), including summed base volume","negative_volume_index":"causal multiplicative index initialized at 1000 at the first valid bar after any gap; update by close ratio only on a strict base-volume decline; carry unchanged otherwise","signal":"255-period EMA of NVI, alpha=2/256, adjust=false, minimum 255 consecutive valid bars","cross":"strict current NVI/signal crossover from immediately prior valid state","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"initial_index":1000.,"signal_periods":255,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","positive_volume_index","one_bar_stale_crossover","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","volume"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_negative_volume_index_definition_read":True,"repository_negative_volume_index_candidate_found":False,"prior_volume_indicator_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Negative Volume Index 255-period signal crossover under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no index update, initial value, signal period, crossover, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVNVI preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
