"""Outcome-blind preregistration for WMLHR-16."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="WMLHR-16";DEFAULT_OUTPUT=Path("results/weekend_monday_liquidity_handoff_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"weekend_monday_liquidity_handoff_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A completed Saturday-Sunday BTC displacement formed under lower weekend participation can be superseded when Monday's first eight hours move in the opposite direction with higher quote-volume per hour. Follow the Monday liquidity-reentry direction through the remaining UTC day.","side":"strict sign of Monday 00:00-08:00 completed return","why_distinct":"WMLHR trades a weekly liquidity-regime handoff between a 48-hour weekend and Monday opening block. It is not weekend high-vol overreaction fading, multi-day trend concordance, cross-asset cash-open transfer, run persistence, funding, or a thresholded volatility signal.","volatile_market_target":"liquidity re-entry against a weekend displacement is later audited on causal RV20 q90, never gated by it","why_low_gross9_overlap_is_plausible":"at most one sixteen-hour Monday position each week"},
 "features":{"weekend_window":"exact 2,880 one-minute bars [Saturday 00:00,Monday 00:00)","monday_window":"exact 480 one-minute bars [Monday 00:00,08:00)","weekend_return":"log(close Sunday 23:59/open Saturday 00:00), strict nonzero","monday_return":"log(close Monday 07:59/open Monday 00:00), strict nonzero","direction_handoff":"returns have opposite signs","weekend_quote_per_hour":"sum weekend quote_asset_volume/48","monday_quote_per_hour":"sum Monday-block quote_asset_volume/8","liquidity_reentry":"Monday quote per hour > weekend quote per hour","source_valid":"exact unique minute grids, coherent finite positive OHLC, finite nonnegative quote volume, no imputation"},
 "rv20_stress_slice":{"rv20":"sqrt(365*mean exact daily returns^2 over t-20 through t-1)","threshold":"numpy linear q90 over 756 strictly prior available RV20 observations","entry_filter":False,"future_use":"only after all sequential full-calendar stages pass"},
 "clock":{"decision":"Monday 08:00 UTC after both windows complete","entry":"exact BTCUSDT Monday 08:05 UTC open","hold":"16 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact realized funding only after novelty"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","persistent_long_vol_comparator":"same accepted clock and 0.5 gross, side forced long","full_calendar_decomposition":"candidate minus comparator net return","rv20_q90_decomposition":"same decomposition on causal RV20 q90 decisions","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"candidate_specific_q90_residual_positive":True,"comparator_cannot_satisfy_candidate_claim":True},
 "diagnostic_controls":{"definitions":{"no_liquidity_reentry":"Monday direction on every opposite-sign handoff","weekend_continuation":"weekend return side on primary clock","monday_fade":"negative Monday return side on primary clock","direction_flip":"negative primary side"},"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"exact_wmlhr_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no weekday, window, volume comparison, side, clock, hold, RV20, subset, comparator, control, or gate repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("WMLHR preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+"\n");print(a.output)
