"""Outcome-blind preregistration for HVLOWR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVLOWR-8";SLUG="high_volatility_leverage_only_wick_rejection_reversal";DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":f"{SLUG}_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"When the BTC perpetual makes an extreme normalized intrabar excursion beyond the simultaneous BTC spot excursion but closes no farther than spot in that direction, leverage-only price discovery has been rejected by the cash market. During elevated BTC variation, fade the rejected perpetual-only wick for eight hours.","side":"short an upper leverage-only rejection; long a lower leverage-only rejection","why_distinct":"Premium-index wick rejection studies the synthetic premium candle itself. Spot displacement, basis, error-correction, flow leadership, and first-passage candidates use closes, basis states, flow, or ordered barrier times. HVLOWR instead compares simultaneous normalized high/open and open/low excursions of the actual spot and perpetual markets, then requires close-level cash nonconfirmation. It uses no fitted outcome, OI, funding, volume, prior event set, or promoted control.","why_suited_to_volatile_regimes":"causal trailing perpetual 24-hour realized variation must occupy its upper 35 percent","why_low_gross9_overlap_is_plausible":"irregular cross-market high/low excursion divergence onsets are absent from Gross9 primitives"},
 "features":{"decision_grid":"every exact UTC five-minute boundary D","market_bars":"five exact coherent native one-minute bars [D-5m,D) for BTCUSDT perpetual and spot","normalized_upper_excursion":"log(five-minute high/five-minute open) separately for perpetual and spot","normalized_lower_excursion":"log(five-minute open/five-minute low) separately for perpetual and spot","upper_excess":"perpetual upper excursion minus spot upper excursion","lower_excess":"perpetual lower excursion minus spot lower excursion","excess_ranks":"separate strict-prior midranks of upper_excess and lower_excess over at most 8640 jointly valid decisions, minimum 6048, current excluded","upper_rejection":"upper_excess rank>=0.995 and perpetual log(close/open)<=spot log(close/open)","lower_rejection":"lower_excess rank>=0.995 and perpetual log(close/open)>=spot log(close/open)","direction":"exactly one rejection side; simultaneous upper and lower rejection is ineligible","btc_realized_variation":"sqrt(sum squared exact perpetual one-minute log(close/open) returns over [D-24h,D))","variation_rank":"strict-prior midrank over at most 8640 jointly valid decisions, minimum 6048, current excluded; rank>=0.65","onset":"directional rejection true now and false at immediately prior exact source-valid five-minute decision; missing prior cannot trigger","no_imputation":True},
 "clock":{"decision":"D after both completed bars and causal ranks are available","entry":"exact BTCUSDT perpetual D+5m open","side":"opposite the rejected perpetual-only excursion","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements only after novelty"},
 "policy":{"history_decisions":8640,"minimum_history_decisions":6048,"excess_rank_min":.995,"variation_bars":288,"variation_rank_min":.65,"onset_required":True,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","rank_0_99","no_close_nonconfirmation","one_bar_stale_rejection","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"perpetual":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m"},"spot":{"table":"bars_binance_spot","symbol":"BTCUSDT","interval":"1m"},"columns":["ts","open","high","low","close"],"window":["2023-05-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration_commit":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"adjacent_spot_premium_basis_and_first_passage_outcomes_known":True,"repository_exact_actual_market_excursion_divergence_rejection_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cash-nonconfirmation of leveraged intrabar excursion mechanism"},
 "stopping_rule":"terminal first failure; no market, bar, normalization, rank history, rank threshold, close confirmation, variation, onset, side, clock, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}) or x!=build():raise RuntimeError("HVLOWR prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_bytes(b);print(a.output)
