"""Outcome-blind preregistration for HVECC-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVECC-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_cyber_cycle_trigger_crossover_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_cyber_cycle_trigger_crossover_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' canonical Cyber Cycle crossing its one-bar trigger on completed four-hour BTC auctions identifies a filtered cyclical turn; follow the new cycle direction for twenty-four hours.","side":"long when Cycle crosses strictly above its one-bar-lagged trigger; short on the strict reverse crossover","why_distinct":"Cyber Cycle applies a symmetric 1-2-2-1 median-price smoother and a recursive second-order high-pass cycle filter before crossing the cycle against its lag. It is not a price-average crossover, normalized sinewave, fixed return oscillator, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse recursive cycle-versus-trigger turns are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Cybernetic Analysis for Stocks and Futures, Cyber Cycle","source":"https://www.mql5.com/en/articles/288","fixed_definition":"median price; 1-2-2-1 smoothing; alpha=0.07 recursive Cyber Cycle; first six observations use the published finite-difference initialization; trigger is Cycle lagged one bar; line crossover","selection_use":"published alpha, formula, initialization, trigger, and crossover direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","median_price":"(completed high+completed low)/2","smooth":"(price+2*price_lag1+2*price_lag2+price_lag3)/6","cycle":"(1-alpha/2)^2*(smooth-2*smooth_lag1+smooth_lag2)+2*(1-alpha)*cycle_lag1-(1-alpha)^2*cycle_lag2, alpha=0.07","initialization":"within each uninterrupted source run, observations before index 7 use (price-2*price_lag1+price_lag2)/4 when available; require seven uninterrupted observations before source validity","trigger":"immediately prior finite Cycle","event":"current Cycle-minus-trigger strict nonzero sign differs from its immediately prior finite nonzero sign","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"alpha":.07,"warmup_observations":7,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","zero_cross","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_cyber_cycle_definition_read":True,"repository_cyber_cycle_candidate_found":False,"prior_ehlers_filter_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Ehlers alpha-0.07 Cyber Cycle/one-bar-trigger crossover under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no alpha, input, initialization, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVECC preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
