"""Outcome-blind preregistration for HVEIS-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVEIS-24";DEFAULT_OUTPUT=Path("results/high_volatility_elder_impulse_color_transition_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_elder_impulse_color_transition_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, an Elder Impulse System transition into green or red on completed four-hour BTC auctions identifies agreement between trend slope and momentum acceleration; follow the newly aligned color for twenty-four hours.","side":"long when current color becomes green after a non-green valid color; short when current color becomes red after a non-red valid color","why_distinct":"HVEIS requires simultaneous sign agreement of the 13-period EMA slope and MACD histogram slope. It is a two-component transition state rather than a MACD-line crossover, price band/channel, volume force, oscillator, OI, funding, premium, or Gross9 state primitive.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%, while dual trend/momentum agreement suppresses isolated noisy turns","why_low_gross9_overlap_is_plausible":"sparse four-hour dual-slope color-transition clocks are absent from Gross9 primitives"},
 external_basis={"origin":"Alexander Elder, Impulse System","fixed_definition":"13-period EMA slope plus standard MACD(12,26,9) histogram slope; green when both rise, red when both fall, neutral otherwise","selection_use":"published components, periods, color logic, and direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","trend":"13-period close EMA, adjust=false, minimum 13 consecutive valid bars; slope=current-prior EMA","macd":"12-period close EMA minus 26-period close EMA; 9-period EMA signal of valid MACD; histogram=MACD-signal","momentum":"current histogram minus prior histogram","color":"green when trend slope>0 and histogram slope>0; red when both<0; neutral otherwise","transition":"current green after non-green or current red after non-red, requiring consecutive valid states","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"trend_ema_periods":13,"macd_fast_periods":12,"macd_slow_periods":26,"macd_signal_periods":9,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","histogram_slope_only","one_bar_stale_transition","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_elder_impulse_definition_read":True,"repository_elder_impulse_candidate_found":False,"prior_rsi_cci_stochastic_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Elder Impulse color transition under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no EMA/MACD period, smoothing, slope, color, transition, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVEIS preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
