"""Outcome-blind preregistration for HPPRR-12."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any

DEFAULT_OUTPUT=Path("results/hkd_peg_pressure_rotation_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"hkd_peg_pressure_rotation_relay_v1","policy_id":"HPPRR-12","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
  "mechanism":{"claim":"An unusually large completed Asian-session USD/HKD move measures rotation in pressure against the HKD trading band. In a high-variation BTC regime, movement toward HKD weakness is risk-off and maps short BTC, while movement toward HKD strength maps long BTC for twelve hours.","side":"negative strict sign of completed USDHKD 00:00-08:00 UTC log return","why_distinct":"No prior repository alpha uses USDHKD or a currency-board pressure rotation. HPPRR uses one externally fixed Asian peg-pressure channel, not the six-pair dollar factor, FX volatility sponsorship, EM-currency beta, crypto flow, funding, or a prior diagnostic control.","why_suited_to_volatile_regimes":"BTC completed prior-24h realized variation must rank in its causal upper 35%.","why_low_gross9_overlap_is_plausible":"sparse weekday 08:05 UTC entries conditioned on USDHKD pressure are absent from Gross9 primitives."},
  "features":{"fx_session":"bars_polygon USDHKD interval=1m rows with 00:00<=UTC time<08:00 on one UTC weekday","fx_session_valid":"at least 450 distinct minutes, first timestamp no later than 00:05, last timestamp no earlier than 07:55, finite positive OHLC; no imputation","peg_pressure_change":"log(session_close/session_open); strict nonzero; positive means HKD weakening pressure","pressure_magnitude_rank":"strict-prior midrank of absolute peg_pressure_change over at most 90 prior valid sessions, minimum 60, current excluded; rank>=0.70","btc_realized_variation":"sqrt(sum squared completed-hour BTC log returns over 24 hours ending at decision)","volatility_rank":"strict-prior midrank over at most 90 valid decision days, minimum 60, current excluded; rank>=0.65","no_imputation":True},
  "clock":{"decision":"exact weekday D 08:00 UTC after both source paths complete","entry":"exact BTCUSDT D 08:05 UTC open","side":"negative strict sign of peg_pressure_change","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","funding_oi_premium":"not signal inputs; exact funding only after novelty passes"},
  "policy":{"fx_prior_sessions":90,"fx_prior_min_sessions":60,"pressure_magnitude_rank_min":.70,"realized_variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "source_plan":{"fx":{"table":"bars_polygon","symbol":"USDHKD","interval":"1m","window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"materialize_after_preregistration":True},"completed_btc":"hash-bound completed-hour BTC source through 2026-08-01 for pre-entry variation only","execution_price":"sealed until source-support and Gross9 novelty pass"},
  "diagnostic_controls":{"names":["no_volatility_gate","no_pressure_tail","one_session_stale_pressure","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
  "research_boundary":{"database_metadata_only_opened_before_preregistration":True,"usdhkd_values_used_to_select_rule":False,"prior_candidate_outcomes_used_to_set_hpprr_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent currency-board pressure rotation channel at the Asian-session boundary"},
  "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no session, pressure definition, rank, side, hold, clock, volatility, or subset repair."
 };return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+"\n");print(a.output)
