"""Outcome-blind preregistration for HVTOCM-30M."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any

POLICY_ID="HVTOCM-30M";DEFAULT_OUTPUT=Path("results/high_volatility_turn_of_candle_momentum_preregistration_2026-08-09.json")
MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_turn_of_candle_momentum_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"Bitcoin's first UTC half-hour return carries information into the final UTC half-hour. On days beginning after an already high-variation 24-hour state, follow the completed first-half-hour direction only during 23:30-24:00 UTC.","side":"strict sign of the completed 00:00-00:30 UTC return","why_distinct":"HVHOW learns four six-hour weekly slots from labels. Intraday path candidates enter immediately after their feature blocks. HVTOCM freezes a published first-to-last half-hour timing relation, waits 23 hours without consuming intervening data, and trades only the final 30 minutes; no prior event set or control is reused.","why_low_gross9_overlap_is_plausible":"one high-variation 23:30 UTC entry with a 30-minute hold is absent from Gross9","literature_context":{"paper":"Turn-of-The-Candle Effect in Bitcoin Returns","supported_direction":"the first half-hour positively predicts the last half-hour return, with greatest predictability when the opening session has high volume or volatility","implementation_is_not_a_replication":True}},
 "features":{"variation_window":"exact 289 BTCUSDT 5m closes from D-24h-5m through D-5m, producing 288 completed close-to-close returns before D","realized_variation":"sqrt(sum squared 5m log returns)","variation_rank":"strict-prior midrank over at most 90 prior valid UTC days, minimum 60, current excluded; rank>=0.65","opening_half_hour":"exact six completed contiguous BTCUSDT 5m bars [D,D+30m)","opening_return":"log(D+25m close/D open), strict nonzero","information_embargo":"no bar, price, volume, funding, OI, premium, or outcome between D+30m and the 23:30 entry is a signal input","validity":"exact unique grid, finite positive coherent OHLC, no imputation"},
 "clock":{"decision":"D+00:30 UTC after opening half-hour completes","scheduled_entry":"D+23:30 UTC open; signal is held unchanged without observing an eligibility input during the wait","exit":"D+24:00 UTC open","hold":"30 elapsed minutes","side":"opening-return sign","reservation":"global half-open; one position per UTC day","split_crossing_action":"skip","gross_exposure":.5,"funding":"not a signal input; exact settlements only during economics"},
 "policy":{"variation_prior_days":90,"variation_minimum_days":60,"variation_rank_min":.65,"opening_minutes":30,"scheduled_entry_hour":23,"scheduled_entry_minute":30,"hold_minutes":30,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"definitions":{"no_variation_gate":"opening-half-hour momentum every valid UTC day","opening_half_hour_fade":"negative opening-return sign on the primary clock","second_half_hour_momentum":"strict sign of [00:30,01:00) return on the same scheduled 23:30 clock and variation law","one_day_stale_opening_return":"previous valid UTC day's opening-return sign on the primary eligibility clock","same_clock_forced_long":"side +1 on primary clock"},"cannot_be_promoted":True},
 "source_plan":{"historical_market":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m through 2026-08-01","execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"published_direction_read_before_candidate":True,"prior_calendar_candidate_outcomes_known":True,"prior_event_sets_or_controls_reused":False,"exact_hvtocm_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published fixed first-to-last half-hour timing effect plus user-requested high volatility"},
 "stopping_rule":"terminal first failure; no UTC day, variation, opening window, embargo, entry, side, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVTOCM preregistration drift")
 if hashlib.sha256(MARKET.read_bytes()).hexdigest()!=MARKET_SHA:raise RuntimeError("HVTOCM market binding drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
