"""Outcome-blind preregistration for HVMBC-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVMBC-8";DEFAULT_OUTPUT=Path("results/high_volatility_median_breadth_contradiction_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_median_breadth_contradiction_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When a completed high-variation eight-hour BTC block's endpoint return has the opposite sign from the median of its 96 completed five-minute returns, a minority of large jumps has displaced the close against broad interval drift. Trade with the median return breadth for eight hours.","side":"strict sign of the median 5m open-to-close log return, opposite the strict block return sign","why_distinct":"Jump-reversal candidates measure bipower residual magnitude, sign-run and entropy candidates measure ordering or concentration, and range candidates use extrema. HVMBC uses the robust cross-sectional median direction versus endpoint direction, no prior event set or diagnostic control.","volatile_market_target":"completed-block realized-variation causal rank at least 0.65","why_low_gross9_overlap_is_plausible":"conditional 00:05/08:05/16:05 UTC median-breadth contradiction clocks are absent from Gross9"},
 "features":{"decision_grid":"exact UTC 00:00, 08:00, 16:00 boundaries","block":"96 exact coherent BTCUSDT perpetual five-minute aggregates in [D-8h,D), each from five unique 1m rows","bar_return":"strict log(5m close/open)","breadth_return":"median of all 96 finite bar returns, strict nonzero","block_return":"log(last close/first open), strict nonzero","contradiction":"breadth and block returns have opposite strict signs","realized_variation":"sqrt(sum squared 5m bar returns), strict positive","variation_rank":"strict-prior midrank over at most 270 earlier source-valid blocks, minimum 252; current excluded","eligibility":"contradiction and variation rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact block boundary after all source bars complete","entry":"decision+5m exact BTCUSDT open","side":"breadth-return sign","hold":"8 elapsed hours","reservation":"fixed blocks and holds nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium_rv20":"not signal inputs; exact funding only after novelty; RV20 q90 only after all stages"},
 "policy":{"block_hours":8,"bars_5m":96,"history_blocks":270,"minimum_history_blocks":252,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all stages","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_contradiction_gate","no_variation_gate","block_return_side","mean_bar_return_side","one_block_stale_features","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_only":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"related_jump_and_breadth_outcomes_known":True,"median_endpoint_contradiction_used_to_select_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent robust return-breadth contradiction mechanism"},
 "stopping_rule":"terminal first failure; no block, median, contradiction, rank, history, side, timing, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVMBC prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
