"""Outcome-blind preregistration for HVPPHL-R10-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVPPHL-R10-24"
DEFAULT_OUTPUT=Path("results/high_volatility_pivot_points_high_low_reversal_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_pivot_points_high_low_reversal_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
  mechanism={"claim":"During elevated realized variation, causal confirmation of a canonical ten-bar-surrounded pivot low or high on completed four-hour BTC auctions identifies a bar-count reversal; follow the reversal direction for twenty-four hours.","side":"long when a strict pivot low is confirmed; short when a strict pivot high is confirmed; ignore a bar classified as both","why_distinct":"PPHL confirms that a historical center bar is the unique low or high against ten completed bars on each side, delaying availability by ten four-hour bars. It is not a contemporaneous extreme, channel breakout, moving average, oscillator, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"confirmed swing extrema can separate reversal structure from noisy one-bar extremes, while completed trailing twenty-four-hour realized variation at confirmation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse, forty-hour-delayed strict bar-count reversal confirmations are absent from Gross9 primitives"},
  external_basis={"origin":"Pivot Points High/Low (Bar Count Reversals); QuantConnect LEAN canonical implementation","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/PivotPointsHighLow.cs","documentation_source":"https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/pivot-points-high-low","fixed_definition":"documented high and low surrounding counts 10, strict=true, 21-bar rolling windows, center index 10; pivot high requires every other high strictly lower, pivot low requires every other low strictly higher; confirmed only when the tenth right-side bar completes; lastStoredValues=100 is storage-only","selection_use":"official documented counts, strict comparisons, causal right-side confirmation, and published bar-count reversal interpretation only; no incidence or outcomes"},
  features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","candidate_center":"the completed bar ending forty elapsed hours before confirmation","high_pivot":"center high strictly exceeds highs of all ten earlier and ten later completed bars","low_pivot":"center low strictly undercuts lows of all ten earlier and ten later completed bars","event":"at current confirmation only, low pivot gives +1 and high pivot gives -1; Both and None give 0","causal_availability":"no center classification is available before all ten right-side bars have completed","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive at confirmation time","variation_rank":"strict-prior midrank over at most 180 earlier valid confirmations, minimum 120, current excluded; rank>=0.65","recursive_reset":"21-bar high/low windows reset after any invalid completed four-hour bar","no_imputation":True},
  clock={"feature_available":"four-hour boundary after the tenth right-side confirmation bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
  policy={"surrounding_high_bars":10,"surrounding_low_bars":10,"last_stored_values":100,"strict":True,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  diagnostic_controls={"names":["no_variation_gate","raw_bar_direction","one_bar_stale_confirmation","direction_flip"],"cannot_be_promoted":True},
  source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
  research_boundary={"canonical_pphl_definition_read":True,"repository_pphl_candidate_found":False,"prior_range_reversal_candidate_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official LEAN PPHL(10,10,100,strict) causal reversal confirmation under the requested high-variation regime"},
  stopping_rule="Terminal first failure; no surrounding count, strictness, confirmation delay, Both handling, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVPPHL-R10-24 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
