"""Outcome-blind preregistration for HVLVPR-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVLVPR-24";DEFAULT_OUTPUT=Path("results/high_volatility_liquidity_volatility_premium_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_liquidity_volatility_premium_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"The volatility of market liquidity commands a positive, time-varying cryptocurrency risk premium. During elevated BTC realized variation, an upper-tail daily innovation in intraday Amihud-liquidity volatility maps long and a lower-tail innovation maps short for the next day.","side":"long when the signed liquidity-volatility innovation rank is at least 0.80; short when it is at most 0.20","why_distinct":"HVALPR ranked the level innovation of daily mean Amihud illiquidity and HVLIR ranked one hourly price-impact level. HVLVPR instead measures the within-day second moment of 288 five-minute Amihud observations, then ranks the signed change in that liquidity-risk state. It uses no completed return direction, flow, basis, OI, funding, fitted outcome, prior event, or promoted control.","why_suited_to_volatile_regimes":"the completed daily BTC realized-variation rank must be in its causal upper 35%, targeting July-like unstable markets","why_low_gross9_overlap_is_plausible":"sparse daily liquidity-risk innovation clocks are absent from Gross9 primitives"},
 external_basis={"paper":"Cryptocurrency returns and the volatility of liquidity","author":"Thomas Leirvik","journal":"Finance Research Letters 44 (2022), 102031","doi":"10.1016/j.frl.2021.102031","reported_relation":"positive but highly time-varying relation between idiosyncratic volatility of cryptocurrency market liquidity and expected returns","untested_adaptation":"five-minute Binance perpetual Amihud observations, within-day sample volatility, prior-median signed innovation, two-sided ranks, high-variation gate, and one-day BTC hold are a transparent causal adaptation rather than a claimed replication"},
 features={"decision_grid":"every calendar day at exact 00:00 UTC","window":"288 exact coherent five-minute groups from 1,440 BTCUSDT one-minute rows [D-24h,D)","five_minute_return":"log(group close/group open), finite","five_minute_quote_turnover":"sum quote_asset_volume, finite strict positive in every group","five_minute_amihud":"abs(five-minute return)/five-minute quote turnover, finite nonnegative","daily_liquidity_volatility":"sample standard deviation (ddof=1) of all 288 five-minute Amihud observations, finite strict positive","reference":"median log daily liquidity volatility over thirty exact source-valid days ending strictly before current day","innovation":"log(current daily liquidity volatility)-strictly-prior thirty-day median log liquidity volatility, finite strict nonzero","realized_variation":"sqrt(sum squared five-minute returns), finite strict positive","prior_ranks":"strict-prior midranks of innovation and variation over at most 180 earlier source-valid days, minimum 120, current excluded","liquidity_volatility_tail":"innovation rank>=0.80 or <=0.20","variation_gate":"realized-variation rank>=0.65","source_validity":"exact distinct minute grid, finite positive coherent OHLC, finite positive quote turnover, no imputation","no_imputation":True},
 clock={"feature_available":"00:00 UTC after the completed daily window","entry":"exact BTCUSDT 00:05 UTC open","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"intraday_groups":288,"reference_days":30,"history_days":180,"minimum_history_days":120,"innovation_rank_long_min":.80,"innovation_rank_short_max":.20,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_liquidity_volatility_tail","no_variation_gate","daily_mean_amihud_innovation","one_day_stale_innovation","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"external_liquidity_volatility_basis_read":True,"repository_liquidity_volatility_candidate_found":False,"nearest_amihud_level_and_impact_candidates_known":True,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"prior_event_sets_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"paper-reported volatility-of-liquidity premium expressed as a fixed transparent second-moment innovation state"},
 stopping_rule="Terminal first failure; no liquidity measure, intraday aggregation, reference window, rank history, tail, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVLVPR preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
