"""Outcome-blind preregistration for PPLAR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="PPLAR-8";DEFAULT_OUTPUT=Path("results/premium_price_latency_assimilation_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"premium_price_latency_assimilation_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A large completed premium-index impulse that persists for a second hour while BTC first under-responds and then begins a small same-direction response identifies derivative demand that price has only partly assimilated. Follow the premium direction for eight elapsed hours.","side":"strict sign of the early completed-hour premium-index close-minus-open change","why_distinct":"PPLAR measures cross-surface temporal transmission: an early premium impulse, premium persistence, initial BTC under-response, and a bounded delayed BTC assimilation. It is not premium compression, premium snapback, same-hour premium acceleration, funding, OI, implied volatility, or a fitted model.","volatile_market_target":"delayed premium-to-price assimilation is intended to isolate directional derivative demand during volatile auctions; causal RV20 q90 remains only a later audit","why_low_gross9_overlap_is_plausible":"top-quintile premium impulses with two-hour causal assimilation onsets and an eight-hour reservation"},
 "features":{"decision_grid":"every exact 2-hour UTC boundary D","early_window":"E=[D-2h,D-1h), exactly 60 coherent one-minute premium and BTC bars","late_window":"L=[D-1h,D), exactly 60 coherent one-minute premium and BTC bars","early_premium_change":"p_E=premium_close(E)-premium_open(E), strict nonzero; differences are used because premium may cross zero","late_premium_change":"p_L=premium_close(L)-premium_open(L)","early_btc_return":"r_E=log(BTC_close(E)/BTC_open(E))","late_btc_return":"r_L=log(BTC_close(L)/BTC_open(L)), strict nonzero","prior_statistics":"strict-prior histories over at most 540 valid exact two-hour decisions, minimum 360, current excluded: midranks of abs(p_E) and abs(r_E), plus median abs(r_L)","eligible_state":"rank(abs(p_E))>=0.80; p_E*p_L>0; rank(abs(r_E))<=0.40; sign(r_L)=sign(p_E); and 0<abs(r_L)<=0.5*prior_median(abs(r_L))","onset":"current eligible state true and immediately preceding exact two-hour decision eligible state false","source_valid":"complete unique coherent minute grids in both tables, finite BTC positive OHLC and finite premium OHLC; no imputation"},
 "rv20_stress_slice":{"rv20":"sqrt(365*mean exact daily returns^2 over t-20 through t-1)","threshold":"numpy linear q90 over 756 strictly prior available RV20 observations","entry_filter":False,"future_use":"only after all sequential full-calendar stages pass"},
 "clock":{"decision":"exact two-hour UTC boundary after E and L complete","entry":"exact BTCUSDT decision+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact realized funding only after novelty"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","persistent_long_vol_comparator":"same accepted clock and 0.5 gross, side forced long","full_calendar_decomposition":"candidate minus comparator net return","rv20_q90_decomposition":"same decomposition on causal RV20 q90 decisions","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"candidate_specific_q90_residual_positive":True,"comparator_cannot_satisfy_candidate_claim":True},
 "diagnostic_controls":{"definitions":{"premium_persistence_without_underresponse":"retain premium impulse/persistence and delayed same-direction BTC response but omit early BTC rank<=0.40","late_btc_return_only":"strict-prior top-quintile abs(r_L) onset, side=sign(r_L)","contemporaneous_agreement":"top-quintile abs(p_L) with sign(r_L)=sign(p_L), onset, side=sign(p_L)","one_hour_stale_premium":"replace p_E and p_L by completed premium changes over [D-3h,D-2h) and [D-2h,D-1h), retain the primary current BTC E/L terms, prior statistics, eligibility, onset, and side=sign(stale p_E)","direction_flip":"negative primary side"},"cannot_be_promoted":True},
 "source_plan":{"premium":{"table":"bars_binance_premium","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_after_preregistration":True},"btc":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"exact_pplar_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no window, transmission bound, rank, median, onset, side, clock, hold, RV20, subset, comparator, control, or gate repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("PPLAR preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+"\n");print(a.output)
