"""Outcome-blind preregistration for HVSMI-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVSMI-24";DEFAULT_OUTPUT=Path("results/high_volatility_stochastic_momentum_index_zero_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_stochastic_momentum_index_zero_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a completed four-hour canonical Stochastic Momentum Index crossing zero identifies a change in whether double-smoothed close location lies above or below the midpoint of its recent high-low envelope; follow the new side for twenty-four hours.","side":"long when SMI crosses strictly above zero; short when it crosses strictly below zero","why_distinct":"Blau SMI double-smooths both close displacement from the rolling high-low midpoint and the envelope width before taking their ratio. SMI Ergodic instead smooths signed close changes relative to absolute close changes; ordinary stochastic uses unsmoothed close location. This candidate uses no volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse double-smoothed range-midpoint balance crossings are absent from Gross9 primitives"},
 external_basis={"origin":"William Blau Stochastic Momentum Index as implemented and documented by TradingView","source":"https://www.tradingview.com/support/solutions/43000707882-stochastic-momentum-index-smi/","fixed_definition":"%K length 10; relativeRange=close-(highestHigh+lowestLow)/2; highestLowestRange=highestHigh-lowestLow; each receives two consecutive EMA(3); SMI=200*smoothed relativeRange/smoothed range; zero divides positive from negative close location","selection_use":"official formula, published default K=10 and D=3, and zero direction only; no optional SMI signal EMA, incidence, or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","range_window":"highest completed high and lowest completed low over ten uninterrupted bars","relative_range":"completed close minus rolling high-low midpoint","range_width":"rolling highest high minus rolling lowest low, strict positive","double_ema":"two causal consecutive EMA(3) recursions with alpha=0.5, each seeded from its first finite input and emitted after three uninterrupted inputs","smi":"200*double-EMA(relative_range)/double-EMA(range_width), strict positive denominator","event":"current finite nonzero SMI sign differs from immediately prior finite nonzero sign","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"k_periods":10,"d_periods":3,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","unsmoothed_midpoint_cross","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_stochastic_momentum_index_definition_read":True,"repository_stochastic_momentum_index_candidate_found":False,"prior_smi_ergodic_and_stochastic_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official TradingView SMI(10,3) zero crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no K/D length, EMA initialization, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVSMI preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
