"""Outcome-blind preregistration for HVFAER-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVFAER-8";DEFAULT_OUTPUT=Path("results/high_volatility_failed_auction_escape_reversal_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_failed_auction_escape_reversal_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"After a completed four-hour BTC range, a two-hour auction that escapes exactly one boundary intrabar but closes back strictly inside the range is a failed price-discovery attempt. If the final two-hour auction closes through the prior-range midpoint away from the failed boundary with an agreeing body, follow that reversal for eight hours during elevated realized variation.","side":"short after an upper-boundary failed escape and bearish midpoint confirmation; long after a lower-boundary failed escape and bullish midpoint confirmation","why_distinct":"Break-retest and inside-resolution follow accepted escapes; engulfing acceptance requires both boundaries; overreaction fades use return magnitude rather than a one-sided failed auction plus a disjoint midpoint confirmation. HVFAER uses no volume, flow, funding, OI, cross-asset, fitted outcome, prior event, or control.","why_suited_to_volatile_regimes":"the full completed eight-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"three daily failed-auction reversal clocks are absent from Gross9 primitives"},
 features={"decision_grid":"exact 02:00/10:00/18:00 UTC boundaries","prior_range":"first 240 one-minute rows [D-8h,D-4h), high=max high, low=min low, midpoint=(high+low)/2","escape_auction":"next 120 rows [D-4h,D-2h)","upper_failed_escape":"escape high>prior high, escape low>prior low, and escape close strictly inside prior range","lower_failed_escape":"escape low<prior low, escape high<prior high, and escape close strictly inside prior range","confirmation_auction":"final 120 rows [D-2h,D)","short_confirmation":"upper failed escape and confirmation close<prior midpoint and confirmation close<confirmation open","long_confirmation":"lower failed escape and confirmation close>prior midpoint and confirmation close>confirmation open","ambiguity":"exactly one failed-escape side and confirmation must hold","realized_variation":"sqrt(sum squared one-minute log(close/open) returns across [D-8h,D)), finite strict positive","variation_rank":"strict-prior midrank over at most 270 earlier source-valid blocks, minimum 180, current excluded; rank>=0.65","eligible_state":"one failed escape, opposite midpoint confirmation, and variation gate pass","no_imputation":True},
 clock={"decision":"completed confirmation-auction boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_blocks":270,"minimum_history_blocks":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_failed_escape_requirement","no_variation_gate","reclaim_close_only","one_block_stale_prior_range","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"prior_break_retest_inside_resolution_engulfing_overreaction_and_donchian_outcomes_known":True,"repository_failed_auction_escape_reversal_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"one-sided failed boundary escape followed by disjoint opposite midpoint confirmation"},
 stopping_rule="Terminal first failure; no range, escape, reclaim, midpoint, confirmation, body, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVFAER preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
