"""Outcome-blind preregistration for HVODHR-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVODHR-8";DEFAULT_OUTPUT=Path("results/high_volatility_opening_drive_hold_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_opening_drive_hold_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"A directional opening-hour drive that establishes a fresh range, followed by seven completed hours whose closes never surrender the opening-range midpoint and whose terminal close extends the opening boundary, represents sustained initiative price discovery. Follow that accepted direction for eight hours when the completed block has elevated realized variation.","side":"long after an upward opening drive with midpoint hold and upper extension; short after the symmetric downward drive","why_distinct":"Opening-range failure trades rejection in three two-hour phases; break-retest uses a preceding four-hour range and explicit later retest; inside-resolution begins with containment. HVODHR requires a one-hour initiative drive, seven-hour close-by-close midpoint preservation, and terminal extension within one completed block, with no volume, flow, funding, OI, cross-asset, fitted outcome, prior event, or control.","why_suited_to_volatile_regimes":"the full completed eight-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"three daily opening-drive acceptance clocks are absent from Gross9 primitives"},
 features={"decision_grid":"exact 02:00/10:00/18:00 UTC boundaries","block":"480 exact coherent BTCUSDT one-minute rows [D-8h,D)","opening_drive":"first 60 rows; opening high=max high, low=min low, midpoint=(high+low)/2, direction=sign(last close-first open), strict nonzero","acceptance_window":"remaining 420 rows","long_acceptance":"opening direction positive, every acceptance-window minute close>opening midpoint, and terminal close>opening high","short_acceptance":"opening direction negative, every acceptance-window minute close<opening midpoint, and terminal close<opening low","ambiguity":"exactly one acceptance side must hold","realized_variation":"sqrt(sum squared one-minute log(close/open) returns across [D-8h,D)), finite strict positive","variation_rank":"strict-prior midrank over at most 270 earlier source-valid blocks, minimum 180, current excluded; rank>=0.65","eligible_state":"accepted opening drive and variation gate pass","no_imputation":True},
 clock={"decision":"completed eight-hour boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_blocks":270,"minimum_history_blocks":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_midpoint_hold","no_variation_gate","terminal_break_only","one_block_stale_opening_range","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"prior_opening_failure_break_retest_inside_resolution_and_price_path_outcomes_known":True,"repository_opening_drive_hold_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"opening-hour initiative followed by seven-hour close-by-close midpoint preservation and extension"},
 stopping_rule="Terminal first failure; no drive, range, midpoint, preservation, extension, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVODHR preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
