"""Outcome-blind preregistration for HVDSR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVDSR-12";DEFAULT_OUTPUT=Path("results/high_volatility_dominant_shock_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_dominant_shock_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When one completed hourly BTC return accounts for an unusually large share of a high-variation UTC day's total absolute hourly displacement, the day contains a localized information shock rather than diffuse noise. Follow the dominant shock hour's direction for twelve hours.","side":"strict sign of the earliest hour attaining the largest absolute completed hourly return","why_distinct":"HVDVBR selected the maximum-volume five-minute bar and required block-return agreement. HVTVIR measured variance backloading into a fixed final three-hour window. Bipower and skew candidates measured jump magnitude or signed moments. HVDSR localizes the largest hourly return anywhere in the day and ranks its share of total absolute hourly displacement.","volatile_market_target":"completed-day realized-variation causal rank must be at least 0.65","why_low_gross9_overlap_is_plausible":"one dominant-shock-conditioned 00:05 UTC daily clock is absent from Gross9"},
 "features":{"source_day":"exact prior UTC day","hourly_path":"24 exact coherent BTCUSDT perpetual hourly aggregates, each from 60 unique 1m bars","hourly_return":"log(hour close/hour open), finite; at least one strict nonzero","dominant_hour":"earliest hour attaining max(abs(hourly_return))","dominant_share":"max(abs(hourly_return))/sum(abs(hourly_return)), denominator strict positive","realized_variation":"sqrt(sum squared hourly returns), strict positive","causal_ranks":"strict-prior midranks of dominant_share and realized_variation over at most 270 prior source-valid days, minimum 180; current excluded","eligibility":"dominant-share rank>=0.65 and realized-variation rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact D 00:00 UTC after prior day completes","entry":"exact BTCUSDT D 00:05 UTC open","side":"dominant completed-hour return sign","hold":"12 elapsed hours","reservation":"daily opportunities are nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium_rv20":"not signal inputs; funding only after novelty; RV20 q90 only after all economics pass"},
 "policy":{"hours":24,"history_days":270,"minimum_history_days":180,"dominant_share_rank_min":.65,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_dominant_share_gate","no_variation_gate","completed_day_return_side","latest_maximum_tie_break","one_day_stale_features","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_only":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"related_jump_volume_temporal_outcomes_known":True,"dominant_hour_values_used_to_select_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent localized information-shock mechanism"},
 "stopping_rule":"terminal first failure; no aggregation, dominant-hour definition, rank, history, threshold, tie break, side, timing, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVDSR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
