"""Outcome-blind preregistration for HVCREDIT-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template

POLICY_ID="HVCREDIT-24";DEFAULT_OUTPUT=Path("results/high_volatility_credit_risk_appetite_relay_preregistration_2026-08-11.json")
def canonical_hash(value:Any)->str:return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_credit_risk_appetite_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"The completed US cash-session return of high-yield corporate credit relative to investment-grade corporate credit isolates a traded credit-risk appetite impulse while reducing their common duration component. During elevated BTC variation, follow that relative credit impulse for twenty-four hours after both ETF closes are certainly public.","side":"long when log(HYG close/open)-log(LQD close/open) is strictly positive; short when strictly negative","why_distinct":"HVRPC requires same-sign SPY/TLT returns and measures cross-asset liquidity consensus. Treasury candidates use official yields; FX candidates use currencies; crypto candidates use derivatives or flow. HVCREDIT uses the same-session relative return of two corporate-credit quality tiers, no equity return, Treasury price, crypto direction, prior event, repair, or promoted control.","why_suited_to_volatile_regimes":"the preceding twenty-four-hour BTC realized variation must rank in its causal upper 35%, restricting credit transmission to July-like crypto risk states","why_low_gross9_overlap_is_plausible":"one external 23:05 UTC corporate-credit-quality clock per eligible US session is absent from Gross9 primitives"},
 external_basis={"hyg":{"official_source":"https://www.ishares.com/us/products/239565/ishares-iboxx-usd-high-yield-corporate-bond-etf","definition":"USD-denominated non-investment-grade corporate credit"},"lqd":{"official_source":"https://www.ishares.com/us/products/239566/ishares-iboxx-investment-grade-corporate-bond-etf","definition":"USD-denominated investment-grade corporate credit"},"selection_use":"official credit-quality exposures only; the same-session relative-return BTC relay is an untested preregistered adaptation; no incidence or outcomes"},
 features={"credit_source":"candidate-specific Yahoo chart raw unadjusted HYG and LQD regular-session daily open/close snapshots downloaded only after preregistration push","session":"same US trading date D with finite positive raw opens and closes for both ETFs","hyg_return":"log(HYG close/open)","lqd_return":"log(LQD close/open)","relative_credit_return":"hyg_return-lqd_return, finite strict nonzero","availability":"D 23:00 UTC, safely after the 16:00 America/New_York regular close in EST and EDT","btc_variation":"sqrt(sum squared exact BTCUSDT five-minute open-to-close log returns over the prior 24 elapsed hours ending at decision)","variation_rank":"strict-prior midrank over at most 270 previous valid daily 23:00 UTC states, minimum 180, current excluded; rank>=0.65","no_adjusted_close":True,"no_imputation":True},
 clock={"decision":"each shared HYG/LQD regular-session date D at 23:00 UTC","entry":"exact BTCUSDT 23:05 UTC open","hold":"24 elapsed hours","side":"strict relative-credit-return sign","reservation":"chronological global half-open nonoverlap; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"variation_history_decisions":270,"minimum_variation_history_decisions":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","hyg_only","inverse_lqd_only","one_session_stale_credit","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"hyg":"Yahoo chart query1=2022-09-01 query2=2026-08-02 exclusive interval=1d events=history; raw open/close only","lqd":"same contract","destination":"data/high_volatility_credit_risk_appetite_relay_sources_2022_2026/hyg_lqd_sessions.csv.gz","btc":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"official_etf_definitions_read":True,"repository_hyg_lqd_candidate_found":False,"prior_spy_tlt_treasury_fx_outcomes_known":True,"credit_values_opened":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent traded corporate-credit-quality risk channel plus requested high BTC variation"},
 stopping_rule="Terminal first failure; no ETF substitution, adjusted-price use, session, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(value):
 core={k:v for k,v in value.items() if k!="manifest_hash"}
 if value.get("manifest_hash")!=canonical_hash(core) or value!=build():raise RuntimeError("HVCREDIT preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
