"""Outcome-blind preregistration for HVRPCTR-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_cross_structure_action_vote as gates
POLICY_ID="HVRPCTR-24";DEFAULT_OUTPUT=Path("results/high_volatility_risk_parity_consensus_transition_preregistration_2026-08-18.json");SOURCE=Path("data/high_volatility_risk_parity_consensus_relay_sources_2020_2026/daily_consensus_states.csv.gz");SOURCE_SHA="35d7a19dcf1840c46aa5625f92e670bdd62b7036e6b05d659c6c0975ae334b50"
def sha256(p:str|Path)->str:return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 g=gates.build();core={"protocol_version":"high_volatility_risk_parity_consensus_transition_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-18","singleton":True,"candidate_family":[POLICY_ID],"candidate_family_size":1,"source_incidence_opened":False,"outcomes_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"A polarity transition between consecutive same-direction SPY/TLT consensus sessions changes the broad risk-parity liquidity regime rather than merely extending a level. During elevated BTC variation, follow the new common direction for twenty-four hours.","side":"new common strict sign of SPY and TLT after an opposite common sign at the immediately prior source-valid session","why_distinct":"HVRPC trades every high-variation SPY/TLT consensus level and failed train. HVRPCTR trades only common-direction polarity transitions between consecutive frozen consensus sessions, forming a new event topology. It uses no HVRPC event set/control, credit spread, crypto direction, OI, funding, premium, options, fitted outcome, or promoted control.","why_low_gross9_overlap_is_plausible":"irregular external risk-parity consensus polarity transitions are sparser than the terminal level clock"},
 "features":{"source":{"path":str(SOURCE),"sha256":SOURCE_SHA},"consensus":"current SPY and TLT returns are strict nonzero with one common sign","previous":"immediately prior source-valid shared cash session is also consensus","transition":"current and previous common consensus signs are strict opposites","availability":"current session date 23:00 UTC","variation_gate":"frozen causal BTC variation_rank>=0.65","no_imputation":True},"policy":{"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},"clock":{"entry":"decision+5m exact BTCUSDT open","hold":"24 elapsed hours","reservation":"chronological half-open nonoverlap; exit first on equal entry","funding":"not signal input; exact settlements after Gross9"},
 "stages":g["stages"],"source_support_gates":g["source_support_gates"],"gross9_novelty_gates":g["gross9_novelty_gates"],"economic_gates":g["economic_gates"],"diagnostic_controls":{"names":["no_variation_gate","level_not_transition","one_session_stale_transition","previous_side","direction_flip","forced_long"],"cannot_be_promoted":True},"research_boundary":{"prior_HVRPC_train_failure_known":True,"HVRPC_event_set_or_controls_reused":False,"exact_transition_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"classification":"exploratory discovery; not fresh confirmatory evidence","selection_basis":"risk-parity consensus polarity transition"},"stopping_rule":"source, Gross9, train/test/eval/final; terminal first failure; no assets, consensus, previous-session law, transition, variation, side, clock, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x!=build():raise RuntimeError("HVRPCTR prereg drift")
 if sha256(SOURCE)!=SOURCE_SHA:raise RuntimeError("HVRPCTR source drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
