"""Preregister CFTCMSPS-168 before computing its incidence or outcomes."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any

POLICY_ID="CFTCMSPS-168"
DEFAULT_OUTPUT=Path("results/cftc_micro_standard_positioning_segmentation_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c={
  "protocol_version":"cftc_micro_standard_positioning_segmentation_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-11","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
  "mechanism":{"claim":"A weekly increase in standard CME Bitcoin asset-manager net share relative to the simultaneous change in Micro Bitcoin leveraged-money net share identifies institutional positioning that is not mirrored by the smaller-contract speculative segment. During elevated BTC variation, follow the sign of that cross-contract segmentation for one report cycle.","side":"strict sign of delta[(standard asset-manager long-short)/standard OI] minus delta[(micro leveraged-money long-short)/micro OI]","why_distinct":"CAMOP2W isolated standard-contract option positions and waited for a published second-week effect. CITA compared standard-contract participant classes. CFTCMSPS uses futures-only cross-contract segmentation between standard institutional and Micro leveraged-money positioning, no options, no prior event set, and no prior control.","why_suited_to_volatile_regimes":"prior-24h BTC realized variation must be in its causal upper half","why_low_gross9_overlap_is_plausible":"one conservative weekly external regulatory segmentation clock is absent from Gross9"},
  "features":{"source":"official CFTC TFF futures-only annual files","standard_contract":{"name":"BITCOIN - CHICAGO MERCANTILE EXCHANGE","code":"133741","position":"Asset_Mgr_Positions_Long_All minus Asset_Mgr_Positions_Short_All, divided by Open_Interest_All"},"micro_contract":{"name":"MICRO BITCOIN - CHICAGO MERCANTILE EXCHANGE","code":"133742","position":"Lev_Money_Positions_Long_All minus Lev_Money_Positions_Short_All, divided by Open_Interest_All"},"weekly_changes":"current net share minus immediately prior report net share; both contracts require exact consecutive report dates seven calendar days apart","segmentation":"standard asset-manager share change minus micro leveraged-money share change; strict nonzero","conservative_availability":"Tuesday report date plus seven calendar days 00:00 UTC","btc_variation":"sqrt(sum squared exact completed BTCUSDT 5m close/open log returns over the prior 24 hours); daily-boundary strict-prior midrank over 270 states, minimum 180, current excluded; rank>=0.50","no_imputation":True,"grid":False},
  "clock":{"decision":"report_date+7 calendar days 00:00 UTC","entry":"decision+5m BTCUSDT open","hold":"168 elapsed hours","reservation":"weekly half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not a signal input; exact held settlements only after novelty","rv20":"q90 audit only after all economics pass"},
  "policy":{"variation_history_days":270,"variation_minimum_days":180,"variation_rank_min":.50,"report_delay_days":7,"entry_delay_minutes":5,"hold_hours":168,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
  "diagnostic_controls":{"names":["no_variation_gate","standard_asset_manager_only","micro_leveraged_only","one_report_stale_segmentation","direction_flip","forced_long"],"cannot_be_promoted":True},
  "source_plan":{"cftc":{"paths":"data/cftc_camop2w_raw/fut_fin_txt_2021.zip through fut_fin_txt_2026.zip","opened_for_prior_candidate_but_no_CFTCMSPS_formula_or_incidence_computed":True},"btc":"hash-bound completed 5m cache plus read-only Postgres extension through 2026-08-01","execution_prices":"sealed until source and novelty pass"},
  "research_boundary":{"prior_CFTC_raw_rows_opened":True,"exact_cross_contract_segmentation_formula_incidence_or_outcomes_known":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent standard-versus-micro regulated positioning segmentation"},
  "stopping_rule":"Terminal first failure; no contract, participant class, normalization, threshold, side, lag, hold, clock, subset, source, or control repair."}
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 if x["manifest_hash"]!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("CFTCMSPS manifest drift")
 if x["outcomes_opened"] or x["source_incidence_opened"] or x["gross9_rows_opened"]:raise RuntimeError("CFTCMSPS boundary opened")
def main()->None:
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
if __name__=="__main__":main()
