"""Outcome-blind preregistration for HVHCEM-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path('results/high_volatility_haar_coarse_energy_migration_continuation_preregistration_2026-08-10.json')
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={'protocol_version':'high_volatility_haar_coarse_energy_migration_continuation_v1','policy_id':'HVHCEM-12','as_of_date':'2026-08-10','outcomes_opened':False,'source_incidence_opened':False,'gross9_rows_opened':False,'singleton':True,
 'mechanism':{'claim':'In a high-variation completed BTC path, a causal upper-tail increase in the share of Haar detail energy carried by the three coarsest dyadic scales identifies locally organized multiscale repricing rather than fine-scale churn. Follow the completed path direction for twelve hours.','side':'strict sign of the sum of the 128 completed five-minute returns','why_distinct':'HVLFER used global DFT low-frequency energy over a full day; HVTPTF used linear time-price fit; HVSAR used lag-one return dependence; path classifiers fit outcomes. HVHCEM uses a dependency-free orthonormal Haar pyramid, localized non-overlapping 10h40m paths, and the change in coarse detail-energy share. It reuses no event set, control, model, flow, volume, funding, OI, premium, or external asset.','why_suited_to_volatile_regimes':'completed path variation must rank in its causal upper 35% and coarse-scale energy migration in its upper quartile','why_low_gross9_overlap_is_plausible':'sparse endogenous 00:05/12:05 UTC dyadic-energy migration clocks are absent from Gross9 primitives'},
 'features':{'decision_grid':'exact 00:00 and 12:00 UTC boundaries','path':'128 exact contiguous completed BTCUSDT five-minute returns over [decision-10h40m,decision), built from 640 exact coherent one-minute bars','five_minute_return':'log(last close/first open) for each exact five-row aggregate','haar_pyramid':'at each level pair adjacent values as approximation=(left+right)/sqrt(2), detail=(left-right)/sqrt(2), recursively through seven levels; no padding or library dependency','detail_energy_by_level':'sum squared detail coefficients for levels 1 through 7, where level 1 is finest and level 7 coarsest','coarse_energy_share':'sum detail energies at levels 5,6,7 divided by sum detail energies at all seven levels; denominator strict positive','coarse_energy_migration':'current coarse_energy_share minus immediately previous source-valid boundary share; strict positive','migration_rank':'strict-prior midrank over at most 270 previous valid migrations, minimum 252, current excluded; rank>=0.75','realized_variation':'sqrt(sum squared 128 five-minute returns)','variation_rank':'strict-prior midrank over at most 270 previous valid paths, minimum 252, current excluded; rank>=0.65','completed_return':'sum 128 returns; strict nonzero','no_imputation':True},
 'clock':{'decision':'exact boundary after all 640 source minutes complete','entry':'exact BTCUSDT decision+5m open','hold':'12 elapsed hours','reservation':'fixed half-day decisions; global half-open, exit first on equal open','split_crossing_action':'skip','gross_exposure':.5,'funding_oi_premium_rv20':'not signal inputs; exact funding only after novelty; RV20 q90 only after all stages pass'},
 'policy':{'bars':128,'haar_levels':7,'coarse_levels':[5,6,7],'prior_boundaries':270,'minimum_prior_boundaries':252,'migration_rank_min':.75,'variation_rank_min':.65,'entry_delay_minutes':5,'hold_hours':12,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 'stages':{'train':['2023-07-01T00:00:00Z','2024-01-01T00:00:00Z'],'test':['2024-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'eval':['2025-01-01T00:00:00Z','2026-01-01T00:00:00Z'],'final':['2026-01-01T00:00:00Z','2026-08-01T00:00:00Z']},
 'source_support_gates':{'minimum_events':{'train':8,'test':12,'eval':12,'final':8},'minority_side_share_min':.2,'max_month_share':.45},
 'novelty_gates':{'exact_entry_jaccard_max':.1,'candidate_near_6h_share_max':.35,'occupied_5m_bar_jaccard_max':.25,'absolute_signed_exposure_pearson_max':.35,'must_pass_before_economics':True},
 'economic_gates':{'absolute_return_positive':True,'cagr_to_strict_mdd_min':3.,'strict_mdd_max_pct':15.,'mean_gross_underlying_min_bp':20.,'weekly_signflip_one_sided_p_max':.1,'stress_absolute_return_positive':True,'stress_cagr_to_strict_mdd_min':2.5,'each_calendar_half_positive':True,'stop_on_first_failure':True,'future_can_rank_repair_or_reselect':False,'accounting':'fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR'},
 'source_plan':{'btc':{'table':'bars_binance','symbol':'BTCUSDT','interval':'1m','columns':['ts','open','high','low','close'],'read_after_preregistration':True},'execution_price':'sealed until source support and Gross9 novelty pass'},
 'diagnostic_controls':{'names':['no_migration_gate','no_volatility_gate','coarse_share_level','one_boundary_stale_migration','direction_flip'],'diagnostic_controls_cannot_be_promoted':True},
 'research_boundary':{'prior_wave_model_outcomes_known':True,'prior_exact_haar_energy_event_sets_reused':False,'candidate_incidence_opened':False,'postentry_return_or_pnl_opened':False,'gross9_rows_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False,'promoted_prior_control':False,'selection_basis':'independent deterministic localized Haar coarse-energy migration'},
 'stopping_rule':'Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no scale, rank, side, hold, clock, window, subset, or control repair.'}
 return {**core,'manifest_hash':canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!='manifest_hash'}
 if x.get('manifest_hash')!=canonical_hash(core) or x!=build():raise RuntimeError('HVHCEM preregistration drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+'\n');print(a.output)
