"""Outcome-blind preregistration for SPVTA-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/spot_perpetual_variance_transfer_asymmetry_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"spot_perpetual_variance_transfer_asymmetry_v1","policy_id":"SPVTA-8","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
  "mechanism":{"claim":"Within a completed eight-hour block, relocation of spot realized variation into the second four hours while perpetual variation does not relocate marks cash-market information arriving faster than derivatives path energy. If spot and perpetual agree on the final two-hour direction during a high-variation BTC regime, follow that direction for eight hours.","side":"common strict sign of completed final-two-hour spot and perpetual returns","why_distinct":"SLVCR used one-hour return magnitude partial transmission plus BVOL/DVOL expansion; cash-basis, spot-flow, and spot-participation candidates use level wedges, aggressive flow, or volume share. SPVTA uses only two-half venue-specific path-energy relocation and final-two-hour direction, with no prior event set or control.","why_suited_to_volatile_regimes":"perpetual completed prior-24h realized variation must rank in its causal upper 35%.","why_low_gross9_overlap_is_plausible":"three fixed daily boundaries conditioned on spot-versus-perpetual path-energy relocation are absent from Gross9 primitives."},
  "features":{"block":"exact eight completed consecutive UTC hours [D-8h,D) for BTCUSDT spot and perpetual at D hour 00, 08, or 16","hour_valid":"hash-bound source-valid positive open/close for both venues; no imputation","hour_return":"log(hour_close/hour_open) independently by venue","first_half_variation":"sum squared hour_return over first four hours","second_half_variation":"sum squared hour_return over final four hours","variation_share":"second_half_variation divided by total eight-hour variation, independently by venue; positive total required","relocation":"spot variation_share minus perpetual variation_share; strict positive","geometry":"spot variation_share>0.5 and perpetual variation_share<=0.5","relocation_rank":"strict-prior midrank of relocation over at most 90 prior valid blocks, minimum 60, current excluded; rank>=0.65","final_two_hour_return":"sum of final two completed hourly log returns independently by venue; both strict nonzero and same sign","btc_realized_variation":"sqrt(sum squared perpetual hourly returns over 24 hours ending at D)","volatility_rank":"strict-prior midrank over at most 90 valid decision blocks, minimum 60, current excluded; rank>=0.65","no_imputation":True},
  "clock":{"decision":"exact D at UTC hour 00, 08, or 16 after all source rows complete","entry":"exact BTCUSDT D+5m open","side":"common strict final-two-hour return sign","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","funding_oi_premium_implied_vol":"not signal inputs; exact funding only after novelty passes"},
  "policy":{"block_hours":8,"half_hours":4,"direction_hours":2,"prior_blocks":90,"prior_min_blocks":60,"relocation_rank_min":.65,"realized_variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "source_plan":{"spot_hourly":{"path":"data/spot_led_volatility_catchup_sources_2023_2026/spot_hourly.csv.gz","sha256":"94d398e948f1283321e3784abc2a2d5dfff7a2331ff88c9720754a5720d2c6fc"},"perpetual_hourly":"hash-bound completed-hour BTC source through 2026-08-01","execution_price":"sealed until source-support and Gross9 novelty pass"},
  "diagnostic_controls":{"names":["no_volatility_gate","no_relocation_tail","no_opposite_half_geometry","spot_direction_only","one_block_stale_relocation","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
  "research_boundary":{"prior_spot_perpetual_family_outcomes_known":True,"prior_spot_perpetual_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_spvta_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent venue-specific variance-relocation mechanism"},
  "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no block, halves, geometry, relocation, rank, direction, side, hold, clock, volatility, or subset repair."
 };return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+"\n");print(a.output)
