"""Outcome-blind preregistration for HVCRMR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/high_volatility_causal_response_memory_relay_preregistration_2026-08-09.json")
SOURCE_BINDINGS={"data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz":"a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"}
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"high_volatility_causal_response_memory_relay_v1","policy_id":"HVCRMR-12","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
  "mechanism":{"claim":"The sign of BTC's response to high-volatility twelve-hour shocks is regime-dependent. A causal memory of only already-completed comparable shocks can identify whether the current regime rewards continuation or reversal without selecting a fixed direction from future stages.","side":"current completed shock sign multiplied by the strict sign of the mean signed response of the latest 32 already-completed eligible shocks","why_distinct":"The 2026-07 causal-online-expert experiment selected among six outcome-contaminated legacy sleeves over a hyperparameter grid. HVCRMR has no expert pool, no sleeve reuse, no grid, no adverse-utility selection, and no future-stage ranking. It is one price-response law with one fixed memory and clock.","why_suited_to_volatile_regimes":"only source-calibrated upper-tail twelve-hour range and displacement shocks can enter the response memory or signal.","why_low_gross9_overlap_is_plausible":"Gross9 has no causal high-volatility response-memory state or fixed twelve-hour shock clock."},
  "features":{"decision":"exact 00:00 and 12:00 UTC boundaries","shock_window":"144 exact consecutive completed five-minute bars [D-12h,D)","shock_return":"log(last completed close/first open); strict nonzero","range_vol":"max(high)/min(low)-1 over the shock window","calibration":"2023H1 exact boundaries only: abs(shock_return) q60 and range_vol q65; no emitted OOS incidence or current-event post-entry outcome","eligible_opportunity":"abs(shock_return)>=q60 and range_vol>=q65","counterfactual_response":"for an eligible opportunity at U, sign(shock_return[U])*log(open[U+12h+5m]/open[U+5m]); it becomes available only at U+12h+5m","memory":"latest 32 counterfactual responses whose availability<=current decision D; at least 16; arithmetic mean must be strict nonzero","current_side":"sign(shock_return[D])*sign(mean(memory))","no_imputation":True,"grid":False},
  "clock":{"entry":"exact D+5m open","hold":"12 elapsed hours","reservation":"fixed boundaries are naturally half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "diagnostic_controls":{"names":["fixed_momentum","fixed_reversal","sixteen_response_memory","one_opportunity_stale_memory","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
  "source_plan":{"historical":"hash-bound five-minute market through 2026-06-01","live_extension":"read-only Postgres completed bars through 2026-08-01","execution_prices":"current emitted-event outcomes sealed until source support and Gross9 novelty pass; already-completed counterfactual responses are causal signal inputs"},"source_bindings":SOURCE_BINDINGS,
  "research_boundary":{"prior_online_expert_outcomes_known":True,"legacy_experts_or_events_reused":False,"prior_candidate_outcomes_used_to_set_hvcrmr_rule":False,"candidate_incidence_opened":False,"current_event_postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"singleton causal response-memory mechanism"},
  "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no calibration, memory, minimum history, response, side, hold, clock, or subset repair."
 };return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2)+'\n');print(a.output)
