"""Outcome-blind preregistration for HVSFLR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/high_volatility_spot_flow_leadership_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_spot_flow_leadership_relay_v1","policy_id":"HVSFLR-6","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
 "mechanism":{"claim":"At a fixed eight-hour boundary in an unusually volatile BTC block, same-direction final-two-hour spot and perpetual returns are more durable when Binance spot aggressive-flow imbalance has the same sign, has absolute magnitude at least 0.10, and is at least 1.5 times the perpetual imbalance magnitude. Follow the cash-led direction for six elapsed hours.","side":"common strict nonzero sign of final-two-hour spot return, perpetual return, and spot taker imbalance","why_distinct":"HVSFLR compares direct spot and perpetual aggressive-flow strength to identify cash leadership. HVAFC used perpetual flow alone; SPVIR used spot volume participation plus BVOL/DVOL ignition; SLVCR used price catch-up rather than taker-flow leadership. No prior event set or control is reused.","why_suited_to_volatile_regimes":"completed perpetual eight-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"three fixed UTC cross-market flow-leadership clocks are absent from Gross9"},
 "features":{"sources":["BTCUSDT bars_binance interval=1m","BTCUSDT bars_binance_spot interval=1m"],"block_valid":"480 exact aligned distinct minute rows per source in [decision-8h,decision), finite positive coherent OHLC, finite nonnegative quote_asset_volume and taker_buy_quote, taker_buy_quote<=quote_asset_volume, positive final-two-hour quote volume in both sources; no imputation","spot_late_return":"log(spot close at decision-1m/spot open at decision-2h)","perp_late_return":"log(perp close at decision-1m/perp open at decision-2h)","normalized_taker_imbalance":"(2*sum(taker_buy_quote)-sum(quote_asset_volume))/sum(quote_asset_volume) over final two hours, separately by source","leadership":"abs(spot imbalance)>=0.10 and abs(spot imbalance)>=1.5*abs(perp imbalance)","direction_confirmation":"spot return, perp return and spot imbalance share one strict nonzero sign","realized_variation":"sum squared perpetual 1m close-to-close log returns within completed 8h block","variation_rank":"strict-prior midrank among at most 270 valid fixed eight-hour blocks, minimum 180, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact 00:00,08:00,16:00 UTC","entry":"exact decision+5m BTCUSDT perpetual open","hold":"6 elapsed hours","reservation":"global half-open; exit first on equal open","funding_oi_premium_implied_vol":"not signal inputs; exact funding only after novelty passes"},
 "policy":{"history_observations":270,"minimum_history_observations":180,"variation_rank_min":.65,"absolute_spot_taker_imbalance_min":.10,"spot_to_perp_imbalance_ratio_min":1.5,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"perp_1m":{"table":"bars_binance","columns":["ts","open","high","low","close","quote_asset_volume","taker_buy_quote"]},"spot_1m":{"table":"bars_binance_spot","columns":["ts","open","high","low","close","quote_asset_volume","taker_buy_quote"]},"symbol":"BTCUSDT","interval":"1m","window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"materialize_after_preregistration":True,"execution_price":"sealed until source-support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_volatility_gate","no_leadership_ratio_gate","one_boundary_stale_geometry","direction_fade"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"prior_spot_perp_candidate_incidence_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_hvsflr_direction_threshold_hold_or_clock":False,"hvsflr_candidate_incidence_opened":False,"hvsflr_post_entry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent high-volatility cash-flow leadership mechanism"},
 "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no threshold, side, hold, clock, leadership, or subset repair."}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+"\n");print(a.output)
