"""Outcome-blind preregistration for DTFAR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/daily_taker_flow_acceleration_relay_preregistration_2026-08-08.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"daily_taker_flow_acceleration_relay_v1","policy_id":"DTFAR-12","as_of_date":"2026-08-08","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
 "mechanism":{"claim":"At the fixed UTC day boundary, a one-standard-deviation daily acceleration in normalized aggressive BTC/USDT taker flow during an unusually volatile BTC day identifies a fresh migration of directional liquidity rather than a persistent crowded level. The flow-acceleration direction should relay for twelve hours.","side":"sign of the completed daily change in normalized BTCUSDT taker flow","why_distinct":"DTFAR trades the first difference of daily dominant-book normalized flow. DAFSR and DAFCAR conditioned on the flow level's sign relationship with price; DSQFCR used cross-denominator same-day consensus; intrahour flow candidates used dense BTC activity clocks.","why_suited_to_volatile_regimes":"completed-day realized variation must be in its causal upper 35%","why_low_gross9_overlap_is_plausible":"one 00:05 UTC daily flow-acceleration clock is absent from Gross9"},
 "features":{"normalized_flow":"daily sum(signed_taker_flow_btc)/sum(base_volume_btc) from 24 source-complete BTCUSDT hours","flow_change":"current completed-day normalized flow minus immediately prior completed-day normalized flow, nonzero","flow_change_z":"standardized against at most 90 strictly prior finite changes, minimum 60, current excluded; prior sample std positive","flow_gate":"abs(flow_change_z)>=1.0","realized_variation":"sqrt(sum of 24 squared completed-hour BTC log returns)","volatility_rank":"strict-prior midrank against at most 90 valid days, minimum 60; current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact D 00:00 UTC after every source feature is available","entry":"exact BTCUSDT D+5m open","side":"sign(flow_change)","hold":"12 elapsed hours","reservation":"fixed daily decisions; global half-open, exit first on equal open","price_direction_oi_funding_implied_vol":"not signal inputs; exact funding only for later PnL"},
 "policy":{"prior_days":90,"prior_min_days":60,"absolute_flow_change_z_min":1.0,"realized_variation_rank_min":0.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":0.5,"base_cost_per_notional_side":0.0006,"stress_cost_per_notional_side":0.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":0.20,"max_month_share":0.45},"novelty_gates":{"exact_entry_jaccard_max":0.10,"candidate_near_6h_share_max":0.35,"occupied_5m_bar_jaccard_max":0.25,"absolute_signed_exposure_pearson_max":0.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.0,"strict_mdd_max_pct":15.0,"mean_gross_underlying_min_bp":20.0,"weekly_signflip_one_sided_p_max":0.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"flow":"hash-bound Binance stablecoin quote-flow panel through 2026-07-31","completed_price":"hash-bound completed-hour BTC through 2026-08-01 for pre-entry variation only","execution_price":"sealed until source-support and Gross9 novelty pass"},"diagnostic_controls":{"names":["no_volatility_gate","no_flow_tail","flow_level","one_day_stale_acceleration","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"prior_daily_flow_candidate_incidence_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_define_dtfar":False,"dtfar_candidate_incidence_opened":False,"dtfar_post_entry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent daily flow-acceleration mechanism"},"stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no threshold, side, hold, clock, or subset repair."}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+"\n");print(a.output)
