"""Outcome-blind preregistration for HVERDR-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_cross_structure_action_vote as gates
POLICY_ID="HVERDR-24";DEFAULT_OUTPUT=Path("results/high_volatility_equity_duration_rotation_relay_preregistration_2026-08-18.json");SOURCE=Path("data/high_volatility_risk_parity_consensus_relay_sources_2020_2026/daily_consensus_states.csv.gz");SOURCE_SHA="35d7a19dcf1840c46aa5625f92e670bdd62b7036e6b05d659c6c0975ae334b50"
def sha256(p:str|Path)->str:return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 g=gates.build();core={"protocol_version":"high_volatility_equity_duration_rotation_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-18","singleton":True,"candidate_family":[POLICY_ID],"candidate_family_size":1,"source_incidence_opened":False,"outcomes_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"Opposite completed US cash-session returns in SPY and TLT identify a rotation between equity risk appetite and duration demand rather than a common liquidity impulse. During elevated BTC variation, follow the SPY risk-on/off direction for twenty-four hours.","side":"strict sign of SPY regular-session open-to-close return when TLT has the opposite strict sign","why_distinct":"HVRPC requires same-sign SPY/TLT consensus; HVERDR uses the mutually exclusive disagreement state. Sector and credit candidates use different assets, while Treasury candidates use yields. It uses no HVRPC event set or controls, crypto direction, OI, funding, premium, options, fitted outcome, or promoted control.","why_low_gross9_overlap_is_plausible":"external conditional 23:05 UTC equity-duration rotation sessions are absent from Gross9"},
 "features":{"source":{"path":str(SOURCE),"sha256":SOURCE_SHA},"session":"same frozen US cash-session date with finite positive raw unadjusted SPY/TLT opens and closes","disagreement":"SPY and TLT returns strict nonzero with opposite signs","availability":"session date at 23:00 UTC after both regular closes","variation_gate":"frozen causal seven-day BTC variation_rank>=0.65","no_imputation":True},"policy":{"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},"clock":{"decision":"frozen 23:00 UTC session availability","entry":"23:05 UTC exact BTCUSDT open","hold":"24 elapsed hours","reservation":"chronological half-open nonoverlap; exit first on equal entry","funding":"not signal input; exact settlements after Gross9"},
 "stages":g["stages"],"source_support_gates":g["source_support_gates"],"gross9_novelty_gates":g["gross9_novelty_gates"],"economic_gates":g["economic_gates"],"diagnostic_controls":{"names":["no_variation_gate","spy_only","tlt_direction","one_session_stale_disagreement","direction_flip","forced_long"],"cannot_be_promoted":True},
 "research_boundary":{"prior_HVRPC_train_failure_known":True,"HVRPC_event_set_or_controls_reused":False,"exact_disagreement_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"classification":"exploratory discovery; not fresh confirmatory evidence","selection_basis":"mutually exclusive equity-duration rotation state"},"stopping_rule":"source, Gross9, train/test/eval/final; terminal first failure; no source, disagreement, variation, side, clock, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x!=build():raise RuntimeError("HVERDR prereg drift")
 if sha256(SOURCE)!=SOURCE_SHA:raise RuntimeError("HVERDR source drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
