"""Outcome-blind preregistration for HVDCOS-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID='HVDCOS-8';DEFAULT_OUTPUT=Path('results/high_volatility_directional_change_fresh_overshoot_relay_preregistration_2026-08-11.json')
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop('manifest_hash')
 c.update(protocol_version='high_volatility_directional_change_fresh_overshoot_relay_v1',policy_id=POLICY_ID,as_of_date='2026-08-11',
 mechanism={'claim':'A fixed-threshold directional change starts a new intrinsic-time overshoot regime. When a reversal is confirmed within the final hour of a completed high-variation eight-hour BTC block, follow the newly confirmed intrinsic direction for the next eight hours.','side':'long after the latest confirmed upward directional change; short after the latest confirmed downward directional change','why_distinct':'Prior directional-change scarcity work counted reversals and combined count tails with total displacement; intrinsic-topology work fed multi-threshold densities into a fitted classifier. HVDCOS uses neither count scarcity nor fitted topology: it uses one strictly prior volatility-scaled threshold, the state-machine direction of the latest confirmation, and confirmation recency. It reuses no prior event set or control and uses no volume, flow, OI, funding, or outcome fitting.','why_suited_to_volatile_regimes':'the completed current eight-hour realized variation must rank in its causal upper 35%','why_low_gross9_overlap_is_plausible':'sparse intrinsic-time confirmations occurring in the final physical hour at 00/08/16 UTC boundaries are absent from Gross9 primitives'},
 external_basis={'origin':'Golub, Chliamovitch, Dupuis and Chopard, Multi-scale Representation of High Frequency Market Liquidity','paper':'https://arxiv.org/pdf/1402.2198','paper_sha256':'4b65227e4da7eaaaaf381c20c8716e0c1c99d80abfd188d6bf0456c5f30bc166','support':'directional changes and subsequent overshoots provide an event-based intrinsic-time state representation','selection_use':'canonical fixed-threshold directional-change/overshoot state machine only; BTC threshold scaling, recency, direction and hold application are untested; no incidence or outcomes'},
 features={'decision_grid':'exact 00:00, 08:00 and 16:00 UTC boundaries','prior_scale_window':'288 exact nonoverlapping five-minute closes over [T-32h,T-8h), yielding 287 close-to-close log returns','directional_change_threshold':'sqrt(sum squared prior-scale returns / 24), a fixed one-hour realized standard-deviation scale, finite strict positive and frozen for the entire current block','current_path':'96 exact nonoverlapping five-minute closes over [T-8h,T)','state_machine':'initialize from the first close; establish initial up/down mode after a threshold move from the running opposite extreme; thereafter confirm down when peak-current>=threshold and confirm up when current-trough>=threshold, resetting the active extreme at confirmation','event':'at least one post-initialization directional change is confirmed; the latest confirmation close is in [T-1h,T)','side':'latest confirmed intrinsic direction, strict +1 or -1','current_variation':'sqrt(sum squared 95 current-path close-to-close returns), finite strict positive','variation_rank':'strict-prior midrank over at most 270 earlier source-valid decisions, minimum 180, current excluded; rank>=0.65','no_imputation':True},
 clock={'feature_available':'completed eight-hour boundary','entry':'exact BTCUSDT boundary+5m open','hold':'8 elapsed hours','reservation':'global half-open; exit first on equal open','gross_exposure':.5,'funding':'not a signal input; exact settlements only after novelty passes'},
 policy={'prior_scale_hours':24,'current_block_hours':8,'threshold_hours':1,'fresh_confirmation_minutes':60,'variation_history_decisions':270,'minimum_variation_history_decisions':180,'variation_rank_min':.65,'entry_delay_minutes':5,'hold_hours':8,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 diagnostic_controls={'names':['no_variation_gate','any_confirmation_in_block','current_block_return_side','one_block_stale_confirmation','direction_flip','forced_long'],'cannot_be_promoted':True},
 source_plan={'bars':{'table':'bars_binance','symbol':'BTCUSDT','interval':'1m','columns':['ts','open','high','low','close'],'window':['2023-04-01T00:00:00Z','2026-08-01T00:00:00Z'],'read_after_preregistration':True},'execution_price':'sealed until source support and Gross9 novelty pass'},
 research_boundary={'directional_change_definition_read':True,'repository_fresh_overshoot_candidate_found':False,'prior_directional_change_count_and_topology_outcomes_known':True,'prior_event_sets_reused':False,'prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock':False,'candidate_incidence_opened':False,'postentry_return_or_pnl_opened':False,'gross9_rows_opened':False,'candidate_count':1,'grid':False,'repair_of_directional_change_scarcity':False,'repair_of_intrinsic_topology_classifier':False,'promoted_prior_control':False,'selection_basis':'published fixed-threshold directional-change overshoot state representation under the requested high-variation regime'},
 stopping_rule='Terminal first failure; no threshold scale, current window, confirmation recency, variation rank, side, hold, clock, subset, control, or other repair.')
 return {**c,'manifest_hash':canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!='manifest_hash'}
 if v.get('manifest_hash')!=canonical_hash(core) or v!=build():raise RuntimeError('HVDCOS-8 preregistration drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+'\n');print(a.output)
