"""Outcome-blind preregistration for HVDFRM-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVDFRM-12";DEFAULT_OUTPUT=Path("results/high_volatility_dollar_factor_response_memory_relay_preregistration_2026-08-09.json")
FACTOR=Path("data/dollar_factor_shock_relay_sources_2023_2026/dollar_factor_sessions.csv.gz");FACTOR_SHA="b7c533dc5c21685184b09efad2a813ded9e4099a73685486d8ea88a0b00ac790";FACTOR_MANIFEST=FACTOR.parent/"manifest.json";FACTOR_MANIFEST_SHA="44d7c8aaa0349be6db7c8790b86c5324af490afc14ffd48c54069a6f9fc7f6fa"
MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_dollar_factor_response_memory_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","singleton":True,"current_candidate_outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"The sign of BTC's response to a robust completed global-dollar factor is regime-dependent. At each high-variation weekday close, the signed mean of only the latest already-completed dollar-factor responses identifies whether direct or inverse transmission currently dominates; apply that causal orientation to the current factor for twelve hours.","side":"factor sign multiplied by sign of the latest-32 mean of factor-sign times mature twelve-hour BTC response","why_distinct":"DFSR fixes inverse transmission and applies a factor-tail gate. HVCRMR stores responses to BTC price shocks. HVDOER selects among raw-price experts at 03:00. HVDFRM uses every high-variation full-session external dollar factor, one fixed response law, no factor tail, no expert pool, and no future-stage fit.","volatile_market_target":"pre-decision BTC 24-hour realized-variation rank at least 0.65","why_low_gross9_overlap_is_plausible":"weekday 21:05 UTC external-factor response-memory clocks are absent from Gross9"},
 "features":{"factor_source":"hash-bound six-pair DFSR source-only full-session dollar factors; no DFSR event clock or side reused","decision":"exact source weekday 21:00 UTC","factor":"strict nonzero median standardized canonical-dollar factor","variation":"sqrt(sum squared exact completed hourly BTC returns over prior 24h)","variation_rank":"strict-prior midrank over at most 90 valid weekday decisions, minimum 60, current excluded; rank>=0.65","mature_response":"factor sign at prior eligible decision times log(BTC open at entry+12h / BTC open at entry); label enters memory only after exit open","response_memory":"arithmetic mean of latest at most 32 mature eligible responses, minimum 20, current and unmatured excluded, strict nonzero","no_imputation":True},
 "causal_label_authorization":{"allowed_before_incidence":"only prior eligible response labels whose twelve-hour exit open is at or before current decision","same_decision_or_unmatured_label_forbidden":True,"funding_pnl_cagr_mdd_forbidden":True},
 "clock":{"entry":"exact weekday 21:05 UTC open","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium_rv20":"not signal inputs; exact funding after novelty; RV20 q90 only after all economics pass"},
 "policy":{"response_memory":32,"minimum_mature_responses":20,"variation_prior_days":90,"variation_minimum_days":60,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","fixed_inverse_factor","fixed_direct_factor","one_observation_stale_memory","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"factor":{"path":str(FACTOR),"sha256":FACTOR_SHA,"manifest":str(FACTOR_MANIFEST),"manifest_sha256":FACTOR_MANIFEST_SHA},"historical_market":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m through 2026-08-01","execution_prices":"sealed except causally mature response-label opens until source and novelty pass"},
 "research_boundary":{"prior_fixed_fx_and_online_outcomes_known":True,"exact_hvdfrm_incidence_or_current_outcomes_known":False,"candidate_incidence_opened":False,"current_candidate_postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent external-factor causal response-memory mechanism"},
 "stopping_rule":"terminal first failure; no factor, memory, label, variation, side, clock, timing, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVDFRM preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
