"""Outcome-blind preregistration for CAEVC-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="CAEVC-8";DEFAULT_OUTPUT=Path("results/cross_asset_elasticity_vacuum_continuation_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"cross_asset_elasticity_vacuum_continuation_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When BTC makes a large completed-hour move while its standardized execution-count response is unusually weak relative to its realized path variation and to the same elasticity across six liquid alts, the move reflects a BTC-specific participation vacuum rather than broad two-way risk transfer. Follow the completed BTC direction for eight elapsed hours at the new lower-tail crossing.","side":"strict sign of the completed BTC hour return","why_distinct":"CAEVC compares count-response-minus-path-variation elasticity cross-sectionally. HVLIR used BTC return divided by quote turnover; cross-asset volatility breadth counted alt volatility states; ticket candidates divided notional by trades. CAEVC uses neither notional, ticket size, taker direction, volume strata, funding, OI, nor a fitted outcome model.","volatile_market_target":"the BTC absolute completed-hour return must be in its causal top quintile; RV20 q90 remains only a later audit","why_low_gross9_overlap_is_plausible":"new hourly lower-tail crossings of a seven-symbol activity-elasticity residual plus an eight-hour reservation"},
 "features":{"symbols":["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT"],"decision_grid":"every exact UTC hour D","hour_window":"12 exact coherent completed five-minute aggregates [D-1h,D) per symbol","hour_return":"r_s=log(last 5m close/first 5m open)","path_variation":"v_s=sqrt(sum(log(5m close/5m open)^2)) over all 12 bars, strict positive","execution_count":"N_s=sum number_of_trades over all 60 constituent one-minute rows, strict positive integer","prior_zscore":"for each symbol and feature independently, (current-prior mean)/prior sample standard deviation over at most 720 prior valid hours, minimum 672, current excluded, positive finite prior standard deviation required","activity_elasticity":"A_s=z(log1p(N_s))-z(v_s)","cross_asset_vacuum":"Q=A_BTC-median(A_ETH,A_SOL,A_BNB,A_XRP,A_DOGE,A_ADA)","tail_ranks":"strict-prior midranks of Q and abs(r_BTC) over at most 2160 prior valid seven-symbol hours, minimum 1440, current excluded","eligible_state":"Q_rank<=0.10 and abs(BTC hour return)_rank>=0.80 and BTC return strict nonzero","onset":"current eligible state true and immediately preceding exact hourly opportunity has Q_rank>0.10; a missing prior opportunity cannot trigger","source_valid":"all seven symbols have exact unique 1m grids, coherent finite positive OHLC, integer nonnegative number_of_trades, 12 complete 5m aggregates and positive hourly count; no imputation"},
 "rv20_stress_slice":{"rv20":"sqrt(365*mean exact daily returns^2 over t-20 through t-1)","threshold":"numpy linear q90 over 756 strictly prior available RV20 observations","entry_filter":False,"future_use":"only after all sequential full-calendar stages pass"},
 "clock":{"decision":"exact UTC hour after all seven completed paths are available","entry":"exact BTCUSDT decision+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact realized BTC funding only after novelty"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","persistent_long_vol_comparator":"same accepted clock and 0.5 gross, side forced long","full_calendar_decomposition":"candidate minus comparator net return","rv20_q90_decomposition":"same decomposition on causal RV20 q90 decisions","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"candidate_specific_q90_residual_positive":True,"comparator_cannot_satisfy_candidate_claim":True},
 "diagnostic_controls":{"definitions":{"btc_only_activity_vacuum":"strict-prior bottom-decile crossing of A_BTC with the same BTC return-tail gate and side","cross_asset_vacuum_without_return_tail":"strict-prior bottom-decile crossing of Q with nonzero BTC return, side=sign(return)","btc_return_tail_only":"strict-prior top-quintile abs BTC hourly return crossing, side=sign(return)","one_hour_stale_elasticity":"primary eligible boolean and side shifted by one exact hour with onset applied after the shift","direction_flip":"negative primary side"},"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbols":["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT"],"interval":"1m","columns":["ts","open","high","low","close","number_of_trades"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"exact_caevc_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no symbol, zscore, history, rank, onset, side, clock, hold, RV20, subset, comparator, control, or gate repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("CAEVC preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+"\n");print(a.output)
