"""Outcome-blind preregistration for HVSDD-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVSDD-8";DEFAULT_OUTPUT=Path("results/high_volatility_spot_displacement_dominance_relay_preregistration_2026-08-13.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_spot_displacement_dominance_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-13",
 mechanism={"claim":"In an elevated-variation BTC auction, a completed direction repeatedly carried more strongly by spot than perpetual price displacement across most nonoverlapping half-hour intervals represents cash-sponsored price discovery rather than leverage-led marking; follow the common completed direction for eight elapsed hours.","side":"common strict sign of completed eight-hour spot and perpetual returns","why_distinct":"HVSDD counts interval-level same-direction cash displacement dominance using returns only. Cash-participation migration uses quote-turnover shares; spot-flow leadership uses aggressor flow; first-passage leadership uses barrier timing; basis/error-correction uses price-level spread; variance transfer discards direction. HVSDD uses no volume, flow, basis, fitted outcome, OI, funding, prior event, or control.","why_suited_to_volatile_regimes":"current perpetual variation must occupy its causal upper thirty-five percent and cash must dominate at least two-thirds of half-hour directional intervals","why_low_gross9_overlap_is_plausible":"offset cross-market interval-dominance clocks are absent from Gross9 primitives"},
 features={"decision_grid":"exact 02:00, 10:00, and 18:00 UTC boundaries","paths":"96 exact completed aligned spot and perpetual five-minute closes over [D-8h,D)","half_hour_returns":"sixteen nonoverlapping log(last close/first open) returns per venue from exact six-bar groups","cash_dominant_interval":"spot and perpetual half-hour returns share one strict sign and abs(spot return)>abs(perpetual return)","dominance_share":"cash-dominant interval count/16; must be >=2/3","aggregate_confirmation":"completed eight-hour spot and perpetual returns share one strict nonzero sign","perpetual_variation":"sqrt(sum squared 95 five-minute close-to-close perpetual returns), finite strict positive","variation_rank":"strict-prior midrank over at most 270 earlier jointly source-valid decisions, minimum 180, current excluded; rank>=0.65","eligibility":"dominance and aggregate confirmation and variation gate","no_imputation":True},
 clock={"feature_available":"offset eight-hour boundary after both paths complete","entry":"exact perpetual BTCUSDT open five elapsed minutes later","side":"common completed direction","hold":"8 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":0.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"bar_minutes":5,"path_bars":96,"interval_bars":6,"intervals":16,"dominance_min":2/3,"history_decisions":270,"minimum_history_decisions":180,"variation_rank_min":0.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":0.5,"base_cost_per_notional_side":0.0006,"stress_cost_per_notional_side":0.001},
 diagnostic_controls={"names":["no_variation_gate","simple_majority_dominance","no_aggregate_confirmation","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"spot":{"table":"bars_binance_spot","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"perpetual":{"table":"bars_binance","same_symbol_interval_columns_window":True,"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"interval_level_cash_displacement_dominance_selected":True,"repository_exact_spot_displacement_dominance_candidate_found":False,"adjacent_cash_participation_flow_first_passage_basis_and_variance_candidates_known":True,"adjacent_candidate_outcomes_used_to_set_formula_side_hold_clock_or_threshold":False,"prior_event_sets_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"fixed sixteen-interval cash displacement dominance and high-variation confirmation"},
 stopping_rule="Terminal first failure; no interval, dominance, confirmation, variation rank, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v:dict[str,Any])->None:
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVSDD preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
