"""Outcome-blind preregistration for FGER-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/fear_greed_extremity_reversal_preregistration_2026-08-09.json")
SOURCE_URL="https://api.alternative.me/fng/?limit=0&format=json"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"fear_greed_extremity_reversal_v1","policy_id":"FGER-24","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
 "mechanism":{"claim":"In an already high-volatility BTC regime, a published Crypto Fear & Greed extreme represents sentiment-linked liquidity withdrawal and overreaction. Extreme fear is faded long and extreme greed is faded short for one day.","side":"long when the lagged published index is <=25; short when it is >=75","external_support":{"paper":"Farzulla (2026), The Extremity Premium: Sentiment Regimes and Adverse Selection in Cryptocurrency Markets","arxiv":"2602.07018v3","supported_fact":"fear and greed extremes exhibit uncertainty-linked liquidity withdrawal beyond neutral regimes","implementation_is_not_a_published_replication":True,"untested_adaptation":"extreme states are tested as contrarian BTC return signals"},"why_distinct":"No prior repository alpha uses the Alternative.me Fear & Greed history. FGER uses a daily behavioral state, not price-only range, flow, funding, options, or a terminal control.","why_suited_to_volatile_regimes":"BTC prior-24h realized variation must rank at least 0.65 causally","why_low_gross9_overlap_is_plausible":"one-day-lagged sentiment-extreme entries at 00:05 UTC are absent from Gross9 primitives"},
 "features":{"index_source":"Alternative.me Crypto Fear & Greed historical JSON","extremes":{"fear_max":25,"greed_min":75},"availability":"an index row labeled UTC date D is not usable until D+1 00:00 UTC, regardless of API timestamp","btc_variation":"sqrt(sum squared log(close/open)) over exact BTCUSDT 1m bars [D,D+1d) completed at D+1 00:00 UTC","btc_variation_rank":"strict-prior midrank against at most 90 prior daily variations; minimum 60; current excluded; rank>=0.65","missing_duplicate_or_conflicting":"ineligible or source failure; no imputation"},
 "clock":{"decision":"daily 00:00 UTC after the one-day-lagged index and prior BTC day are complete","entry":"exact 00:05 UTC BTCUSDT 5m open","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium":"not signal inputs; exact funding only after novelty passes","no_imputation":True},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},"economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"sentiment":{"url":SOURCE_URL,"download_after_preregistration":True,"fields":["value","value_classification","timestamp"]},"btc_1m":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","close"],"read_only":True},"execution_price":"sealed until source support and Gross9 novelty pass"},"diagnostic_controls":{"names":["no_volatility_gate","classification_text_only","one_day_stale_sentiment","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},"research_boundary":{"source_transport_checked_without_body":False,"source_values_used_to_select_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published sentiment-extremity mechanism plus standard provider category boundaries and user-required high volatility"},"stopping_rule":"terminal first-failure sequence: source support, Gross9 novelty, strict economics; no threshold, lag, direction, hold, timing, volatility, or subset repair"}
 return {**core,"manifest_hash":canonical_hash(core)}
def validate(r:dict[str,Any])->None:
 if r.get("manifest_hash")!=canonical_hash({k:v for k,v in r.items() if k!="manifest_hash"}) or r.get("outcomes_opened") is not False or r.get("source_incidence_opened") is not False:raise RuntimeError("FGER preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
