"""Outcome-blind preregistration for VGSFR-6."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any

DEFAULT_OUTPUT=Path("results/volatility_gated_stablecoin_sequential_follower_relay_preregistration_2026-08-08.json")
def canonical_hash(value:Any)->str:return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"volatility_gated_stablecoin_sequential_follower_relay_v1","policy_id":"VGSFR-6","as_of_date":"2026-08-08","outcomes_opened":False,
 "mechanism":{"claim":"In an already elevated cross-venue implied-volatility regime, aggressive BTC spot flow that appears first in exactly one alternative stablecoin quote book and then propagates to the second while USDT remains behind identifies ordered liquidity diffusion; the alternative-book direction should relay for six hours.","side":"sign of the prior-hour alternative-book leader","why_distinct":"VGSFR is a two-hour ordered leader-to-follower transition across BTCUSDC/BTCFDUSD under a high BVOL-and-DVOL level gate. SQFD was a simultaneous alternative-book consensus event without a volatility regime; prior volatility candidates did not use stablecoin-quote flow topology.","why_low_gross9_overlap_is_plausible":"ordered quote-book diffusion plus dual implied-volatility levels is absent from Gross9 and does not use REX path geometry"},
 "clock":{"hours":"two consecutive completed spot source hours p then c","normalization":"per-book robust z=(imbalance-prior720h q50)/((q75-q25)/1.349), shifted one hour, minimum 672; zero scale invalid","leader_state_p":"exactly one of BTCUSDC/BTCFDUSD has abs(z)>=1.0; the other has the same nonzero sign and abs(z)<0.50; side*s times z_USDT <0.25","follower_state_c":"the same leader and follower retain side s; follower abs(z)>=0.75; leader abs(z)>=0.50; s*z_USDT<0.50","participation":"current alternative-book volume share >= strict-prior 720h q50 with 672 observations","volatile_regime":"current completed-hour BVOL close and DVOL close are each >= their own strict-prior 720h q60 with 672 observations","trigger":"false-to-true onset on an exact consecutive hourly source grid","decision":"current source-hour close after all three spot books and both volatility candles are complete","entry":"exact BTCUSDT decision+5m open","side":"s","hold":"6 elapsed hours","reservation":"global half-open, exit first on equal open","funding":"not a signal input; exact settlements only for later PnL","oi":"not a signal input","no_imputation":True},
 "policy":{"prior_hours":720,"prior_min_hours":672,"leader_abs_z_min":1.0,"follower_prior_abs_z_max_exclusive":.50,"follower_current_abs_z_min":.75,"leader_current_abs_z_min":.50,"usdt_prior_signed_z_max_exclusive":.25,"usdt_current_signed_z_max_exclusive":.50,"alternative_share_quantile":.50,"volatility_level_quantile":.60,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"spot_flow_panel":{"path":"data/binance_stablecoin_quote_flow_btc_2023_2026_aug/BTC_stablecoin_quote_flow_1h_2023-07-01_2026-07-31T23.csv.gz","sha256":"44374b9a2298ae4b64f0c1e7208665b1c08c8221045308694311123deae1c805"},"spot_flow_manifest":{"path":"data/binance_stablecoin_quote_flow_btc_2023_2026_aug/build_manifest.json","sha256":"b9c64c3ce651934d9761a6d0731e814b2a92f5237b3040e11f794d7eb024a898"},"volatility":"reuse hash-bound OCDR-12C BVOL/DVOL snapshot through 2026-08-01","execution_price":"sealed until source-support and Gross9 novelty pass"},
 "research_boundary":{"prior_sqfd_train_outcome_known":True,"prior_sqfd_outcome_used_to_define_vgsfr":False,"vgsfr_mechanism_proposed_by_outcome_blind_critic_before_prior_sqfd_report_review":True,"vgsfr_candidate_incidence_opened":False,"vgsfr_post_entry_return_or_pnl_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False}}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2,ensure_ascii=False)+"\n");print(a.output)
