"""Outcome-blind preregistration for HVCOM-355M."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVCOM-355M";DEFAULT_OUTPUT=Path("results/high_volatility_new_york_opening_momentum_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_new_york_opening_momentum_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"On Monday-Friday New York mornings, the completed 09:30-10:00 local BTC move captures the first directional risk transfer of the nominal US cash-open overlap; when strictly prior BTC variation is elevated, follow that opening direction from 10:05 through 16:00 local.","side":"strict sign of the completed 09:30-10:00 America/New_York BTC return","why_distinct":"HVCOM uses a DST-aware recurring weekday New York clock and a disjoint completed opening half-hour to trade only the remainder of the nominal cash session. The US-cash-close candidate waits for the full session; Thursday macro candidates trade one weekday after 08:30 releases; UTC intraday candidates use different clocks. It uses no equity return, holiday fit, volume, flow, OI, funding, fitted outcome, reused event, repair, or promoted control.","why_suited_to_volatile_regimes":"the twenty-four elapsed hours ending before the opening response must rank in the causal upper 35%, focusing the clock on July-like risk-transfer days","why_low_gross9_overlap_is_plausible":"DST-aware 10:05 New York weekday entries ending at 16:00 local are absent from Gross9 primitives"},
 external_basis={"origin":"predefined US cash-open overlap clock; no empirical BTC coefficient is claimed","fixed_definition":"every Monday-Friday in America/New_York; reaction [09:30,10:00), entry 10:05, exit 16:00; Python IANA timezone rules; exchange holidays intentionally not inferred or filtered","selection_use":"institutional overlap clock and continuation direction fixed without opening candidate incidence or outcomes"},
 features={"decision_grid":"every Monday-Friday 10:00 America/New_York","reaction_window":"six exact completed BTCUSDT five-minute bars [09:30,10:00) local, each from five coherent one-minute rows","reaction_return":"log(09:55 bar close/09:30 bar open), finite strict nonzero","variation_window":"288 exact completed five-minute bars over the twenty-four elapsed hours ending at 09:30 local","realized_variation":"sqrt(sum squared five-minute open-to-close log returns), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier source-valid weekday decisions, minimum 120, current excluded; rank>=0.65","timezone":"America/New_York via IANA, including DST folds/gaps","calendar":"Monday-Friday local only; no exchange-holiday inference or outcome-dependent exclusion","no_imputation":True},
 clock={"feature_available":"10:00 America/New_York after reaction completes","entry":"exact 10:05 local BTCUSDT open","exit":"exact 16:00 local BTCUSDT open","hold":"355 elapsed minutes","reservation":"nonoverlapping chronological half-open positions; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_days":180,"minimum_history_days":120,"variation_rank_min":.65,"reaction_start_local":"09:30","reaction_end_local":"10:00","entry_local":"10:05","exit_local":"16:00","hold_minutes":355,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","first_fifteen_minute_direction","one_weekday_stale_reaction","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-01-01T00:00:00Z","2026-08-02T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"repository_same_new_york_opening_clock_candidate_found":False,"prior_cash_session_macro_and_intraday_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"predefined weekday New York opening-overlap continuation clock under requested high variation"},
 stopping_rule="Terminal first failure; no weekday calendar, timezone, reaction window, variation, side, entry, exit, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVCOM preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(z.output)
