"""Outcome-blind preregistration for HVMPC-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVMPC-24";DEFAULT_OUTPUT=Path("results/high_volatility_macro_polarity_concordance_relay_preregistration_2026-08-09.json");NEWS=Path("data/frbsf_daily_news_sentiment_1980_2026_aug.csv");EPU=Path("data/us_daily_epu_1985_2026_aug.csv");MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_macro_polarity_concordance_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A weekly improvement in broad US news sentiment accompanied by a weekly decline in newspaper-based policy uncertainty is a jointly confirmed risk-on transition; the opposite pair is risk-off. After both daily sources are certainly public and BTC variation is elevated, follow the jointly confirmed polarity for one day.","side":"strict sign of seven-calendar-day FRBSF news-sentiment change, equal to negative sign of seven-day log EPU change","why_distinct":"HVNSR and HVEPUH each rank one source's shock magnitude. HVMPC uses no source-tail gate and instead requires a cross-provider sign relation between sentiment and uncertainty over the same seven-day horizon. Neither individual-source diagnostic clock is reused or promoted.","volatile_market_target":"completed seven-day BTC variation causal rank must be at least 0.65","why_low_gross9_overlap_is_plausible":"a conservatively delayed cross-provider macro polarity clock is absent from Gross9"},
 "features":{"source_day":"calendar day D with exact observations in both frozen official daily panels","news_change":"FRBSF news_sentiment[D]-news_sentiment[D-7], finite and strict nonzero","epu_change":"log(EPU[D]/EPU[D-7]), both positive, finite and strict nonzero","polarity_concordance":"sign(news_change)=-sign(epu_change)","availability":"D+8 00:00 UTC, preserving the conservative news-sentiment embargo and later than EPU D+2","btc_variation":"sqrt(sum squared exact completed 5m BTC log returns over seven UTC days ending at decision)","variation_rank":"strict-prior midrank over at most 270 source-valid decisions, minimum 180; current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"D+8 00:00 UTC","entry":"decision+5m BTCUSDT open","hold":"24 elapsed hours","side":"jointly confirmed news-sentiment polarity","reservation":"daily nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements after novelty"},
 "policy":{"change_days":7,"publication_delay_days":8,"variation_history_days":270,"minimum_history_days":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all stages","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"definitions":{"news_only":"news change direction plus current variation without EPU concordance","epu_only":"negative EPU change direction plus current variation without news concordance","no_variation_gate":"joint polarity concordance without BTC variation rank","one_week_stale_pair":"prior exact paired changes with current variation","direction_flip":"negative primary side","same_clock_forced_long":"side +1 on primary clock"},"cannot_be_promoted":True},
 "source_plan":{"news":{"path":str(NEWS),"official_page":"https://www.frbsf.org/research-and-insights/data-and-indicators/daily-news-sentiment-index/","frozen_before_preregistration":True},"epu":{"path":str(EPU),"official_url":"https://www.policyuncertainty.com/media/All_Daily_Policy_Data.csv","frozen_before_preregistration":True},"historical_market":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m through 2026-08-01","execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_individual_macro_outcomes_known":True,"cross_source_polarity_incidence_or_outcomes_known":False,"individual_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cross-provider macro polarity concordance"},
 "stopping_rule":"terminal first failure; no source, delay, horizon, polarity, variation, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVMPC prereg drift")
 if hashlib.sha256(MARKET.read_bytes()).hexdigest()!=MARKET_SHA:raise RuntimeError("HVMPC market drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
