"""Outcome-blind preregistration for HVCQTR-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_cross_structure_action_vote as gates
POLICY_ID="HVCQTR-24";DEFAULT_OUTPUT=Path("results/high_volatility_credit_quality_transition_relay_preregistration_2026-08-18.json");SOURCE=Path("data/high_volatility_credit_risk_appetite_relay_sources_2022_2026/daily_credit_states.csv.gz");SOURCE_SHA="88d227fff477484ce40e2da8578368cd3345b6fc62c4e6d99a4325b4aed67e59"
def sha256(p:str|Path)->str:return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 g=gates.build();core={"protocol_version":"high_volatility_credit_quality_transition_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-18","singleton":True,"candidate_family":[POLICY_ID],"candidate_family_size":1,"source_incidence_opened":False,"outcomes_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"A sign transition in the same-session HYG-minus-LQD return changes the traded corporate-credit risk-appetite regime rather than merely extending a level. During elevated BTC variation, follow the new credit-quality direction for twenty-four hours.","side":"strict sign of current HYG log return minus current LQD log return after an opposite prior source-valid sign","why_distinct":"HVCREDIT trades every high-variation credit-relative level and failed Gross9. HVCQTR trades only polarity transitions between consecutive frozen credit sessions, forming a new event topology. It uses no HVCREDIT event set/control, equity return, Treasury price, crypto direction, OI, funding, premium, options, fitted outcome, or promoted control.","why_low_gross9_overlap_is_plausible":"irregular external credit-quality polarity transitions are sparser than the terminal level clock"},
 "features":{"source":{"path":str(SOURCE),"sha256":SOURCE_SHA},"relative_credit_return":"log(HYG close/open)-log(LQD close/open), finite strict nonzero","previous":"immediately prior source-valid shared cash session in frozen chronological order","transition":"current and previous relative returns have strict opposite signs","availability":"current session date 23:00 UTC","variation_gate":"frozen causal BTC variation_rank>=0.65","no_imputation":True},"policy":{"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},"clock":{"entry":"decision+5m exact BTCUSDT open","hold":"24 elapsed hours","reservation":"chronological half-open nonoverlap; exit first on equal entry","funding":"not signal input; exact settlements after Gross9"},
 "stages":g["stages"],"source_support_gates":g["source_support_gates"],"gross9_novelty_gates":g["gross9_novelty_gates"],"economic_gates":g["economic_gates"],"diagnostic_controls":{"names":["no_variation_gate","level_not_transition","one_session_stale_transition","previous_side","direction_flip","forced_long"],"cannot_be_promoted":True},"research_boundary":{"prior_HVCREDIT_Gross9_failure_known":True,"HVCREDIT_event_set_or_controls_reused":False,"exact_transition_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"classification":"exploratory discovery; not fresh confirmatory evidence","selection_basis":"credit-quality relative-return regime transition"},"stopping_rule":"source, Gross9, train/test/eval/final; terminal first failure; no assets, return, previous-session law, transition, variation, side, clock, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x!=build():raise RuntimeError("HVCQTR prereg drift")
 if sha256(SOURCE)!=SOURCE_SHA:raise RuntimeError("HVCQTR source drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
