"""Outcome-blind preregistration for HVCVR-2."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/high_volatility_close_vwap_reversion_relay_preregistration_2026-08-08.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_close_vwap_reversion_relay_v1","policy_id":"HVCVR-2","as_of_date":"2026-08-08","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
 "mechanism":{"claim":"At a fixed four-hour boundary in an unusually volatile completed BTC block, a close materially displaced from that block's base-volume VWAP represents a short-lived inventory-location imbalance. Fade the close back toward the traded center for two elapsed hours.","long":"normalized close-minus-VWAP displacement <=-0.20","short":"normalized close-minus-VWAP displacement >=0.20","why_distinct":"HVCVR chooses direction from the completed block's traded-volume center. FHVAR chose continuation from agreeing two-hour return signs and variance acceleration; its direction-fade control cannot be promoted and is not reused. Prior daily tail fades did not use block VWAP.","why_suited_to_volatile_regimes":"completed four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"six fixed UTC block-VWAP clocks and volume-location geometry are absent from Gross9"},
 "features":{"source":"BTCUSDT bars_binance interval=1m","block_valid":"240 exact distinct minute rows in [decision-4h,decision), finite positive coherent OHLC, finite nonnegative base and quote volume, positive summed base volume; no imputation","block_vwap":"sum(quote_asset_volume)/sum(volume)","block_close":"close at decision-1m","block_range":"max(high)-min(low), strictly positive","normalized_displacement":"(block_close-block_vwap)/block_range","realized_variation":"sum squared 1m close-to-close log returns within the block","variation_rank":"strict-prior midrank among at most 180 valid fixed four-hour blocks, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact 00:00,04:00,08:00,12:00,16:00,20:00 UTC","entry":"exact decision+5m BTCUSDT open","hold":"2 elapsed hours","reservation":"global half-open; exit first on equal open","funding_oi_premium_implied_vol":"not signal inputs; exact funding only after novelty passes"},
 "policy":{"history_observations":180,"minimum_history_observations":120,"variation_rank_min":.65,"absolute_normalized_displacement_min":.20,"entry_delay_minutes":5,"hold_hours":2,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"btc_1m":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","volume","quote_asset_volume"],"window":["2023-06-01T00:00:00Z","2026-08-01T00:00:00Z"],"materialize_after_preregistration":True},"execution_price":"sealed until source-support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_volatility_gate","no_displacement_gate","one_boundary_stale_geometry","direction_follow"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"related_high_volatility_reversion_family_known":True,"prior_candidate_event_sets_reused":False,"fhvar_direction_fade_control_promoted":False,"prior_candidate_outcomes_used_to_set_hvcvr_direction_threshold_hold_or_clock":False,"hvcvr_candidate_incidence_opened":False,"hvcvr_post_entry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent high-volatility traded-center displacement mechanism"},
 "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no threshold, side, hold, clock, VWAP, or subset repair."}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+"\n");print(a.output)
