"""Outcome-blind preregistration for HVCACM-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVCACM-8";SLUG="high_volatility_cross_alt_channel_position_migration_relay";ALTS=("ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","ADAUSDT","DOGEUSDT");DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":f"{SLUG}_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"At fixed twice-daily decisions, a broad thirty-minute migration of alt prices through their completed eight-hour high-low channels reveals coordinated risk repricing before terminal breakouts. During locally elevated BTC variation, BTC follows that channel-migration direction for eight hours.","side":"strict sign of the median selected-alt channel-position migration","why_distinct":"Close-location consensus uses one terminal bar's static intrabar geometry and extreme-traversal uses ordering of extrema. HVCACM measures each alt's normalized location inside a rolling eight-hour channel at two causal endpoints thirty minutes apart, ranks the absolute migration against that alt's own prior scheduled history, and requires broad migration agreement. It uses no terminal candle location, breakout event, current BTC direction, post-entry fit, reused event set, or promoted control.","why_suited_to_volatile_regimes":"BTC completed 24-hour realized variation ranks in the upper 35 percent against the 20 strictly prior scheduled source-valid decisions, adapting causally to local July-like volatility","why_low_gross9_overlap_is_plausible":"fixed 02:35 and 14:35 UTC entries with an eight-hour hold are absent from Gross9 primitive clocks"},
 "features":{"bars":"exact five-minute OHLC aggregated from five consecutive bars_binance one-minute rows; all seven symbols complete, finite, positive, coherent; no imputation","decision_times":"every calendar day at exact 02:30 and 14:30 UTC","channel":"for each alt at each endpoint, rolling maximum high and minimum low over the 96 completed five-minute bars ending at that endpoint; range strict positive","channel_position":"(completed close-channel_low)/(channel_high-channel_low), finite in [0,1]","migration":"current channel_position minus channel_position at D-30m; finite strict nonzero","migration_rank":"for each alt independently, strict-prior midrank of absolute migration over at most 120 prior jointly valid scheduled decisions, minimum 60, current excluded; selected when rank>=0.65","score":"median migration among selected alts","consensus_gate":"at least four selected alts, abs(score)>=0.10, and at least three selected migration signs equal score sign","btc_realized_variation":"sqrt(sum squared exact BTC five-minute log(close/open) returns over [D-24h,D))","variation_rank":"strict-prior midrank over 20 prior jointly source-valid scheduled decisions, minimum 15, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact daily 02:30 or 14:30 UTC","entry":"exact BTCUSDT perpetual decision+5m open","side":"score sign","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements only after novelty"},
 "policy":{"channel_bars":96,"migration_lag_bars":6,"migration_prior_decisions":120,"migration_minimum_decisions":60,"migration_rank_min":.65,"minimum_selected_alts":4,"score_absolute_min":.10,"minimum_agreeing_alts":3,"variation_bars":288,"variation_prior_decisions":20,"variation_minimum_decisions":15,"variation_rank_min":.65,"decision_hours_utc":[2,14],"decision_minute":30,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","no_migration_tail","three_alt_consensus","fixed_prior_channel","one_decision_stale_migration","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"market":{"table":"bars_binance","symbols":["BTCUSDT",*ALTS],"interval":"1m","columns":["ts","symbol","open","high","low","close"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"read_after_preregistration_commit":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_cross_alt_family_outcomes_known":True,"repository_exact_channel_position_migration_event_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cross-alt dynamic rolling-channel migration mechanism"},
 "stopping_rule":"terminal first failure; no universe, aggregation, channel window, migration lag, normalization, histories, ranks, consensus, local-volatility gate, direction, clock, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 if x.get('manifest_hash')!=canonical_hash({k:v for k,v in x.items() if k!='manifest_hash'}) or x!=build():raise RuntimeError('HVCACM prereg drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+'\n').encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f'refusing overwrite {a.output}')
 a.output.write_bytes(b);print(a.output)
