"""Outcome-blind preregistration for HVVRT-12."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVVRT-12";DEFAULT_OUTPUT=Path("results/high_volatility_variance_ratio_trend_onset_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_variance_ratio_trend_onset_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a completed twenty-four-hour raw variance ratio for overlapping one-hour versus five-minute BTC returns crossing above unity identifies positive serial dependence replacing random-walk-or-reverting noise; follow the completed four-hour displacement for twelve hours.","side":"strict sign of the completed trailing four-hour close-to-close return at an upward unity crossing","why_distinct":"HVVRT compares the population variance of overlapping twelve-step return sums with twelve times the population variance of one-step returns. It measures serial dependence directly rather than volatility level, one-minute/five-minute sampling noise, Hurst fitting, price/average cross, range geometry, volume, flow, OI, funding, fitted outcomes, reused events, repair, or promoted control.","why_suited_to_volatile_regimes":"the same completed twenty-four-hour one-step realized variation must rank in its causal upper 35%, isolating trend onset inside July-like volatility","why_low_gross9_overlap_is_plausible":"sparse four-hour serial-dependence unity-onset clocks are absent from Gross9 primitives"},
 external_basis={"origin":"Lo-MacKinlay variance-ratio random-walk diagnostic, raw variance-ratio convention","fixed_definition":"288 completed five-minute close-to-close log returns; q=12; VR=population variance of all overlapping q-step sums divided by q times population variance of one-step returns; unity separates random-walk variance scaling from positive serial dependence","selection_use":"published variance-scaling identity, one-hour q=12 aggregation, unity benchmark, and trend interpretation only; no incidence or outcomes; no hypothesis-test statistic is claimed"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bars":"exact aggregation of coherent BTCUSDT one-minute rows into five-minute closes","one_step_returns":"288 consecutive five-minute close-to-close log returns ending at T, requiring 289 completed closes","q_step_returns":"all 277 overlapping sums of twelve consecutive one-step returns","variance_ratio":"population variance(q_step_returns)/(12*population variance(one_step_returns)), finite positive denominator","event":"current VR strictly above 1 after immediately prior finite VR at or below 1","direction":"strict completed trailing four-hour close-to-close return","variation":"sqrt(sum squared 288 one-step returns), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid four-hour decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after all source closes","entry":"exact BTCUSDT open five elapsed minutes later","side":"strict trailing four-hour displacement sign","hold":"12 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"one_step_minutes":5,"sample_returns":288,"aggregation_steps":12,"direction_hours":4,"unity":1.,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","below_unity_reversion","one_bar_stale_onset","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2019-12-30T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"variance_ratio_definition_read":True,"repository_variance_ratio_candidate_found":False,"prior_variance_signature_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"fixed raw q=12 variance-ratio unity onset under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no sampling, sample length, q, variance convention, unity event, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVVRT preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(z.output)
