"""Outcome-blind preregistration for HVVRAT-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVVRAT-24";DEFAULT_OUTPUT=Path("results/high_volatility_volume_ratio_centerline_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_volume_ratio_centerline_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a canonical twenty-six-period Volume Ratio crossing its neutral 100 centerline on completed four-hour BTC auctions identifies a change in whether gross up-close or down-close participation dominates; follow the new participation side for twenty-four hours.","side":"long on a strict upward crossing of 100 and short on a strict downward crossing of 100","why_distinct":"HVVRAT separately sums gross base volume on up-close and down-close auctions, allocates half of unchanged-close volume to each side, and takes their rolling ratio. Unlike VZO it has finite rectangular memory rather than EMA signed-net normalization; unlike OBV it is not cumulative; unlike CVD it uses close direction rather than taker classification. It uses no OI, funding, fitted outcome, reused event, repair, or promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%, focusing participation-balance changes on July-like volatile conditions","why_low_gross9_overlap_is_plausible":"sparse four-hour rolling gross up/down participation-ratio crossings are absent from Gross9 primitives"},
 external_basis={"origin":"canonical Volume Ratio indicator convention","fixed_definition":"26 completed periods; numerator=sum up-close base volume plus half unchanged-close volume; denominator=sum down-close base volume plus half unchanged-close volume; ratio=100*numerator/denominator; neutral centerline 100","selection_use":"published period, gross-side allocation, ratio, centerline, and direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T), with strictly positive summed base volume","direction":"strict sign of current completed close minus immediately prior completed close","up_volume":"full base volume when direction positive, else zero","down_volume":"full base volume when direction negative, else zero","unchanged_volume":"full base volume when direction zero, else zero","volume_ratio":"100*(rolling26 up_volume + 0.5 rolling26 unchanged_volume)/(rolling26 down_volume + 0.5 rolling26 unchanged_volume), finite positive denominator","event":"strict Volume Ratio crossing of 100 from immediately prior finite state","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"volume_ratio_periods":26,"centerline":100.,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","net_volume_zero_cross","one_bar_stale_cross","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","volume"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_volume_ratio_definition_read":True,"repository_volume_ratio_candidate_found":False,"prior_vzo_obv_cvd_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Volume Ratio(26) neutral-center crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no Volume Ratio period, allocation, formula, centerline, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVVRAT preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(z.output)
