"""Outcome-blind singleton preregistration for CVOBR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
OUT=Path("results/cboe_vix_overnight_btc_confirmation_relay_preregistration_2026-08-08.json");CBOE=Path("data/cboe_volatility_surface_2021_2026/cboe_volatility_surface_2021-01-01_2026-08-07.csv.gz");CBOE_MANIFEST=Path("data/cboe_volatility_surface_2021_2026/manifest.json");PRICE=Path("data/options_led_intrahour_absorption_sources_2023_2026/btc_intrahour_path.csv.gz");PRICE_MANIFEST=Path("data/options_led_intrahour_absorption_sources_2023_2026/manifest.json");HASHES={str(CBOE):"42eb1093f5167aec9c71a4733ab3451e40807c81dc7cb49568a6a0c634267ba0",str(CBOE_MANIFEST):"ec1dd33efcee29b75c80294fb594969cd1b12a9343fc40f888525db4400bc936",str(PRICE):"7413b1dde7148efbc30eccd077e4f7430d57be87836bbd4551df9f6f85609579",str(PRICE_MANIFEST):"1ca33578613d084801c02fce5f15213daa6c5a419ad621b056648b2f01e276e2"}
def chash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"cboe_vix_overnight_btc_confirmation_relay_v1","policy_id":"CVOBR-6","as_of_date":"2026-08-08","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,"mechanism":{"claim":"After an extreme completed Cboe VIX move, an overnight BTC move through 10:00 ET in the usual opposite risk direction confirms cross-market transmission; the confirmed BTC direction should continue for six hours.","eligible":"strict-prior rank(abs(delta log VIX))>=0.75 and sign(BTC overnight return)==-sign(delta log VIX)","side":"sign(BTC overnight return)","why_distinct":"CVOBR combines an official external volatility shock with a causally completed BTC overnight confirmation; prior Cboe candidates used no pre-entry BTC confirmation and prior intraday candidates had no Cboe clock.","why_low_gross9_overlap_is_plausible":"next-Cboe-session 10:05 ET entries after extreme external shocks are absent from Gross9"},"features":{"vix_change":"current Cboe close minus immediately prior exact common source row in log space","vix_magnitude_rank":"strict-prior midrank over 252 valid changes, minimum 126; current appended after rank","overnight_btc":"return from the BTC hour_open at source date 16:00 America/New_York through hour_close of [09:00,10:00) America/New_York on the next exact Cboe source date","availability":"all BTC bars completed by 10:00 ET; entry five minutes later","missing_or_zero":"ineligible; no imputation"},"clock":{"entry":"next exact Cboe source date 10:05 America/New_York","hold":"6 elapsed hours","reservation":"global half-open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_forbidden_as_signal_inputs":True},"stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},"economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True},"controls":["no_extreme_gate","vix_only_risk_direction","btc_only_overnight","confirmation_break","direction_flip"],"source_bindings":HASHES,"research_boundary":{"candidate_incidence_opened":False,"post_entry_outcomes_opened":False,"gross9_rows_opened":False,"grid":False,"repair_of_prior_cboe_candidates":False,"promoted_prior_control":False,"future_can_rank_repair_or_reselect":False},"stopping_rule":"terminal first failure; no repair"};return {**core,"manifest_hash":chash(core)}
def validate(p:dict[str,Any])->None:
 if p.get("manifest_hash")!=chash({k:v for k,v in p.items() if k!="manifest_hash"}):raise RuntimeError("CVOBR canonical hash mismatch")
 for raw,want in HASHES.items():
  if hashlib.sha256(Path(raw).read_bytes()).hexdigest()!=want:raise RuntimeError("CVOBR source hash mismatch")
def write(path:Path=OUT)->dict[str,Any]:
 p=build();validate(p);b=json.dumps(p,indent=2,ensure_ascii=False,allow_nan=False)+"\n";path.parent.mkdir(parents=True,exist_ok=True)
 if path.exists() and path.read_text()!=b:raise RuntimeError("CVOBR prereg byte drift")
 path.write_text(b);return p
if __name__=="__main__":a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=OUT);x=a.parse_args();print(write(x.output)["manifest_hash"])
