"""Outcome-blind preregistration for HVVPCI-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVVPCI-24";DEFAULT_OUTPUT=Path("results/high_volatility_volume_price_confirmation_zero_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_volume_price_confirmation_zero_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a canonical Volume Price Confirmation Indicator crossing zero on completed four-hour BTC auctions marks price trend direction newly confirmed by relative volume participation; follow the new confirmed direction for twenty-four hours.","side":"long on a strict upward VPCI zero crossing and short on a strict downward zero crossing","why_distinct":"VPCI multiplies long-horizon volume-weighted versus unweighted price divergence by short-horizon volume-weighted price ratio and short/long volume participation ratio. It is not PVO volume acceleration, PVT cumulative signed turnover, OBV/CVD directional accumulation, VWAP displacement alone, Force Index, OI, funding, fitted outcomes, reused events, a repair, or a promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%, restricting confirmation changes to July-like volatile conditions","why_low_gross9_overlap_is_plausible":"sparse four-hour joint price-volume confirmation sign-change clocks are absent from Gross9 primitives"},
 external_basis={"origin":"Buff Dormeier canonical Volume Price Confirmation Indicator convention","fixed_definition":"short=5 and long=20 completed periods; VPC=long VWMA minus long SMA; VPR=short VWMA divided by short SMA; VM=short average volume divided by long average volume; VPCI=VPC*VPR*VM; strict zero crossing","selection_use":"published components, periods, multiplicative formula, zero interpretation, and direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T), with strictly positive summed base volume","vwma_short":"sum(close*base_volume,5)/sum(base_volume,5)","vwma_long":"sum(close*base_volume,20)/sum(base_volume,20)","sma_short":"mean(close,5)","sma_long":"mean(close,20)","volume_short":"mean(base_volume,5)","volume_long":"mean(base_volume,20)","vpc":"vwma_long-sma_long","vpr":"vwma_short/sma_short","volume_multiplier":"volume_short/volume_long","vpci":"vpc*vpr*volume_multiplier","event":"strict VPCI zero crossing from immediately prior finite state","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"short_periods":5,"long_periods":20,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","vpc_only_zero_cross","one_bar_stale_cross","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","volume"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_vpci_definition_read":True,"repository_vpci_candidate_found":False,"prior_volume_indicator_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical VPCI(5,20) zero crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no VPCI component, period, formula, crossing, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVVPCI preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(z.output)
