"""Outcome-blind preregistration for HVBFRR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVBFRR-12";DEFAULT_OUTPUT=Path("results/high_volatility_btc_factor_residual_relay_preregistration_2026-08-09.json");ALTS=["ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","ADAUSDT","DOGEUSDT"]
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_btc_factor_residual_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A large BTC return left unexplained by the contemporaneous equal-weight liquid-alt factor during a high-variation completed block identifies BTC-specific information rather than broad crypto beta. Follow that residual direction for twelve hours.","side":"strict sign of the current causal BTC-on-alt-factor residual","why_distinct":"Cross-alt breadth relays use sign majorities, BTC disagreement, or magnitude underreaction without estimating BTC beta. Alt residual families trade market-neutral alt pairs and hold no BTC. HVEBCR models ETH residual on BTC. HVBFRR instead removes a causally fitted six-alt factor from BTC itself and trades the BTC-specific residual at one daily clock.","volatile_market_target":"completed BTC eight-hour realized-variation causal rank must be at least 0.65","why_low_gross9_overlap_is_plausible":"one daily 02:05 UTC beta-residual clock is absent from Gross9"},
 "features":{"decision":"exact daily 02:00 UTC","block":"exact eight-hour [D-8h,D) paths for BTCUSDT and six frozen alt perpetuals, each 480 unique coherent 1m bars","returns":"log(last close/first open) by symbol","alt_factor":"equal-weight arithmetic mean of six finite alt log returns","causal_fit":"OLS BTC_return=a+b*alt_factor on at most 270 strictly prior source-valid daily blocks, minimum 180; current excluded","residual":"current BTC return minus prior-only fitted value","residual_scale":"sample standard deviation of prior fitted residuals over the same fit window, strict positive","standardized_residual":"residual/residual_scale, strict nonzero; abs>=1.0","btc_realized_variation":"sqrt(sum squared BTC 1m log(close/open) returns across the block), strict positive","variation_rank":"strict-prior midrank over at most 270 prior source-valid blocks, minimum 180; current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact daily 02:00 UTC after all seven blocks complete","entry":"exact BTCUSDT 02:05 UTC open","side":"standardized BTC factor-residual sign","hold":"12 elapsed hours","reservation":"daily opportunities are nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium_rv20":"not signal inputs; funding after novelty; RV20 q90 only after all economics pass"},
 "policy":{"symbols":["BTCUSDT",*ALTS],"block_hours":8,"fit_days":270,"minimum_fit_days":180,"absolute_standardized_residual_min":1.,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_residual_tail","no_variation_gate","raw_btc_return_side","fixed_beta_one","one_day_stale_fit","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbols":["BTCUSDT",*ALTS],"interval":"1m","columns":["ts","open","high","low","close"],"read_only":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"related_cross_alt_and_eth_residual_outcomes_known":True,"btc_factor_residual_values_used_to_select_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent BTC-specific cross-sectional factor-residual mechanism"},
 "stopping_rule":"terminal first failure; no symbol panel, block, factor, fit, scale, residual threshold, variation, side, timing, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVBFRR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
