"""Outcome-blind preregistration for HVCPMR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVCPMR-8";DEFAULT_OUTPUT=Path("results/high_volatility_cash_participation_migration_relay_preregistration_2026-08-12.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_cash_participation_migration_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-12","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"In a high-variation completed BTC auction, a same-direction spot and perpetual move is more durable when Binance spot's share of combined spot-plus-perpetual quote turnover rises materially from the first four hours to the second four hours and the final two-hour perpetual move still confirms the auction. Follow the cash-sponsored direction for eight hours.","side":"common strict sign of completed eight-hour spot return, perpetual return, and final-two-hour perpetual return","why_distinct":"SPVIR uses an hourly upper-tail level of spot base-volume share plus BVOL/DVOL ignition; STCSR uses a daily spot share of transaction count; HVSFLR compares spot/perpetual aggressive-flow imbalance levels; DCVPR rotates Upbit versus Binance participation over a day. HVCPMR uses the within-auction first difference of Binance spot quote-turnover share across two disjoint four-hour halves, without implied volatility, taker direction, Upbit, funding, OI, fitted outcomes, prior events, or controls.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour perpetual realized variation must rank in its causal upper 35%, targeting July-like volatile markets","why_low_gross9_overlap_is_plausible":"new onsets of offset intrablock cash-share migration with three-way directional confirmation are absent from Gross9 primitives"},
 "features":{"window":"exact aligned 480 one-minute BTCUSDT rows [D-8h,D) from bars_binance_spot and bars_binance","half_share":"sum spot quote_asset_volume / sum(spot plus perpetual quote_asset_volume) separately over exact first and second 240-minute halves","migration":"second-half share minus first-half share, strictly positive","migration_rank":"strict-prior midrank of positive migration against at most 270 prior source-valid positive migrations; minimum 180; current excluded; rank at least 0.70","returns":"spot and perpetual log(last close/first open) over full block, plus perpetual final-two-hour log return; all strict nonzero and same sign","btc_variation":"sum squared perpetual log(close/open) over exact 1440 one-minute rows [D-24h,D)","variation_rank":"strict-prior midrank against at most 270 prior source-valid decisions; minimum 180; current excluded; rank at least 0.65","trigger":"false-to-true onset of migration tail, variation, and directional confirmation against previous source-valid decision","invalid":"missing/duplicate/nonpositive/incoherent OHLC, negative volume, nonpositive combined turnover, or incomplete aligned grids; no imputation"},
 "clock":{"decision":"exact 06:00, 14:00, and 22:00 UTC","entry":"exact perpetual BTCUSDT open five elapsed minutes later","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 "policy":{"block_minutes":480,"half_minutes":240,"confirmation_minutes":120,"history_decisions":270,"minimum_history_decisions":180,"migration_rank_min":.70,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},"post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, and final","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_migration_tail","no_variation_gate","trade_count_share_migration","one_block_stale_features","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"spot":{"table":"bars_binance_spot","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume","number_of_trades"]},"perpetual":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume","number_of_trades"]},"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_only":True,"execution_price":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"repository_collision_search_opened":True,"exact_disjoint_half_spot_share_migration_candidate_found":False,"prior_spot_participation_outcomes_known":True,"prior_event_sets_reused":False,"prior_controls_promoted":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"selection_basis":"independent intrablock cash-participation migration sponsorship"},
 "stopping_rule":"terminal first-failure sequence: source support, Gross9 novelty, train/test/eval/final strict economics, then RV20 q90 audit; no venue, volume field, block, half, migration, history, rank, confirmation, variation, onset, side, hold, clock, subset, threshold, source, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def main()->None:
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();b=(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_bytes(b);print(json.dumps({"policy_id":POLICY_ID,"output":str(a.output),"sha256":hashlib.sha256(b).hexdigest()}))
if __name__=="__main__":main()
