"""Outcome-blind preregistration for DLSDR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path('results/deribit_led_shock_deceleration_reversal_preregistration_2026-08-08.json')
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={'protocol_version':'deribit_led_shock_deceleration_reversal_v1','policy_id':'DLSDR-6','as_of_date':'2026-08-08','outcomes_opened':False,
 'mechanism':{'claim':'when BVOL and DVOL reprice in opposite directions and Deribit has the larger normalized body, an extreme first-half BTC shock followed by same-direction flow at no more than half the magnitude identifies price impact exhaustion under options-market leadership','side':'opposite sign of first-half BTC return','why_distinct':'DLSDR replaces CVSDR absolute-OI tail confirmation with Deribit normalized-body leadership and does not require CVDAR opposite-direction absorption','why_low_gross9_overlap_is_plausible':'the clock is anchored to cross-venue options leadership plus an intrahour impact-decay path absent from Gross9'},
 'clock':{'decision':'T after a completed UTC hour','volatility':'BVOL and DVOL normalized bodies have opposite nonzero signs and abs(DVOL body)>abs(BVOL body)','price_source':'60 exact BTCUSDT 1m bars in [T-1h,T), split at exact minute 30','first_half_shock':'nonzero absolute first-half return >= strictly-prior 720h q75 with 672 observations','deceleration':'second-half return has the same nonzero sign and absolute magnitude <= one half of first-half absolute return','oi':'not a signal input','funding':'not a signal input; opened only for later exact PnL accounting','trigger':'false-to-true onset, prior hour source-valid and consecutive','entry':'exact BTCUSDT T+5m open, all features available by T','side':'opposite sign of first-half return','hold':'6 elapsed hours','reservation':'global half-open, exit first on equal open','no_imputation':True},
 'policy':{'prior_hours':720,'prior_min_hours':672,'first_half_absolute_return_quantile':.75,'maximum_deceleration_ratio':.5,'entry_delay_minutes':5,'hold_hours':6,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 'stages':{'train':['2023-07-01T00:00:00Z','2024-01-01T00:00:00Z'],'test':['2024-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'eval':['2025-01-01T00:00:00Z','2026-01-01T00:00:00Z'],'final':['2026-01-01T00:00:00Z','2026-08-01T00:00:00Z']},
 'source_support_gates':{'minimum_events':{'train':8,'test':12,'eval':12,'final':8},'minority_side_share_min':.2,'max_month_share':.45},
 'novelty_gates':{'exact_entry_jaccard_max':.1,'candidate_near_6h_share_max':.45,'occupied_5m_jaccard_max':.3,'absolute_signed_exposure_pearson_max':.35,'must_pass_before_economics':True},
 'economic_gates':{'absolute_return_positive':True,'cagr_to_strict_mdd_min':3.,'strict_mdd_max_pct':15.,'mean_gross_underlying_min_bp':20.,'weekly_signflip_one_sided_p_max':.1,'stress_absolute_return_positive':True,'stress_cagr_to_strict_mdd_min':2.5,'each_calendar_half_positive':True,'stop_on_first_failure':True,'future_can_rank_repair_or_reselect':False,'accounting':'fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR'},
 'source_plan':{'volatility':'reuse hash-bound OCDR-12C BVOL/DVOL snapshot','intrahour_price':'reuse hash-bound OLIAH completed-hour intrahour snapshot','execution_price':'sealed until source-support and Gross9 novelty pass'},
 'research_boundary':{'prior_candidate_incidence_known':True,'prior_candidate_outcomes_used_for_dlsdr':False,'dlsdr_candidate_incidence_opened':False,'dlsdr_post_entry_return_or_pnl_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False}}
 return {**core,'manifest_hash':canonical_hash(core)}
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2,ensure_ascii=False)+'\n');print(a.output)
