"""Outcome-blind preregistration for HVTII-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVTII-24";DEFAULT_OUTPUT=Path("results/high_volatility_trend_intensity_index_midline_crossover_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_trend_intensity_index_midline_crossover_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a canonical Trend Intensity Index crossing its 50 midline on completed four-hour BTC auctions identifies a change in whether positive or negative deviations from the major trend dominate; follow the new dominant side for twenty-four hours.","side":"long when TII crosses strictly above 50 from at or below 50; short when it crosses strictly below 50 from at or above 50","why_distinct":"HVTII measures the share of absolute deviations from a 60-period simple moving average contributed by positive deviations over a separate 30-period window. It is not a return oscillator, candle-range ratio, volume/flow measure, OI, funding, premium, or Gross9 primitive.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%, restricting trend-deviation dominance changes to July-like volatile conditions","why_low_gross9_overlap_is_plausible":"sparse four-hour two-window deviation-share midline clocks are absent from Gross9 primitives"},
 external_basis={"origin":"M. H. Pee, canonical Trend Intensity Index convention","fixed_definition":"60-period close SMA; over the latest 30 completed deviations, TII=100*sum(max(close-SMA,0))/sum(abs(close-SMA)); 50 midline and strict crossing","selection_use":"published 60/30 formula, midline, and direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","major_average":"simple mean of the latest 60 consecutive valid completed four-hour closes","deviation":"current completed close minus current major average","trend_intensity_index":"100 times the rolling 30-period sum of positive deviations divided by the rolling 30-period sum of absolute deviations; denominator finite and strictly positive","cross":"strict current crossing of 50 from the immediately prior valid TII","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"major_periods":60,"minor_periods":30,"midline":50.,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","close_sma_cross","one_bar_stale_crossover","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_trend_intensity_index_definition_read":True,"repository_trend_intensity_index_candidate_found":False,"prior_trend_oscillator_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Trend Intensity Index 50-midline crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no TII formula, period, midline, crossing, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVTII preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
