"""Outcome-blind preregistration for HVTIFP-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVTIFP-8";SLUG="high_volatility_taker_imbalance_flow_persistence";DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c={"protocol_version":"high_volatility_taker_imbalance_flow_persistence_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"Positive serial persistence in completed five-minute aggressive quote-flow imbalance means urgency is being executed in a sequence rather than one isolated burst. During elevated BTC variation, a fresh upper-tail persistence state should continue in the completed net aggressive-flow direction for eight hours.","side":"strict sign of completed eight-hour aggregate aggressive quote-flow imbalance","why_distinct":"HVAFC uses only final-two-hour flow sign and requires price confirmation. Dual-half signed-volume assigns quote turnover by candle return sign and does not read taker fields. Quarter-hour and daily flow candidates aggregate fixed buckets without estimating serial dependence. HVTIFP uses lag-one correlation of 96 continuous taker imbalance observations and no price direction, volume-sign proxy, funding, OI, premium, cross-asset input, fitted outcome, prior event set, or promoted control.","why_suited_to_volatile_regimes":"completed BTC eight-hour variation must occupy its causal upper 35 percent while positive flow persistence enters its upper quartile","why_low_gross9_overlap_is_plausible":"offset three-daily aggressive-flow serial-persistence onsets are absent from Gross9 primitives"},
 "features":{"decision_grid":"exact 06:00, 14:00 and 22:00 UTC boundaries D","source_window":"480 exact unique coherent bars_binance BTCUSDT interval=1m rows [D-8h,D)","five_minute_flow":"for each of 96 exact groups, sum quote_asset_volume and taker_buy_quote; require finite nonnegative values, taker<=quote, and group quote strict positive","imbalance":"(2*group_taker_buy_quote-group_quote_asset_volume)/group_quote_asset_volume, finite in [-1,1]","flow_persistence":"ordinary Pearson correlation of imbalance[0:95] and imbalance[1:96], finite strict positive","persistence_rank":"strict-prior midrank over at most 270 earlier source-valid decisions, minimum 180, current excluded; rank>=0.75","net_flow":"(2*sum all taker_buy_quote-sum all quote_asset_volume)/sum all quote_asset_volume, finite strict nonzero","btc_returns":"95 close-to-close natural-log returns from 96 five-minute closes","realized_variation":"sqrt(sum squared btc_returns), finite strict positive","variation_rank":"strict-prior 270/180 midrank, current excluded; rank>=0.65","onset":"eligible now and immediately preceding scheduled source-valid decision ineligible; missing or invalid predecessor cannot trigger","no_imputation":True},
 "clock":{"decision":"D after all flow and price minutes complete","entry":"exact BTCUSDT perpetual D+5m open","side":"sign(net_flow)","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal entry","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact held settlements only after novelty"},
 "policy":{"window_minutes":480,"aggregation_minutes":5,"history_decisions":270,"minimum_history_decisions":180,"persistence_rank_min":.75,"variation_rank_min":.65,"decision_hours_utc":[6,14,22],"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},"post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_persistence_gate","no_variation_gate","imbalance_level_tail","one_decision_stale_persistence","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume","taker_buy_quote"]},"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True,"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"database_schema_and_coverage_metadata_only_opened_before_preregistration":True,"prior_flow_confirmation_half_bucket_mutual_information_and_impact_family_outcomes_known":True,"repository_taker_imbalance_lag1_persistence_candidate_found":False,"prior_event_sets_or_controls_reused":False,"prior_outcomes_used_to_set_aggregation_correlation_rank_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent serial aggressive-flow execution mechanism"},
 "stopping_rule":"terminal first failure; no aggregation, imbalance, correlation, history, rank, onset, variation, net-flow side, clock, hold, subset, threshold, comparator, or control repair"};return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVTIFP preregistration drift")
 if x["outcomes_opened"] or x["source_incidence_opened"] or x["gross9_rows_opened"]:raise RuntimeError("HVTIFP evidence boundary opened")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_bytes(b);print(a.output)
