"""Outcome-blind preregistration for BHARR-48."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/bitcoin_hashrate_acceleration_retarget_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"bitcoin_hashrate_acceleration_retarget_relay_v1","policy_id":"BHARR-48","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"At each immutable Bitcoin difficulty retarget, acceleration in epoch-over-epoch difficulty growth reflects strengthening committed mining capacity and maps long BTC; deceleration reflects deteriorating marginal miner capacity and maps short. The transmission is evaluated only outside calm BTC conditions and held for forty-eight hours.","side":"strict sign of log(D_h/D_h-2016)-log(D_h-2016/D_h-4032)","why_distinct":"BHARR uses the second difference of consensus difficulty at irregular proof-of-work retarget blocks. It is not daily CoinMetrics miner data, block-arrival throughput, fee stress, price momentum, a scheduled macro clock, Gross9, or a prior control.","why_suited_to_volatile_regimes":"prior-24h realized variation rank at confirmed availability must be >=0.35, excluding the calmest 35% while retaining enough immutable retarget events for the frozen support floor.","why_low_gross9_overlap_is_plausible":"retarget blocks arrive roughly biweekly at endogenous block timestamps after six confirmations"},
 "authority":{"chain":"Bitcoin mainnet canonical proof-of-work chain","retarget_height":"positive height divisible by 2016","difficulty":"decode compact nBits from the canonical block header exactly; never use a mutable chart value","transports":["https://blockstream.info/api","https://mempool.space/api"],"dual_replay":"height hash, header bytes, nBits, and H+6 confirmation hash/timestamp must agree byte-for-byte","availability":"canonical timestamp of block H+6; entry is first exact 5m open strictly after it"},
 "features":{"difficulty_change":"log(decoded difficulty at H / decoded difficulty at H-2016)","acceleration":"current difficulty_change minus previous difficulty_change using H-4032","zero":"strict zero acceleration is inactive","volatility":"sum squared BTCUSDT 1m close-to-close log returns over exact 24h ending at the last completed minute strictly before H+6 timestamp","volatility_rank":"strict-prior midrank at retarget events, at most 52, minimum 26, current excluded, >=0.35","no_imputation":True},
 "clock":{"entry":"first exact 5m BTCUSDT open strictly after H+6 canonical timestamp","hold":"48 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"exact only after novelty pass"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},"economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "diagnostic_controls":{"names":["no_volatility_gate","difficulty_level_change","one_retarget_stale_acceleration","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"transport_documentation_opened":True,"retarget_hash_header_nbits_or_incidence_opened":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"new immutable consensus retarget acceleration mechanism"},"stopping_rule":"terminal first failure: dual source integrity/support, Gross9 novelty, sequential economics; no confirmation, rank, threshold, side, hold, transport, or subset repair"};return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2,allow_nan=False)+"\n");print(a.output)
