"""Outcome-blind preregistration for CCRSR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="CCRSR-12";DEFAULT_OUTPUT=Path("results/commodity_currency_relative_stress_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"commodity_currency_relative_stress_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A large completed New York-session rise in USDCAD relative to USDAUD isolates CAD and oil-linked stress from broad US-dollar movement; the inverse isolates relative commodity-risk relief. In a high-variation BTC regime, relative CAD stress maps short BTC and relief maps long for twelve hours.","side":"negative strict sign of USDCAD session return minus USDAUD session return","why_distinct":"Dollar-factor and dollar-breadth candidates aggregate canonical USD direction across six pairs. ACUCR uses AUD/JPY sign concordance in Asia. CCRSR differences two same-quote commodity currencies, cancelling common USD direction and retaining a continuous CAD-versus-AUD relative shock; it is neither a pair subset breadth nor a prior control.","volatile_market_target":"pre-decision BTC 24-hour realized-variation causal rank must be at least 0.65","why_low_gross9_overlap_is_plausible":"one weekday 21:05 UTC relative commodity-FX clock is absent from Gross9"},
 "features":{"fx_session":"bars_polygon USDCAD and USDAUD 1m rows with 13:00<=UTC time<21:00 on one UTC weekday","session_valid":"each pair has at least 450 distinct minutes, first<=13:05, last>=20:55, finite positive coherent OHLC; no imputation","returns":"log(session close/session open) independently","relative_stress":"USDCAD return minus USDAUD return, strict nonzero","absolute_stress_rank":"strict-prior midrank over at most 252 prior valid weekday sessions, minimum 126; current excluded; rank>=0.70","btc_realized_variation":"sqrt(sum squared exact completed BTC hourly returns over 24 hours ending at 21:00)","variation_rank":"strict-prior midrank over at most 252 prior valid weekday decisions, minimum 126; current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact weekday 21:00 UTC","entry":"exact BTCUSDT 21:05 UTC open","side":"negative relative-stress sign","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium_rv20":"not signal inputs; funding after novelty; RV20 q90 only after all economics pass"},
 "policy":{"fx_prior_sessions":252,"fx_prior_min_sessions":126,"absolute_stress_rank_min":.70,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_stress_tail","no_variation_gate","usdcad_only","usdaud_only","one_session_stale_stress","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"fx":{"table":"bars_polygon","symbols":["USDCAD","USDAUD"],"interval":"1m","columns":["ts","open","high","low","close"],"read_only":True},"btc":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","close"],"read_only":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"prior_fx_factor_breadth_carry_outcomes_known":True,"relative_pair_values_used_to_select_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent common-dollar-cancelled commodity-currency stress channel"},
 "stopping_rule":"terminal first failure; no pair, session, spread, rank, history, threshold, variation, side, timing, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("CCRSR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
