"""Outcome-blind preregistration for LEMRR-16."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="LEMRR-16";DEFAULT_OUTPUT=Path("results/late_extreme_midpoint_rejection_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"late_extreme_midpoint_rejection_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"At exact Tuesday and Friday UTC boundaries, a completed 24-hour range whose last absolute extreme is rejected through the full-range midpoint identifies a failed late auction. Follow the rejection away from that last extreme for sixteen elapsed hours.","side":"short when the last high is later than the last low and the completed close is strictly below the range midpoint; long for the symmetric late-low rejection","why_distinct":"LEMRR uses the temporal ordering of exact daily price extremes jointly with midpoint rejection. It is not trailing-return concordance, wick magnitude, Donchian reclaim, close-VWAP displacement, run persistence, funding, flow, or a fitted threshold.","volatile_market_target":"two-sided range traversal and late-boundary failure should express most strongly in volatile markets; causal RV20 q90 is only a later audit","why_low_gross9_overlap_is_plausible":"at most two sparse sixteen-hour UTC-boundary positions per week, conditional on a path-order rejection"},
 "features":{"window":"exact 1,440 one-minute bars [decision-24h,decision)","range_high":"maximum completed high","range_low":"minimum completed low","last_high_time":"last timestamp attaining range_high","last_low_time":"last timestamp attaining range_low","midpoint":"(range_high+range_low)/2","late_high_rejection":"last_high_time>last_low_time and final close<midpoint","late_low_rejection":"last_low_time>last_high_time and final close>midpoint","source_valid":"exact unique minute grid, coherent finite positive OHLC, strict high>low, unequal last-extreme timestamps, no imputation"},
 "rv20_stress_slice":{"rv20":"sqrt(365*mean exact daily returns^2 over t-20 through t-1)","threshold":"numpy linear q90 over 756 strictly prior available RV20 observations","entry_filter":False,"future_use":"only after all sequential full-calendar stages pass"},
 "clock":{"decision":"Tuesday and Friday 00:00 UTC after the 24-hour window completes","entry":"exact BTCUSDT decision+5m open","hold":"16 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact realized funding only after novelty"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","persistent_long_vol_comparator":"same accepted clock and 0.5 gross, side forced long","full_calendar_decomposition":"candidate minus comparator net return","rv20_q90_decomposition":"same decomposition on causal RV20 q90 decisions","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"candidate_specific_q90_residual_positive":True,"comparator_cannot_satisfy_candidate_claim":True},
 "diagnostic_controls":{"definitions":{"no_midpoint_rejection":"side opposite the last extreme on every source-valid Tuesday/Friday window","close_location_only":"side of close versus midpoint on every source-valid Tuesday/Friday window","close_open_fade":"negative sign of completed 24-hour open-to-close return on primary clock","direction_flip":"negative primary side"},"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"exact_lemrr_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no weekday, window, extreme occurrence rule, midpoint condition, side, clock, hold, RV20, subset, comparator, control, or gate repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("LEMRR preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+"\n");print(a.output)
