"""Outcome-blind preregistration for OVRCR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path('results/oil_volatility_rotation_btc_confirmation_relay_preregistration_2026-08-08.json')
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={'protocol_version':'oil_volatility_rotation_btc_confirmation_relay_v1','policy_id':'OVRCR-6','as_of_date':'2026-08-08','outcomes_opened':False,
 'mechanism':{'claim':'A large completed daily change in Cboe OVX relative to VIX identifies rotation of volatility demand toward or away from oil-market risk. If BTC subsequently moves overnight in the implied risk direction through the next session 10:00 ET, the confirmed cross-asset direction should relay for six hours.','eligible':'strict-prior 252-session midrank(abs(delta log(OVX/VIX))) >= 0.60 with 126 observations','long':'delta log(OVX/VIX)<0 and BTC 16:00 ET-to-next-10:00 ET return>0','short':'delta log(OVX/VIX)>0 and BTC overnight return<0','side':'confirmed BTC overnight direction','why_distinct':'OVRCR uses official OVX/VIX cross-asset volatility rotation. Existing Cboe candidates used VIX, VVIX, SKEW and VIX term maturities; no prior candidate uses oil-specific implied volatility.','why_suited_to_volatile_regimes':'the clock activates on unusually large relative repricing of oil-market volatility demand and requires BTC transmission confirmation','why_low_gross9_overlap_is_plausible':'Gross9 has no external oil-versus-broad-equity volatility rotation clock'},
 'clock':{'source_session':'completed common OVX/VIX session S; daily values unavailable for trading until after the session close','btc_confirmation':'BTCUSDT return from S 16:00 America/New_York open to next common trading session 10:00 America/New_York open','decision':'next session 10:00 ET after OVX/VIX source and BTC confirmation are complete','entry':'exact BTCUSDT decision+5m open','side':'sign of BTC confirmation, required opposite sign of relative-volatility change','hold':'6 elapsed hours','reservation':'global half-open; chronological signals; exit first on equal open','no_imputation':True},
 'policy':{'prior_sessions':252,'prior_min_sessions':126,'absolute_rotation_rank_min':.60,'entry_delay_minutes':5,'hold_hours':6,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 'stages':{'train':['2023-07-01T00:00:00Z','2024-01-01T00:00:00Z'],'test':['2024-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'eval':['2025-01-01T00:00:00Z','2026-01-01T00:00:00Z'],'final':['2026-01-01T00:00:00Z','2026-08-01T00:00:00Z']},
 'source_support_gates':{'minimum_events':{'train':8,'test':12,'eval':12,'final':8},'minority_side_share_min':.2,'max_month_share':.45},'novelty_gates':{'exact_entry_jaccard_max':.1,'candidate_near_6h_share_max':.35,'occupied_5m_jaccard_max':.25,'absolute_signed_exposure_pearson_max':.35,'must_pass_before_economics':True},
 'economic_gates':{'absolute_return_positive':True,'cagr_to_strict_mdd_min':3.,'strict_mdd_max_pct':15.,'mean_gross_underlying_min_bp':20.,'weekly_signflip_one_sided_p_max':.1,'stress_absolute_return_positive':True,'stress_cagr_to_strict_mdd_min':2.5,'each_calendar_half_positive':True,'stop_on_first_failure':True,'future_can_rank_repair_or_reselect':False,'accounting':'fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR'},
 'diagnostic_controls':{'ovx_change_only':'absolute OVX change rank plus usual risk direction','vix_change_only':'absolute VIX change rank plus usual risk direction','no_btc_confirmation':'relative rotation maps high to SHORT and low to LONG','one_session_stale_rotation':'rotation signal lagged one source session','direction_flip':'same entries opposite side'},
 'source_plan':{'ovx_raw':{'path':'data/cboe_ovx_2021_2026/source/OVX_History.csv','sha256':'77f872f1e069cc93554fe6d80dc6f9d44d0a798ad0a906202a570ad81f73417a'},'ovx_manifest':{'path':'data/cboe_ovx_2021_2026/source_manifest.json','sha256':'fcceb47791eb499b3e4bee42bb35e02b4be4700fd84c684ce2822ed5e1d61511'},'vix':'hash-bound extended Cboe volatility surface','btc_confirmation':'hash-bound preentry BTC intrahour snapshot','execution_price':'sealed until source-support and Gross9 novelty pass'},
 'research_boundary':{'ovx_data_rows_opened':False,'prior_candidate_incidence_known':True,'prior_candidate_outcomes_used_for_ovrcr':False,'ovrcr_candidate_incidence_opened':False,'ovrcr_post_entry_return_or_pnl_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False,'diagnostic_controls_cannot_be_promoted':True}}
 return {**core,'manifest_hash':canonical_hash(core)}
if __name__=='__main__':p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2,ensure_ascii=False)+'\n');print(a.output)
