"""Outcome-blind preregistration for HVSPSTL-8."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any

POLICY_ID="HVSPSTL-8";SLUG="high_volatility_spot_perpetual_sign_transition_leadership_relay";DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":f"{SLUG}_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"Within a completed volatile BTC auction, an extreme excess of spot-return signs predicting the next perpetual-return sign over perpetual signs predicting the next spot sign identifies directional price discovery flowing from cash into leverage. When both venues agree in the final hour, follow that common direction for eight hours.","side":"common strict sign of final-hour spot and perpetual cumulative returns","why_distinct":"HVSPER uses level-spread error-correction loadings; HVSCTBA uses same-minute sign-conditioned continuous betas; spot-flow and first-passage candidates use order flow or threshold timing. HVSPSTL uses only a categorical one-minute cross-venue transition-count asymmetry, no levels, regression, magnitude, flow, turnover, basis, funding, OI, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"completed perpetual path variation must occupy its causal upper 35 percent","why_low_gross9_overlap_is_plausible":"offset categorical cash-to-leverage transition-leadership onsets are absent from Gross9"},
 "features":{"decision_grid":"exact 01:00, 09:00, and 17:00 UTC boundaries D","block":"480 exact aligned coherent BTCUSDT spot and perpetual one-minute rows [D-8h,D), plus exact D-8h-1m closes solely for first close-to-close returns","minute_return_sign":"strict sign of aligned close-to-close log return; zero returns abstain","spot_to_perpetual_hits":"count over 479 transitions where nonzero spot sign at t equals nonzero perpetual sign at t+1","perpetual_to_spot_hits":"count over 479 transitions where nonzero perpetual sign at t equals nonzero spot sign at t+1","eligible_pairs":"separate nonzero denominator for each direction, each at least 360","leadership_advantage":"spot_to_perpetual hit fraction minus perpetual_to_spot hit fraction, finite strict positive","leadership_rank":"strict-prior midrank over at most 270 source-valid positive advantages, minimum 180, current excluded; rank>=0.75","direction_confirmation":"final 60 completed minute returns summed separately by venue have one common strict sign","variation":"sqrt(sum squared 480 perpetual minute returns), finite strict positive","variation_rank":"strict-prior midrank over at most 270 source-valid decisions, minimum 180, current excluded; rank>=0.65","onset":"full rule true now and false at immediately prior exact source-valid decision; missing prior cannot trigger","no_imputation":True},
 "clock":{"decision":"D after all source paths complete","entry":"exact perpetual BTCUSDT D+5m open","side":"common final-hour direction","hold":"8 elapsed hours","reservation":"natural global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements only after novelty"},
 "policy":{"block_minutes":480,"minimum_transition_pairs":360,"history_decisions":270,"minimum_history_decisions":180,"leadership_rank_min":.75,"variation_rank_min":.65,"onset_required":True,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_leadership_tail","no_variation_gate","same_minute_concordance","one_block_stale_leadership","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"spot":{"table":"bars_binance_spot","symbol":"BTCUSDT"},"perpetual":{"table":"bars_binance","symbol":"BTCUSDT"},"interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration_commit":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_spot_perpetual_outcomes_known":True,"repository_exact_cross_venue_sign_transition_leadership_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent categorical cross-venue directed-transition mechanism"},
 "stopping_rule":"terminal first failure; no venue, block, sign, transition, denominator, rank, confirmation, variation, onset, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}) or x!=build():raise RuntimeError("HVSPSTL prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_bytes(b);print(a.output)
