"""Outcome-blind preregistration for HVTLRR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVTLRR-8";DEFAULT_OUTPUT=Path("results/high_volatility_turnover_lead_response_relay_preregistration_2026-08-10.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_turnover_lead_response_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-10","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When high versus low quote-turnover five-minute auctions consistently precede signed price responses in one direction during a completed high-variation BTC block, activity is leading directional price discovery rather than merely accompanying it. If the lead-response sign agrees with completed displacement, follow that direction for eight elapsed hours.","side":"common strict sign of turnover-to-next-return correlation and completed eight-hour return","why_distinct":"HVTLRR correlates current log quote turnover with the following bar's signed return. LFIC uses signed aggressive-flow imbalance; HVVRCR uses contemporaneous return-volume covariance; HVSRP uses absolute return shocks; HVTCCR uses turnover-share HHI without lagged response. No event set, diagnostic control, fitted outcome, funding, OI, premium, or cross-asset input is reused.","why_suited_to_volatile_regimes":"the causal variation tail selects volatile blocks while a turnover-leading response tail identifies staged information transmission","why_low_gross9_overlap_is_plausible":"offset three-daily turnover-lead onsets with eight-hour reservation are absent from Gross9 primitives"},
 "features":{"decision_grid":"exact 04:00/12:00/20:00 UTC boundaries","block":"96 exact coherent BTCUSDT perpetual five-minute aggregates from 480 unique one-minute rows [D-8h,D)","bar_turnover":"sum quote_asset_volume in each group, finite nonnegative","turnover_coordinate":"log1p(bar_turnover)","next_bar_return":"log(next five-minute close/next five-minute open)","lead_response":"sample Pearson correlation of turnover_coordinate[t] and next_bar_return[t+1] across 95 ordered pairs; both sample standard deviations strict positive; correlation strict nonzero","response_strength_rank":"strict-prior midrank of abs(lead_response) over at most 270 valid blocks, minimum 180, current excluded; rank>=0.75","realized_variation":"sqrt(sum squared five-minute bar returns), strict positive","variation_rank":"strict-prior midrank over at most 270 valid blocks, minimum 180, current excluded; rank>=0.65","block_return":"log(last close/first open), strict nonzero and same sign as lead_response","onset":"eligible now and immediately prior exact source-valid block ineligible; missing prior cannot trigger","no_imputation":True},
 "clock":{"decision":"completed eight-hour boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 "policy":{"history_blocks":270,"minimum_history_blocks":180,"response_strength_rank_min":.75,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_response_tail","no_variation_gate","contemporaneous_turnover_response","one_boundary_stale_response","direction_flip"],"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"prior_flow_response_volume_covariance_shock_response_and_turnover_hhi_outcomes_known":True,"repository_unsigned_turnover_to_next_return_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_rank_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"lagged activity-to-price transmission mechanism"},
 "stopping_rule":"Terminal first failure; no lag, correlation, rank, confirmation, side, hold, clock, subset, or control repair."};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}) or x!=build():raise RuntimeError("HVTLRR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(r,indent=2,allow_nan=False)+"\n");print(a.output)
