"""Outcome-blind preregistration for TPYSR-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/treasury_parallel_yield_shock_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"treasury_parallel_yield_shock_relay_v1","policy_id":"TPYSR-24","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
  "mechanism":{"claim":"A same-direction standardized daily shock in both the two-year and ten-year US Treasury par yields is a broad duration repricing rather than an isolated curve-point move. During high BTC variation, rising yields tighten the discount-rate/liquidity environment and map short BTC, while falling yields map long BTC for the next day.","side":"opposite strict sign of the median standardized two-year and ten-year yield changes","why_distinct":"No existing repository candidate uses DGS2/DGS10 or the official Treasury 2y/10y daily par-yield pair. Treasury auction candidates use issuance-event demand, SOFR candidates use money-market dislocation, and FX candidates use currency returns. TPYSR is a continuous duration-factor transmission mechanism, not a repair or diagnostic control.","why_suited_to_volatile_regimes":"the completed pre-entry BTC 24-hour realized variation must rank in its causal upper 35%.","why_low_gross9_overlap_is_plausible":"one sparse D+1 sovereign-duration shock clock is absent from Gross9 primitives."},
  "features":{"source":"official US Treasury Daily Treasury Par Yield Curve Rates XML feed","source_url_template":"https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_yield_curve&field_tdr_date_value={year}","observation":"official 2-year and 10-year par yields for Treasury observation date D","availability":"conservatively D+1 00:00 UTC; no same-date use","valid_transition":"current and previous official observations both finite positive and separated by 1 to 5 calendar days","yield_changes":"delta2=2y[D]-2y[previous], delta10=10y[D]-10y[previous], both strict nonzero with identical sign","standardization":"each tenor change standardized independently against at most 90 strictly prior valid changes, minimum 60, current excluded, sample std positive","parallel_factor":"cross-sectional median of the two standardized changes; strict nonzero","factor_rank":"strict-prior midrank of abs(parallel_factor) over at most 90 valid factors, minimum 60, current excluded; rank>=0.70","btc_realized_variation":"sqrt(sum squared exact completed hourly BTC log returns over [decision-24h,decision))","volatility_rank":"strict-prior midrank over at most 90 valid Treasury decisions, minimum 60, current excluded; rank>=0.65","no_imputation":True},
  "clock":{"decision":"exact D+1 00:00 UTC","entry":"exact D+1 00:05 UTC BTCUSDT open","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "diagnostic_controls":{"names":["two_year_only","ten_year_only","no_factor_tail","no_volatility_gate","one_observation_stale_factor","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
  "source_plan":{"treasury":"download and hash-bind official annual XML feeds for 2023-2026 only after this preregistration commit","completed_btc":"hash-bound completed-hour BTC source through 2026-08-01","execution_prices":"sealed until source support and Gross9 novelty pass"},
  "research_boundary":{"prior_macro_and_fx_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_tpysr_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent official sovereign-duration factor transmission"},
  "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no tenor, rank, side, hold, availability, volatility, or subset repair."
 };return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2)+'\n');print(a.output)
