"""Outcome-blind preregistration for GOICR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="GOICR-12";DEFAULT_OUTPUT=Path("results/gross_oi_churn_release_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"gross_oi_churn_release_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"Heavy two-way open-interest replacement with little net OI displacement is inventory transfer rather than simple leverage creation or liquidation. When the final completed hour escapes directionally at the onset of that cancellation state, follow the price direction for twelve elapsed hours.","side":"strict sign of the final completed-hour BTC return","why_distinct":"GOICR uses fixed-window total variation of log OI minus its net displacement: C=1-|sum d_i|/sum|d_i|. Existing OI candidates use net OI changes, OI-price divergence, purge, or departure-and-first-reclosure episodes. GOICR does not reuse round-trip episode settings, residual phase, signed inventory work, funding, premium, positioning ratios, or a prior diagnostic control.","volatile_market_target":"high gross OI replacement plus a late directional escape is a leveraged volatile-auction state; causal RV20 q90 remains only a later audit","why_low_gross9_overlap_is_plausible":"new three-hour-grid cancellation onsets with twelve-hour reservation"},
 "features":{"decision_grid":"exact UTC 00:00,03:00,...,21:00 boundaries D","oi_window":"73 exact BTCUSDT period=5m OI rows at timestamps [D-6h-5m,D-5m], producing 72 completed increments; each row positive and no imputation","oi_increment":"d_i=log(OI_i/OI_(i-1))","gross_churn":"G=sum(abs(d_i)), strict positive","net_displacement":"N=abs(sum(d_i))","cancellation":"C=1-N/G, finite in [0,1] up to 1e-12 tolerance","late_escape":"R=log(BTC close at D-5m / BTC open at D-1h), using exactly twelve complete coherent five-minute aggregates; strict nonzero","prior_ranks":"strict-prior midranks of G, C, N, and abs(R) over at most 720 prior valid exact three-hour decisions, minimum 480, current excluded","eligible_state":"G_rank>=0.65, C_rank>=0.80, and abs(R)_rank>=0.65","onset":"current eligible state true and immediately preceding exact three-hour opportunity false; missing prior cannot trigger","availability":"OI row timestamp D-5m and all price bars complete by D; entry one full five-minute bar later","source_valid":"exact unique OI and price timestamp grids, positive finite OI/OHLC, coherent price bars, no imputation"},
 "rv20_stress_slice":{"rv20":"sqrt(365*mean exact daily returns^2 over t-20 through t-1)","threshold":"numpy linear q90 over 756 strictly prior available RV20 observations","entry_filter":False,"future_use":"only after all sequential full-calendar stages pass"},
 "clock":{"decision":"exact three-hour UTC boundary after source completion","entry":"exact BTCUSDT decision+5m open","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact realized funding only after novelty"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","persistent_long_vol_comparator":"same accepted clock and 0.5 gross, side forced long","full_calendar_decomposition":"candidate minus comparator net return","rv20_q90_decomposition":"same decomposition on causal RV20 q90 decisions","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"candidate_specific_q90_residual_positive":True,"comparator_cannot_satisfy_candidate_claim":True},
 "diagnostic_controls":{"definitions":{"net_oi_tail_only":"N_rank>=0.65 and abs(R)_rank>=0.65 onset, side=sign(R)","gross_churn_without_cancellation":"G_rank>=0.65 and abs(R)_rank>=0.65 onset, side=sign(R)","late_price_escape_only":"abs(R)_rank>=0.65 onset, side=sign(R)","one_decision_stale_churn":"primary eligible boolean and side shifted by one exact three-hour decision with onset applied after shift","direction_flip":"negative primary side"},"cannot_be_promoted":True},
 "source_plan":{"oi":{"table":"open_interest_binance","symbol":"BTCUSDT","period":"5m","columns":["ts","sum_open_interest"],"read_after_preregistration":True},"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"prior_oi_family_outcomes_known":True,"exact_goicr_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_oi_roundtrip":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no OI path, window, rank, history, onset, side, clock, hold, RV20, subset, comparator, control, or gate repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("GOICR preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+"\n");print(a.output)
