"""Outcome-blind preregistration for CABUR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="CABUR-8"; ALTS=("ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT"); DEFAULT_OUTPUT=Path("results/cross_alt_breadth_underreaction_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"cross_alt_breadth_underreaction_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A broad four-hour move across liquid alt perpetuals with BTC moving less in absolute terms identifies cross-alt price discovery not yet assimilated by BTC. In a high-variation BTC regime, follow the alt majority through the next eight-hour interval.","side":"strict majority sign of six completed alt returns","why_distinct":"CABLR required BTC to move in the opposite direction over an eight-hour block; CABER faded confirmed BTC-alt moves; flow-leadership candidates used trade flow. CABUR requires magnitude underreaction, not sign disagreement or confirmation, on independent four-hour blocks and reuses no event set or control.","why_suited_to_volatile_regimes":"completed prior-24h BTC realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"three fixed 04:05/12:05/20:05 UTC cross-alt underreaction clocks are absent from Gross9 primitives"},
 "features":{"universe":["BTCUSDT",*ALTS],"blocks":"exact 240 one-minute bars for all seven symbols over [00:00,04:00), [08:00,12:00), or [16:00,20:00) UTC","returns":"log(last close/first open) per symbol; qualifying alt returns strict nonzero","breadth":"at least four of six alt return signs equal one strict majority sign","alt_impulse":"median absolute return across six alts","alt_impulse_rank":"strict-prior midrank over at most 270 valid blocks, minimum 180, current excluded; rank>=0.70","btc_underreaction":"absolute BTC block return is strictly less than alt_impulse","btc_realized_variation":"sqrt(sum squared BTC 1m close-to-close returns over exact 24 hours ending at decision)","variation_rank":"strict-prior midrank over at most 270 valid decisions, minimum 180, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact 04:00,12:00,20:00 UTC after four-hour block completion","entry":"exact decision+5m BTCUSDT open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not an input; exact funding only after novelty"},
 "policy":{"history_observations":270,"minimum_history_observations":180,"breadth_min":4,"alt_impulse_rank_min":.70,"variation_rank_min":.65,"underreaction_ratio_max":1.,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all four stages","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "source_plan":{"table":"bars_binance","interval":"1m","symbols":["BTCUSDT",*ALTS],"columns":["ts","open","high","low","close"],"read_after_preregistration":True,"execution_price":"sealed until source and novelty pass"},
 "diagnostic_controls":{"names":["no_volatility_gate","no_impulse_tail","no_underreaction_gate","three_of_six_breadth","one_block_stale_geometry","direction_flip","forced_long"],"cannot_be_promoted":True},
 "research_boundary":{"prior_cablr_caber_flow_leadership_evidence_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_cabur_direction_rank_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cross-alt price-discovery underreaction transmission"},
 "stopping_rule":"Terminal first failure; no universe, block, breadth, impulse, underreaction, rank, side, clock, hold, subset, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2)+"\n");print(a.output)
