"""Outcome-blind preregistration for HVEAAR-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVEAAR-8";DEFAULT_OUTPUT=Path("results/high_volatility_engulfing_auction_acceptance_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_engulfing_auction_acceptance_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"When a completed four-hour BTC auction strictly engulfs both boundaries of the preceding disjoint four-hour range yet closes in one outer quartile with an agreeing body, the two-sided liquidity sweep has resolved into accepted price discovery. Follow that accepted direction for eight hours during elevated realized variation.","side":"long for upper-quartile bullish acceptance and short for lower-quartile bearish acceptance","why_distinct":"Break-retest acceptance crosses one prior boundary and retests it; range traversal orders absolute daily extrema; wick imbalance compares aggregate tails; close-location rules use one range without a prior-range engulfment requirement. HVEAAR requires a later disjoint auction to sweep both prior boundaries and resolve at one extreme with agreeing body, using no volume, flow, funding, OI, cross-asset, fitted outcome, prior event, or control.","why_suited_to_volatile_regimes":"the combined completed eight-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"offset three-daily two-sided sweep-resolution clocks are absent from Gross9 primitives"},
 features={"decision_grid":"exact 04:00/12:00/20:00 UTC boundaries","prior_auction":"first 240 one-minute rows [D-8h,D-4h), aggregated OHLC","engulfing_auction":"last 240 one-minute rows [D-4h,D), aggregated OHLC","strict_engulfment":"engulfing high>prior high and engulfing low<prior low","close_location":"(engulfing close-engulfing low)/(engulfing high-engulfing low), denominator strict positive","long_acceptance":"strict engulfment, close_location>=0.75, and engulfing close>engulfing open","short_acceptance":"strict engulfment, close_location<=0.25, and engulfing close<engulfing open","ambiguity":"exactly one acceptance side must hold","realized_variation":"sqrt(sum squared one-minute log(close/open) returns across [D-8h,D)), finite strict positive","variation_rank":"strict-prior midrank over at most 270 earlier source-valid blocks, minimum 180, current excluded; rank>=0.65","eligible_state":"one accepted engulfing direction and variation gate pass","no_imputation":True},
 clock={"decision":"completed engulfing-auction boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_blocks":270,"minimum_history_blocks":180,"outer_quartile":.25,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_outer_quartile","no_variation_gate","engulfing_body_only","one_block_stale_prior_range","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"prior_break_retest_range_traversal_wick_and_close_location_outcomes_known":True,"repository_engulfing_auction_acceptance_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"two-sided prior-range sweep followed by extreme same-body terminal acceptance"},
 stopping_rule="Terminal first failure; no auction, engulfment, close-location, body, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVEAAR preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
