"""Outcome-blind preregistration for HVEWCS-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVEWCS-24";DEFAULT_OUTPUT=Path("results/high_volatility_ewma_conditional_skew_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ewma_conditional_skew_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"In turbulent Bitcoin regimes, the sign of a fixed exponentially weighted conditional skew estimate represents the direction of time-varying expected return compensation. Follow the sign of thirty completed daily returns' EWMA skew for twenty-four hours when both skew magnitude and twenty-day variation are causally high.","side":"strict sign of the completed thirty-day EWMA conditional skew estimate","why_distinct":"HVRSR fades one day's intraday normalized third moment; directional-tail candidates compare positive and negative minute tails. HVEWCS uses thirty separate completed daily close-to-close returns, a fixed seven-day half-life central-moment estimator, and follows rather than fades conditional skew only in a high daily-variation state, with no prior event, fitted return, or promoted control.","why_suited_to_volatile_regimes":"completed twenty-day daily realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"one 02:05 UTC daily conditional-skew clock with twenty-four-hour reservation is absent from Gross9 primitives"},
 external_basis={"paper":"Time-varying expected returns, conditional skewness and Bitcoin return predictability","authors":"David Atance and Gregorio Serna","published":"2024-08","doi":"10.1016/j.qref.2024.101868","reported_relation":"conditional skewness predicts future Bitcoin returns; relation is positive in the turmoil subsample","selection_use":"mechanism sign in volatile regimes only; no repository incidence or outcome opened"},
 features={"decision_grid":"every calendar day at exact 02:00 UTC","daily_returns":"thirty completed UTC-02:00 close-to-close BTC log returns ending at decision, requiring thirty-one exact coherent daily endpoint closes","weights":"fixed exponentially decaying weights with seven-day half-life, newest return highest, normalized to sum one","weighted_mean":"sum(weight*return)","weighted_variance":"sum(weight*(return-weighted_mean)^2), finite strict positive","conditional_skew":"sum(weight*(return-weighted_mean)^3)/weighted_variance^(3/2), finite strict nonzero","variation":"sqrt(sum squared final twenty daily returns), finite strict positive","prior_ranks":"strict-prior midranks over at most 180 earlier source-valid daily decisions, minimum 120, current excluded","skew_strength_gate":"absolute conditional-skew rank>=0.70","variation_gate":"variation rank>=0.65","no_imputation":True},
 clock={"decision":"completed daily endpoint at 02:00 UTC","entry":"exact BTCUSDT 02:05 UTC open","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"return_days":30,"variation_days":20,"weight_half_life_days":7,"history_days":180,"minimum_history_days":120,"skew_strength_rank_min":.70,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_skew_strength","no_variation_gate","unweighted_skew","one_day_stale_features","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-02-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"external_primary_mechanism_read":True,"prior_intraday_realized_skew_and_tail_outcomes_known":True,"repository_ewma_conditional_skew_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"paper-supported positive conditional-skew relation in turbulent regimes with fixed EWMA estimator"},
 stopping_rule="Terminal first failure; no return window, half-life, moment estimator, rank history, skew strength, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVEWCS preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
