"""Outcome-blind preregistration for HVVHF-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVVHF-24";DEFAULT_OUTPUT=Path("results/high_volatility_vertical_horizontal_filter_trend_onset_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_vertical_horizontal_filter_trend_onset_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, the canonical twenty-eight-period Vertical Horizontal Filter first crossing into a strong-trend state on completed four-hour BTC auctions marks conversion of noisy travel into directional displacement; follow the sign of the same-window net close displacement for twenty-four hours.","side":"at a strict VHF upward crossing of 0.4, long when current close exceeds the close 28 bars earlier and short when it is lower","why_distinct":"VHF divides the close range by total absolute close travel and therefore measures path efficiency without ADX directional movement, return magnitude threshold, range location, recursive filter, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the trend-efficiency onset must coincide with completed trailing twenty-four-hour realized variation in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse path-efficiency trend-onset clocks are absent from Gross9 primitives"},
 external_basis={"origin":"Adam White, canonical Vertical Horizontal Filter","sources":["https://traders.com/documentation/feedbk_docs/2000/07/Abstracts_new/Gopalakrishnan/Gopalakrishnan.html","https://www2.wealth-lab.com/WL5wiki/VHF.ashx"],"fixed_definition":"28 completed closes; VHF=(highest close-lowest close)/sum of 28 absolute close changes; strong-trend boundary 0.4 as in the published platform example; direction from same-window net close displacement","selection_use":"published period, formula, trend-state example boundary, and contemporaneous displacement interpretation only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","close_range":"highest minus lowest completed close over latest 28 bars","absolute_travel":"sum of latest 28 absolute completed close changes, requiring 29 uninterrupted closes","vhf":"close_range divided by absolute_travel, invalid at zero denominator","trend_onset":"current VHF strictly above 0.4 after immediately prior VHF at or below 0.4","direction":"sign of current completed close minus close 28 bars earlier, invalid at zero","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"vhf_periods":28,"trend_threshold":.4,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","direction_only","one_bar_stale_onset","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_vhf_definition_read":True,"repository_vhf_candidate_found":False,"prior_trend_strength_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical VHF(28) strong-trend onset with same-window displacement direction under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no period, formula, threshold, displacement direction, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVVHF preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
