"""Outcome-blind preregistration for HVEQT-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVEQT-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_quotient_early_onset_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_quotient_early_onset_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' published Quotient Transform crossing its bias-specific zero threshold on completed four-hour BTC auctions identifies early onset of a directional move; follow the new direction for twenty-four hours.","side":"long when the K=+0.85 quotient strictly crosses above zero; short when the K=-0.85 quotient strictly crosses below zero, matching the article's inverted downward-bias rule","why_distinct":"A 100-period high-pass and period-30 SuperSmoother form a Roofing Filter, a fast-attack .991-decay peak normalizes it, and sign-specific nonlinear quotient transforms move the onset thresholds to X=-.85 for long and X=+.85 for short. It is not a raw Roofing zero-cross, price or moving-average crossover, fixed symmetric oscillator threshold on an untransformed field, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the transform is designed for early trend detection and only triggers while completed trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"nonlinear bias-specific normalized-Roofing onset crossings are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, The Quotient Transform, TASC August 2014","source":"https://traders.com/documentation/feedbk_docs/2014/08/TradersTips.html","fixed_definition":"maxBarsLen=100, LPPeriod=30, peak decay=.991, K=+.85 for upward bias; HP and SuperSmoother Roofing Filter; X=Filt/Peak; Quotient=(X+K)/(K*X+1); long when positive-K quotient crosses above zero; article also specifies negative K and inverted logic for short entry in a downward-biased market","selection_use":"published parameters, recursions, normalization, positive/negative K transforms, and their stated entry directions only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","high_pass":"published two-pole high-pass removing periods longer than 100 completed decisions","super_smoother":"published period-30 two-pole SuperSmoother of the high-pass field","normalization":"Peak=max(abs(Filt),.991*prior_Peak); X=Filt/Peak when Peak>0","quotients":"Q_long=(X+.85)/(.85*X+1); Q_short=(X-.85)/(1-.85*X)","event":"strict finite Q_long zero cross upward for long or Q_short zero cross downward for short relative to the immediately prior valid decision","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"invalid completed four-hour bars reset HP, smoother, and Peak; initialize recursive outputs and Peak to zero; require 100 uninterrupted observations and finite current/prior quotients","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"high_pass_period":100,"low_pass_period":30,"peak_decay":.991,"linearity_control":.85,"warmup_observations":100,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","normalized_roofing_zero_cross","one_bar_stale_onset","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_quotient_strategy_read":True,"repository_quotient_candidate_found":False,"prior_roofing_filter_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published Ehlers positive-K upward-bias and negative-K inverted downward-bias Quotient Transform entries under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no period, decay, K, recursion, normalization, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVEQT preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
