"""Outcome-blind OOS preregistration for HVCAFRR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID='HVCAFRR-8';SLUG='high_volatility_cross_alt_frozen_response_ridge_relay';ALTS=('ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','DOGEUSDT','ADAUSDT');DEFAULT_OUTPUT=Path(f'results/{SLUG}_preregistration_2026-08-13.json')
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build():
 core={'protocol_version':'high_volatility_cross_alt_frozen_response_ridge_relay_v1','policy_id':POLICY_ID,'slug':SLUG,'as_of_date':'2026-08-13','singleton':True,'oos_outcomes_opened':False,'oos_source_incidence_opened':False,'gross9_rows_opened':False,
 'mechanism':{'claim':'A fixed pre-OOS ridge response law can distinguish which completed cross-alt displacement and path-efficiency configurations historically transmitted into BTC over the next funding cycle. In elevated BTC variation, follow only upper-tail absolute frozen predictions; never refit on OOS outcomes.','side':'strict sign of the frozen ridge prediction of the next eight-hour BTC log return','why_distinct':'HVABLR and HVEBLR use one lagged correlation and contemporaneous directional confirmation. HVKAR uses BTC-only daily nearest neighbors trained on 2021-2023. Online expert/FTRL candidates update from OOS outcomes. HVCAFRR uses six named alt returns plus six signed path efficiencies and BTC normalized displacement in one fixed linear response law calibrated only on 2023H1; no OOS refit, tree, neighbor retrieval, event reuse, promoted control, funding, OI, premium, volume, or flow input is used.','why_suited_to_volatile_regimes':'completed trailing twenty-four-hour BTC realized variation must rank in its causal upper 35 percent, selecting July-like volatile states','why_low_gross9_overlap_is_plausible':'offset upper-tail frozen cross-alt response predictions are absent from Gross9 primitives'},
 'features':{'decision_grid':'exact 06:00, 14:00, and 22:00 UTC boundaries D','source_path':'96 exact five-minute aggregates per symbol from 480 exact coherent bars_binance one-minute rows [D-8h,D)','alt_return_features':'six named alt sums of five-minute log(close/open) returns','alt_signed_efficiency_features':'for each alt, sign(alt return)*abs(alt return)/sum absolute five-minute returns, denominator strict positive','btc_normalized_displacement':'sum BTC five-minute returns divided by sqrt(sum BTC one-minute squared log(close/open) returns), denominator strict positive','feature_vector_order':['ETH_return','SOL_return','BNB_return','XRP_return','DOGE_return','ADA_return','ETH_signed_efficiency','SOL_signed_efficiency','BNB_signed_efficiency','XRP_signed_efficiency','DOGE_signed_efficiency','ADA_signed_efficiency','BTC_normalized_displacement'],'btc_realized_variation_24h':'sqrt(sum squared exact BTC one-minute log(close/open) returns over [D-24h,D)), finite strict positive','variation_rank':'strict-prior midrank over at most 270 source-valid decisions including calibration history, minimum 180, current excluded; OOS eligibility requires rank>=0.65','no_imputation':True},
 'model':{'calibration_decisions':['2023-01-09T06:00:00Z','2023-07-01T00:00:00Z'],'label':'log(BTCUSDT open at D+8h+5m / open at D+5m); only labels whose exit is strictly before 2023-07-01 are admitted','calibration_boundary':'calibration feature and label values may be opened only after this preregistration; no OOS entry/exit price, return, funding, PnL, or Gross9 row may be opened before authorization','normalization':'componentwise calibration median and max(calibration IQR,1e-12); frozen','family':'closed-form ridge with explicit intercept','ridge_lambda':1.0,'penalty':'identity on 13 normalized slopes; intercept unpenalized','minimum_calibration_rows':480,'fit_once':True,'oos_refit':False,'prediction':'intercept plus normalized feature dot frozen slopes; strict nonzero','prediction_strength_rank':'strict-prior midrank of absolute frozen predictions over at most 270 earlier source-valid decisions including calibration predictions, minimum 180, current excluded; OOS eligibility requires rank>=0.75','grid':False},
 'clock':{'entry':'exact BTCUSDT OOS D+5m open','hold':'8 elapsed hours','reservation':'global chronological half-open; exit first on equal entry','split_crossing_action':'skip','gross_exposure':.5,'funding':'not a signal input; exact held-interval funding only after novelty'},
 'policy':{'history_decisions':270,'minimum_history_decisions':180,'prediction_rank_min':.75,'variation_rank_min':.65,'ridge_lambda':1.,'minimum_calibration_rows':480,'entry_delay_minutes':5,'hold_hours':8,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 'stages':{'train':['2023-07-01T00:00:00Z','2024-01-01T00:00:00Z'],'test':['2024-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'eval':['2025-01-01T00:00:00Z','2026-01-01T00:00:00Z'],'final':['2026-01-01T00:00:00Z','2026-08-01T00:00:00Z']},'source_support_gates':{'minimum_events':{'train':8,'test':12,'eval':12,'final':8},'minority_side_share_min':.2,'max_month_share':.45},'novelty_gates':{'exact_entry_jaccard_max':.1,'candidate_near_6h_share_max':.35,'occupied_5m_bar_jaccard_max':.25,'absolute_signed_exposure_pearson_max':.35,'must_pass_before_economics':True},
 'economic_gates':{'absolute_return_positive':True,'cagr_to_strict_mdd_min':3.,'strict_mdd_max_pct':15.,'mean_gross_underlying_min_bp':20.,'weekly_signflip_one_sided_p_max':.1,'stress_absolute_return_positive':True,'stress_cagr_to_strict_mdd_min':2.5,'each_calendar_half_positive':True,'stop_on_first_failure':True,'accounting':'fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR'},'post_stage_volatility_audit':{'prerequisite':'unchanged all-stage pass','rv20_q90_entry_filter':False,'minimum_q90_trades':8,'candidate_q90_absolute_return_positive':True,'identical_clock_forced_long_residual_positive':True},
 'diagnostic_controls':{'names':['no_prediction_tail','no_variation_gate','alt_returns_only_ridge','one_block_stale_prediction','direction_flip','forced_long'],'cannot_be_promoted':True},'source_plan':{'bars':{'table':'bars_binance','symbols':['BTCUSDT',*ALTS],'interval':'1m','columns':['ts','symbol','open','high','low','close'],'window':['2023-01-01T00:00:00Z','2026-08-01T00:00:00Z'],'read_after_preregistration':True},'calibration_execution_opens':'BTCUSDT D+5m and D+8h+5m opens for admitted 2023H1 labels only','oos_execution_prices':'sealed until source support and Gross9 novelty pass'},
 'research_boundary':{'prior_machine_learning_and_cross_alt_outcomes_known':True,'repository_frozen_cross_alt_path_response_ridge_candidate_found':False,'prior_event_sets_or_controls_reused':False,'prior_outcomes_used_to_set_feature_order_lambda_rank_side_hold_or_clock':False,'calibration_values_opened_before_preregistration':False,'oos_candidate_incidence_opened':False,'oos_postentry_return_or_pnl_opened':False,'gross9_rows_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False,'promoted_prior_control':False,'selection_basis':'independent fixed pre-OOS cross-asset response-estimation mechanism'},'stopping_rule':'terminal first failure; no calibration window, feature, normalization, lambda, label, history, prediction rank, variation, side, clock, hold, subset, threshold, refit, comparator, or control repair'};return {**core,'manifest_hash':canonical_hash(core)}
def validate(x):
 if x.get('manifest_hash')!=canonical_hash({k:v for k,v in x.items() if k!='manifest_hash'}) or x!=build():raise RuntimeError('HVCAFRR prereg drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+'\n').encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f'refusing overwrite {a.output}')
 a.output.write_bytes(b);print(a.output)
