"""Outcome-blind preregistration for SLVCR-6."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any

DEFAULT_OUTPUT=Path("results/spot_led_volatility_catchup_relay_preregistration_2026-08-08.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"spot_led_volatility_catchup_relay_v1","policy_id":"SLVCR-6","as_of_date":"2026-08-08","outcomes_opened":False,"source_incidence_opened":False,
 "mechanism":{"claim":"When Binance BTCUSDT spot and perpetual move in the same direction during a completed hour but a large cash-market move is transmitted only partially to the perpetual while both BVOL and DVOL expand, cash-led price discovery should pull the perpetual in the same direction for six hours.","side":"sign of the completed spot return","why_distinct":"SLVCR uses hourly spot-versus-perpetual price transmission under joint crypto implied-volatility expansion. CSPR used five-minute signed-flow coherence, execution centroids, and opposite perpetual capital/event flow; SLVCR uses none of those. PVIAR used premium-index intrahour acceleration, and DQDIR used stablecoin quote-flow topology plus OI contraction.","why_low_gross9_overlap_is_plausible":"cash-led hourly spot/perpetual transmission under dual implied-volatility ignition is absent from Gross9"},
 "clock":{"decision":"T after exact completed UTC hour [T-1h,T)","spot_source":"60 exact bars_binance_spot BTCUSDT interval=1m rows","perpetual_source":"60 exact bars_binance BTCUSDT interval=1m rows","returns":"hour_close/hour_open-1 independently for spot and perpetual","spot_tail":"nonzero abs spot return >= strictly-prior 720h q60 with 672 valid observations","direction_agreement":"spot and perpetual completed-hour returns have the same nonzero sign","partial_transmission":"abs perpetual return <= 0.50*abs spot return","volatility_ignition":"normalized completed-hour BVOL and DVOL bodies are both strictly positive","trigger":"false-to-true onset with prior source-valid consecutive hour","entry":"exact BTCUSDT perpetual T+5m open","side":"sign of spot return","hold":"6 elapsed hours","reservation":"global half-open, exit first on equal open","funding":"not a signal input; exact settlements only for later PnL","oi_premium_forbidden_as_signal_inputs":True,"no_imputation":True},
 "policy":{"spot_prior_hours":720,"spot_min_hours":672,"spot_absolute_return_quantile":.60,"maximum_perpetual_to_spot_return_ratio":.50,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"spot_hourly":{"table":"bars_binance_spot","symbol":"BTCUSDT","interval":"1m","window":["2023-06-01T00:00:00Z","2026-08-01T00:00:00Z"],"materialize_after_preregistration":True},"perpetual_completed_hour":"reuse hash-bound OLIAH completed-hour snapshot","volatility":"reuse hash-bound OCDR-12C BVOL/DVOL snapshot","execution_price":"sealed until source-support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_joint_expansion","no_spot_tail","no_direction_agreement","no_partial_transmission","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"prior_spot_perpetual_family_outcomes_known":True,"prior_candidate_outcomes_used_to_define_slvcr":False,"slvcr_candidate_incidence_opened":False,"slvcr_post_entry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no repair"}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2,ensure_ascii=False)+"\n");print(a.output)
