"""Outcome-blind preregistration for CATLR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/cross_asset_ticket_leadership_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"cross_asset_ticket_leadership_relay_v1","policy_id":"CATLR-12","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
  "mechanism":{"claim":"A high-volatility BTC move is more likely to be durable when BTC's average quote notional per execution expands relative to its own history substantially more than the corresponding normalized ticket sizes of six liquid alt perpetuals. The cross-sectional ticket lead identifies BTC-specific large-order sponsorship rather than market-wide retail activity.","side":"strict sign of the completed BTC eight-hour return","why_distinct":"HVSTER used absolute BTC execution-count and average-ticket calibration and faded small-ticket activity. CQSTL compared stablecoin quote contracts. Cross-alt candidates used return breadth or taker-flow direction. CATLR uses self-normalized average ticket size across BTC versus six alt perpetuals and follows BTC-specific sponsorship; no prior event or control is reused.","why_suited_to_volatile_regimes":"both BTC eight-hour absolute displacement and sixteen-hour range volatility must be causal upper-tail states.","why_low_gross9_overlap_is_plausible":"Gross9 has no seven-symbol relative ticket-size leadership primitive."},
  "features":{"decision":"exact 00:00/08:00/16:00 UTC after eight completed hours","symbols":["BTCUSDT","ADAUSDT","BNBUSDT","DOGEUSDT","ETHUSDT","SOLUSDT","XRPUSDT"],"block":"480 exact consecutive one-minute rows per symbol in [D-8h,D)","average_ticket":"sum(quote_asset_volume)/sum(number_of_trades), positive denominator","self_normalized_ticket":"log(average_ticket/current strictly-prior median average_ticket) using at most 90 prior valid blocks, minimum 60, current excluded","ticket_leadership":"BTC self_normalized_ticket minus cross-sectional median of six alt self_normalized_ticket values","leadership_rank":"strict-prior midrank of ticket_leadership over at most 90 valid blocks, minimum 60, current excluded; rank>=0.75; negative leadership is ineligible","btc_return":"log(last minute close/first minute open), strict nonzero","return_rank":"strict-prior midrank of abs(btc_return), at most 90 valid blocks, minimum 60, current excluded; rank>=0.60","range_vol":"max(high)/min(low)-1 over sixteen exact completed BTC hours [D-16h,D)","volatility_rank":"strict-prior midrank over at most 90 valid blocks, minimum 60, current excluded; rank>=0.65","no_imputation":True},
  "clock":{"entry":"exact D+5m BTCUSDT open","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "diagnostic_controls":{"names":["btc_ticket_only","alt_ticket_suppression_only","no_return_tail","no_volatility_gate","one_block_stale_leadership","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
  "database_contract":{"env_file":"/home/pakchu/rllm/.env","table":"bars_binance","interval":"1m","columns":["symbol","ts","open","high","low","close","quote_asset_volume","number_of_trades"],"read_only":True},
  "research_boundary":{"prior_ticket_and_cross_alt_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_catlr_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cross-sectional self-normalized ticket sponsorship mechanism"},
  "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no symbol, median, rank, side, hold, clock, volatility, return, or subset repair."
 };return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2)+'\n');print(a.output)
