"""Outcome-blind preregistration for HVDEC-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVDEC-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_decycler_oscillator_zero_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_decycler_oscillator_zero_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' canonical 125-period Decycler Oscillator crossing zero on completed four-hour BTC auctions identifies a near-zero-lag reversal in the isolated trend component; follow the new oscillator sign for twenty-four hours.","side":"long on a strict nonpositive-to-positive Decycler Oscillator crossing; short on a strict nonnegative-to-negative crossing","why_distinct":"The Decycler Oscillator recursively subtracts a two-pole high-pass component from close, then high-pass filters that decycled trend at half the original period and normalizes by current close. It is not a moving-average crossover, return sum, range oscillator, regression, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the published near-zero-lag trend reversal must coincide with completed trailing twenty-four-hour realized variation in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse cascaded recursive high-pass trend-component sign reversals are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Decyclers, TASC September 2015","source":"https://traders.com/Documentation/FEEDbk_docs/2015/09/TradersTips.html","fixed_definition":"HPPeriod=125 and K=1; published alpha and two-pole high-pass recursions; Decycle=Close-HP; second high-pass uses half-period; oscillator=100*K*DecycleOsc/Close; zero line","selection_use":"published default parameters, formula, normalization, and zero line only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","decycler":"Close minus the recursively filtered 125-period high-frequency component","decycler_oscillator":"second published two-pole high-pass recursion over Decycle using 0.5*HPPeriod, normalized as 100*K*DecycleOsc/Close","event":"strict finite normalized oscillator zero crossing from the immediately prior finite oscillator","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"all recursive filter state resets after any invalid completed four-hour bar and requires three consecutive valid inputs before output","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"hp_periods":125,"k":1.0,"fast_control_hp_periods":100,"fast_control_k":1.2,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","fast_100_decycler","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_decycler_definition_read":True,"repository_decycler_candidate_found":False,"prior_recursive_filter_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Ehlers Decycler Oscillator(125,1) zero crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no period, recursion, initialization, threshold, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVDEC preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
