"""Outcome-blind preregistration for HVIBS-D20-80-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVIBS-D20-80-24";DEFAULT_OUTPUT=Path("results/high_volatility_internal_bar_strength_extreme_reversal_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_internal_bar_strength_extreme_reversal_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated completed realized variation, a daily BTC close in the bottom or top fifth of its own completed high-low range is an Internal Bar Strength extreme. Fade the one-day closing-location displacement for twenty-four hours.","side":"long when IBS<=0.20; short when IBS>=0.80","why_distinct":"IBS is the completed daily candle's own close location with no trailing price envelope. The prior range-boundary fade used a rolling twelve-hour range, six fixed four-hour clocks, 0.10/0.90 edges, two-hour holds, and a top-20% range-rank gate. This policy reuses no event set or control and uses no volume, flow, OI, funding, or fitted outcome.","why_suited_to_volatile_regimes":"daily closing-location overshoot is admitted only when completed twenty-day close-to-close realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse daily own-range closing-location extremes are absent from Gross9 primitives"},
 external_basis={"origin":"Internal Bar Strength; QuantConnect LEAN canonical implementation and conventional 20/80 extreme interpretation","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/InternalBarStrength.cs","definition_source_sha256":"5d91f2f8de34f2dfa62b4a84666bd3bee4b1a38422ec025668504664024e3fd0","fixed_definition":"IBS=(close-low)/(high-low); exact zero range returns .5; LEAN states low values are bullish and high values bearish; conventional bottom/top fifth extremes are fixed at .20/.80","selection_use":"official formula and direction plus conventional symmetric 20/80 extreme levels only; no incidence or outcomes"},
 features={"decision_grid":"every calendar day at exact 00:00 UTC","daily_bar":"exact aggregation of 1,440 coherent BTCUSDT one-minute rows [D-24h,D)","ibs":"(daily close-daily low)/(daily high-daily low), strict positive range required by this policy","event":"IBS<=.20 gives long, IBS>=.80 gives short; middle values no event","variation":"sqrt(sum squared latest twenty completed daily close-to-close log returns), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier source-valid daily decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"daily aggregation, variation window, and rank history reset after any invalid completed day","no_imputation":True},
 clock={"feature_available":"00:00 UTC after completed daily bar","entry":"exact BTCUSDT 00:05 UTC open","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"lower_extreme_max":.20,"upper_extreme_min":.80,"variation_days":20,"variation_history_days":180,"minimum_variation_history_days":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","middle_half_direction","one_day_stale_extreme","direction_follow","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_internal_bar_strength_definition_read":True,"repository_internal_bar_strength_candidate_found":False,"prior_range_boundary_and_close_location_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical daily IBS symmetric extreme reversal under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no bar, extreme levels, variation, side, hold, clock, subset, threshold, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVIBS-D20-80-24 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
