"""Outcome-blind preregistration for HVABANDS-B10-W4-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVABANDS-B10-W4-24";DEFAULT_OUTPUT=Path("results/high_volatility_acceleration_bands_breakout_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_acceleration_bands_breakout_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated completed realized variation, a four-hour close newly escaping the official Acceleration Bands(10,4,SMA) envelope identifies directional price acceleration beyond a range-expanded high/low boundary. Follow the outward break for twenty-four hours.","side":"long on a strict close cross above the completed upper band; short on a strict close cross below the completed lower band","why_distinct":"Acceleration Bands first expands every high and low by its own contemporaneous range-to-midprice coefficient and then averages those transformed boundaries. This is neither close dispersion (Bollinger), ATR around a center (Keltner), raw extrema (Donchian), nor OLS residual dispersion (Regression Channel). No fitted outcome, volume, flow, OI, funding, reused event set, or promoted control is used.","why_suited_to_volatile_regimes":"the transformed envelope demands acceleration beyond recent range geometry while trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse four-hour transformed-range envelope crossings are absent from Gross9 primitives"},
 external_basis={"origin":"Price Headley Acceleration Bands; QuantConnect LEAN canonical implementation","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/AccelerationBands.cs","definition_source_sha256":"e1e6e364022d59bcf780746237437f747b84a1c75e4ecc9ea1c6202fdd3eb9c0","documentation_source":"https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/acceleration-bands","fixed_definition":"official documentation example period=10,width=4,Simple; coefficient=4*(high-low)/(high+low) with SafeDivision; raw upper=high*(1+coefficient), raw lower=low*(1-coefficient), raw middle=close; each output is its 10-period SMA; warmup 10","selection_use":"official example period, default width, SMA type, formulas, readiness, and outward crossing only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","coefficient":"4*(high-low)/(high+low), denominator strict positive for valid BTC prices","upper_band":"SMA(10) of high*(1+coefficient), including current completed bar","lower_band":"SMA(10) of low*(1-coefficient), including current completed bar","event":"current close>current upper and previous close<=previous upper gives long; current close<current lower and previous close>=previous lower gives short; exactly one side","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier source-valid four-hour decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"bar aggregation, all three SMA windows, crossing state, and variation history reset after any invalid completed source bar","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"period":10,"width":4.0,"moving_average":"simple","variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","middle_band_cross","raw_transformed_boundary_break","one_bar_stale_cross","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_acceleration_bands_definition_read":True,"repository_acceleration_bands_candidate_found":False,"prior_bollinger_keltner_donchian_and_regression_channel_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official documented AccelerationBands(10,4,SMA) outward crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no period, width, average type, transformation, crossing, variation, side, hold, clock, subset, threshold, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVABANDS-B10-W4-24 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
