"""Outcome-blind preregistration for KCLR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/korean_cash_leadership_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"korean_cash_leadership_relay_v1","policy_id":"KCLR-12","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
 "mechanism":{"claim":"During a high-variation completed Asia session, same-direction movement in Upbit KRW-BTC cash and Binance BTCUSDT perpetual is cash-sponsored regional price discovery when the absolute Upbit move exceeds the perpetual move. Follow the common direction for twelve hours as the larger Korean cash impulse transmits globally.","side":"common strict nonzero sign of completed Upbit and Binance returns","why_distinct":"KPAR used FX-adjusted kimchi-premium acceleration; DCVPRR used cross-venue participation rotation; SLVCR used Binance spot/perpetual partial transmission under implied-volatility expansion. KCLR uses direct Upbit-versus-perpetual price leadership, no FX, premium, volume, flow, or implied volatility, and promotes no prior control.","why_suited_to_volatile_regimes":"completed Binance session realized-variation rank must be at least 0.65","why_low_gross9_overlap_is_plausible":"one daily 08:05 UTC regional cash-leadership clock is distinct from the dense asymmetric fresh_kimchi_fx sleeve"},
 "features":{"session":"exact aligned bars_upbit KRW-BTC and bars_binance BTCUSDT 1m paths [00:00,08:00) UTC each calendar day; all 480 timestamps required","returns":"log(07:59 close/00:00 open) independently by venue; strict nonzero and same sign","leadership":"abs(Upbit return)>abs(Binance perpetual return), strict inequality and no magnitude threshold","btc_variation":"sqrt(sum squared Binance 1m log(close/open)) over the completed session","btc_variation_rank":"strict-prior midrank against at most 270 previous valid daily sessions; minimum 180; current excluded; rank>=0.65","availability":"08:00 UTC after both exact source paths complete","missing_duplicate_nonpositive_or_incoherent":"ineligible or source failure; no imputation"},
 "clock":{"decision":"each calendar day 08:00 UTC after both source sessions complete","entry":"exact 08:05 UTC BTCUSDT perpetual 5m open","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes","no_imputation":True},
 "policy":{"history_observations":270,"minimum_history_observations":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"upbit":{"table":"bars_upbit","symbol":"KRW-BTC","interval":"1m","columns":["ts","open","high","low","close"],"read_only":True},"perpetual":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_only":True},"execution_price":"sealed until source support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_volatility_gate","no_leadership_gate","binance_leadership","one_day_stale_geometry","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"database_metadata_only_opened_before_preregistration":True,"upbit_or_binance_values_used_to_select_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent Korean cash price-leadership channel plus user-required high volatility"},
 "stopping_rule":"terminal first-failure sequence: source support, Gross9 novelty, strict economics; no session, leadership, threshold, side, hold, timing, volatility, or subset repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(r:dict[str,Any])->None:
 if r.get("manifest_hash")!=canonical_hash({k:v for k,v in r.items() if k!="manifest_hash"}) or r.get("outcomes_opened") is not False or r.get("source_incidence_opened") is not False:raise RuntimeError("KCLR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
