"""Outcome-blind singleton preregistration for VSDAR-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/volatility_shock_disagreement_absorption_relay_preregistration_2026-08-08.json");SOURCE=Path("data/cboe_volatility_surface_2021_2026/cboe_volatility_surface_2021-01-01_2026-08-07.csv.gz");SOURCE_MANIFEST=Path("data/cboe_volatility_surface_2021_2026/manifest.json");SOURCE_SHA256="42eb1093f5167aec9c71a4733ab3451e40807c81dc7cb49568a6a0c634267ba0";SOURCE_MANIFEST_SHA256="ec1dd33efcee29b75c80294fb594969cd1b12a9343fc40f888525db4400bc936"
def chash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"volatility_shock_disagreement_absorption_relay_v1","policy_id":"VSDAR-24","as_of_date":"2026-08-08","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
 "mechanism":{"claim":"A large one-session VIX move opposed by the VVIX/VIX relative-convexity move is an unconfirmed volatility shock likely to be absorbed after the close; BTC should relay opposite the VIX shock's usual risk implication for the next 24 elapsed hours.","long":"delta_log_vix>0 and delta_log(VVIX/VIX)<0","short":"delta_log_vix<0 and delta_log(VVIX/VIX)>0","side":"sign(delta_log_vix): rising VIX maps to BTC LONG because absorption reverses the usual risk-off implication","why_distinct":"VSDAR is a magnitude-gated first-difference disagreement/absorption clock. CVACR required three-way same-sign continuation, CVSRC used static outer levels, and CTHD used static tail pressure.","why_low_gross9_overlap_is_plausible":"official Cboe next-session shock-disagreement timing is external to BTC activity clocks"},
 "features":{"vix_change":"log(VIX_t/VIX_t-1)","relative_convexity_change":"log((VVIX/VIX)_t/(VVIX/VIX)_t-1)","absolute_vix_change_rank":"strict-prior midrank over 252 valid observations, minimum 126; current appended after rank","magnitude_gate":"absolute_vix_change_rank>=0.75","adjacency":"immediately previous exact common source row; no calendar fill","zero_or_nonfinite":"ineligible","no_imputation":True},
 "clock":{"trigger":"every eligible disagreement observation; no onset filter","entry":"first later exact common Cboe source date at 09:35 America/New_York","hold":"24 elapsed hours","reservation":"global half-open, entry equal to prior exit accepted","split_crossing_action":"skip","gross_exposure":.5,"btc_price_oi_funding_forbidden_as_signal_inputs":True},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},"economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, favorable then adverse held 5m, global HWM, full-calendar CAGR"},
 "controls":["no_magnitude_gate","vix_shock_only","relative_convexity_only","same_sign_confirmation","direction_flip"],"source_binding":{"panel":{"path":str(SOURCE),"sha256":SOURCE_SHA256},"manifest":{"path":str(SOURCE_MANIFEST),"sha256":SOURCE_MANIFEST_SHA256}},"research_boundary":{"candidate_incidence_opened":False,"candidate_post_entry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_cvacr":False,"promoted_prior_control":False,"future_can_rank_repair_or_reselect":False},"stopping_rule":"terminal first failure; no threshold, side, hold, or subset repair"};return {**core,"manifest_hash":chash(core)}
def validate(p:dict[str,Any])->None:
 core={k:v for k,v in p.items() if k!="manifest_hash"}
 if p.get("manifest_hash")!=chash(core):raise RuntimeError("VSDAR canonical hash mismatch")
 for path,want in ((SOURCE,SOURCE_SHA256),(SOURCE_MANIFEST,SOURCE_MANIFEST_SHA256)):
  if hashlib.sha256(path.read_bytes()).hexdigest()!=want:raise RuntimeError("VSDAR source hash mismatch")
def write(output:Path=DEFAULT_OUTPUT)->dict[str,Any]:
 p=build();validate(p);b=json.dumps(p,indent=2,ensure_ascii=False,allow_nan=False)+"\n";output.parent.mkdir(parents=True,exist_ok=True)
 if output.exists() and output.read_text()!=b:raise RuntimeError("VSDAR prereg byte drift")
 output.write_text(b);return p
if __name__=="__main__":a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);x=a.parse_args();print(json.dumps({"output":str(x.output),"manifest_hash":write(x.output)["manifest_hash"]},indent=2))
