"""Outcome-blind preregistration for HVSVF-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID='HVSVF-8';SLUG='high_volatility_signed_variance_feedback_relay';DEFAULT_OUTPUT=Path('results/high_volatility_signed_variance_feedback_relay_preregistration_2026-08-10.json')
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  'protocol_version':'high_volatility_signed_variance_feedback_relay_v1','policy_id':POLICY_ID,'slug':SLUG,'as_of_date':'2026-08-10','outcomes_opened':False,'source_incidence_opened':False,'gross9_rows_opened':False,'singleton':True,
  'mechanism':{'claim':'Within a completed high-variation BTC path, the normalized lagged product of each five-minute return with the next return squared identifies which signed shocks systematically propagate into subsequent activity. A new upper-tail absolute propagation state should continue in the feedback sign for eight hours.','side':'strict sign of the signed return-to-next-variance feedback score','why_distinct':'Realized-skew candidates sum contemporaneous return cubes; HVSAR correlates adjacent signed returns; HAR and VoV candidates forecast variation magnitude; HVRSSR estimates negative covariance and fades total displacement. HVSVF uses a directional lag operator from signed return r_t to unsigned next-interval energy r_(t+1)^2, reusing no event set or control.','volatile_market_target':'completed eight-hour realized-variation strict-prior rank >=0.65','why_low_gross9_overlap_is_plausible':'three daily onset opportunities based on a lagged third-order path functional are absent from Gross9 primitives'},
  'features':{'decision_grid':'exact 00:00, 08:00 and 16:00 UTC boundaries D','source_window':'480 exact coherent bars_binance BTCUSDT interval=1m rows [D-8h,D)','five_minute_aggregation':'96 exact left-labeled groups of five consecutive rows; OHLC first/max/min/last','five_minute_returns':'95 close-to-close natural-log returns from aggregated closes','feedback_numerator':'sum over t=1..94 of r_t * r_(t+1)^2','feedback_denominator':'sqrt(sum r_t^2 * sum r_(t+1)^4), finite strict positive','feedback_score':'numerator/denominator, finite in [-1,1] and strict nonzero','feedback_magnitude_rank':'strict-prior midrank of abs(feedback_score) over at most 270 earlier source-valid blocks, minimum 180; current excluded; rank>=0.80','realized_variation':'sum squared 95 five-minute returns, finite strict positive','variation_rank':'strict-prior 270/180 midrank; current excluded; rank>=0.65','eligible_state':'feedback-magnitude and variation gates pass','onset':'eligible now and immediately previous exact source-valid block ineligible','no_imputation':True},
  'clock':{'decision':'D after the full path completes','entry':'exact BTCUSDT D+5m open','side':'strict sign(feedback_score)','hold':'8 elapsed hours','reservation':'global half-open; exit first on equal entry','split_crossing_action':'skip','gross_exposure':.5,'funding':'not a signal input; exact realized funding only after novelty'},
  'policy':{'window_minutes':480,'five_minute_bars':96,'return_observations':95,'feedback_pairs':94,'prior_blocks':270,'minimum_prior_blocks':180,'feedback_magnitude_rank_min':.80,'variation_rank_min':.65,'entry_delay_minutes':5,'hold_hours':8,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
  'stages':{'train':['2023-07-01T00:00:00Z','2024-01-01T00:00:00Z'],'test':['2024-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'eval':['2025-01-01T00:00:00Z','2026-01-01T00:00:00Z'],'final':['2026-01-01T00:00:00Z','2026-08-01T00:00:00Z']},
  'source_support_gates':{'minimum_events':{'train':8,'test':12,'eval':12,'final':8},'minority_side_share_min':.2,'max_month_share':.45},
  'novelty_gates':{'exact_entry_jaccard_max':.1,'candidate_near_6h_share_max':.35,'occupied_5m_bar_jaccard_max':.25,'absolute_signed_exposure_pearson_max':.35,'must_pass_before_economics':True},
  'economic_gates':{'absolute_return_positive':True,'cagr_to_strict_mdd_min':3.,'strict_mdd_max_pct':15.,'mean_gross_underlying_min_bp':20.,'weekly_signflip_one_sided_p_max':.1,'stress_absolute_return_positive':True,'stress_cagr_to_strict_mdd_min':2.5,'each_calendar_half_positive':True,'stop_on_first_failure':True,'accounting':'fixed quantity, exact funding, 6bp/10bp per notional side, held 5m favorable then adverse, global HWM, full-calendar CAGR'},
  'post_stage_volatility_audit':{'prerequisite':'unchanged all-stage pass','rv20_q90_entry_filter':False,'minimum_q90_trades':8,'candidate_q90_absolute_return_positive':True,'identical_clock_forced_long_residual_positive':True},
  'diagnostic_controls':{'names':['no_feedback_tail_gate','no_variation_gate','contemporaneous_signed_quarticity','one_block_stale_geometry','direction_flip','forced_long'],'cannot_be_promoted':True},
  'source_plan':{'table':'bars_binance','symbol':'BTCUSDT','interval':'1m','columns':['ts','open','high','low','close'],'query_window':['2023-01-01T00:00:00Z','2026-08-01T00:00:00Z'],'read_after_preregistration':True,'execution_prices':'sealed until source and novelty pass'},
  'research_boundary':{'prior_skew_serial_dependence_variation_outcomes_known':True,'repository_signed_return_to_next_variance_candidate_found':False,'prior_event_sets_or_controls_reused':False,'prior_outcomes_used_to_set_formula_rank_side_hold_or_clock':False,'candidate_incidence_opened':False,'postentry_return_or_pnl_opened':False,'gross9_rows_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False,'promoted_prior_control':False,'selection_basis':'independent lagged signed-return-to-variance propagation functional'},
  'stopping_rule':'terminal first failure; no window, functional, rank, onset, side, clock, hold, subset, threshold, or control repair'}
 return {**core,'manifest_hash':canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!='manifest_hash'}
 if x.get('manifest_hash')!=canonical_hash(core) or x!=build():raise RuntimeError('HVSVF preregistration drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+'\n');print(a.output)
