"""Outcome-blind preregistration for HVMOMER-R10-20-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVMOMER-R10-20-24"
DEFAULT_OUTPUT=Path("results/high_volatility_momersion_regime_switch_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_momersion_regime_switch_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
  mechanism={"claim":"During elevated realized variation, a documented Momersion(10,20) crossing its neutral 50 boundary identifies a switch between momentum and mean-reversion in consecutive four-hour close changes; on the switch bar, follow its close change when momentum becomes dominant and fade it when mean reversion becomes dominant for twenty-four hours.","side":"on a strict crossing above 50, use the sign of current close minus prior close; on a strict crossing below 50, use the opposite sign; require a strict nonzero current change","why_distinct":"Momersion counts whether consecutive close changes share a sign or alternate signs, using up to twenty products and a ten-product readiness floor. It is not magnitude momentum, autocorrelation, a moving average, channel, range path, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the regime switch distinguishes continuation from alternation while completed trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse sign-product regime boundary switches with conditional follow/fade direction are absent from Gross9 primitives"},
  external_basis={"origin":"Michael Harris Momersion Indicator; QuantConnect LEAN canonical implementation","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/Momersion.cs","documentation_source":"https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/momersion","fixed_definition":"documented minPeriod=10 and fullPeriod=20; each observation is (C_t-C_t-1)*(C_t-1-C_t-2); mc counts positive products and mRc negative products; Momersion=100*mc/(mc+mRc), returning 50 when not ready or when zero products are at least half; warmup 12 closes","neutral_interpretation":"above 50 means momentum sign persistence dominates; below 50 means mean-reverting sign alternation dominates","selection_use":"official documented periods, product signs, 50 neutral boundary, and published momentum-versus-mean-reversion interpretation only; no incidence or outcomes"},
  features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","change":"current completed close minus immediately prior completed close","product":"current change times immediately prior change","momersion":"100 times positive nonzero products divided by all nonzero products in the latest up-to-20 product window once at least 10 products exist; official zero-density fallback 50","event":"strict finite crossing from <=50 to >50 follows current change sign; strict crossing from >=50 to <50 takes the opposite; current change zero gives no event","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"close, product window, readiness, and crossing state reset after any invalid completed four-hour bar","no_imputation":True},
  clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
  policy={"minimum_product_observations":10,"full_product_observations":20,"neutral_level":50.0,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  diagnostic_controls={"names":["no_variation_gate","raw_one_bar_direction","one_bar_stale_switch","direction_flip"],"cannot_be_promoted":True},
  source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
  research_boundary={"canonical_momersion_definition_read":True,"repository_momersion_candidate_found":False,"prior_sign_memory_candidate_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official LEAN Momersion(10,20) neutral regime switch under the requested high-variation regime"},
  stopping_rule="Terminal first failure; no periods, neutral level, product treatment, switch direction, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVMOMER-R10-20-24 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
