"""Outcome-blind preregistration for HVHHM-C10-N5-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVHHM-C10-N5-8";DEFAULT_OUTPUT=Path("results/high_volatility_hammer_hanging_man_context_reversal_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_hammer_hanging_man_context_reversal_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated completed realized variation, an official hourly lower-shadow rejection candle is bullish when its body is below or near the prior low (Hammer) and bearish when its body is above or near the prior high (Hanging Man). Enter only an unambiguous official context output for eight hours.","side":"long for Hammer-only +1, short for Hanging-Man-only -1; ignore a bar satisfying both contexts","why_distinct":"Unlike wick-imbalance reversal, the lower shadow direction alone does not determine side. Identical short-body, long-lower-shadow morphology is mapped through causal location relative to the prior candle: below/near prior low versus above/near prior high. Official lagged body, upper-shadow, and near-range settings are fixed; no fitted outcome, reused event set, volume, flow, OI, or funding is used.","why_suited_to_volatile_regimes":"contextual rejection at a prior hourly extreme can resolve sharply while trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse hourly candle-shape plus prior-extreme context clocks are absent from Gross9 primitives"},
 external_basis={"origin":"Hammer and Hanging Man candlestick patterns; QuantConnect LEAN canonical implementations","hammer_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/CandlestickPatterns/Hammer.cs","hammer_source_sha256":"c1ccef0cd37cec31dd63c0c1bfaf95e1f090ab675eb1b70860e2e8d80d3a4656","hanging_man_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/CandlestickPatterns/HangingMan.cs","hanging_man_source_sha256":"1c0357a3a185122ffe2e3860c30ce0f84cb941089601e62b4803ffb4b31fe828","candle_settings_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/CandlestickPatterns/CandleSettings.cs","fixed_definition":"current real body < factor 1 prior-10 real-body average; lower shadow > factor 1 current real body because ShadowLong period is 0; upper shadow < factor .1 prior-10 high-low average; Hammer body low endpoint <= prior low + factor .2 prior-5 high-low Near average; Hanging Man body low endpoint >= prior high - the same causal Near average","warmup":"LEAN Period is max(BodyShort 10, ShadowLong 0, ShadowVeryShort 10, Near 5)+1+1 = 12 hourly bars","selection_use":"official defaults, strict/inclusive inequalities, outputs, and readiness only; no incidence or outcomes"},
 features={"decision_grid":"every exact hourly UTC boundary","source_bar":"exact aggregation of 60 coherent BTCUSDT one-minute rows [T-1h,T)","real_body":"absolute close-open","lower_shadow":"min(open,close)-low","upper_shadow":"high-max(open,close)","hammer":"official ready Hammer condition true and Hanging Man false","hanging_man":"official ready Hanging Man condition true and Hammer false","ambiguity":"ignore if both or neither","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 2160 earlier source-valid hourly decisions, minimum 720, current excluded; rank>=0.65","recursive_reset":"hour aggregation, all candle-setting totals, readiness, and variation history reset after any invalid completed source hour","no_imputation":True},
 clock={"feature_available":"hour boundary after completed rejection candle","entry":"exact BTCUSDT open five elapsed minutes later","hold":"8 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"body_short_average_period":10,"body_short_factor":1.0,"shadow_long_average_period":0,"shadow_long_factor":1.0,"shadow_very_short_average_period":10,"shadow_very_short_factor":.1,"near_average_period":5,"near_factor":.2,"indicator_period_hours":12,"variation_hours":24,"variation_history_decisions":2160,"minimum_variation_history_decisions":720,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","morphology_only_lower_wick_direction","no_near_context","one_hour_stale_pattern","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_hammer_and_hanging_man_definitions_read":True,"repository_hammer_hanging_man_candidate_found":False,"prior_wick_candidates_known_but_economic_outcomes_unopened":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official LEAN contextual lower-shadow pair under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no timeframe, candle settings, context, ambiguity, variation, side, hold, clock, subset, threshold, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVHHM-C10-N5-8 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
