"""Outcome-sequenced preregistration for CVEH-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="CVEH-6";DEFAULT_OUTPUT=Path("results/cross_venue_efficiency_handoff_relay_preregistration_2026-08-10.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c={"protocol_version":"cross_venue_efficiency_handoff_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-10","oos_outcomes_opened":False,"candidate_source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"During a volatile BTC block, clean same-direction cash and perpetual paths with accelerating spot BTC volume but inefficient perpetual displacement identify a cash-led directional handoff that should continue for six hours.","side":"common strict sign of completed spot and perpetual final-two-hour returns","why_distinct":"CVEH uses cross-venue path-efficiency asymmetry plus relative base-volume acceleration onset. It is not a cash-basis level/change, spot participation level, taker/trade-count signal, spot-price underreaction gap, or any prior diagnostic control.","volatile_market_target":"causal eight-hour perpetual variation rank>=0.65","why_low_gross9_overlap_is_plausible":"sparse cross-venue efficiency-handoff onset on eight-hour boundaries is absent from Gross9"},
 "feature_contract":{"source_window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"decision":"exact 00:00/08:00/16:00 UTC after [D-8h,D)","price":"480 exact unique coherent positive BTCUSDT 1m OHLC rows independently from bars_binance and bars_binance_spot; no imputation","volume":"finite strictly positive BTC base volume from both venues; late=[D-2h,D), early=[D-4h,D-2h)","late_return":"log(last close/first open) over each venue final two hours","late_path_length":"sum absolute close-to-close log returns within each final-two-hour path plus absolute log(first close/first open), exactly 120 increments","efficiency":"abs(late_return)/late_path_length, requiring positive path length","volume_acceleration":"log(late 2h base-volume sum / early 2h base-volume sum) per venue","handoff":"spot volume acceleration minus perpetual volume acceleration","variation":"sum 479 squared perpetual close-to-close log returns","causal_ranks":"strict-prior midrank over at most270 source-valid blocks minimum180 current excluded","primary_state":"variation_rank>=.65, same strict nonzero late-return signs, spot_efficiency_rank>=.80, perpetual_efficiency_rank<=.50, handoff_rank>=.75","onset":"current primary_state true and immediately preceding eight-hour primary_state not true; invalid preceding state counts not true"},
 "clock":{"entry":"D+5m BTCUSDT perpetual open","side":"common late-return sign","hold":"6 elapsed hours","reservation":"global half-open, exit first on equal open","split_crossing_action":"skip","funding":"not input; exact PnL settlements only after novelty","leverage":.5},
 "policy":{"history_blocks":270,"minimum_history_blocks":180,"variation_rank_min":.65,"spot_efficiency_rank_min":.8,"perpetual_efficiency_rank_max":.5,"handoff_rank_min":.75,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},"economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity exact funding 6bp/10bp per side strict held favorable-then-adverse 5m MDD full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged passes all stages","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},"diagnostic_controls":{"names":["no_volume_handoff","no_efficiency_asymmetry","spot_efficiency_only","one_boundary_stale_geometry","direction_flip","same_clock_forced_long","same_clock_forced_short"],"cannot_be_promoted":True},"source_plan":{"perpetual":{"table":"bars_binance","columns":["ts","open","high","low","close","volume"]},"spot":{"table":"bars_binance_spot","columns":["ts","open","high","low","close","volume"]},"symbol":"BTCUSDT","interval":"1m","read_only":True,"execution_prices":"sealed until source support and novelty pass"},
 "research_boundary":{"shared_spot_perpetual_source_backbone_known":True,"candidate_specific_geometry_incidence_opened":False,"prior_event_sets_or_controls_promoted":False,"oos_postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"selection_basis":"new cash-efficiency and base-volume migration mechanism specified before incidence/outcomes"},"stopping_rule":"freeze prereg/source support/novelty/economics; terminal first failure; no source/rank/onset/side/hold/clock/subset/control repair"}
 return {**c,"manifest_hash":canonical_hash(c)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2,allow_nan=False)+"\n");print(a.output)
