"""Outcome-blind preregistration for HVSFL-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVSFL-8";DEFAULT_OUTPUT=Path("results/high_volatility_spot_first_passage_leadership_relay_preregistration_2026-08-13.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_spot_first_passage_leadership_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-13",
 mechanism={"claim":"During elevated BTC variation, a spot market that first crosses a strictly-prior-volatility-scaled directional barrier and is only later confirmed through the same barrier by the perpetual market identifies cash-led price discovery rather than leveraged anticipation; follow the spot-led direction for eight elapsed hours.","side":"direction of the spot market's first symmetric-barrier passage","why_distinct":"HVSFL compares ordered first-passage times of cash and perpetual prices through one frozen barrier. Spot-flow leadership uses signed trade flow; error correction uses contemporaneous basis displacement; variance transfer compares volatility; permutation entropy compares symbolic complexity. HVSFL uses no flow, volume, basis level, fitted outcome, OI, funding, prior event, or control.","why_suited_to_volatile_regimes":"current perpetual variation must occupy its causal upper thirty-five percent and both markets must complete the same volatility-scaled directional move","why_low_gross9_overlap_is_plausible":"offset eight-hour cross-market first-passage clocks are absent from Gross9 primitives"},
 features={"decision_grid":"exact 02:00, 10:00, and 18:00 UTC boundaries","prior_scale":"288 exact completed spot five-minute closes over [D-32h,D-8h), yielding 287 returns","barrier":"sqrt(sum squared prior-scale returns / 24), a finite strict-positive one-hour spot realized standard-deviation frozen before the current block","current_paths":"96 exact completed spot and BTCUSDT perpetual five-minute closes over [D-8h,D), each normalized by its own first bar open","spot_first_passage":"earliest completed spot close reaching either +barrier or -barrier; ties or simultaneous opposite ambiguity are ineligible","perpetual_confirmation":"earliest completed perpetual close reaching the same directional barrier","lead_requirement":"spot passage precedes perpetual confirmation by at least two completed five-minute bars; perpetual must not cross the opposite barrier before same-direction confirmation","variation":"sqrt(sum squared current perpetual close-to-close returns), finite strict positive","variation_rank":"strict-prior midrank over at most 270 earlier jointly source-valid decisions, minimum 180, current excluded; rank>=0.65","eligibility":"valid directional spot first passage, valid lagged same-direction perpetual confirmation, and variation gate","no_imputation":True},
 clock={"feature_available":"offset eight-hour boundary after both paths complete","entry":"exact perpetual BTCUSDT open five elapsed minutes later","side":"spot first-passage direction","hold":"8 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":0.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"bar_minutes":5,"prior_scale_bars":288,"current_path_bars":96,"prior_scale_hours":24,"minimum_lead_bars":2,"history_decisions":270,"minimum_history_decisions":180,"variation_rank_min":0.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":0.5,"base_cost_per_notional_side":0.0006,"stress_cost_per_notional_side":0.001},
 diagnostic_controls={"names":["no_variation_gate","one_bar_minimum_lead","perpetual_first_passage","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"spot":{"table":"bars_binance_spot","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"perpetual":{"table":"bars_binance","same_symbol_interval_columns_window":True,"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"cross_market_first_passage_definition_selected":True,"repository_exact_spot_first_passage_leadership_candidate_found":False,"adjacent_spot_flow_error_correction_variance_transfer_and_entropy_candidates_known":True,"adjacent_candidate_outcomes_used_to_set_formula_side_hold_clock_or_threshold":False,"prior_event_sets_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"fixed prior-spot-volatility symmetric first passage with ten-minute cash lead and later perpetual confirmation"},
 stopping_rule="Terminal first failure; no scale, barrier, lead, confirmation, variation rank, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v:dict[str,Any])->None:
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVSFL preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
