"""Outcome-blind preregistration for HVEVP-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVEVP-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_voss_predictor_crossover_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_voss_predictor_crossover_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' published negative-group-delay Voss Predictor crossing its companion two-pole BandPass on completed four-hour BTC auctions identifies a cyclical turning point before the underlying filter; follow the predicted direction for twenty-four hours.","side":"long on a strict Voss-over-BandPass crossing; short on a strict Voss-under-BandPass crossing","why_distinct":"A period-20 bandwidth-.25 recursive BandPass feeds an order-nine weighted autoregressive Voss predictor with predict=3, and the forward-looking field crosses its source filter. It is not a zero crossing, truncated filter, raw price or moving-average crossover, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the predictor targets cyclical turning points and must cross while completed trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"negative-group-delay predictor-versus-source-filter crossings are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, A Peek Into The Future, TASC August 2019","source":"https://traders.com/Documentation/FEEDbk_docs/2019/08/TradersTips.html","fixed_definition":"Period=20, Predict=3, Bandwidth=.25, Order=3*Predict; Filt=.5*(1-S1)*(Close-Close[2])+F1*(1+S1)*Filt[1]-S1*Filt[2]; SumC=sum count 0..Order-1 of ((count+1)/Order)*Voss[Order-count]; Voss=((3+Order)/2)*Filt-SumC; author suggests simple Voss/BandPass crossovers as a trading-system basis","selection_use":"published parameters, recursions, predictor/source crossover, and natural crossover side only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","bandpass":"F1=cos(2*pi/Period); G1=cos(Bandwidth*2*pi/Period); S1=1/G1-sqrt(1/G1^2-1); published two-pole recursion on completed close","voss":"Order=3*Predict; weighted prior Voss sum and published negative-group-delay recursion","event":"strict finite Voss-minus-BandPass zero crossing relative to immediately prior valid decision","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"invalid completed four-hour bars reset BandPass and Voss state; initialize recursive outputs to zero; require at least Period uninterrupted observations and finite current/prior fields","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"period":20,"predict":3,"bandwidth":.25,"order":9,"warmup_observations":20,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","voss_zero_cross","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_voss_predictor_strategy_read":True,"repository_voss_candidate_found":False,"prior_bandpass_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published Ehlers period-20 predict-3 Voss Predictor versus BandPass crossover under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no period, predict, bandwidth, order, recursion, crossover, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVEVP preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
