"""Outcome-blind preregistration for HVNFCI-72."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVNFCI-72";DEFAULT_OUTPUT=Path("results/high_volatility_nfci_weekend_relay_preregistration_2026-08-09.json");SOURCE=Path("data/chicago_fed_nfci_alfred_causal_vintages_2020_2026.csv");MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_nfci_weekend_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"A weekly tightening or easing in the Chicago Fed National Financial Conditions Index is a broad external risk-state change. After the release is certainly public and when BTC variation is elevated, tightening maps short BTC and easing maps long BTC over the weekend liquidity interval.","side":"negative strict sign of causal week-over-week NFCI change","why_distinct":"NFCI jointly summarizes money, debt, equity, and banking conditions. Existing Treasury, SOFR, dollar, Cboe, Fed-balance-sheet, FX, and crypto-native candidates use narrower objects and no repository alpha uses causal ALFRED NFCI vintages.","why_suited_to_volatile_regimes":"the weekly release is traded only when completed BTC variation is in its causal upper 35%","why_low_gross9_overlap_is_plausible":"one Friday 00:05 UTC macro-financial weekend clock is absent from Gross9"},
 "features":{"source":"ALFRED real-time vintages of Chicago Fed NFCI","reference":"weekly observation ending Friday W","causal_vintage":"next Friday W+7 calendar days, after normal Wednesday and holiday-shifted Thursday release","observation":"NFCI value for W read from only the W+7 ALFRED vintage","change":"causal NFCI[W]-causal NFCI[W-7], strict nonzero; each term independently from its own next-Friday vintage","direction":"positive=tighter conditions, negative=looser conditions","btc_variation":"sqrt(sum squared exact completed 5m BTC log returns over seven UTC days ending at decision W+7 00:00)","variation_rank":"strict-prior midrank over at most 156 source-valid weekly decisions, minimum 104, current excluded; rank>=0.65","no_imputation":True,"no_latest_vintage_backfill":True},
 "clock":{"decision":"W+7 Friday 00:00 UTC","entry":"decision+5m BTCUSDT open","hold":"72 elapsed hours","side":"negative NFCI change sign","reservation":"weekly nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements after novelty"},
 "policy":{"variation_history_weeks":156,"minimum_history_weeks":104,"variation_rank_min":.65,"publication_delay_days":7,"entry_delay_minutes":5,"hold_hours":72,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all stages","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"definitions":{"no_variation_gate":"every valid NFCI change","one_week_stale_nfci":"prior NFCI change with current variation","direction_flip":"negative primary side","same_clock_forced_long":"side +1 on primary clock"},"cannot_be_promoted":True},
 "source_plan":{"nfci":{"series":"NFCI","vintage_provider":"ALFRED","destination":str(SOURCE),"download_after_preregistration_commit":True,"one_reference_value_per_next_friday_vintage":True},"historical_market":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m through 2026-08-01","execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"official_page":"https://www.chicagofed.org/research/data/nfci/current-data","release_calendar":"https://www.chicagofed.org/research/data/data-release-calendar","prior_macro_outcomes_known":True,"prior_event_sets_or_controls_reused":False,"exact_hvnfci_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent real-time-vintage broad financial-conditions mechanism"},
 "stopping_rule":"terminal first failure; no source, vintage, delay, variation, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVNFCI prereg drift")
 if SOURCE.exists():raise RuntimeError("HVNFCI source must not exist before preregistration freeze")
 if hashlib.sha256(MARKET.read_bytes()).hexdigest()!=MARKET_SHA:raise RuntimeError("HVNFCI market drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
