"""Outcome-blind preregistration for HVPIAR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVPIAR-8";DEFAULT_OUTPUT=Path("results/high_volatility_price_impact_asymmetry_relay_preregistration_2026-08-09.json");MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_price_impact_asymmetry_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"During a high-variation completed eight-hour BTC path, an extreme asymmetry between downside and upside absolute return per unit quote turnover identifies which side of the book is structurally fragile. Relay toward the fragile side for eight elapsed hours.","side":"negative sign of log(downside impact/upside impact): downside fragility maps short, upside fragility maps long","why_distinct":"Existing liquidity-impact work measures aggregate turnover efficiency and follows displacement. HVPIAR compares separately completed positive and negative bar impact and does not use block direction, aggressor flow, spread, OI, funding, or a prior control.","why_suited_to_volatile_regimes":"the asymmetry is admitted only when completed path variation is in its causal upper tail","why_low_gross9_overlap_is_plausible":"a directional book-fragility asymmetry clock is absent from Gross9"},
 "features":{"source":"exact BTCUSDT 5m OHLC and quote_asset_volume","decision_grid":"exact 00:00, 08:00, 16:00 UTC","path":"96 exact completed five-minute bars in [decision-8h,decision), plus exact prior close","bar_return":"log(close/previous close), strict nonzero bars assigned by sign","side_support":"at least 16 positive-return and 16 negative-return bars; zero returns excluded","upside_impact":"sum positive returns / sum quote turnover on positive-return bars","downside_impact":"sum absolute negative returns / sum quote turnover on negative-return bars","impact_asymmetry":"log(downside_impact/upside_impact), strict nonzero","asymmetry_rank":"strict-prior midrank of abs(impact_asymmetry) over at most 270 valid blocks, minimum 252, current excluded; rank>=0.80","variation":"sqrt(sum squared bar returns)","variation_rank":"strict-prior midrank over same policy, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact boundary after completed path","entry":"decision+5m BTCUSDT open","hold":"8 elapsed hours","side":"negative impact-asymmetry sign","reservation":"natural nonoverlap; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements after novelty"},
 "policy":{"history_blocks":270,"minimum_history_blocks":252,"minimum_bars_each_sign":16,"asymmetry_rank_min":.8,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all stages","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"definitions":{"no_asymmetry_tail":"fragility side and variation gate without asymmetry rank","no_variation_gate":"asymmetry tail only","one_block_stale_asymmetry":"prior block asymmetry with current variation","direction_flip":"negative primary side","same_clock_forced_long":"side +1 on primary clock"},"cannot_be_promoted":True},
 "source_plan":{"historical_market":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m OHLC and quote_asset_volume through 2026-08-01","execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_liquidity_outcomes_known":True,"prior_event_sets_or_controls_reused":False,"exact_hvpiar_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent signed price-impact asymmetry mechanism"},
 "stopping_rule":"terminal first failure; no source, impact definition, rank, variation, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVPIAR prereg drift")
 if hashlib.sha256(MARKET.read_bytes()).hexdigest()!=MARKET_SHA:raise RuntimeError("HVPIAR market drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
