"""Outcome-blind preregistration for HVORFR-6."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any

POLICY_ID="HVORFR-6"; DEFAULT_OUTPUT=Path("results/high_volatility_opening_range_failure_relay_preregistration_2026-08-09.json")
MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz"); MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_opening_range_failure_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"Within a completed six-hour BTC auction, a middle-phase one-sided break of the opening two-hour range that closes back inside, followed by a final-phase move through the opening-range midpoint opposite the break, is a confirmed failed auction rather than an unfinished breakout. In high realized variation, follow the confirmed failure direction for six elapsed hours.","side":"short after an upper opening-range failure and long after a lower opening-range failure","why_distinct":"LEMRR uses the ordering of full-day absolute extremes at Tuesday/Friday boundaries. Range-boundary and Donchian candidates use trailing historical ranges. HVORFR defines a fresh within-block opening range, an exclusive middle-phase excursion, an inside close, and a separate final midpoint confirmation at two daily clocks; no prior event or control is reused.","volatile_market_target":"completed six-hour realized-variation causal rank at least 0.65","why_low_gross9_overlap_is_plausible":"two conditional 06:05/18:05 UTC failed-auction clocks are absent from Gross9"},
 "features":{"blocks":"exact [00:00,06:00) and [12:00,18:00) UTC blocks of 72 coherent completed 5m bars","opening_phase":"first 24 bars; opening_high=max(high), opening_low=min(low), midpoint=(high+low)/2, strict positive range","middle_phase":"next 24 bars; exactly one of middle_high>opening_high or middle_low<opening_low; middle final close strictly inside opening range","final_phase":"last 24 bars; final return strict opposite break direction and final close strictly beyond opening midpoint in that direction","variation":"sqrt(sum squared 72 completed 5m open-to-close log returns)","variation_rank":"strict-prior midrank over at most 252 valid blocks, minimum 180, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact 06:00 or 18:00 UTC after block completes","entry":"exact decision+5m BTCUSDT open","hold":"6 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium_rv20":"not signal inputs; exact funding after novelty; RV20 q90 only after all economics pass"},
 "policy":{"block_bars":72,"phase_bars":24,"variation_prior_blocks":252,"variation_minimum_blocks":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","inside_close_only","no_midpoint_confirmation","one_block_stale_geometry","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"historical":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m through 2026-08-01 with exact overlap parity","execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"prior_price_geometry_outcomes_known":True,"exact_hvorfr_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent three-phase opening-range failed-auction mechanism"},
 "stopping_rule":"terminal first failure; no block, phase, range, confirmation, rank, variation, side, timing, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVORFR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
