"""Outcome-blind preregistration for HVEFR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVEFR-8";DEFAULT_OUTPUT=Path("results/high_volatility_extreme_funding_residual_relay_preregistration_2026-08-10.json")
MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_extreme_funding_residual_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-10","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"An actual BTCUSDT funding settlement far from its own causal rolling median identifies unusually one-sided leverage crowding. In elevated realized variation, fade the funding residual for the next inventory cycle.","side":"negative strict sign of current funding rate minus its strictly-prior 90-settlement median","why_distinct":"HVEFR uses the level residual at every actual settlement, not the failed fixed 00-to-08 acceleration contract, price/funding sign confirmation, cross-alt funding, OI, options volatility, or a prior diagnostic control.","volatile_market_target":"completed prior-24h BTC variation causal rank at least 0.65","why_low_gross9_overlap_is_plausible":"only extreme residual settlements survive two causal ranks and an eight-hour global reservation"},
 "features":{"funding_source":"read-only funding_rates_binance BTCUSDT actual records","funding_median":"median of at most 90 strictly previous actual settlements, minimum 60; current excluded","funding_residual":"current funding_rate minus causal median, strict nonzero","residual_rank":"strict-prior midrank of absolute residual over at most 270 valid residuals, minimum 180; current excluded; rank>=0.75","btc_variation":"sqrt(sum squared exact completed 5m close-to-close BTC log returns over [settlement-24h,settlement))","variation_rank":"strict-prior midrank at actual settlement opportunities over at most 270 valid states, minimum 180; current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"actual funding_time after funding rate and prior BTC path are available","entry":"decision+5m exact BTCUSDT open","hold":"8 elapsed hours","side":"-sign(funding residual)","reservation":"chronological half-open nonoverlap; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"all exact settlements during held interval included only after novelty"},
 "policy":{"funding_median_history":90,"funding_median_minimum":60,"residual_rank_history":270,"residual_rank_minimum":180,"residual_rank_min":.75,"variation_history":270,"variation_minimum":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","no_residual_tail","raw_funding_sign_reversal","one_settlement_stale_residual","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"funding":{"table":"funding_rates_binance","symbol":"BTCUSDT","actual_timestamps":True},"historical_market":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT through 2026-08-01","execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_funding_family_outcomes_known":True,"prior_event_sets_or_controls_reused":False,"exact_hvefr_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent causal funding-level residual crowding mechanism"},
 "stopping_rule":"terminal first failure; no history, rank, residual, side, variation, clock, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x["manifest_hash"]!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVEFR drift")
 if hashlib.sha256(MARKET.read_bytes()).hexdigest()!=MARKET_SHA:raise RuntimeError("market drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2)+"\n");print(a.output)
