"""Outcome-blind preregistration for HVPST-12."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVPST-12";DEFAULT_OUTPUT=Path("results/high_volatility_pastor_stambaugh_temporary_impact_reversal_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_pastor_stambaugh_temporary_impact_reversal_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, an unusually negative completed Pastor-Stambaugh-style liquidity gamma means direction-signed turnover is producing next-bar reversal after controlling current return, identifying temporary price impact; fade the completed four-hour displacement for twelve hours at a fresh illiquidity-tail onset.","side":"short a strictly positive completed trailing four-hour return and long a strictly negative return","why_distinct":"HVPST regresses next five-minute return on current return and current direction-signed, block-mean-normalized quote turnover inside a completed day. Kyle-style candidates use contemporaneous signed-flow impact; turnover lead-response uses unconditional turnover/next-return association; Roll uses return autocovariance. HVPST isolates the incremental next-return reversal coefficient and uses no OI, funding, fitted postentry outcome, reused event, repair, or promoted control.","why_suited_to_volatile_regimes":"both the negative-gamma illiquidity magnitude and completed realized variation must occupy causal upper tails, targeting temporary impact during July-like stress","why_low_gross9_overlap_is_plausible":"sparse four-hour completed liquidity-gamma onsets with twelve-hour reservations are absent from Gross9 primitives"},
 external_basis={"origin":"Pastor-Stambaugh return-reversal liquidity regression convention","fixed_definition":"within 288 completed five-minute bars, regress r[t+1] on intercept, r[t], and sign(r[t])*quote_turnover[t]/block mean quote turnover; negative signed-turnover coefficient gamma represents temporary price impact and greater -gamma is lower liquidity","selection_use":"published lead regression, return control, signed-volume construction, and negative-gamma interpretation only; no candidate incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_window":"288 exact completed BTCUSDT five-minute bars [T-24h,T), each from five coherent one-minute rows","return":"log five-minute close/open, strict sign required for signed-turnover regressor","signed_turnover":"sign(return)*quote_asset_volume/mean quote_asset_volume over the completed block","regression":"OLS next_return=a+b*current_return+gamma*signed_turnover on the first 287 bars, full rank and finite","illiquidity":"-gamma, requiring gamma<0 and finite positive illiquidity","illiquidity_rank":"strict-prior midrank over at most 180 earlier source-valid decisions, minimum 120, current excluded; rank>=0.80","direction":"strict completed trailing four-hour close/open return","variation":"sqrt(sum squared 288 five-minute returns), finite strict positive","variation_rank":"strict-prior 180/120 midrank, current excluded; rank>=0.65","event":"eligible now and immediately prior exact source-valid decision ineligible","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source block","entry":"exact BTCUSDT open five elapsed minutes later","side":"opposite strict trailing four-hour displacement","hold":"12 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"source_hours":24,"bars_per_source":288,"illiquidity_history_decisions":180,"minimum_illiquidity_history_decisions":120,"illiquidity_rank_min":.80,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"direction_hours":4,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_illiquidity_tail_gate","no_variation_gate","omit_return_control","one_bar_stale_onset","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"pastor_stambaugh_definition_read":True,"repository_pastor_stambaugh_candidate_found":False,"prior_kyle_roll_turnover_lead_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published temporary-impact liquidity gamma under independently fixed causal tail gates"},
 stopping_rule="Terminal first failure; no regression, scaling, rank, variation, onset, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVPST preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(z.output)
