"""Outcome-blind preregistration for HVCAPCR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVCAPCR-6";DEFAULT_OUTPUT=Path("results/high_volatility_cross_alt_premium_crowding_reversal_preregistration_2026-08-12.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_cross_alt_premium_crowding_reversal_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-12","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When the completed one-hour Binance premium-index levels of six liquid alt perpetuals share one sign and their cross-sectional median is unusually far from its causal baseline, leveraged crowding is market-wide rather than BTC-specific. During elevated BTC variation, fade that common alt premium crowding in BTC for six elapsed hours.","side":"negative strict sign of the cross-sectional median alt premium residual","why_distinct":"Existing cross-alt leverage candidates use funding settlements or price, flow, turnover, and range geometry. Existing premium candidates use BTCUSDT alone. HVCAPCR uses the contemporaneous cross-sectional median of six alt-only premium-index levels, with no alt return, BTC direction, funding value, OI, fitted outcome, prior event set, or promoted control.","why_suited_to_volatile_regimes":"BTC trailing twenty-four-hour realized variation must occupy its causal upper 35% while absolute cross-alt premium crowding enters its upper 20%.","why_low_gross9_overlap_is_plausible":"hourly false-to-true cross-alt premium-crowding onsets are absent from Gross9 primitives"},
 "features":{"alts":["ADAUSDT","BNBUSDT","DOGEUSDT","ETHUSDT","SOLUSDT","XRPUSDT"],"premium_hour":"60 exact bars_binance_premium one-minute closes [T-1h,T) per alt; arithmetic mean per symbol; finite signed values","sign_concordance":"all six hourly premium means strict nonzero and one common sign","cross_alt_median":"median of six hourly premium means","causal_baseline":"median of at most 720 strictly prior source-valid hourly cross-alt medians; minimum 672; current excluded","residual":"cross-alt median minus causal baseline, strict nonzero and same sign as all six premium means","residual_rank":"strict-prior midrank of absolute residual over the same causal history; rank at least 0.80","btc_variation":"sum squared log(close/open) over exact 1440 BTCUSDT one-minute rows [T-24h,T)","variation_rank":"strict-prior midrank over at most 720 prior source-valid hours, minimum 672, current excluded; rank at least 0.65","trigger":"false-to-true onset versus previous consecutive source-valid hour","invalid":"missing, duplicate, nonfinite premium; incomplete/nonpositive/incoherent BTC OHLC; sign disagreement; no imputation"},
 "clock":{"decision":"every exact UTC hour T","entry":"BTCUSDT open at T+5m","hold":"6 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 "policy":{"history_hours":720,"minimum_history_hours":672,"residual_rank_min":.80,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, held 5m favorable-then-adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train/test/eval/final","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","four_of_six_concordance","no_residual_tail","one_hour_stale_features","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"tables":["bars_binance_premium","bars_binance"],"interval":"1m","window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_only":True,"execution_prices":"sealed until source and Gross9 novelty pass"},
 "research_boundary":{"repository_collision_search_opened":True,"exact_cross_alt_premium_crowding_candidate_found":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"selection_basis":"independent cross-sectional leveraged-crowding source axis"},
 "stopping_rule":"terminal first failure; no symbol, premium aggregation, concordance, baseline, history, rank, variation, onset, side, hold, clock, subset, threshold, source, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();b=(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode();a.output.parent.mkdir(parents=True,exist_ok=True)
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_bytes(b);print(json.dumps({"policy_id":POLICY_ID,"output":str(a.output),"sha256":hashlib.sha256(b).hexdigest()}))
if __name__=="__main__":main()
