"""Outcome-blind preregistration for HVMCIA-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVMCIA-8";DEFAULT_OUTPUT=Path("results/high_volatility_median_crossing_impulse_asymmetry_relay_preregistration_2026-08-10.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_median_crossing_impulse_asymmetry_relay_v1",policy_id=POLICY_ID,
 mechanism={"claim":"In a volatile completed BTC block, repeated crossings of the block's robust median price can have systematically larger first accepted displacements on one side. Follow the side with stronger post-crossing acceptance rather than the endpoint direction.","side":"strict sign of upward minus downward median-crossing overshoot mass","why_distinct":"Median breadth uses constituent returns; median-shift compares return halves; cumulative-VWAP recross counts crossings of an expanding volume-weighted reference; range traversal uses absolute extrema. HVMCIA fixes the completed block median level and compares the first accepted log-price overshoot after every upcross versus downcross, with no endpoint gate, volume, flow, funding, OI, cross-asset, prior event, fitted outcome, or control.","why_suited_to_volatile_regimes":"completed realized variation must rank in its causal upper 35% while median-crossing acceptance asymmetry enters its upper 30%","why_low_gross9_overlap_is_plausible":"offset three-daily robust-level crossing-impulse onsets are absent from Gross9 primitives"},
 features={"decision_grid":"exact 07:00/15:00/23:00 UTC boundaries","block":"480 exact coherent bars_binance BTCUSDT one-minute rows [D-8h,D)","log_close_path":"p_i=log(close_i), i=0..479","median_level":"sample median of the 480 completed log closes","upcross":"p_(i-1)<=median and p_i>median for i=1..479","downcross":"p_(i-1)>=median and p_i<median for i=1..479","crossing_support":"at least one upcross and one downcross","up_overshoot_mass":"sum(p_i-median) over upcrosses","down_overshoot_mass":"sum(median-p_i) over downcrosses","crossing_impulse_asymmetry":"(up_mass-down_mass)/(up_mass+down_mass), finite strict nonzero","asymmetry_rank":"strict-prior midrank of abs(crossing_impulse_asymmetry) over at most 270 earlier source-valid blocks, minimum 180, current excluded; rank>=0.70","realized_variation":"sqrt(sum squared log(close/open) minute returns), finite strict positive","variation_rank":"strict-prior 270/180 midrank, current excluded; rank>=0.65","eligible_state":"asymmetry and variation gates pass","onset":"eligible now and immediately previous exact source-valid block ineligible; missing prior cannot trigger","no_imputation":True},
 clock={"decision":"completed eight-hour boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_blocks":270,"minimum_history_blocks":180,"asymmetry_rank_min":.70,"variation_rank_min":.65,"minimum_upcrosses":1,"minimum_downcrosses":1,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_asymmetry_tail","no_variation_gate","crossing_step_return_asymmetry","one_block_stale_crossings","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"prior_median_breadth_median_shift_vwap_recross_and_range_traversal_outcomes_known":True,"repository_median_crossing_impulse_asymmetry_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_rank_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"directional first-acceptance displacement across a robust completed level"},
 stopping_rule="Terminal first failure; no level, crossing convention, impulse formula, rank, onset, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVMCIA preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
