"""Outcome-blind preregistration for HVDVVR-12."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any

POLICY_ID="HVDVVR-12";DEFAULT_OUTPUT=Path("results/high_volatility_dvol_variation_risk_relay_preregistration_2026-08-09.json")
DVOL=Path("data/options_crowding_deleveraging_relay_sources_v4_2023_2026/dvol_hourly.csv.gz");DVOL_SHA="5556bc470ce7c8134cf6d2a09fc1eab8f233604a8029fe6a4eaf838ff302446c"
SOURCE_MANIFEST=DVOL.parent/"manifest.json";SOURCE_MANIFEST_SHA="5a6b8fb8d2da235afee4709d219bc3e537498e15078fafa27d57ba284723cd7e"
MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_dvol_variation_risk_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"When Deribit BTC DVOL itself travels unusually violently over a completed day while BTC realized variation is also elevated, the direction of the net implied-volatility repricing identifies risk transfer: rising DVOL maps short BTC and falling DVOL maps long BTC for twelve hours.","side":"negative strict sign of the completed 24-hour DVOL close-to-close change","why_distinct":"Prior DVOL candidates used level crossings, single-hour bodies, BVOL/DVOL disagreement, or ordered handoffs. HVDVVR uses the realized quadratic variation of 24 consecutive DVOL closes as the event and DVOL net change only for direction; no BVOL, OI, funding, premium, or prior event set is used.","why_suited_to_volatile_regimes":"both options volatility-of-volatility and BTC realized variation must lie in causal upper tails","why_low_gross9_overlap_is_plausible":"one daily crypto-options VoV clock is absent from Gross9"},
 "features":{"dvol_source":"hash-bound hourly Deribit BTC DVOL snapshot through 2026-08-01","decision":"each exact 00:00 UTC after 24 completed hourly DVOL bars","dvol_window":"24 exact bars with coherent positive OHLC and close_time=bar_start+1h","dvol_change":"log(last close / close immediately preceding the 24-hour window), strict nonzero","dvol_variation":"sqrt(sum squared log changes across 25 consecutive closes ending at decision)","dvol_variation_rank":"strict-prior midrank against at most 720 earlier hourly 24h variation states, minimum 336, current excluded; rank>=0.75","btc_variation":"sqrt(sum squared exact completed 5m BTC log returns over the same 24 hours)","btc_variation_rank":"strict-prior midrank against at most 720 earlier hourly 24h states, minimum 336, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact 00:00 UTC","entry":"decision+5m BTCUSDT open","hold":"12 elapsed hours","side":"opposite DVOL change sign","reservation":"daily nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements after novelty"},
 "policy":{"dvol_hours":24,"rank_history_hours":720,"rank_minimum_hours":336,"dvol_variation_rank_min":.75,"btc_variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all stages","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"definitions":{"no_dvol_variation_gate":"DVOL direction and high BTC variation without VoV tail","no_btc_variation_gate":"DVOL VoV tail without BTC variation rank","dvol_direction":"same sign as DVOL change on primary clock","one_day_stale_dvol":"prior exact daily DVOL state with current BTC variation gate","direction_flip":"negative primary side","same_clock_forced_long":"side +1 on primary clock"},"cannot_be_promoted":True},
 "source_plan":{"dvol":{"path":str(DVOL),"sha256":DVOL_SHA,"manifest":str(SOURCE_MANIFEST),"manifest_sha256":SOURCE_MANIFEST_SHA},"historical_market":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m through 2026-08-01","execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_options_family_outcomes_known":True,"prior_event_sets_or_controls_reused":False,"exact_hvdvvr_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent crypto-options volatility-of-volatility mechanism"},
 "stopping_rule":"terminal first failure; no source, window, rank, variation, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVDVVR prereg drift")
 for p,h in ((DVOL,DVOL_SHA),(SOURCE_MANIFEST,SOURCE_MANIFEST_SHA),(MARKET,MARKET_SHA)):
  if hashlib.sha256(p.read_bytes()).hexdigest()!=h:raise RuntimeError(f"HVDVVR source drift: {p}")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
