"""Outcome-blind preregistration for HVAMST-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ALTS=("ADAUSDT","BNBUSDT","DOGEUSDT","ETHUSDT","SOLUSDT","XRPUSDT");DEFAULT_OUTPUT=Path("results/high_volatility_alt_mst_hub_ignition_relay_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_alt_mst_hub_ignition_relay_v1","policy_id":"HVAMST-8","as_of_date":"2026-08-13","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When the correlation minimum-spanning tree of six liquid alt returns newly becomes unusually hub-dominated, crypto price discovery has concentrated in one dynamically selected alt rather than a diffuse common mode. During elevated BTC variation, follow the unique hub's completed final-hour direction for eight elapsed hours.","side":"strict sign of the unique MST hub alt's final-hour return","why_distinct":"HVCMMI measures PC1 eigenvalue share and an eigenvector projection; alt leadership rotation selects the largest endpoint return; lag-transfer consensus fits directed betas. HVAMST constructs a deterministic Kruskal tree from pairwise correlation distances, ranks degree centralization, and takes direction only from the unique graph hub. It reuses no event set or control and uses no BTC direction, volume, flow, funding, OI, premium, fitted outcome, or post-entry data.","why_suited_to_volatile_regimes":"completed BTC variation must occupy its causal upper 35 percent and MST degree centralization its causal upper quartile","why_low_gross9_overlap_is_plausible":"05:05/13:05/21:05 UTC graph-centralization onsets are absent from Gross9 clocks"},
 "features":{"decision_grid":"exact 05:00/13:00/21:00 UTC boundaries D","aligned_window":"96 exact epoch-aligned five-minute bars from 480 unique coherent bars_binance one-minute rows [D-8h,D) for BTC and six alts","alt_return":"log(five-minute close/open), 96 observations per alt; each sample variance strict positive","correlation":"six-by-six float64 sample Pearson correlation matrix, finite with unit diagonal","distance":"sqrt(max(0,2*(1-correlation))) for each unordered alt pair","mst":"Kruskal algorithm over edges ordered by (distance, frozen first symbol index, frozen second symbol index); union-find without nondeterministic tie handling; exactly five edges","unique_hub":"exactly one alt has strict maximum MST degree; ties reject","degree_centralization":"sum over six nodes of (hub_degree-node_degree) divided by 20, the six-node star maximum; finite in [0,1]","centralization_rank":"strict-prior midrank over at most 270 source-valid decisions, minimum 180, current excluded; rank>=0.75","hub_final_hour_return":"sum final 12 five-minute returns of unique hub, finite strict nonzero","btc_realized_variation":"sqrt(sum squared 96 BTC five-minute returns), finite strict positive","variation_rank":"strict-prior 270/180 midrank, current excluded; rank>=0.65","onset":"eligible now and immediately preceding scheduled source-valid decision ineligible; missing or invalid prior cannot trigger","no_imputation":True},
 "clock":{"decision":"completed aligned eight-hour boundary D","entry":"exact BTCUSDT perpetual D+5m open","side":"sign of unique MST hub final-hour return","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium":"not signal inputs; exact funding only after novelty"},
 "policy":{"alt_symbols":list(ALTS),"prior_decisions":270,"minimum_prior_decisions":180,"centralization_rank_min":.75,"variation_rank_min":.65,"decision_hours_utc":[5,13,21],"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval and final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "source_plan":{"market":{"table":"bars_binance","symbols":["BTCUSDT",*ALTS],"interval":"1m","columns":["ts","symbol","open","high","low","close"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"read_after_preregistration_commit":True,"execution_price":"sealed until source support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_centralization_tail","no_variation_gate","equal_weight_alt_direction","one_decision_stale_tree","direction_flip","forced_long"],"cannot_be_promoted":True},
 "research_boundary":{"prior_cross_alt_mode_leadership_transfer_and_correlation_outcomes_known":True,"repository_alt_correlation_minimum_spanning_tree_candidate_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"reversal_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent graph-topological concentration mechanism selected from formula-absence and complete-source audit only"},
 "stopping_rule":"terminal first failure; no universe, aggregation, correlation, distance, tree algorithm, tie rule, hub, centralization, history, rank, threshold, variation, onset, direction, clock, hold, subset, source, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVAMST prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
