"""Outcome-blind preregistration for HVSAUDAR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_cross_structure_action_vote as gates
POLICY_ID="HVSAUDAR-8";DEFAULT_OUTPUT=Path("results/high_volatility_spot_underwater_autocorrelation_router_preregistration_2026-08-18.json");STATE=Path("data/high_volatility_spot_adverse_underwater_duration_sources_2023_2026/states.csv.gz");STATE_SHA="94bae225225150d5fce8db70c79eb122460ccab8722531dacf3d0d3de507e110"
BASE={"preregistration":{"path":"results/high_volatility_spot_adverse_underwater_duration_relay_preregistration_2026-08-18.json","sha256":"6f65fe4632da0c714cf971a95d1be98fb28bb8ef2a4926188656ff58af676446"},"support":{"path":"results/high_volatility_spot_adverse_underwater_duration_relay_support_2026-08-18.json","sha256":"1fc578d0c95d12c4f9cea7da4ee0f712fc0546573c2e334011eb19e2ee55b27a"},"gross9":{"path":"results/high_volatility_spot_adverse_underwater_duration_relay_gross9_novelty_2026-08-18.json","sha256":"77a222777e6baf434260657baf9b1768745b42f0ac02bcc6b9ae321b028edc6c"},"clock":{"path":"data/high_volatility_spot_adverse_underwater_duration_relay_clocks_2023_2026.csv.gz","sha256":"2a7a893cdc2026227c00ba0a7622f35277c149498cd8413dd21e2d286eaf38d9"}}
def sha256(p:str|Path)->str:return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 g=gates.build();core={"protocol_version":"high_volatility_spot_underwater_autocorrelation_router_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-18","singleton":True,"candidate_family":[POLICY_ID],"candidate_family_size":1,"source_incidence_opened":False,"outcomes_opened":False,"gross9_rows_opened":False,"base_artifacts":BASE,
 "mechanism":{"claim":"Spot directional-underwater events should continue when the strictly prior month of completed spot block returns is serially persistent and reverse when it is alternating; use the long-memory autocorrelation sign as a causal regime router.","side":"immutable HVSAUD base side multiplied by strict sign of prior 30-day spot block-return lag-one Pearson correlation","why_distinct":"HVSAR uses contemporaneous five-minute autocorrelation inside one 12-hour path and requires a dependence tail. HVSAUDAR uses no current path returns beyond the immutable event, no tail threshold, and estimates a slow 90-block state from strictly previous eight-hour cash returns. It uses no outcome labels, OI, funding, premium, options, fitted outcomes, or promoted controls.","why_low_gross9_overlap_is_plausible":"immutable sparse HVSAUD event times already passed Gross9; slow source-state routing changes signed exposure"},
 "state":{"source":{"path":str(STATE),"sha256":STATE_SHA},"history":"latest 90 strictly prior source-valid spot eight-hour block returns","minimum_history":60,"autocorrelation":"Pearson correlation of consecutive prior block returns; both lag vectors require strict positive sample standard deviation","current_excluded":True,"routing":"positive correlation keeps base side; negative correlation inverts; zero/nonfinite/insufficient history is cash","stage_reset":False},
 "policy":{"history_blocks":90,"minimum_history_blocks":60,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},"clock":{"event_times":"immutable HVSAUD decisions, entries, exits","entry":"immutable D+5m","hold":"8 elapsed hours","funding":"not signal input; exact settlements after Gross9"},
 "stages":g["stages"],"source_support_gates":g["source_support_gates"],"gross9_novelty_gates":g["gross9_novelty_gates"],"economic_gates":g["economic_gates"],"research_boundary":{"base_train_pass_test_failure_known":True,"exact_autocorrelation_routed_incidence_or_outcomes_known":False,"current_or_future_state_returns_used":False,"postentry_return_or_pnl_opened":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"classification":"exploratory source-state routing; not fresh confirmatory evidence","selection_basis":"slow serial-dependence sign as a continuation/reversal regime state"},
 "stopping_rule":"source, Gross9, train/test/eval/final; terminal first failure; no base event, history, minimum history, autocorrelation, sign, tie, side, clock, hold, subset, threshold, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x!=build():raise RuntimeError("HVSAUDAR prereg drift")
 if sha256(STATE)!=STATE_SHA:raise RuntimeError("HVSAUDAR state drift")
 for a in BASE.values():
  if sha256(a["path"])!=a["sha256"]:raise RuntimeError("HVSAUDAR base drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
