"""Outcome-blind preregistration for HVTMF-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVTMF-24";DEFAULT_OUTPUT=Path("results/high_volatility_twiggs_money_flow_zero_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_twiggs_money_flow_zero_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a canonical twenty-one-period Twiggs Money Flow crossing its zero line on completed four-hour BTC auctions marks quote-volume-weighted auction-location pressure changing sign; follow the crossing direction for twenty-four hours.","side":"long when TMF crosses strictly above zero after being at or below zero; short when TMF crosses strictly below zero after being at or above zero","why_distinct":"TMF uses the prior close to form true-range auction boundaries, applies exponential rather than rolling-sum memory to close-location flow and exact base volume, and normalizes the two smoothed series. It is not CMF rolling pressure, a cumulative A/D oscillator, taker flow, OI, funding, a fitted outcome, a reused event, or a promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse four-hour true-range-adjusted exponentially smoothed auction-pressure sign-change clocks are absent from Gross9 primitives"},
 external_basis={"origin":"Colin Twiggs, canonical Twiggs Money Flow convention","fixed_definition":"21 completed periods; true high=max(high,prior close), true low=min(low,prior close); adjusted flow=((close-true low)-(true high-close))/(true high-true low)*base volume; TMF=EMA(adjusted flow,21)/EMA(base volume,21), adjust=false; canonical zero-line direction","selection_use":"published period, formula, zero line, and direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T), including summed base volume and the immediately prior completed close","true_range_bounds":"true high=max(current high, prior completed close); true low=min(current low, prior completed close)","adjusted_money_flow":"((close-true low)-(true high-close))/(true high-true low)*four-hour base volume; zero numerator when true range is zero","tmf":"21-period adjust=false EMA of adjusted money flow divided by the matching EMA of base volume; minimum 21 consecutive valid bars; zero denominator invalid","cross":"current CMF strictly crosses zero from immediately prior valid TMF","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"tmf_periods":21,"zero_level":0.,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","ordinary_high_low_bounds","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","volume"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_tmf_definition_read":True,"repository_tmf_candidate_found":False,"prior_chaikin_family_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical true-range-adjusted exponentially smoothed money-flow zero cross under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no TMF period, volume field, true-range formula, zero line, crossing, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVTMF preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
