"""Outcome-blind preregistration for CMMTCR-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="CMMTCR-24";DEFAULT_OUTPUT=Path("results/cross_market_multi_horizon_trend_concordance_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"cross_market_multi_horizon_trend_concordance_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When BTC's completed six-hour and twenty-four-hour returns agree with ETH's completed six-hour return, short and daily BTC trends are confirmed by the most liquid crypto risk proxy. In a high-variation state, the cross-market trend persists for the next day.","side":"common strict sign of BTC 6h, BTC 24h, and ETH 6h returns","why_distinct":"STCR used BTC-only 3d/14d trends at Monday/Thursday decisions with a 72h hold and no volatility gate. ETH leadership candidates used lead-lag or residual disagreement. CMMTCR uses same-time BTC multi-horizon plus ETH confirmation at a daily 02:00 clock, reuses no event set, and promotes no control.","why_suited_to_volatile_regimes":"completed BTC 24-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"one sparse 02:05 UTC daily cross-market clock is absent from Gross9 primitives"},
 "features":{"decision":"daily exact 02:00 UTC","source":"exact contiguous bars_binance 1m BTCUSDT and ETHUSDT rows","btc_6h_return":"log(last completed close/first open) over [decision-6h,decision)","btc_24h_return":"same over [decision-24h,decision)","eth_6h_return":"same ETH formula over [decision-6h,decision)","concordance":"all three finite strict nonzero returns have the same sign","btc_realized_variation":"sqrt(sum squared BTC 1m close/open log returns over [decision-24h,decision))","variation_rank":"strict-prior midrank over at most 90 valid daily observations, minimum 60, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"daily 02:00 UTC after all paths complete","entry":"exact BTCUSDT 02:05 UTC open","side":"common strict trend sign","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal open","funding":"not an input; exact funding only after novelty"},
 "policy":{"variation_prior_days":90,"variation_prior_min_days":60,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all stages","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "source_plan":{"table":"bars_binance","symbols":["BTCUSDT","ETHUSDT"],"interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True,"execution_price":"sealed until source and novelty pass"},
 "diagnostic_controls":{"names":["no_volatility_gate","btc_horizons_only","btc_6h_eth_6h_only","one_day_stale_geometry","direction_flip","forced_long"],"cannot_be_promoted":True},
 "research_boundary":{"prior_stcr_eth_leadership_evidence_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_cmmtcr_direction_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cross-market multi-horizon trend confirmation in volatile BTC"},
 "stopping_rule":"Terminal first failure; no market, horizon, concordance, volatility, side, clock, hold, subset, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2)+"\n");print(a.output)
