"""Outcome-blind preregistration for HVSRAR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVSRAR-8";DEFAULT_OUTPUT=Path("results/high_volatility_sign_run_asymmetry_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_sign_run_asymmetry_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"Within a completed high-variation eight-hour BTC auction, the longest consecutive positive-return run versus the longest consecutive negative-return run measures asymmetric directional persistence that averages and entropy conceal. When the maximum-run asymmetry is historically extreme, follow the longer-run direction for the next eight hours.","side":"sign(longest positive 5m return run minus longest negative 5m return run)","why_distinct":"Sign entropy uses only the aggregate positive/negative proportion, serial autocorrelation averages all adjacent products, and directional persistence uses broader path displacement. HVSRAR uses the difference between the two extreme consecutive run lengths, reuses no event set or control, and is not a repair of those terminal candidates.","volatile_market_target":"completed-block realized-variation causal rank must be at least 0.65","why_low_gross9_overlap_is_plausible":"sparse conditional 00:05/08:05/16:05 UTC entries with eight-hour holds are absent from Gross9 primitives"},
 "features":{"decision_grid":"exact UTC 00:00, 08:00, and 16:00 boundaries","block":"96 exact coherent BTCUSDT perpetual five-minute aggregates in [D-8h,D), each from five unique 1m rows","return_sign":"strict sign of each completed 5m log(close/open) return; zero breaks every run","positive_run":"maximum count of consecutive strictly positive return signs","negative_run":"maximum count of consecutive strictly negative return signs","run_asymmetry":"positive_run-negative_run; strict nonzero","run_share":"abs(run_asymmetry)/(positive_run+negative_run), denominator strict positive","realized_variation":"sqrt(sum squared five-minute log(close/open) returns), strict positive","causal_ranks":"strict-prior midranks of run_share and realized_variation over at most 270 earlier source-valid blocks, minimum 252; current excluded","eligibility":"run-share rank>=0.80 and variation rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact block boundary after all source bars complete","entry":"exact BTCUSDT decision+5m open","side":"run-asymmetry sign","hold":"8 elapsed hours","reservation":"fixed blocks and holds are nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium_rv20":"not signal inputs; funding only after novelty; RV20 q90 only after all economics pass"},
 "policy":{"block_hours":8,"bars_5m":96,"history_blocks":270,"minimum_history_blocks":252,"run_share_rank_min":.80,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_run_share_gate","no_variation_gate","net_block_return_side","one_block_stale_features","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_only":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"related_sign_path_outcomes_known":True,"extreme_run_asymmetry_used_to_select_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent extreme consecutive-run asymmetry mechanism"},
 "stopping_rule":"terminal first failure; no block, run definition, rank, history, threshold, side, timing, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVSRAR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
