"""Outcome-blind preregistration for HVISCER-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVISCER-8";DEFAULT_OUTPUT=Path("results/high_volatility_intraday_state_conditioned_expert_rotation_relay_preregistration_2026-08-13.json");MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_intraday_state_conditioned_expert_rotation_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-13","singleton":True,"current_candidate_outcomes_opened":False,"candidate_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"Momentum and reversal behavior estimated across quiet and volatile decisions can obscure regime-specific performance. Score formulaic 4h/12h experts only on causally matured prior decisions that were themselves in the high-variation state, and trade the first four-hour boundary where the positive-score conditional winner changes.","side":"current side emitted by the new highest mean high-variation-conditioned gross-log-payoff expert","why_distinct":"HVDOER and HVOER score every mature label regardless of the volatility state at label origin. HVTCEC uses unconditional top-two concordance and no winner transition. HVISCER uses only prior high-variation-origin labels and emits a positive-score conditional winner transition; no prior event set or control is reused.","why_suited_to_volatile_regimes":"current completed eight-hour variation and every learning-label origin must have causal rank at least 0.65","why_low_gross9_overlap_is_plausible":"sparse offset intraday state-conditioned winner rotations are absent from Gross9 calendars"},
 "features":{"decision_grid":"exact 02:00, 06:00, 10:00, 14:00, 18:00, and 22:00 UTC","returns":{"r4":"log(last completed close/completed close exactly 4h earlier)","r12":"log(last completed close/completed close exactly 12h earlier)"},"experts_in_tie_order":["momentum_4h","reversal_4h","momentum_12h","reversal_12h"],"expert_sides":{"momentum_4h":"sign(r4)","reversal_4h":"-sign(r4)","momentum_12h":"sign(r12)","reversal_12h":"-sign(r12)"},"counterfactual_label":"expert side at prior four-hour decision times times log(open at prior entry+8h/open at prior entry); label matures only when exit open is observed","label_origin_gate":"include a mature label only if its origin decision had a finite causal variation rank>=0.65","online_score":"arithmetic mean gross log payoff before costs over latest at most 60 included mature labels, minimum 30; largest wins and frozen expert order breaks ties","rotation":"current conditional winner differs from immediately prior consecutive four-hour ranking-valid conditional winner","positive_score":"new winner mean gross-log-payoff score>0","variation":"sqrt(sum squared 96 exact completed 5m intrabar log(close/open) returns over prior 8h)","variation_rank":"strict-prior midrank over at most 270 source-valid four-hour decisions, minimum 180, current excluded; rank>=0.65","no_imputation":True},
 "causal_label_authorization":{"allowed":"only fixed expert labels whose exit open is observed at or before current decision","current_candidate_postentry_return_forbidden":True,"funding_pnl_cagr_mdd_forbidden":True,"future_stage_refit_or_reset":False},
 "clock":{"entry":"decision+5m exact BTCUSDT open","hold":"8 elapsed hours","reservation":"winner changes inside an active half-open position are suppressed, not queued","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact held settlements after novelty"},
 "policy":{"expert_memory_labels":60,"minimum_mature_labels":30,"variation_history_decisions":270,"variation_minimum_decisions":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},"post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"definitions":{"no_variation_gate":"all positive-score conditional winner rotations","no_positive_score":"conditional winner rotations regardless of score sign","winner_level":"every positive-score conditional winner level","one_decision_stale_winner":"prior conditional winner side on primary clock","direction_flip":"negative primary side","same_clock_forced_long":"side +1"},"cannot_be_promoted":True},
 "source_plan":{"historical":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m through 2026-08-01 with overlap parity","mature_expert_label_opens":"explicitly authorized source labels only","economic_execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_unconditional_and_daily_state_conditioned_online_expert_terminal_results_known":True,"prior_event_sets_or_controls_reused":False,"exact_candidate_incidence_opened":False,"current_candidate_postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent volatility-state-conditioned causal expert learning mechanism"},"stopping_rule":"terminal first failure; no expert, memory, label, rotation, variation, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVISCER prereg drift")
 if hashlib.sha256(MARKET.read_bytes()).hexdigest()!=MARKET_SHA:raise RuntimeError("HVISCER market drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
