"""Outcome-blind preregistration for HVHVD-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/high_volatility_horizontal_visibility_direction_relay_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_horizontal_visibility_direction_relay_v1","policy_id":"HVHVD-8","as_of_date":"2026-08-13","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A volatile BTC path whose nonadjacent horizontal-visibility edges overwhelmingly rise or fall has multiscale directional ordering that is not captured by endpoint return alone. At a fresh upper-tail visibility-direction onset confirmed by completed displacement, follow that graph-implied direction for eight elapsed hours.","side":"common strict sign of lag-weighted nonadjacent visibility-edge displacement and completed block return","why_distinct":"Path efficiency, endpoint-chord bow, excursion ordering, recurrence, persistent topology and ordinal patterns do not construct a horizontal visibility graph. HVHVD uses only the strict pairwise visibility relation and lag-weighted signs of nonadjacent graph edges; it reuses no event set or control and uses no volume, flow, count, funding, OI, premium, fitted outcome, or post-entry data.","why_suited_to_volatile_regimes":"completed variation must occupy its causal upper 35 percent and absolute graph direction its causal upper quartile","why_low_gross9_overlap_is_plausible":"06:05/14:05/22:05 UTC visibility-graph onsets are absent from Gross9 structural clocks"},
 "features":{"decision_grid":"exact 06:00/14:00/22:00 UTC boundaries D","block":"96 exact epoch-aligned five-minute closes formed from 480 unique coherent BTCUSDT perpetual one-minute rows [D-8h,D)","log_price_nodes":"natural logarithm of the 96 five-minute closes in chronological order","horizontal_visibility_edge":"for i<j, edge exists iff every intermediate node k satisfies x_k<min(x_i,x_j); only nonadjacent edges j-i>=2 enter the statistic","edge_direction":"strict sign of x_j-x_i; equal endpoint edge invalidates the block","visibility_direction":"sum over nonadjacent edges of (j-i)*sign(x_j-x_i) divided by sum(j-i); at least 24 nonadjacent edges; finite strict nonzero","direction_strength_rank":"strict-prior midrank of abs(visibility_direction) over at most 270 source-valid decisions, minimum 180, current excluded; rank>=0.75","realized_variation":"sqrt(sum squared five-minute log(close/open) returns), finite strict positive","variation_rank":"strict-prior 270/180 midrank, current excluded; rank>=0.65","block_return":"log(last five-minute close/first five-minute open), finite strict nonzero and same sign as visibility_direction","onset":"eligible now and immediately preceding scheduled source-valid decision ineligible; missing or invalid prior cannot trigger","no_imputation":True},
 "clock":{"decision":"completed eight-hour boundary D","entry":"exact BTCUSDT perpetual D+5m open","side":"common graph-direction and block-return sign","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium":"not signal inputs; exact funding only after novelty"},
 "policy":{"minimum_nonadjacent_edges":24,"prior_decisions":270,"minimum_prior_decisions":180,"direction_strength_rank_min":.75,"variation_rank_min":.65,"decision_hours_utc":[6,14,22],"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval and final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration_commit":True},"execution_price":"sealed until source support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_direction_tail","no_variation_gate","unweighted_visibility_edges","one_decision_stale_graph","direction_flip","forced_long"],"cannot_be_promoted":True},
 "research_boundary":{"prior_path_geometry_topology_and_pattern_outcomes_known":True,"repository_horizontal_visibility_graph_candidate_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"reversal_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent graph-theoretic multiscale path-ordering mechanism selected from formula-absence and complete-source audit only"},
 "stopping_rule":"terminal first failure; no graph relation, edge subset, weighting, minimum edge count, history, rank, threshold, variation, confirmation, onset, clock, hold, side, subset, source, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVHVD prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
