"""Outcome-blind preregistration for HVUO-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVUO-24";DEFAULT_OUTPUT=Path("results/high_volatility_ultimate_oscillator_reentry_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ultimate_oscillator_reentry_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a canonical Ultimate Oscillator returning inside its 30/70 envelope combines short-, medium-, and long-horizon buying pressure to identify multi-scale exhaustion beginning to normalize; follow the inward re-entry direction for twenty-four hours.","side":"long when Ultimate Oscillator crosses strictly above 30 after being at or below 30; short when it crosses strictly below 70 after being at or above 70","why_distinct":"HVUO combines close-relative buying pressure and true range over fixed 7/14/28 horizons with canonical 4/2/1 weighting. It is multi-scale pressure normalization rather than a single-window stochastic/RSI/CCI, recursive SAR, channel, volume, OI, funding, premium, or Gross9 state logic.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%, where multi-horizon pressure exhaustion can distinguish normalization from one-bar noise","why_low_gross9_overlap_is_plausible":"sparse four-hour multi-scale pressure re-entry clocks are absent from Gross9 primitives"},
 external_basis={"origin":"Larry Williams, canonical Ultimate Oscillator","fixed_definition":"buying pressure=close-min(low,prior close); true range=max(high,prior close)-min(low,prior close); 7/14/28 rolling BP/TR averages weighted 4/2/1; oscillator=100*weighted average/7; conventional 30/70 re-entry","selection_use":"published horizons, formulas, weights, levels, and direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","buying_pressure":"close-min(low,prior completed close) on consecutive valid four-hour bars","true_range":"max(high,prior close)-min(low,prior close)","averages":"rolling sums BP divided by rolling sums TR over exactly 7,14,28 consecutive transitions; zero denominator invalid","ultimate_oscillator":"100*(4*average7+2*average14+average28)/7","reentry":"current oscillator strictly crosses inward through 30 or 70 from immediately prior valid oscillator","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"short_periods":7,"medium_periods":14,"long_periods":28,"short_weight":4.,"medium_weight":2.,"long_weight":1.,"lower_level":30.,"upper_level":70.,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","equal_horizon_weights","one_bar_stale_reentry","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_uo_definition_read":True,"repository_uo_candidate_found":False,"prior_rsi_cci_stochastic_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Ultimate Oscillator inward re-entry under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no horizon, weight, formula, level, crossing, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVUO preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
