"""Outcome-blind preregistration for HVEBS-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVEBS-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_even_better_sinewave_zero_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_even_better_sinewave_zero_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' normalized Even Better Sinewave crossing zero on completed four-hour BTC auctions identifies a denoised cycle phase transition; follow the new phase direction for twenty-four hours.","side":"long on a strict nonpositive-to-positive normalized wave crossing; short on a strict nonnegative-to-negative crossing","why_distinct":"A one-pole duration-40 high-pass removes trend, a period-10 two-pole Super Smoother removes aliasing noise, and a three-bar wave is normalized by contemporaneous power. It is not the two-pole Roofing Filter, a price-average crossover, bounded price/range oscillator, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"power-normalized denoised cycle phase crossings are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Even Better Sinewave Indicator, Cycle Analytics for Traders","source":"https://www.sierrachart.com/SupportBoard.php?ThreadID=59987","fixed_definition":"close input; Duration=40 one-pole high-pass; period-10 Super Smoother; Wave=three-bar mean of filtered values; Pwr=three-bar mean square; normalized Wave/sqrt(Pwr); zero line","selection_use":"published defaults, recursions, normalization, and zero reference only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","high_pass":"0.5*(1+alpha)*(close-prior_close)+alpha*prior_HP, alpha=(1-sin(2pi/40))/cos(2pi/40)","filtered":"period-10 two-pole Super Smoother of current and prior HP","wave":"mean current and prior two filtered values","power":"mean squared current and prior two filtered values","normalized_wave":"wave/sqrt(power), invalid at zero power","initialization":"after a gap first HP and first two filtered observations are zero; require 40 uninterrupted observations before source validity","event":"strict finite normalized-wave zero crossing","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"duration":40,"super_smoother_period":10,"wave_period":3,"warmup_observations":40,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","unnormalized_filtered_cross","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_even_better_sinewave_definition_read":True,"repository_even_better_sinewave_candidate_found":False,"prior_filter_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Ehlers duration-40 normalized Even Better Sinewave zero crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no duration, smoother, normalization, initialization, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVEBS preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
