"""Outcome-blind preregistration for HVEDR-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVEDR-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_dual_roc_consensus_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_dual_roc_consensus_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' published fast/slow dual-ROC consensus newly becoming unanimously positive or negative on completed four-hour BTC auctions identifies a multi-band directional transition; follow the consensus for twenty-four hours.","side":"long on the first decision where both two-bar ROCs are strictly positive after the prior decision was not unanimously positive; short symmetrically when both become strictly negative after not unanimously negative","why_distinct":"The strategy SuperSmooths close at 20, separately high-pass filters it at 55 and 156, takes two-decision momentum of each band, and requires same-sign consensus. It is not the RMS Cybernetic Oscillator, a single zero-cross, moving-average crossover, raw return sum, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"multi-band directional agreement must newly emerge while completed trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse dual recursive-band momentum-consensus transitions are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Making A Better Oscillator, Simple Dual ROC Strategy, TASC June 2025","source":"https://traders.com/Documentation/FEEDbk_docs/2025/06/TradersTips.html","fixed_definition":"SuperSmoother length=20; high-pass lengths 55 and 156; ROC is current high-pass minus lag two; published long condition ROC1>0 and ROC2>0; symmetric negative consensus used for short direction","selection_use":"published parameters, recursions, two-bar ROC, and positive consensus; negative consensus is the exact sign-symmetric short counterpart; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","super_smoother":"published 20-period recursive SuperSmoother of completed close","fast_roc":"55-period high-pass of SuperSmoother minus its two-decision lag","slow_roc":"156-period high-pass of SuperSmoother minus its two-decision lag","event":"new entry into strict same-sign ROC consensus relative to immediately prior valid decision","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"all recursive state resets after any invalid completed four-hour bar; event requires uninterrupted current and prior consensus states","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"smoother_periods":20,"fast_high_pass_periods":55,"slow_high_pass_periods":156,"roc_lag_periods":2,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","fast_roc_only","slow_roc_only","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_dual_roc_strategy_read":True,"repository_same_mechanism_candidate_found":False,"prior_cybernetic_zero_cross_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published Ehlers SS20/HP55/HP156 two-bar dual ROC consensus under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no period, recursion, lag, consensus, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVEDR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
