"""Outcome-blind preregistration for HVSPB-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVSPB-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_super_passband_reentry_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_super_passband_reentry_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' Super Passband waveform returning inward through its symmetric fifty-bar RMS envelope on completed four-hour BTC auctions marks a low-lag cycle reversal; follow the re-entry direction for twenty-four hours.","side":"long when PB crosses strictly above negative RMS after being at or below it; short when PB crosses strictly below positive RMS after being at or above it","why_distinct":"The passband is a second-order recursion equivalent to the difference of two Ehlers EMA speeds, rejecting both low- and high-frequency components, while its event is scaled by its own trailing RMS energy. It is not a price-average crossover, bounded return/range oscillator, Roofing Filter zero cross, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"energy-scaled bandpass envelope re-entry clocks are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, The Super Passband Filter, TASC July 2016","sources":["https://traders.com/Documentation/FEEDbk_docs/2016/07/TradersTips.html","https://efs.kb.esignal.com/hc/en-us/articles/6362955543067-2016-Jul-The-Super-Passband-Filter-by-John-F-Ehlers"],"fixed_definition":"close input; Period1=40, Period2=60, a1=5/40, a2=5/60; published second-order PB recursion; RMS=sqrt(mean latest 50 PB squared)); inward crossings of -RMS/+RMS","selection_use":"published defaults, recursion, energy envelope, and example crossing direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","passband":"(a1-a2)*close+(a2*(1-a1)-a1*(1-a2))*prior_close+((1-a1)+(1-a2))*prior_PB-(1-a1)*(1-a2)*lag2_PB","initialization":"after an invalid gap, first two valid PB observations are zero; require 60 uninterrupted observations before source validity","rms":"square root of mean squared PB over latest 50 uninterrupted observations","reentry":"current PB strictly crosses above -RMS from <= for long or below +RMS from >= for short","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"short_period":40,"long_period":60,"rms_period":50,"warmup_observations":60,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","zero_cross","one_bar_stale_reentry","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_super_passband_definition_read":True,"repository_super_passband_candidate_found":False,"prior_filter_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Ehlers 40/60 Super Passband RMS-envelope re-entry under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no periods, coefficients, RMS window, initialization, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVSPB preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
