"""Outcome-blind preregistration for HVRC-B20-2-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVRC-B20-2-24"
DEFAULT_OUTPUT=Path("results/high_volatility_regression_channel_breakout_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_regression_channel_breakout_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
  mechanism={"claim":"During elevated realized variation, a completed four-hour BTC close breaking beyond its documented twenty-period, two-standard-deviation LEAN Regression Channel identifies displacement beyond the fitted trend envelope; follow the breakout for twenty-four hours.","side":"long when close newly crosses strictly above the upper channel; short when close newly crosses strictly below the lower channel","why_distinct":"The channel combines a rolling OLS endpoint projection with the population standard deviation of the same raw close levels. It is not a fixed mean band, Donchian/Keltner/Bollinger rule, fitted outcome, volume, flow, OI, funding, reused event set, or promoted control.","why_suited_to_volatile_regimes":"a close must escape a trend-adjusted price-dispersion envelope while completed trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse four-hour OLS-endpoint channel escapes are absent from Gross9 primitives"},
  external_basis={"origin":"canonical Regression Channel; QuantConnect LEAN implementation","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/RegressionChannel.cs","documentation_source":"https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/regression-channel","fixed_definition":"documented period=20 and k=2; OLS on chronological x=1..20 and closes, endpoint=intercept+slope*20; population standard deviation of the same 20 raw close levels; upper/lower=endpoint +/- 2*std; warmup 20","selection_use":"official documented period, width, population dispersion, endpoint projection, and outer-channel breakout only; no incidence or outcomes"},
  features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","ols":"chronological rolling 20-close intercept and slope evaluated at x=20","dispersion":"population standard deviation with divisor 20 over the same raw closes","channels":"OLS endpoint plus/minus two times dispersion","event":"close newly strictly above upper from not above gives +1; close newly strictly below lower from not below gives -1; transitions between inside and the opposite band require an actual outer crossing","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"rolling OLS, dispersion, and crossing state reset after any invalid completed four-hour bar","no_imputation":True},
  clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
  policy={"period":20,"channel_width":2.0,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  diagnostic_controls={"names":["no_variation_gate","regression_center_crossover","one_bar_stale_breakout","direction_flip"],"cannot_be_promoted":True},
  source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
  research_boundary={"canonical_regression_channel_definition_read":True,"repository_regression_channel_candidate_found":False,"prior_channel_candidate_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official LEAN RegressionChannel(20,2) outer breakout under the requested high-variation regime"},
  stopping_rule="Terminal first failure; no period, width, regression, dispersion, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVRC-B20-2-24 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
