"""Outcome-blind preregistration for PVIAR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/premium_volatility_ignition_acceleration_relay_preregistration_2026-08-08.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"premium_volatility_ignition_acceleration_relay_v1","policy_id":"PVIAR-6","as_of_date":"2026-08-08","outcomes_opened":False,"source_incidence_opened":False,
 "mechanism":{"claim":"During joint BTC BVOL and DVOL expansion, an unusually large first-half Binance BTCUSDT premium-index move followed by a larger same-direction second-half move identifies accelerating derivatives demand before it is fully transmitted to BTC; the premium direction should relay for six hours.","side":"common sign of the two completed half-hour premium-index close-minus-open moves","why_distinct":"PVIAR uses a completed one-hour premium path and joint cross-venue volatility ignition. PCBR required a two-hour compressed premium cage and a ten-minute outside breakout; PSR required alternating high-energy premium motion that recentered. PVIAR uses neither compression nor recentering.","why_low_gross9_overlap_is_plausible":"premium-index intrahour acceleration fused with BVOL/DVOL ignition is absent from Gross9"},
 "clock":{"decision":"T after a completed UTC hour","premium_source":"60 exact bars_binance_premium BTCUSDT interval=1m rows in [T-1h,T), split offsets 0..29 and 30..59","premium_moves":"first_half_close-hour_open and hour_close-second_half_open; differences, not ratios, because premium can cross zero","first_half_shock":"nonzero absolute first-half move >= strictly-prior 720h q60 with 672 valid observations","directional_acceleration":"second-half move has same nonzero sign and absolute magnitude >= first-half absolute magnitude","volatility_ignition":"normalized completed-hour BVOL and DVOL bodies are both strictly positive","trigger":"false-to-true onset with prior source-valid consecutive hour","entry":"exact BTCUSDT T+5m open","side":"common premium move direction","hold":"6 elapsed hours","reservation":"global half-open, exit first on equal open","btc_price_oi_funding_forbidden_as_signal_inputs":True,"no_imputation":True},
 "policy":{"prior_hours":720,"prior_min_hours":672,"first_half_absolute_move_quantile":.60,"minimum_acceleration_ratio":1.,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"premium_snapshot":{"table":"bars_binance_premium","symbol":"BTCUSDT","interval":"1m","window":["2023-06-20T00:00:00Z","2026-08-01T00:00:00Z"],"columns":["ts","open","high","low","close","close_time"],"order":"ts ascending","target":"data/premium_volatility_ignition_sources_2023_2026/premium_1m.csv.gz","materialize_after_preregistration":True},"volatility":"reuse hash-bound OCDR-12C BVOL/DVOL snapshot through 2026-08-01","execution_price":"sealed until source-support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_joint_expansion","no_first_half_tail","no_same_direction","no_acceleration","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"prior_pcbr_psr_incidence_known":True,"prior_candidate_outcomes_used_to_define_pviar":False,"premium_snapshot_rows_opened":False,"candidate_incidence_opened":False,"post_entry_outcomes_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no repair"}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2,ensure_ascii=False)+"\n");print(a.output)
