"""Outcome-blind preregistration for CATPJI-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="CATPJI-6";DEFAULT_OUTPUT=Path("results/cross_asset_traded_price_jensen_isolation_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"cross_asset_traded_price_jensen_isolation_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When the base-volume-weighted arithmetic-to-geometric gap of BTC five-minute traded-price proxies becomes extreme both absolutely and relative to six liquid alts, the completed BTC move is an isolated internal price-dispersion shock rather than broad repricing. Fade the completed BTC hour for six elapsed hours.","side":"negative strict sign of completed BTC hour return","why_distinct":"CATPJI uses a Jensen gap across twelve five-minute quote/base traded-price proxies and then removes the Alt6 median. Close-VWAP candidates use one endpoint-to-center displacement; individual-fill dispersion uses raw fill distributions. This candidate uses no close location, trade count, ticket size, taker direction, funding, OI, or fitted outcome model.","volatile_market_target":"an extreme isolated traded-price Jensen gap is itself a volatile-auction dispersion state; causal RV20 q90 remains only a later audit","why_low_gross9_overlap_is_plausible":"joint top-decile absolute and cross-asset-isolation crossings with a six-hour reservation"},
 "features":{"symbols":["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT"],"decision_grid":"every exact UTC hour D","hour_window":"12 exact coherent completed five-minute aggregates [D-1h,D) per symbol","bar_traded_price":"P_i=quote_asset_volume_i/base_volume_i, requiring both strict positive","base_weight":"w_i=base_volume_i/sum(base_volume over 12 bars)","jensen_gap":"J_s=log(sum quote/sum base)-sum(w_i*log(P_i)); finite and nonnegative up to 1e-15 numerical tolerance","isolation":"I=J_BTC-median(J_ETH,J_SOL,J_BNB,J_XRP,J_DOGE,J_ADA)","hour_return":"r_BTC=log(last 5m close/first 5m open), strict nonzero","tail_ranks":"independent strict-prior midranks of J_BTC and I over at most 2160 prior valid seven-symbol hours, minimum 1440, current excluded","eligible_state":"J_BTC_rank>=0.90 and isolation_rank>=0.90 and BTC hour return strict nonzero","onset":"current eligible state true and immediately preceding exact hourly opportunity has both ranks<0.90; missing prior cannot trigger","source_valid":"all seven symbols have exact unique coherent 1m grids, 12 complete 5m aggregates, positive finite base and quote volume and price OHLC; no imputation"},
 "rv20_stress_slice":{"rv20":"sqrt(365*mean exact daily returns^2 over t-20 through t-1)","threshold":"numpy linear q90 over 756 strictly prior available RV20 observations","entry_filter":False,"future_use":"only after all sequential full-calendar stages pass"},
 "clock":{"decision":"exact UTC hour after all seven completed paths are available","entry":"exact BTCUSDT decision+5m open","hold":"6 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact realized BTC funding only after novelty"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","persistent_long_vol_comparator":"same accepted clock and 0.5 gross, side forced long","full_calendar_decomposition":"candidate minus comparator net return","rv20_q90_decomposition":"same decomposition on causal RV20 q90 decisions","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"candidate_specific_q90_residual_positive":True,"comparator_cannot_satisfy_candidate_claim":True},
 "diagnostic_controls":{"definitions":{"btc_jensen_only":"top-decile J_BTC crossing with nonzero BTC return, fade return","cross_asset_isolation_only":"top-decile isolation crossing with nonzero BTC return, fade return","close_to_hour_vwap":"top-decile absolute log(hour close/(sum quote/sum base)) crossing, fade displacement sign","one_hour_stale_jensen":"primary eligible boolean and side shifted by one exact hour with onset applied after shift","direction_flip":"positive primary return side"},"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbols":["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT"],"interval":"1m","columns":["ts","open","high","low","close","volume","quote_asset_volume"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"exact_catpji_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no symbol, aggregation, rank, history, onset, side, clock, hold, RV20, subset, comparator, control, or gate repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("CATPJI preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+"\n");print(a.output)
