"""Outcome-blind preregistration for HVCQCA-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_cross_structure_action_vote as gates
POLICY_ID="HVCQCA-24";DEFAULT_OUTPUT=Path("results/high_volatility_credit_transition_causal_adapter_preregistration_2026-08-18.json");SOURCE=Path("data/high_volatility_credit_risk_appetite_relay_sources_2022_2026/daily_credit_states.csv.gz");SOURCE_SHA="88d227fff477484ce40e2da8578368cd3345b6fc62c4e6d99a4325b4aed67e59"
def sha256(p:str|Path)->str:return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 g=gates.build();core={"protocol_version":"high_volatility_credit_transition_causal_adapter_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-18","singleton":True,"candidate_family":[POLICY_ID],"candidate_family_size":1,"source_incidence_opened":False,"current_candidate_outcomes_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"The BTC response sign to corporate-credit polarity transitions can change across regimes. Learn that sign only from fully matured prior HYG-minus-LQD transition labels, including pre-high-volatility history, then causally follow or invert the current high-variation transition.","side":"current credit-transition sign multiplied by strict sign of the arithmetic mean of the latest at most 12 matured transition directional labels","why_distinct":"HVCQTR fixes the transition side and failed test; HVCQVAR routes by contemporaneous variation change and failed train. HVCQCA uses no source-state threshold beyond the current frozen variation gate and learns only from prior fully exited transition responses, without stage resets, future labels, costs, funding, equity, PnL, OI, premium, options, or promoted controls.","why_low_gross9_overlap_is_plausible":"high-variation credit transition times remain sparse and already passed Gross9 while adapted signs alter exposure"},
 "features":{"source":{"path":str(SOURCE),"sha256":SOURCE_SHA},"transition":"strict polarity change in HYG-minus-LQD return versus immediately prior source-valid session","label_universe":"all source-valid credit transitions regardless of BTC variation rank","label":"transition side times log(BTC exit_open/entry_open) over 24 hours","maturity":"label exit_time<=current decision_time","memory":"latest at most 12 matured transition labels; minimum 8","score":"arithmetic mean gross log label, strict nonzero","current_gate":"current frozen BTC variation_rank>=0.65","routing":"positive score keeps transition side; negative score inverts; insufficient/nonfinite/zero score is cash","no_imputation":True},
 "policy":{"memory_labels":12,"minimum_mature_labels":8,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},"clock":{"decision":"frozen session 23:00 UTC","entry":"23:05 UTC exact BTCUSDT open","hold":"24 elapsed hours","reservation":"chronological half-open nonoverlap","funding":"not signal input; exact settlements after Gross9"},
 "stages":g["stages"],"source_support_gates":g["source_support_gates"],"gross9_novelty_gates":g["gross9_novelty_gates"],"economic_gates":g["economic_gates"],"research_boundary":{"prior_HVCQTR_train_pass_test_failure_known":True,"prior_HVCQVAR_train_failure_known":True,"transition_definition_reused":True,"transition_event_level_BTC_labels_opened":False,"exact_adapter_incidence_or_outcomes_known":False,"mature_counterfactual_labels_authorized":True,"current_candidate_postentry_return_or_pnl_opened":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"classification":"exploratory causal online adaptation; not fresh confirmatory evidence","selection_basis":"prehistory-seeded causal response sign learning"},"stopping_rule":"source causality, Gross9, train/test/eval/final; terminal first failure; no transition, label universe, memory, minimum labels, maturity, score, gate, side, clock, hold, subset, threshold, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x!=build():raise RuntimeError("HVCQCA prereg drift")
 if sha256(SOURCE)!=SOURCE_SHA:raise RuntimeError("HVCQCA source drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
