"""Outcome-blind preregistration for HVFIC-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVFIC-8";DEFAULT_OUTPUT=Path("results/high_volatility_flow_impact_convexity_relay_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_flow_impact_convexity_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"When large aggressive-flow bars move BTC disproportionately more than small aggressive-flow bars within a completed volatile auction, marginal liquidity is convex rather than linear. If aggregate aggressive flow and block return agree, follow that informed-flow direction for eight hours.","side":"common strict sign of aggregate signed aggressive quote flow and completed block return","why_distinct":"HVTIER compares first-half and second-half aggregate return per turnover. HVPIAR compares upside and downside return per turnover. Kyle handoff compares venues. HVFIC instead conditions one-venue through-origin flow-response slopes on within-block flow magnitude and measures nonlinear marginal-impact convexity; no time half, return-sign bucket, spot source, funding, OI, or fitted outcome is used.","why_suited_to_volatile_regimes":"completed realized variation must rank in its causal upper 35 percent","why_low_gross9_overlap_is_plausible":"offset 01/09/17 UTC nonlinear impact-convexity onsets are absent from Gross9"},
 "features":{"decision_grid":"exact 01:00, 09:00, and 17:00 UTC boundaries D","block":"480 exact coherent native BTCUSDT perpetual one-minute rows [D-8h,D), aggregated into 96 exact five-minute bars","bar_flow":"(2*taker_buy_quote-quote_asset_volume)/quote_asset_volume, positive denominator required","bar_return":"log(five-minute close/five-minute open)","magnitude_split":"strict within-block median of abs(bar_flow); exactly median ties are excluded; require at least 32 high and 32 low bars","conditional_beta":"sum(flow*return)/sum(flow^2) separately for high- and low-magnitude bars; both finite strictly positive","impact_convexity":"log(high_magnitude_beta/low_magnitude_beta), strict positive","convexity_rank":"strict-prior midrank over at most 270 source-valid positive convexities, minimum 180, current excluded; rank>=0.75","aggregate_flow":"sum(2*taker_buy_quote-quote_asset_volume), strict nonzero","block_return":"log(last close/first open), strict nonzero and same sign as aggregate_flow","variation":"sqrt(sum squared five-minute bar returns), strict positive","variation_rank":"strict-prior midrank over at most 270 source-valid blocks, minimum 180, current excluded; rank>=0.65","onset":"full eligible state true now and false at immediately prior source-valid decision","no_imputation":True},
 "clock":{"decision":"completed offset eight-hour boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","side":"common aggregate-flow and block-return sign","reservation":"natural half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements after novelty"},
 "policy":{"block_minutes":480,"five_minute_bars":96,"minimum_bars_each_magnitude":32,"history_blocks":270,"minimum_history_blocks":180,"convexity_rank_min":.75,"variation_rank_min":.65,"onset_required":True,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},"post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"definitions":{"no_convexity_tail":"positive convexity plus variation and agreement without rank","no_variation_gate":"convexity tail and agreement only","linear_impact":"low/high beta ratio tail","one_block_stale_convexity":"prior convexity with current flow direction and variation","direction_flip":"negative primary side","same_clock_forced_long":"side +1"},"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume","taker_buy_quote"],"window":["2023-03-01T00:00:00Z","2026-08-01T00:00:00Z"]},"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_impact_family_outcomes_known":True,"repository_flow_magnitude_conditioned_impact_convexity_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent nonlinear marginal flow-impact mechanism"},"stopping_rule":"terminal first failure; no source, aggregation, magnitude split, beta, rank, variation, agreement, onset, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVFIC prereg drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
