"""Outcome-blind preregistration for HVRDOR-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVRDOR-24";DEFAULT_OUTPUT=Path("results/high_volatility_robust_daily_return_outlier_reversal_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_robust_daily_return_outlier_reversal_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"A completed daily BTC return that is an extreme robust outlier relative to the median and median absolute deviation of the thirty strictly prior daily returns represents a transient low-frequency displacement. In elevated twenty-day variation, fade the outlier for twenty-four hours.","side":"opposite strict sign of current daily return minus the prior-thirty-day median","why_distinct":"VWAP candidates use traded-price centers inside intraday blocks; self-normalized displacement uses one block's L2 path; skew candidates use third moments. HVRDOR compares one completed daily return with a strictly prior robust return distribution using median/MAD, with no price-level anchor, volume, flow, fitted return, prior event, or promoted control.","why_suited_to_volatile_regimes":"completed twenty-day daily realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"one 02:05 UTC robust daily-outlier reversal clock is absent from Gross9 primitives"},
 external_basis={"paper":"TESTING FOR TRADABLE ALPHA IN SHORT-TERM BITCOIN MARKET DATA","author":"Oliver Rustin","written":"2026-03-17","url":"https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6444920","reported_relation":"a low-frequency mean-reversion strategy was modestly and consistently profitable after short-horizon features failed costs","selection_use":"low-frequency mean-reversion mechanism only; fixed robust estimator chosen before incidence"},
 features={"decision_grid":"every calendar day at exact 02:00 UTC","current_return":"completed close-to-close BTC log return over [D-24h,D)","reference_returns":"thirty exact coherent daily close-to-close returns ending strictly before current_return","reference_median":"median of the thirty prior returns","reference_mad":"median absolute deviation from reference_median, finite strict positive","robust_score":"(current_return-reference_median)/(1.4826*reference_mad), finite strict nonzero","variation":"sqrt(sum squared current and prior nineteen daily returns), finite strict positive","prior_ranks":"strict-prior midranks over at most 180 earlier source-valid daily decisions, minimum 120, current excluded","outlier_gate":"absolute robust-score rank>=0.75","variation_gate":"variation rank>=0.65","no_imputation":True},
 clock={"decision":"completed daily endpoint at 02:00 UTC","entry":"exact BTCUSDT 02:05 UTC open","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"reference_days":30,"variation_days":20,"mad_consistency_scale":1.4826,"history_days":180,"minimum_history_days":120,"outlier_rank_min":.75,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_outlier_strength","no_variation_gate","raw_return_fade","one_day_stale_features","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-02-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"external_low_frequency_mean_reversion_basis_read":True,"prior_vwap_self_normalized_and_skew_outcomes_known":True,"repository_robust_daily_return_outlier_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"paper-supported low-frequency mean reversion with fixed prior-only median/MAD score"},
 stopping_rule="Terminal first failure; no return window, robust estimator, MAD scale, rank history, outlier strength, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVRDOR preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
