"""Outcome-blind preregistration for HVSAR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/high_volatility_settlement_absorption_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_settlement_absorption_relay_v1","policy_id":"HVSAR-6","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
 "mechanism":{"claim":"At a fixed eight-hour boundary in an unusually volatile completed BTC block, a final two-hour move that opposes and is no larger than half of the preceding six-hour move while carrying at least 30% of block quote volume marks participation-backed absorption rather than a shallow low-volume pullback. Follow the absorbing final-two-hour direction for six elapsed hours.","side":"strict nonzero sign of completed final-two-hour return, opposite the first-six-hour return","why_distinct":"HVSAR uses fixed 8h blocks, a 6h shock plus 2h opposing path, and quote-volume concentration to distinguish absorption. HVTPR followed the original trend after a 3h/1h shallow pullback with implied-volatility levels; DLVCR used daily same-direction late continuation. Neither event set nor diagnostic control is reused.","why_suited_to_volatile_regimes":"completed eight-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"three sparse UTC absorption clocks with within-block volume migration are absent from Gross9"},
 "features":{"source":"BTCUSDT bars_binance interval=1m","block_valid":"480 exact distinct minute rows in [decision-8h,decision), finite positive coherent OHLC, finite nonnegative quote_asset_volume, positive block quote volume; no imputation","early_return":"log(close at decision-2h-1m/open at decision-8h)","late_return":"log(close at decision-1m/open at decision-2h)","late_quote_volume_share":"final-two-hour quote volume divided by full-block quote volume","realized_variation":"sum squared 1m close-to-close log returns within the completed block","variation_rank":"strict-prior midrank among at most 270 valid fixed eight-hour blocks, minimum 180, current excluded; rank>=0.65","absorption":"early and late returns have opposite strict signs, abs(late)<=0.50*abs(early), late quote-volume share>=0.30","no_imputation":True},
 "clock":{"decision":"exact 00:00,08:00,16:00 UTC","entry":"exact decision+5m BTCUSDT open","hold":"6 elapsed hours","reservation":"global half-open; exit first on equal open","funding_oi_premium_implied_vol":"not signal inputs; exact funding only after novelty passes"},
 "policy":{"history_observations":270,"minimum_history_observations":180,"variation_rank_min":.65,"late_to_early_absolute_return_max":.50,"late_quote_volume_share_min":.30,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"btc_1m":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"materialize_after_preregistration":True},"execution_price":"sealed until source-support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_volatility_gate","no_volume_absorption_gate","one_boundary_stale_geometry","follow_early_shock"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"prior_pullback_and_absorption_candidate_incidence_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_hvsar_direction_threshold_hold_or_clock":False,"hvsar_candidate_incidence_opened":False,"hvsar_post_entry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent participation-backed settlement absorption mechanism"},
 "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no threshold, side, hold, clock, volume, or subset repair."}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+"\n");print(a.output)
