"""Outcome-blind preregistration for CATACF-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="CATACF-8";DEFAULT_OUTPUT=Path("results/cross_asset_trade_arrival_concentration_fracture_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"cross_asset_trade_arrival_concentration_fracture_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When a large completed BTC hour concentrates reported executions into a few five-minute buckets much more strongly than six liquid alts, the move is a BTC-local arrival shock rather than broad repricing. Fade the completed BTC direction for eight elapsed hours at the new upper-tail fracture crossing.","side":"negative strict sign of completed BTC hour return","why_distinct":"CATACF uses the HHI of twelve fixed five-minute execution-count shares and removes the Alt6 median. It does not use fill size, ticket value, quote/base volume, taker direction, within-bar timestamps, funding, OI, or a fitted model. Dominant-volume candidates weight notional rather than reported execution arrivals.","volatile_market_target":"the BTC absolute completed-hour return must be in its causal top quintile; RV20 q90 remains only a later audit","why_low_gross9_overlap_is_plausible":"new upper-tail cross-symbol arrival-concentration fractures with an eight-hour reservation"},
 "features":{"symbols":["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT"],"decision_grid":"every exact UTC hour D","hour_window":"12 exact coherent completed five-minute aggregates [D-1h,D) per symbol","five_minute_count":"N_s_i=sum integer number_of_trades over the five constituent one-minute rows","arrival_hhi":"H_s=sum((N_s_i/sum_j N_s_j)^2), requiring every N_s_i>=0 and positive hourly total","fracture":"F=H_BTC-median(H_ETH,H_SOL,H_BNB,H_XRP,H_DOGE,H_ADA)","hour_return":"r_BTC=log(last 5m close/first 5m open), strict nonzero","tail_ranks":"independent strict-prior midranks of F and abs(r_BTC) over at most 2160 prior valid seven-symbol hours, minimum 1440, current excluded","eligible_state":"fracture_rank>=0.90 and abs(BTC hour return)_rank>=0.80 and BTC return strict nonzero","onset":"current eligible state true and immediately preceding exact hourly opportunity has fracture_rank<0.90; missing prior cannot trigger","source_valid":"all seven symbols have exact unique coherent 1m grids, integer nonnegative number_of_trades, 12 complete 5m aggregates and positive hourly count; no imputation"},
 "rv20_stress_slice":{"rv20":"sqrt(365*mean exact daily returns^2 over t-20 through t-1)","threshold":"numpy linear q90 over 756 strictly prior available RV20 observations","entry_filter":False,"future_use":"only after all sequential full-calendar stages pass"},
 "clock":{"decision":"exact UTC hour after all seven completed paths are available","entry":"exact BTCUSDT decision+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact realized BTC funding only after novelty"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","persistent_long_vol_comparator":"same accepted clock and 0.5 gross, side forced long","full_calendar_decomposition":"candidate minus comparator net return","rv20_q90_decomposition":"same decomposition on causal RV20 q90 decisions","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"candidate_specific_q90_residual_positive":True,"comparator_cannot_satisfy_candidate_claim":True},
 "diagnostic_controls":{"definitions":{"btc_arrival_hhi_only":"top-decile H_BTC crossing with same return-tail gate, fade BTC return","cross_asset_fracture_without_return_tail":"top-decile F crossing with nonzero BTC return, fade return","btc_return_tail_only":"top-quintile abs BTC return crossing, fade return","one_hour_stale_fracture":"primary eligible boolean and side shifted by one exact hour with onset applied after shift","direction_flip":"positive primary BTC return side"},"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbols":["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT"],"interval":"1m","columns":["ts","open","high","low","close","number_of_trades"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"exact_catacf_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no symbol, HHI, rank, history, onset, side, clock, hold, RV20, subset, comparator, control, or gate repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("CATACF preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+"\n");print(a.output)
