"""Outcome-blind preregistration for HVCTI-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVCTI-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_correlation_trend_zero_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_correlation_trend_zero_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' twenty-period Correlation Trend Indicator crossing zero on completed four-hour BTC auctions identifies a reversal in alignment with an ideal straight trend; follow the new correlation sign for twenty-four hours.","side":"long on a strict nonpositive-to-positive CTI crossing; short on a strict nonnegative-to-negative crossing","why_distinct":"CTI is the Pearson correlation of twenty completed close levels with a fixed increasing time ramp, jointly normalizing slope alignment by price dispersion and time dispersion. It is not a return sum, regression forecast, moving-average crossover, range path, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the ideal-line trend reversal must coincide with completed trailing twenty-four-hour realized variation in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse time-ramp price-correlation sign reversals are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Correlation As A Trend Indicator, TASC May 2020","source":"https://traders.com/Documentation/FEEDbk_docs/2020/05/TradersTips.html","fixed_definition":"Length=20 completed closes; Y=-count for count 0..19; textbook correlation numerator and denominator; zero-line crossing direction","selection_use":"published default length, formula, and zero-cross strategy usage only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","time_ramp":"0,-1,...,-19 paired with current through lag19 close so positive correlation denotes a rising chronological trend","cti":"Pearson correlation of twenty uninterrupted completed closes with the fixed time ramp, invalid at zero price variance","event":"strict finite CTI zero crossing from the immediately prior finite CTI","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"cti_periods":20,"slow_control_periods":40,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","slow_40_bar_cti","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_cti_definition_read":True,"repository_cti_candidate_found":False,"prior_trend_indicator_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Ehlers CTI(20) zero crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no period, formula, threshold, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVCTI preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
