"""Outcome-blind preregistration for HVSUDR-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template

POLICY_ID="HVSUDR-24";DEFAULT_OUTPUT=Path("results/high_volatility_semiconductor_utilities_disagreement_relay_preregistration_2026-08-11.json")
def canonical_hash(value:Any)->str:return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_semiconductor_utilities_disagreement_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"When completed US cash-session semiconductor and utilities ETF returns have strict opposite signs, they identify a traded growth-versus-defensive rotation impulse. During elevated BTC variation, follow the semiconductor direction for twenty-four hours after both closes are certainly public.","side":"long when SMH is positive and XLU negative; short when SMH is negative and XLU positive","why_distinct":"SMH/XLU opposite-sign disagreement isolates cyclical technology leadership versus defensive regulated-utility demand. It is not HYG/LQD credit quality, SPY/TLT liquidity consensus, broad equity direction, Treasury yield, FX, crypto flow, prior event artifact, repair, or promoted control.","why_suited_to_volatile_regimes":"the preceding twenty-four-hour BTC realized variation must rank in its causal upper 35%, restricting the relay to July-like crypto risk states","why_low_gross9_overlap_is_plausible":"only opposite-sign sector-rotation sessions produce one external 23:05 UTC clock; this primitive is absent from Gross9"},
 external_basis={"smh":{"official_source":"https://www.vaneck.com/us/en/investments/semiconductor-etf-smh/","definition":"companies involved in semiconductor production and equipment"},"xlu":{"official_source":"https://www.ssga.com/us/en/intermediary/etfs/state-street-utilities-select-sector-spdr-etf-xlu","definition":"utilities-sector companies including electric, water, multi-, independent-power, renewable-electricity, and gas utilities"},"selection_use":"official sector exposures and opposite-sign growth-versus-defensive disagreement only; no candidate incidence or economic outcomes"},
 features={"sector_source":"candidate-specific Yahoo chart raw unadjusted SMH and XLU regular-session daily open/close snapshots downloaded only after preregistration push","session":"same US trading date D with finite positive raw opens and closes for both ETFs","smh_return":"log(SMH close/open)","xlu_return":"log(XLU close/open)","disagreement":"strict opposite signs; zero in either leg is ineligible","availability":"D 23:00 UTC, safely after the 16:00 America/New_York regular close in EST and EDT","btc_variation":"sqrt(sum squared exact BTCUSDT five-minute open-to-close log returns over the prior 24 elapsed hours ending at decision)","variation_rank":"strict-prior midrank over at most 270 previous valid daily 23:00 UTC states, minimum 180, current excluded; rank>=0.65","no_adjusted_close":True,"no_imputation":True},
 clock={"decision":"each shared SMH/XLU regular-session date D at 23:00 UTC","entry":"exact BTCUSDT 23:05 UTC open","hold":"24 elapsed hours","side":"strict SMH return sign on opposite-sign sessions","reservation":"chronological global half-open nonoverlap; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"variation_history_decisions":270,"minimum_variation_history_decisions":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","smh_only","inverse_xlu_only","one_session_stale_rotation","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"smh":"Yahoo chart query1=2022-09-01 query2=2026-08-02 exclusive interval=1d events=history; raw open/close only","xlu":"same contract","destination":"data/high_volatility_semiconductor_utilities_disagreement_relay_sources_2022_2026/smh_xlu_sessions.csv.gz","btc":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"official_etf_definitions_read":True,"repository_smh_xlu_candidate_found":False,"sector_values_opened":False,"prior_external_etf_novelty_density_known":True,"prior_external_etf_economic_outcomes_opened":False,"prior_event_sets_reused":False,"prior_candidate_economic_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent traded semiconductor-versus-utilities risk rotation plus requested high BTC variation"},
 stopping_rule="Terminal first failure; no ETF substitution, adjusted-price use, disagreement relation, session, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(value):
 core={k:v for k,v in value.items() if k!="manifest_hash"}
 if value.get("manifest_hash")!=canonical_hash(core) or value!=build():raise RuntimeError("HVSUDR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
