"""Outcome-blind preregistration for DVBCR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/daily_variance_backloading_continuation_relay_preregistration_2026-08-08.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"daily_variance_backloading_continuation_relay_v1","policy_id":"DVBCR-12","as_of_date":"2026-08-08","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
 "mechanism":{"claim":"At the fixed UTC day boundary, unusually high completed-day BTC realized variation whose final twelve hours contain at least 65% of daily variance identifies a volatility impulse migrating toward the close. If the final six-hour return is nonzero and carries at least half of the absolute twelve-hour return, its direction should continue for twelve hours.","side":"sign of the completed final-six-hour BTC return","why_distinct":"DVBCR measures the temporal center of realized variance and late impulse dominance at one daily clock. HVDPR used three fixed eight-hour decisions, dual implied-volatility levels, same-sign four-hour returns, and path-efficiency ranks; JVCTR used hourly volatility cooling; RV20 used prior-calendar volatility with liquidation fields.","why_suited_to_volatile_regimes":"daily realized variation must be in its causal upper 35%","why_low_gross9_overlap_is_plausible":"one daily variance-center entry at 00:05 UTC is absent from Gross9"},
 "clock":{"decision":"exact 00:00 UTC D after 24 consecutive source-valid completed BTC hours [D-24h,D)","hourly_return":"log(hour_close/hour_open)","daily_realized_variation":"sqrt(sum of 24 squared hourly returns)","volatility_gate":"strict-prior midrank against at most 180 valid days, minimum 126; rank>=0.65, current excluded","variance_backloading":"sum of squared final-12h returns / sum of squared 24h returns >=0.65","late_direction":"final-six-hour log return nonzero and abs(final6h return)>=0.50*abs(final12h return)","entry":"exact BTCUSDT D+5m open","side":"sign(final6h return)","hold":"12 elapsed hours","reservation":"fixed daily decisions; global half-open, exit first on equal open","funding_oi_implied_vol":"not signal inputs; exact funding only for later PnL","no_imputation":True},
 "policy":{"prior_days":180,"prior_min_days":126,"realized_variation_rank_min":0.65,"final_12h_variance_share_min":0.65,"final_6h_to_12h_abs_return_min":0.50,"entry_delay_minutes":5,"hold_hours":12,"leverage":0.5,"base_cost_per_notional_side":0.0006,"stress_cost_per_notional_side":0.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":0.20,"max_month_share":0.45},"novelty_gates":{"exact_entry_jaccard_max":0.10,"candidate_near_6h_share_max":0.35,"occupied_5m_jaccard_max":0.25,"absolute_signed_exposure_pearson_max":0.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.0,"strict_mdd_max_pct":15.0,"mean_gross_underlying_min_bp":20.0,"weekly_signflip_one_sided_p_max":0.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"completed_hour":"hash-bound historical cache joined to completed-hour PostgreSQL-derived tail through 2026-08-01","execution_price":"sealed until source-support and Gross9 novelty pass"},"diagnostic_controls":{"names":["no_volatility_gate","no_backloading_gate","no_late_dominance_gate","first_six_hour_direction","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"prior_intraday_persistence_candidate_incidence_known":True,"prior_candidate_outcomes_used_to_define_dvbcr":False,"dvbcr_candidate_incidence_opened":False,"dvbcr_post_entry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent daily variance-center mechanism chosen before incidence"},"stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no threshold, side, hold, clock, or subset repair."}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+"\n");print(a.output)
