"""Outcome-blind preregistration for HVCVTP-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
if __package__ in (None,""):
 import sys;sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from training import preregister_high_volatility_bds_nonlinear_dependence_relay as template
DEFAULT_OUTPUT=Path("results/high_volatility_cash_volume_temporal_precedence_relay_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash");c.update(
 protocol_version="high_volatility_cash_volume_temporal_precedence_relay_v1",policy_id="HVCVTP-8",as_of_date="2026-08-13",
 mechanism={"claim":"When the quote-turnover-weighted median minute of Binance BTC spot occurs materially before the simultaneous perpetual weighted median minute, cash participation has arrived earlier in the completed auction and leverage is still transmitting that discovery. During elevated BTC variation, follow the direction agreed by both markets and the final two hours for eight elapsed hours.","side":"common strict sign of completed eight-hour spot and perpetual returns and their final-two-hour returns","why_distinct":"Cash-participation migration compares spot share of combined turnover between fixed four-hour halves. Spot-flow leadership uses aggressive-flow direction, and single-venue turnover-variation lag compares turnover with variance. HVCVTP treats each venue's full 480-minute quote-turnover path as a temporal probability distribution and compares their weighted median arrival times; it uses no flow sign, aggregate participation share, variance centroid, funding, OI, premium, fitted outcome, reused event, or promoted control.","why_suited_to_volatile_regimes":"completed perpetual variation and cash temporal precedence must occupy causal upper tails","why_low_gross9_overlap_is_plausible":"04:05/12:05/20:05 UTC cross-venue volume-arrival onsets are absent from Gross9 clocks"},
 features={"decision_grid":"exact 04:00/12:00/20:00 UTC boundaries D","block":"480 exact aligned unique coherent BTCUSDT one-minute rows from bars_binance_spot and bars_binance over [D-8h,D)","quote_turnover":"finite nonnegative quote_asset_volume each minute with strict-positive eight-hour total separately by venue","weighted_median_minute":"lowest zero-based minute index whose cumulative quote turnover is at least half the venue total","cash_precedence":"perpetual weighted median minute minus spot weighted median minute, finite strict positive","precedence_rank":"strict-prior midrank of positive cash_precedence over at most 270 source-valid positive decisions, minimum 180, current excluded; rank>=0.75","direction_confirmation":"eight-hour and final-two-hour log returns for both spot and perpetual are all strict nonzero with one common sign","perpetual_variation":"sqrt(sum squared 480 perpetual minute log(close/open) returns), finite strict positive","variation_rank":"strict-prior midrank over at most 270 jointly source-valid decisions, minimum 180, current excluded; rank>=0.65","onset":"eligible now and immediately previous scheduled jointly source-valid decision ineligible; missing prior cannot trigger","no_imputation":True},
 clock={"decision":"completed aligned eight-hour boundary D","entry":"exact BTCUSDT perpetual D+5m open","side":"common confirmed market-return sign","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium":"not signal inputs; exact funding only after novelty"},
 policy={"prior_decisions":270,"minimum_prior_decisions":180,"precedence_rank_min":.75,"variation_rank_min":.65,"decision_hours_utc":[4,12,20],"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 source_plan={"spot":{"table":"bars_binance_spot","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"]},"perpetual":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"]},"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration_commit":True,"execution_price":"sealed until source support and Gross9 novelty pass"},
 diagnostic_controls={"names":["no_precedence_tail","no_variation_gate","mean_arrival_precedence","one_decision_stale_precedence","direction_flip","forced_long"],"cannot_be_promoted":True},
 research_boundary={"prior_cash_participation_flow_and_single_venue_timing_outcomes_known":True,"repository_exact_cross_venue_quote_volume_weighted_median_time_precedence_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"reversal_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cross-venue temporal-distribution object selected from formula absence and complete-source metadata only; no prior outcome selected its statistic, side, clock, rank, or hold"},
 stopping_rule="terminal first failure; no venue, volume field, temporal distribution, median, history, rank, variation, confirmation, onset, side, clock, hold, subset, source, or control repair")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVCVTP preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
