"""Outcome-blind preregistration for HVECE-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVECE-8";DEFAULT_OUTPUT=Path("results/high_volatility_execution_count_elasticity_relay_preregistration_2026-08-12.json")
def chash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build():
 core={"protocol_version":"high_volatility_execution_count_elasticity_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-12","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"During elevated BTC variation, an unusually large completed displacement per square-root execution count indicates that limited transaction-processing activity produced disproportionate repricing. Follow the completed direction for eight hours at the fresh elasticity-tail onset.","side":"strict sign of completed eight-hour BTC return","why_distinct":"CAEVC compares cross-asset standardized execution-count response minus path variation; CAIIC divides return by quote turnover and removes an alt median; ticket candidates divide turnover by counts. HVECE is a BTC-only count-normalized endpoint displacement, uses no cross-asset residual, turnover, ticket, flow, funding, OI, prior event, or control.","volatile_market_target":"both completed realized variation and count-normalized displacement must enter independent causal upper tails","why_low_gross9_overlap_is_plausible":"three daily execution-elasticity onsets are absent from Gross9"},
 "features":{"decision_grid":"exact 00:00/08:00/16:00 UTC boundaries D","block":"480 exact coherent BTCUSDT bars_binance one-minute rows [D-8h,D)","execution_count":"sum integer nonnegative number_of_trades over 480 rows, strict positive","completed_return":"log(last close/first open), finite strict nonzero","realized_variation":"sum squared log(close/open) minute returns, finite strict positive","execution_elasticity":"abs(completed_return)/sqrt(execution_count), finite strict positive","elasticity_rank":"strict-prior midrank over at most 270 valid blocks, minimum 180, current excluded; rank>=0.80","variation_rank":"strict-prior 270/180 midrank; current excluded; rank>=0.65","eligible_state":"elasticity and variation gates pass","onset":"eligible now and immediately previous exact source-valid block ineligible","no_imputation":True},
 "clock":{"entry":"D+5m BTCUSDT open","side":"sign completed_return","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact settlements only after novelty"},
 "policy":{"prior_blocks":270,"minimum_prior_blocks":180,"elasticity_rank_min":.80,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_elasticity_tail","no_variation_gate","raw_return_tail","one_block_stale_geometry","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","number_of_trades"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_impact_ticket_and_cross_asset_elasticity_outcomes_known":True,"exact_btc_count_normalized_displacement_candidate_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent BTC-only endpoint displacement per square-root execution count"},
 "stopping_rule":"terminal first failure; no count normalization, rank, onset, side, clock, hold, subset, threshold, or control repair"};return {**core,"manifest_hash":chash(core)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=chash(core) or x!=build():raise RuntimeError("HVECE prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
