"""Outcome-blind preregistration for HVEUO-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVEUO-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_ultimate_oscillator_rate_turn_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_ultimate_oscillator_rate_turn_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, the one-bar rate of change of John Ehlers' 2025 Ultimate Oscillator crossing zero on completed four-hour BTC auctions identifies a near-zero-lag momentum turning point; follow the new rate direction for twenty-four hours.","side":"long when Ultimate Oscillator ROC crosses strictly from nonpositive to positive; short when it crosses strictly from nonnegative to negative","why_distinct":"The Ehlers Ultimate Oscillator is the RMS-normalized difference between two recursive high-pass filters at periods 40 and 20; its one-bar ROC detects turns in that band-limited no-lag signal. It is not the Larry Williams 7/14/28 Ultimate Oscillator, a moving-average crossover, raw return sum, range oscillator, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the published exact turning-point detector must coincide with completed trailing twenty-four-hour realized variation in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse RMS-normalized dual-high-pass rate turns are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, The Ultimate Oscillator, TASC April 2025","source":"https://traders.com/Documentation/FEEDbk_docs/2025/04/TradersTips.html","fixed_definition":"BandEdge=20, Bandwidth=2, recursive high-pass periods 40 and 20, Signal=HP40-HP20, RMS over 100 completed signals, UltimateOsc=Signal/RMS, one-bar ROC zero crossings identify turning points","selection_use":"published defaults, formula, normalization, and ROC turning-point convention only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","high_pass":"published second-order recursive high-pass with c1=(1+c2-c3)/4 at periods 40 and 20","signal":"HP40 minus HP20","rms":"sqrt(mean of squared signal over 100 uninterrupted completed decisions), current included","ultimate_oscillator":"signal divided by finite strict-positive RMS","rate":"current Ultimate Oscillator minus immediately prior finite Ultimate Oscillator","event":"strict finite rate zero crossing from the immediately prior finite rate","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"all recursive and RMS state resets after any invalid completed four-hour bar; output requires 100 uninterrupted signals","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"band_edge":20,"bandwidth":2,"rms_periods":100,"chart_control_band_edge":30,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","chart_30_band_edge","oscillator_zero_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_ultimate_oscillator_definition_read":True,"repository_same_mechanism_candidate_found":False,"classic_larry_williams_ultimate_oscillator_found_and_distinguished":True,"prior_recursive_filter_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published Ehlers Ultimate Oscillator(20,2) one-bar ROC zero crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no period, recursion, initialization, RMS, threshold, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVEUO preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
