"""Outcome-blind preregistration for SPVIR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/spot_participation_volatility_ignition_relay_preregistration_2026-08-08.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"spot_participation_volatility_ignition_relay_v1","policy_id":"SPVIR-6","as_of_date":"2026-08-08","outcomes_opened":False,"source_incidence_opened":False,
 "mechanism":{"claim":"When BTC spot's share of combined Binance spot and USD-M perpetual base volume rises into its causal upper tail, same-direction completed-hour spot and perpetual price movement is cash-sponsored rather than leverage-only. Joint BVOL and DVOL expansion confirms a new volatile price-discovery regime whose direction should relay for six hours.","side":"common sign of completed spot and perpetual returns","why_distinct":"SPVIR uses hourly base-volume participation across cash and perpetual markets. SLVCR required partial price transmission and no participation measure. CSPR used signed flow coherence, execution centroids, and perpetual flow rejection at five-minute resolution. VGSQF used stablecoin quote-book flow topology rather than spot/perpetual participation.","why_low_gross9_overlap_is_plausible":"cash participation share fused with dual crypto implied-volatility ignition is absent from Gross9"},
 "clock":{"decision":"T after completed UTC hour [T-1h,T)","sources":"60 exact BTCUSDT interval=1m rows from bars_binance_spot and bars_binance","participation":"spot base volume/(spot base volume+perpetual base volume), denominator positive","participation_tail":"current share >= strictly-prior 720h q75 with 672 valid observations","direction_agreement":"spot and perpetual hour_close/hour_open-1 have the same nonzero sign","volatility_ignition":"normalized completed-hour BVOL and DVOL bodies are both strictly positive","trigger":"false-to-true onset with prior source-valid consecutive hour","entry":"exact BTCUSDT perpetual T+5m open","side":"common price direction","hold":"6 elapsed hours","reservation":"global half-open, exit first on equal open","funding":"not a signal input; exact settlements only for later PnL","oi_premium_forbidden_as_signal_inputs":True,"no_imputation":True},
 "policy":{"participation_prior_hours":720,"participation_min_hours":672,"participation_quantile":.75,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"hourly_spot_perpetual":{"tables":["bars_binance_spot","bars_binance"],"symbol":"BTCUSDT","interval":"1m","window":["2023-06-01T00:00:00Z","2026-08-01T00:00:00Z"],"columns":["ts","open","close","volume"],"materialize_after_preregistration":True},"volatility":"reuse hash-bound OCDR-12C BVOL/DVOL snapshot","execution_price":"sealed until source-support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_joint_expansion","no_participation_tail","no_direction_agreement","one_hour_stale_participation","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"prior_spot_perpetual_family_outcomes_known":True,"prior_candidate_outcomes_used_to_define_spvir":False,"spvir_candidate_incidence_opened":False,"spvir_post_entry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no repair"};return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2,ensure_ascii=False)+"\n");print(a.output)
