"""Outcome-blind preregistration for HVEFD-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVEFD-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_deviation_scaled_fisher_reentry_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_deviation_scaled_fisher_reentry_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' Fisherized deviation-scaled oscillator returning inward through its published +/-2 extremes on completed four-hour BTC auctions identifies a standardized swing beginning to mean-revert; follow the inward direction for twenty-four hours.","side":"long when finite FisherFilt crosses strictly above -2 from at or below -2; short when it crosses strictly below +2 from at or above +2","why_distinct":"The oscillator whitens close with a two-decision difference, SuperSmooths at half a 40-period cycle, scales by a 40-decision RMS, and applies a bounded Fisher transform before extreme reentry. It is not a range Fisher Transform, RSI/CCI reentry, moving-average crossover, raw return sum, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"a standardized tail excursion must begin reverting while completed trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse Fisherized whitened-spectrum extreme reentries are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Probability—Probably A Good Thing To Know, Fisherized Deviation Scaled Oscillator, TASC October 2018","source":"https://traders.com/Documentation/FEEDbk_docs/2018/10/TradersTips.html","fixed_definition":"Period=40; Zeros=Close-Close[2]; SuperSmoother critical period=20; RMS over 40 filtered values; ScaledFilt=Filt/RMS; Fisher=.5*log((1+ScaledFilt/2)/(1-ScaledFilt/2)) for abs(ScaledFilt)<2; overbought=2 and oversold=-2; inward crossings","selection_use":"published default period, formula, thresholds, and entry direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","zeros":"completed close minus its two-decision lag","filtered":"published 20-period SuperSmoother of zeros","scaled":"filtered value divided by strict-positive RMS over 40 uninterrupted filtered decisions","fisher":"published half-log Fisher transform, finite only for abs(scaled)<2","event":"strict inward crossing of -2 or +2 from the immediately prior finite Fisher value","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"all lag, recursive, and RMS state resets after any invalid completed four-hour bar; event requires uninterrupted finite current and prior Fisher values","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"periods":40,"smoother_periods":20,"overbought":2.0,"oversold":-2.0,"raw_scaled_equivalent":1.9280551601516338,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","unfisherized_equivalent_reentry","one_bar_stale_reentry","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_fisherized_deviation_scaled_oscillator_definition_read":True,"repository_same_mechanism_candidate_found":False,"prior_fisher_range_transform_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published Ehlers FDSO(40) +/-2 inward reentry under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no period, recursion, RMS, transform, threshold, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVEFD preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
