"""Outcome-blind preregistration for HVCASPCVAIV-8."""
from __future__ import annotations
import argparse,copy,json
from pathlib import Path
from training import preregister_high_volatility_caspc_ehlers_cross_venue_resolution_router as template
POLICY_ID='HVCASPCVAIV-8';DEFAULT_OUTPUT=Path('results/high_volatility_caspc_variance_acceleration_inventory_opposite_veto_preregistration_2026-08-17.json');canonical_hash=template.canonical_hash;sha=template.sha;VAI={'preregistration':{'path':'results/high_volatility_causal_variance_acceleration_inventory_relay_preregistration_2026-08-16.json','sha256':'8cf94eac46378a61a737f3ef857e07b3e728cb150ce3a24b6ae10f0e9839ac64'},'support':{'path':'results/high_volatility_causal_variance_acceleration_inventory_relay_support_2026-08-16.json','sha256':'b45760985d3c9094333c6d4c58400c24488cbe0d8a48fb235a8118306442f649'},'gross9':{'path':'results/high_volatility_causal_variance_acceleration_inventory_relay_gross9_novelty_2026-08-16.json','sha256':'c60537536ecda6303e88253f0b8537782c229a55ae368c5b50d1df99d69f6f8a'},'clock':{'path':'data/high_volatility_causal_variance_acceleration_inventory_relay_clocks_2020_2026.csv.gz','sha256':'86f7e4f3b7624396b5a39be132b3c1630087648fbabf2d38a6604863e21b507c'}}
BASE={'preregistration':{'path':'results/high_volatility_cross_alt_serial_persistence_consensus_relay_preregistration_2026-08-13.json','sha256':'be77dfa8d83dfcb54171da4cf3263c57336fc629dd8f7b63ff8e8b33a860784a'},'support':{'path':'results/high_volatility_cross_alt_serial_persistence_consensus_relay_support_2026-08-13.json','sha256':'53f401d5ab9a499838c128b7023b4e420925455ca7e858e5a4db5c6e4f83d52e'},'gross9':{'path':'results/high_volatility_cross_alt_serial_persistence_consensus_relay_gross9_novelty_2026-08-13.json','sha256':'61c7fe10f3b331528315e8d7625aff7c8fb8ff1c82b6c553aa34f19ad89832f3'},'clock':{'path':'data/high_volatility_cross_alt_serial_persistence_consensus_relay_clocks_2023_2026.csv.gz','sha256':'bffadb70bea5d96fc779c641dbe3a1f50ba94fdf76a4e950d778a32a2b64b085'}}
def build():
 v=copy.deepcopy(template.build());v.pop('manifest_hash');v['protocol_version']='high_volatility_caspc_variance_acceleration_inventory_opposite_veto_v1';v['policy_id']=POLICY_ID;v['candidate_family']=[POLICY_ID];v['base_artifacts']=BASE
 v['construction']={'base':'immutable HVCASPC-8 event times, side, entry and hold','veto_component':'frozen source-and-Gross9-passed HVCVARIR-8 clock','active_join':'unique HVCVARIR entry<=HVCASPC entry<HVCVARIR exit; timestamp tolerance none','veto':'active opposite HVCVARIR side emits cash; same side or no active HVCVARIR keeps immutable HVCASPC side','multiple_active':'hard failure','activation_gate':'at least one opposite veto in train and at least three over all splits','additional_or_tuned_thresholds':'none','entry':'immutable HVCASPC D+5m','hold':'8 elapsed hours'}
 v['mechanism']={'claim':'Cross-alt serial persistence should be withheld when a causally active variance-acceleration inventory state points oppositely, because fresh leveraged variance expansion contradicts continuation direction.','why_low_gross9_overlap_is_plausible':'a sparse asynchronous variance-acceleration inventory veto subsets HVCASPC incidence independently of Gross9'}
 v['research_boundary']={'HVCASPC_train_pass_test_fail_known':True,'prior_HVCASPCCVDRV_train_stress_failure_known':True,'HVCVARIR_train_failure_known':True,'exact_HVCASPC_HVCVARIR_veto_incidence_or_outcomes_known':False,'source_incidence_opened':False,'postentry_return_or_pnl_opened':False,'classification':'exploratory discovery; not fresh confirmatory evidence','repair_of_prior_candidate':False,'selection_basis':'opposite variance-acceleration plus OI inventory direction as an independent veto on the immutable CASPC base'}
 v['stopping_rule']='source support including activation, Gross9, train/test/eval/final; stop first failure; no join, veto, base, component, side, clock, hold, substitution, or control repair.'
 return {**v,'manifest_hash':canonical_hash(v)}
def validate(v):
 if v['manifest_hash']!=canonical_hash({k:x for k,x in v.items() if k!='manifest_hash'}):raise RuntimeError('manifest drift')
 for arts in (BASE,VAI):
  for a in arts.values():
   if sha(a['path'])!=a['sha256']:raise RuntimeError('component drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2)+"\n");print(a.output)
