"""Outcome-blind preregistration for HVCSER-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path('results/high_volatility_corwin_schultz_spread_expansion_reversal_preregistration_2026-08-10.json')
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  'protocol_version':'high_volatility_corwin_schultz_spread_expansion_reversal_v1','policy_id':'HVCSER-12','as_of_date':'2026-08-10','outcomes_opened':False,'source_incidence_opened':False,'gross9_rows_opened':False,'singleton':True,
  'mechanism':{'claim':'At the completed 21:00 UTC crypto settlement day, an upper-tail expansion in the Corwin-Schultz two-day OHLC-implied bid-ask spread identifies a transitory liquidity-cost shock. In a high realized-variation state, fade the completed one-day BTC displacement for twelve hours.','side':'negative strict sign of the completed 24-hour return','why_distinct':'HVCSER estimates latent spread from the joint algebra of two adjacent daily high-low ranges and their combined two-day range. AARMR measures one-hour interval overlap, RBEFR compares intrabar range to candle bodies, HVLIR divides hourly return by turnover, and HVSAR uses serial return dependence. No prior event set, control, volume, flow, funding, OI, premium, or external asset is reused.','why_suited_to_volatile_regimes':'both completed 24-hour realized variation and positive Corwin-Schultz spread expansion must be causal upper-tail states','why_low_gross9_overlap_is_plausible':'a sparse 21:05 UTC latent-spread expansion clock is absent from Gross9 primitives'},
  'features':{'decision':'daily exact 21:00 UTC','daily_windows':'two adjacent exact 24-hour windows [D-48h,D-24h) and [D-24h,D), each from 1,440 exact coherent one-minute BTCUSDT bars','daily_high_low':'maximum high and minimum low in each completed window; all strict positive','beta':'log(H1/L1)^2 + log(H2/L2)^2','gamma':'log(max(H1,H2)/min(L1,L2))^2','alpha':'(sqrt(2*beta)-sqrt(beta))/(3-2*sqrt(2)) - sqrt(gamma/(3-2*sqrt(2))); require finite','implied_spread':'2*(exp(max(alpha,0))-1)/(1+exp(max(alpha,0))); finite','spread_expansion':'current implied spread minus the immediately prior valid decision implied spread; strict positive','spread_expansion_rank':'strict-prior midrank over at most 90 previous valid expansions, minimum 60, current excluded; rank>=0.70','realized_variation':'sqrt(sum squared log(close/open) over the current completed 24-hour window)','variation_rank':'strict-prior midrank over at most 90 previous valid days, minimum 60, current excluded; rank>=0.65','completed_return':'log(last close/first open) over current window; strict nonzero','no_imputation':True},
  'clock':{'decision':'exact daily 21:00 UTC after both OHLC windows complete','entry':'exact BTCUSDT decision+5m open','hold':'12 elapsed hours','reservation':'fixed daily decisions; global half-open, exit first on equal open','split_crossing_action':'skip','gross_exposure':.5,'funding_oi_premium_rv20':'not signal inputs; exact funding only after novelty; RV20 q90 only after all stages pass'},
  'policy':{'prior_days':90,'minimum_prior_days':60,'spread_expansion_rank_min':.70,'variation_rank_min':.65,'entry_delay_minutes':5,'hold_hours':12,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
  'stages':{'train':['2023-07-01T00:00:00Z','2024-01-01T00:00:00Z'],'test':['2024-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'eval':['2025-01-01T00:00:00Z','2026-01-01T00:00:00Z'],'final':['2026-01-01T00:00:00Z','2026-08-01T00:00:00Z']},
  'source_support_gates':{'minimum_events':{'train':8,'test':12,'eval':12,'final':8},'minority_side_share_min':.2,'max_month_share':.45},
  'novelty_gates':{'exact_entry_jaccard_max':.1,'candidate_near_6h_share_max':.35,'occupied_5m_bar_jaccard_max':.25,'absolute_signed_exposure_pearson_max':.35,'must_pass_before_economics':True},
  'economic_gates':{'absolute_return_positive':True,'cagr_to_strict_mdd_min':3.,'strict_mdd_max_pct':15.,'mean_gross_underlying_min_bp':20.,'weekly_signflip_one_sided_p_max':.1,'stress_absolute_return_positive':True,'stress_cagr_to_strict_mdd_min':2.5,'each_calendar_half_positive':True,'stop_on_first_failure':True,'future_can_rank_repair_or_reselect':False,'accounting':'fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR'},
  'source_plan':{'btc':{'table':'bars_binance','symbol':'BTCUSDT','interval':'1m','columns':['ts','open','high','low','close'],'window':['2023-03-30T21:00:00Z','2026-08-01T00:00:00Z'],'read_after_preregistration':True},'execution_price':'sealed until source support and Gross9 novelty pass'},
  'diagnostic_controls':{'names':['no_spread_expansion_gate','no_volatility_gate','raw_positive_expansion','one_day_stale_expansion','direction_flip'],'diagnostic_controls_cannot_be_promoted':True},
  'research_boundary':{'database_metadata_only_opened_before_preregistration':True,'corwin_schultz_values_or_incidence_opened':False,'postentry_return_or_pnl_opened':False,'gross9_rows_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False,'promoted_prior_control':False,'selection_basis':'independent two-day latent bid-ask-spread expansion mechanism'},
  'stopping_rule':'Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no estimator, threshold, side, hold, clock, window, subset, or control repair.'}
 return {**core,'manifest_hash':canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!='manifest_hash'}
 if x.get('manifest_hash')!=canonical_hash(core) or x!=build():raise RuntimeError('HVCSER preregistration drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();a.output.write_text(json.dumps(x,indent=2)+'\n');print(a.output)
