"""Outcome-blind preregistration for HVAFC-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVAFC-8";DEFAULT_OUTPUT=Path("results/high_volatility_adverse_funding_contraction_relay_preregistration_2026-08-13.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_adverse_funding_contraction_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-13",
 mechanism={"claim":"After an actual extreme BTC perpetual funding settlement, a completed four-hour price move opposite the funding sign accompanied by open-interest contraction is adverse crowd liquidation rather than carry collection; during elevated variation, follow the deleveraging direction for eight elapsed hours.","side":"strict sign of the completed post-settlement four-hour BTC return, necessarily opposite the funding-rate sign","why_distinct":"HVAFC combines the exact settled funding polarity with subsequent endpoint OI contraction and adverse price displacement. Funding-volatility unwind conditions on pre-settlement alignment and post-settlement volatility reset without OI; OI purge ignores funding; funding/OI rotation uses premium state. HVAFC uses no cross-alt spread, fitted outcome, prior event, or control.","why_suited_to_volatile_regimes":"absolute settled funding and completed post-settlement variation must occupy causal upper regimes while falling OI proves inventory exit","why_low_gross9_overlap_is_plausible":"actual funding timestamps delayed four hours by adverse price/OI confirmation are absent from Gross9 primitives"},
 features={"event":"actual Binance BTCUSDT USD-M funding settlement S with finite strict-nonzero rate known at S","funding_extremeness":"strict-prior midrank of abs(rate) over at most 270 earlier settlements, minimum 180, current excluded; rank>=0.65","price_window":"48 exact coherent five-minute perpetual bars [S,S+4h)","post_settlement_return":"log(last close/first open), strict nonzero and sign=-sign(funding rate)","oi_path":"49 exact positive period=5m OI observations S through S+4h","oi_contraction":"log(OI[S+4h]/OI[S])<0","variation":"sqrt(sum squared 48 five-minute log(close/open) returns), finite strict positive","variation_rank":"strict-prior midrank over at most 270 earlier jointly source-valid settlement windows whose S+4h availability precedes current S+4h, minimum 180, current excluded; rank>=0.65","eligibility":"funding extreme, adverse price direction, OI contraction, and variation gate","no_imputation":True},
 clock={"feature_available":"S+4h after all price and OI observations complete","entry":"exact BTCUSDT S+4h+5m open","side":"post-settlement return direction","hold":"8 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":0.5,"funding":"current settlement precedes entry and is not earned; later exact settlements only after novelty passes"},
 policy={"price_bars":48,"window_hours":4,"history_events":270,"minimum_history_events":180,"funding_rank_min":0.65,"variation_rank_min":0.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":0.5,"base_cost_per_notional_side":0.0006,"stress_cost_per_notional_side":0.001},
 diagnostic_controls={"names":["no_funding_rank_gate","no_variation_gate","no_oi_contraction","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"funding":{"table":"funding_rates_binance","symbol":"BTCUSDT","columns":["funding_time","funding_rate"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","same_window_plus_4h":True,"read_after_preregistration":True},"open_interest":{"table":"open_interest_binance","symbol":"BTCUSDT","period":"5m","same_window_plus_4h":True,"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"actual_funding_adverse_oi_contraction_selected":True,"repository_exact_adverse_funding_contraction_candidate_found":False,"adjacent_funding_unwind_oi_purge_and_premium_rotation_candidates_known":True,"adjacent_candidate_outcomes_used_to_set_formula_side_hold_clock_or_threshold":False,"prior_event_sets_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"actual funding polarity followed by four-hour adverse return and endpoint OI contraction under elevated variation"},
 stopping_rule="Terminal first failure; no funding rank, window, OI definition, variation rank, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v:dict[str,Any])->None:
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVAFC preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
