"""Outcome-blind preregistration for HVCAVSC-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVCAVSC-8";SLUG="high_volatility_cross_alt_volume_shock_consensus_relay";ALTS=("ADAUSDT","BNBUSDT","DOGEUSDT","ETHUSDT","SOLUSDT","XRPUSDT");DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":f"{SLUG}_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"A simultaneous own-history quote-turnover shock across at least four liquid alt perpetuals, accompanied by one common completed five-minute return direction, identifies broad information participation rather than an isolated price print. During elevated BTC variation, follow the confirmed participation direction in BTC for eight hours.","side":"common strict return sign among at least four volume-shocked alts","why_distinct":"HVCACJP thresholds return magnitude and HVCABBD thresholds price-region discovery. Return-turnover concordance compares block-level cross-sectional ranks. HVCAVSC instead thresholds each alt's current five-minute quote turnover against its own strictly prior 30-day distribution, then uses return sign only for direction; it uses no BTC return direction, flow imbalance, value anchor, funding, OI, premium, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"causal trailing BTC twenty-four-hour realized variation must occupy its upper 35 percent","why_low_gross9_overlap_is_plausible":"irregular simultaneous cross-alt own-history participation shocks are absent from Gross9 primitives"},
 "features":{"decision_grid":"every exact UTC five-minute boundary D","five_minute_bar":"five exact coherent native one-minute bars [D-5m,D) per symbol","alt_return":"log(last completed close/first completed open), finite strict nonzero for a directional shocked alt","alt_quote_turnover":"sum quote_asset_volume over the completed five-minute bar, finite strict positive","turnover_history":"8640 strictly prior source-valid five-minute observations per alt (30 days), current excluded; minimum 6048","turnover_threshold":"numpy-linear strict-prior 0.95 quantile independently per alt","volume_shock":"current turnover>=own threshold","directional_consensus":"at least four shocked alts have one common strict return sign and strictly outnumber opposite shocked signs","btc_realized_variation":"sqrt(sum squared exact BTC one-minute log(close/open) returns over [D-24h,D)), finite strict positive","variation_history":"at most 8640 strictly prior source-valid decisions, minimum 6048, current excluded","variation_rank":"strict-prior midrank; rank>=0.65","onset":"full broad volume-shock direction exists now and did not exist at immediately prior exact source-valid five-minute decision; missing prior cannot trigger","no_imputation":True},
 "clock":{"decision":"D immediately after all seven completed five-minute bars are available","entry":"exact BTCUSDT perpetual D+5m open","side":"common shocked-alt return direction","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements only after novelty"},
 "policy":{"turnover_history_bars":8640,"minimum_turnover_history_bars":6048,"turnover_quantile":.95,"variation_bars":288,"variation_history_decisions":8640,"minimum_variation_history_decisions":6048,"minimum_consensus_breadth":4,"variation_rank_min":.65,"onset_required":True,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","three_of_six_volume_shock","equal_weight_market_turnover_shock","one_bar_stale_shock","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"table":"bars_binance","symbols":["BTCUSDT",*ALTS],"interval":"1m","columns":["ts","symbol","open","high","low","close","quote_asset_volume"],"window":["2023-05-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration_commit":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_volume_flow_cojump_and_cross_alt_outcomes_known":True,"repository_exact_cross_alt_own_history_volume_shock_consensus_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent irregular cross-sectional participation-shock confirmation"},
 "stopping_rule":"terminal first failure; no universe, bar, turnover, history, quantile, breadth, variation, onset, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}) or x!=build():raise RuntimeError("HVCAVSC prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_bytes(b);print(a.output)
