"""Outcome-blind preregistration for HVTVLR-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVTVLR-8";DEFAULT_OUTPUT=Path("results/high_volatility_turnover_variation_lag_relay_preregistration_2026-08-10.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_turnover_variation_lag_relay_v1",policy_id=POLICY_ID,
 mechanism={"claim":"When the time centroid of completed quote turnover lies materially after the time centroid of realized variation, participation is arriving to sponsor rather than initiate a volatile displacement. At a new upper-tail positive lag with consistent full-block and final-two-hour direction, follow the accepted direction for eight hours.","side":"common strict sign of completed eight-hour and final-two-hour BTC returns","why_distinct":"Daily late-volume continuation uses a terminal calendar bucket, variance backloading uses fixed halves, HVTLRR estimates turnover-to-next-return correlation, and cross-venue torsion compares Spot and perpetual centroids within five-minute buckets. HVTVLR directly compares continuous within-BTC eight-hour turnover and squared-return time centroids and reuses no prior event or control.","why_suited_to_volatile_regimes":"the completed BTC variation rank must be in its upper 35%, while positive lag requires participation to arrive after the price-energy center","why_low_gross9_overlap_is_plausible":"offset three-daily turnover-versus-variation timing onsets are absent from Gross9 primitives"},
 features={"decision_grid":"exact 07:00/15:00/23:00 UTC boundaries","block":"480 exact coherent bars_binance BTCUSDT one-minute rows [D-8h,D)","time_coordinate":"minute index divided by 479, from zero through one","turnover_centroid":"sum(time_coordinate*quote_asset_volume)/sum(quote_asset_volume), denominator strict positive","variation_centroid":"sum(time_coordinate*minute_log_return^2)/sum(minute_log_return^2), denominator strict positive","timing_lag":"turnover_centroid-variation_centroid, finite and strict positive","lag_rank":"strict-prior midrank over at most 270 earlier source-valid blocks, minimum 180, current excluded; rank>=0.75","realized_variation":"sum squared one-minute log(close/open) returns, finite strict positive","variation_rank":"strict-prior 270/180 midrank, current excluded; rank>=0.65","block_return":"log(last close/first open), finite strict nonzero","final_two_hour_return":"same formula over final 120 completed minutes, finite strict nonzero and same sign as block_return","eligible_state":"positive lag, lag-rank, variation-rank, and directional agreement gates pass","onset":"eligible now and immediately previous exact source-valid block ineligible; missing prior cannot trigger","no_imputation":True},
 clock={"decision":"completed eight-hour boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_blocks":270,"minimum_history_blocks":180,"lag_rank_min":.75,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_lag_tail","no_variation_gate","fixed_half_backloading","one_boundary_stale_geometry","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"prior_timing_volume_variation_and_response_outcomes_known":True,"repository_turnover_variation_centroid_lag_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_rank_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"continuous participation-after-variation timing geometry"},
 stopping_rule="Terminal first failure; no centroid, lag sign, rank, direction, hold, clock, subset, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVTVLR preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
