"""Outcome-blind preregistration for SHRR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/scandinavian_haven_risk_rotation_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"scandinavian_haven_risk_rotation_relay_v1","policy_id":"SHRR-12","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
  "mechanism":{"claim":"A completed European-session rotation in which the cyclical Swedish krona weakens while the Swiss franc and Japanese yen strengthen measures broad risk-off pressure with the common dollar component directionally cancelled. In a high-variation BTC regime, risk-off pressure maps short BTC and risk-on relief maps long BTC for twelve hours.","side":"negative strict sign of the three-leg risk-pressure median","why_distinct":"SHRR introduces USDSEK and combines one cyclical currency with two haven currencies under opposite score orientations. HVDBR measured common six-pair dollar breadth, DFSR a signed dollar factor, SERBR GBP-minus-EUR regional beta, and MXRBR one EM currency; all are terminal and no event set or control is reused.","why_suited_to_volatile_regimes":"BTC completed prior-24h realized variation must rank in its causal upper 35%.","why_low_gross9_overlap_is_plausible":"one sparse weekday 16:05 UTC external risk-rotation clock is absent from Gross9 primitives."},
  "features":{"fx_session":"bars_polygon interval=1m rows for USDSEK, USDCHF, and USDJPY with 08:00<=UTC time<16:00 on one UTC weekday","fx_session_valid":"each pair has at least 450 distinct minutes, first timestamp no later than 08:05, last no earlier than 15:55, finite positive OHLC; no imputation","pair_zscores":"each session log return standardized against its own at most 90 strictly prior valid sessions, minimum 60, current excluded; prior sample std positive","risk_scores":"USDSEK z-score, negative USDCHF z-score, and negative USDJPY z-score; positive means risk-off","risk_pressure":"cross-sectional median of all three finite risk scores; strict nonzero","risk_pressure_rank":"strict-prior midrank of absolute risk_pressure over at most 90 prior valid sessions, minimum 60, current excluded; rank>=0.70","btc_realized_variation":"sqrt(sum squared completed-hour BTC log returns over 24 hours ending at decision)","volatility_rank":"strict-prior midrank over at most 90 valid decision days, minimum 60, current excluded; rank>=0.65","no_imputation":True},
  "clock":{"decision":"exact weekday D 16:00 UTC after FX session and BTC variation complete","entry":"exact BTCUSDT D 16:05 UTC open","side":"negative strict sign of risk_pressure","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","funding_oi_premium":"not signal inputs; exact funding only after novelty passes"},
  "policy":{"fx_prior_sessions":90,"fx_prior_min_sessions":60,"risk_pressure_rank_min":.70,"realized_variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "source_plan":{"fx":{"table":"bars_polygon","symbols":["USDSEK","USDCHF","USDJPY"],"interval":"1m","window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"materialize_after_preregistration":True},"completed_btc":"hash-bound completed-hour BTC source through 2026-08-01 for pre-entry variation only","execution_price":"sealed until source-support and Gross9 novelty pass"},
  "diagnostic_controls":{"names":["no_volatility_gate","no_risk_pressure_tail","no_haven_orientation","one_session_stale_risk_pressure","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
  "research_boundary":{"database_metadata_only_opened_before_preregistration":True,"fx_values_used_to_select_rule":False,"prior_fx_family_outcomes_known":True,"prior_fx_candidate_outcomes_used_to_set_shrr_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cyclical-versus-haven FX risk-rotation channel"},
  "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no symbols, orientation, session, pressure definition, rank, side, hold, clock, volatility, or subset repair."
 };return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+"\n");print(a.output)
