"""Outcome-blind preregistration for HVELRSIPSC-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVELRSIPSC-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_laguerre_rsi_premium_sponsorship_reentry_relay_preregistration_2026-08-16.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_laguerre_rsi_premium_sponsorship_reentry_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-16",
 mechanism={"claim":"During elevated realized variation, John Ehlers' four-element Laguerre RSI returning inside its conventional 0.2/0.8 envelope on completed four-hour BTC auctions marks a fast one-sided close-price excursion beginning to normalize; when the completed four-hour BTC perpetual premium displacement agrees with that re-entry side, follow the sponsored re-entry direction for twenty-four hours.","side":"long when Laguerre RSI crosses strictly above 0.2 after being at or below 0.2; short when it crosses strictly below 0.8 after being at or above 0.8","why_distinct":"The oscillator recursively warps close-price time through four Laguerre states before accumulating ordered state differences. HVELRSIPSC adds only exact decision-available same-block BTC perpetual premium displacement concordance; it does not use a fixed rolling close-return window, range location, high/low expansion, volume, OI, flow, funding, fitted outcomes, prior events, or a promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%, while same-direction premium displacement identifies derivative sponsorship","why_low_gross9_overlap_is_plausible":"the conjunction of sparse Laguerre-state re-entry and same-block premium displacement concordance is absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Time Warp—Without Space Travel / Cybernetic Analysis for Stocks and Futures","source":"https://www.mesasoftware.com/papers/TimeWarp.pdf","fixed_definition":"close input; gamma 0.5; L0=(1-gamma)*close+gamma*prior L0; L1=-gamma*L0+prior L0+gamma*prior L1, repeated through L3; CU and CD sum the positive and negative ordered differences L0-L1, L1-L2, L2-L3; ratio CU/(CU+CD); conventional 0.2/0.8 envelope","selection_use":"published input, gamma, recursion, ratio, levels, and direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","laguerre_initialization":"after an invalid gap initialize L0=L1=L2=L3 to the first valid completed bar close; that bar has zero denominator and no oscillator value","laguerre_rsi":"causal four-state Ehlers recursion at gamma 0.5, then CU/(CU+CD), invalid at zero denominator","reentry":"current ratio strictly crosses inward through 0.2 or 0.8 from immediately prior valid ratio","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","premium_block":"240 exact unique coherent BTCUSDT bars_binance_premium interval=1m rows [T-4h,T); finite signed OHLC","premium_displacement":"last completed premium close minus first completed premium open; strict nonzero","premium_sponsorship":"sign(premium_displacement) equals the frozen Laguerre RSI re-entry side","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"gamma":.5,"lower_level":.2,"upper_level":.8,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_premium_sponsorship_gate","no_variation_gate","outward_crossing","one_bar_stale_reentry","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"premium":{"table":"bars_binance_premium","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_laguerre_rsi_definition_read":True,"repository_laguerre_rsi_candidate_found":False,"prior_oscillator_outcomes_known":True,"base_hvelrsi_train_pass_test_fail_known":True,"exact_hvelrsi_premium_intersection_incidence_or_outcomes_known":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published Ehlers Laguerre RSI re-entry with causal premium displacement sponsorship"},
 stopping_rule="Terminal first failure; no gamma, initialization, recursion, level, crossing, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVELRSIPSC preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
