"""Outcome-blind preregistration for HVDVTM-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVDVTM-8";DEFAULT_OUTPUT=Path("results/high_volatility_directional_variation_timing_migration_relay_preregistration_2026-08-10.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_directional_variation_timing_migration_relay_v1",policy_id=POLICY_ID,
 mechanism={"claim":"Within a volatile completed BTC block, the direction whose squared-return energy has a materially later time centroid is the direction in which price discovery is migrating. Follow that late-arriving directional energy for eight hours.","side":"strict sign of positive-return variation centroid minus negative-return variation centroid","why_distinct":"Semivariance imbalance compares total positive versus negative squared mass; temporal variance ignition compares unsigned energy in fixed halves; turnover-variation lag compares activity and unsigned variation centroids. HVDVTM compares continuous time centroids of positive and negative squared-return energy, with no endpoint gate, volume, flow, funding, OI, cross-asset, prior event, fitted outcome, or control.","why_suited_to_volatile_regimes":"completed total variation must rank in its causal upper 35% while directional energy timing separation enters its upper 30%","why_low_gross9_overlap_is_plausible":"offset three-daily signed variation-centroid migration onsets are absent from Gross9 primitives"},
 features={"decision_grid":"exact 06:00/14:00/22:00 UTC boundaries","block":"480 exact coherent bars_binance BTCUSDT one-minute rows [D-8h,D)","minute_return":"log(close/open), finite","time_coordinate":"minute index divided by 479, from zero through one","positive_variation_centroid":"sum(time*r^2 for r>0)/sum(r^2 for r>0), strict positive denominator","negative_variation_centroid":"sum(time*r^2 for r<0)/sum(r^2 for r<0), strict positive denominator","directional_timing_contrast":"positive centroid minus negative centroid, finite strict nonzero","timing_rank":"strict-prior midrank of abs(directional_timing_contrast) over at most 270 earlier source-valid blocks, minimum 180, current excluded; rank>=0.70","realized_variation":"sqrt(sum squared minute returns), finite strict positive","variation_rank":"strict-prior 270/180 midrank, current excluded; rank>=0.65","eligible_state":"timing and variation gates pass","onset":"eligible now and immediately previous exact source-valid block ineligible; missing prior cannot trigger","no_imputation":True},
 clock={"decision":"completed eight-hour boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_blocks":270,"minimum_history_blocks":180,"timing_rank_min":.70,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_timing_tail","no_variation_gate","directional_variation_mass_asymmetry","one_block_stale_timing","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"prior_semivariance_variance_timing_and_turnover_centroid_outcomes_known":True,"repository_directional_variation_timing_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_rank_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"relative arrival time of positive and negative squared-return energy"},
 stopping_rule="Terminal first failure; no energy definition, centroid, rank, onset, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVDVTM preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
