"""Outcome-blind preregistration for HVRSAR-8."""
from __future__ import annotations
import argparse, copy, hashlib, json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template

POLICY_ID="HVRSAR-8"
DEFAULT_OUTPUT=Path("results/high_volatility_rogers_satchell_excursion_asymmetry_reversal_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_rogers_satchell_excursion_asymmetry_reversal_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated completed Rogers-Satchell variation, an unusually one-sided decomposition of the estimator into upper and lower open/close-adjusted excursion energy marks asymmetric rejection. Fade the dominant excursion side for eight hours.","side":"short when summed upper RS energy exceeds summed lower RS energy; long on the strict reverse","why_distinct":"Raw wick imbalance subtracts candle shadows, range traversal uses extreme ordering, and drawup/drawdown asymmetry follows path-ordered extrema. HVRSAR aggregates six canonical logarithmic Rogers-Satchell upper and lower products, normalizes their difference by total RS energy, and uses no volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the total completed RS estimator must rank in its causal upper 35% and absolute directional decomposition in its upper quartile","why_low_gross9_overlap_is_plausible":"offset four-hour open/close-adjusted range-energy asymmetry onsets are absent from Gross9 primitives"},
 external_basis={"origin":"Rogers-Satchell volatility; QuantConnect LEAN canonical implementation","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/RogersSatchellVolatility.cs","definition_source_sha256":"94817a73e8c5dfa323860a841cc67a86d3b9540427542f7bdfa6a5deb9af3fff","documentation_source":"https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/rogers-satchell-volatility","fixed_definition":"per bar upper=ln(H/C)*ln(H/O), lower=ln(L/C)*ln(L/O), RS=sqrt(mean(upper+lower)); valid strict positive OHLC","selection_use":"official estimator and its additive upper/lower terms only; directional fade and 24h aggregation are explicitly untested adaptations; no incidence or outcomes"},
 features={"decision_grid":"every completed four-hour BTCUSDT bar","window":"latest six exact coherent four-hour bars, twenty-four completed hours","upper_energy":"sum ln(high/close)*ln(high/open)","lower_energy":"sum ln(low/close)*ln(low/open)","rs_variation":"sqrt((upper_energy+lower_energy)/6), finite strict positive","excursion_asymmetry":"(upper_energy-lower_energy)/(upper_energy+lower_energy), finite strict nonzero","variation_rank":"strict-prior midrank over at most 270 earlier source-valid decisions, minimum 180, current excluded; rank>=0.65","asymmetry_rank":"strict-prior midrank of abs(excursion_asymmetry) on the same 270/180 basis; rank>=0.75","eligible_state":"both ranks pass and excursion_asymmetry is strict nonzero","onset":"eligible now and immediately previous exact source-valid decision ineligible; missing prior cannot trigger","recursive_reset":"six-bar windows and both rank histories reset after any invalid four-hour bar","no_imputation":True},
 clock={"feature_available":"completed four-hour boundary","entry":"exact BTCUSDT boundary+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"bars":6,"variation_history_decisions":270,"minimum_variation_history_decisions":180,"variation_rank_min":.65,"asymmetry_rank_min":.75,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_asymmetry_tail","no_variation_gate","latest_bar_asymmetry","one_bar_stale_onset","direction_follow","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_price":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_rogers_satchell_definition_read":True,"repository_rogers_satchell_asymmetry_candidate_found":False,"prior_wick_range_and_ordered_excursion_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical additive Rogers-Satchell upper/lower energy decomposition under the requested volatile regime"},
 stopping_rule="Terminal first failure; no RS window, decomposition, ranks, side, hold, clock, subset, threshold, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVRSAR-8 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
