"""Outcome-blind preregistration for ECVDR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any

DEFAULT_OUTPUT=Path("results/equity_commodity_volatility_divergence_relay_preregistration_2026-08-09.json")
SOURCES={"vix_panel":{"path":"data/cboe_volatility_surface_2021_2026/cboe_volatility_surface_2021-01-01_2026-08-07.csv.gz","sha256":"42eb1093f5167aec9c71a4733ab3451e40807c81dc7cb49568a6a0c634267ba0"},"vxn":{"path":"data/cboe_vxn_2021_2026/source/VXN_History.csv","sha256":"a856a08bbec6c5fabd23c98d4b75bc28b93c24370ef8780e3e75243c22f66716"},"gvz":{"path":"data/cboe_gvz_2021_2026/source/GVZ_History.csv","sha256":"eaf949af798669fb6a0d5eb0ee5a3d148a9f2abf4679450e7a9d85c6a5e1bcbb"},"ovx":{"path":"data/cboe_ovx_2021_2026/source/OVX_History.csv","sha256":"77f872f1e069cc93554fe6d80dc6f9d44d0a798ad0a906202a570ad81f73417a"}}
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"equity_commodity_volatility_divergence_relay_v1","policy_id":"ECVDR-12","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
 "mechanism":{"claim":"When VIX and VXN move together while GVZ and OVX move together in the opposite direction, the common equity-volatility sign isolates financial-risk repricing from commodity uncertainty. In high BTC variation, BTC follows equity risk appetite for twelve hours.","side":"short BTC when VIX and VXN changes are strictly positive and GVZ and OVX strictly negative; long for the exact inverse","why_distinct":"CAVBR-12 uses three-of-four same-sign breadth and is terminal. ECVDR requires two internally confirmed pairs with opposite signs, so every ECVDR event is excluded from CAVBR by construction. Prior gold/oil rotation relays use one commodity index against VIX; ECVDR requires joint GVZ-OVX confirmation and joint VIX-VXN confirmation.","why_suited_to_volatile_regimes":"BTC prior-24h realized-variation rank at the next Cboe session decision must be at least 0.65","why_low_gross9_overlap_is_plausible":"official next-Cboe-session 09:35 ET entries have previously shown low Gross9 structural overlap"},
 "features":{"common_source_dates":"exact intersection of positive finite daily closes for VIX,VXN,GVZ,OVX","index_changes":"log(current close/previous exact common-source-date close)","divergence":"VIX and VXN strict same nonzero sign; GVZ and OVX strict same nonzero opposite sign","availability":"source-date divergence usable at 09:30 America/New_York on next exact common Cboe source date","btc_variation":"sqrt(sum squared log(close/open)) over exact BTCUSDT 1m rows in prior 24 elapsed hours","btc_variation_rank":"strict-prior midrank at most 252 prior valid decisions; minimum 126; current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"next exact common Cboe source date 09:30 America/New_York","entry":"decision+5m BTCUSDT 5m open","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"exact settlements only after novelty passes"},
 "policy":{"history_observations":252,"minimum_history_observations":126,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "source_plan":{"cboe":SOURCES,"btc":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","close"],"read_only":True},"execution_price":"sealed until source support and Gross9 novelty pass"},
 "diagnostic_controls":{"names":["no_volatility_gate","equity_pair_only","vix_gvz_only","one_session_stale_divergence","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
 "research_boundary":{"source_file_hashes_and_prior_frozen_candidate_artifacts_only_opened_before_preregistration":True,"rule_selected_from_candidate_incidence_or_outcomes":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened_for_candidate":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent equity-versus-commodity volatility isolation mechanism plus user-required high volatility"},
 "stopping_rule":"terminal first-failure sequence: source support, Gross9 novelty, strict economics; no pair, clock, threshold, side, hold, timing, volatility, or subset repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(r:dict[str,Any])->None:
 if r.get("manifest_hash")!=canonical_hash({k:v for k,v in r.items() if k!="manifest_hash"}) or r.get("outcomes_opened") is not False or r.get("source_incidence_opened") is not False:raise RuntimeError("ECVDR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
