"""Outcome-blind preregistration for HVMFI-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVMFI-24";DEFAULT_OUTPUT=Path("results/high_volatility_market_facilitation_green_state_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_market_facilitation_green_state_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a completed four-hour Bill Williams Market Facilitation Index green state—both range-per-volume and volume increasing—indicates new participation accelerating in the direction of bar development; follow that completed bar direction for twenty-four hours.","side":"strict sign of completed bar close minus open when both BW MFI and base volume exceed their immediately prior completed values","why_distinct":"BW MFI is current high-low expansion per unit of base volume and its green state requires facilitation and participation to rise together. It is not Money Flow Index, raw range or volume alone, volume-weighted momentum, taker flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the participation-backed facilitation state must coincide with completed trailing twenty-four-hour realized variation in its causal upper 35%","why_low_gross9_overlap_is_plausible":"four-hour joint range-per-volume and volume acceleration states are absent from Gross9 primitives"},
 external_basis={"origin":"Bill Williams Market Facilitation Index as documented by MetaQuotes","source":"https://www.metatrader5.com/en/terminal/help/indicators/bw_indicators/market_facilitation","fixed_definition":"BW MFI=(HIGH-LOW)/VOLUME; green state when BW MFI increases and volume increases; new players align positions in the direction of bar development","selection_use":"official formula, green-state classification, and stated bar-direction interpretation only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T), with high=max, low=min, open=first, close=last, base volume=sum","bw_mfi":"(completed bar high-completed bar low)/completed base volume, strict positive range and volume","green_state":"current finite BW MFI strictly exceeds immediately prior finite BW MFI and current base volume strictly exceeds immediately prior positive base volume","bar_direction":"strict sign of completed close-open; zero body is ineligible","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","range_and_volume_up","one_bar_stale_state","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","volume"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_market_facilitation_definition_read":True,"repository_market_facilitation_candidate_found":False,"prior_money_flow_range_volume_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official Bill Williams green state under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no volume field, state, bar direction, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVMFI preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
