"""Outcome-blind preregistration for HVCARTC-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVCARTC-8";DEFAULT_OUTPUT=Path("results/high_volatility_cross_alt_return_turnover_concordance_relay_preregistration_2026-08-11.json")
SYMBOLS=["ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT"]
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_cross_alt_return_turnover_concordance_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated BTC realized variation, the cross-sectional covariance between six liquid alts' completed returns and their own causally normalized quote-turnover shocks identifies whether fresh crypto participation is concentrating in winners or losers; follow that participation-weighted direction in BTC for eight hours.","side":"long when the strict cross-sectional covariance is positive; short when it is negative","why_distinct":"HVCARTC uses the contemporaneous cross-sectional association of alt-only returns with symbol-specific turnover surprises. Turnover diffusion uses entropy of unsigned allocation, return breadth ignores activity, impact divides return by turnover, and flow candidates use taker direction. No BTC directional return, taker split, funding, OI, premium, fitted outcome, prior event, or promoted control is used.","why_suited_to_volatile_regimes":"BTC completed trailing twenty-four-hour realized variation must rank in its causal upper 35%, targeting July-like broad risk-transfer conditions","why_low_gross9_overlap_is_plausible":"offset eight-hour alt return-versus-turnover concordance clocks are absent from Gross9 primitives"},
 external_basis={"origin":"Karpoff price-change/volume relation; crypto cross-sectional participation interpretation","fixed_definition":"six fixed liquid alts; completed eight-hour log return; quote turnover divided by that symbol's strictly prior median; cross-sectional population covariance of return and log turnover ratio; strict covariance sign","selection_use":"economic relation and sign interpretation only; no incidence or outcomes"},
 features={"symbols":SYMBOLS,"decision_grid":"00:00, 08:00, and 16:00 UTC after each completed eight-hour block","source_block":"480 exact coherent one-minute rows [D-8h,D) per symbol","alt_return":"log(last completed close/first completed open), finite","quote_turnover":"sum quote_asset_volume, finite and strictly positive","turnover_baseline":"per symbol median of at most 270 strictly prior valid eight-hour blocks, minimum 180, current excluded","turnover_shock":"log(current quote turnover/prior median)","concordance":"population covariance across the six current alt_return and turnover_shock values; strict nonzero","variation":"BTC sqrt(sum squared completed five-minute open-to-close log returns over [D-24h,D)), finite strict positive","variation_rank":"strict-prior midrank over at most 270 earlier valid decisions, minimum 180, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"exact eight-hour boundary after all completed source blocks","entry":"exact BTCUSDT open five elapsed minutes later","hold":"8 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"turnover_history_decisions":270,"minimum_turnover_history_decisions":180,"variation_hours":24,"variation_history_decisions":270,"minimum_variation_history_decisions":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","raw_turnover_level_covariance","one_block_stale_concordance","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbols":["BTCUSDT",*SYMBOLS],"interval":"1m","columns":["ts","symbol","open","high","low","close","quote_asset_volume"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"price_volume_relation_read":True,"repository_return_turnover_concordance_candidate_found":False,"prior_cross_alt_return_and_turnover_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"cross-sectional concordance between alt return direction and own-history turnover surprise in the requested high-variation regime"},
 stopping_rule="Terminal first failure; no symbol, block, normalization, covariance, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVCARTC preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
