"""Outcome-blind preregistration for HVHILBERT-I7-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVHILBERT-I7-24";DEFAULT_OUTPUT=Path("results/high_volatility_hilbert_in_phase_zero_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_hilbert_in_phase_zero_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated completed realized variation, a strict zero crossing of the official default Hilbert Transform real (InPhase) component marks a causal transition in the detrended price cycle. Follow the new InPhase sign for twenty-four hours.","side":"long when ready InPhase crosses strictly from <=0 to >0; short when it crosses from >=0 to <0","why_distinct":"This policy uses the fixed-length LEAN Hilbert FIR real component directly. MAMA uses different Hilbert-style kernels, homodyne period estimation, phase-dependent adaptive alpha, and an adaptive-average crossover; synthetic/sinewave candidates estimate bounded dominant cycles. HVHILBERT has no adaptive period, moving average, fitted outcome, reused event set, volume, flow, OI, or funding.","why_suited_to_volatile_regimes":"a fixed-filter cycle sign transition is admitted only while trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse four-hour fixed-Hilbert real-component crossings are absent from Gross9 primitives"},
 external_basis={"origin":"John Ehlers Hilbert Transform; QuantConnect LEAN canonical implementation","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/HilbertTransform.cs","definition_source_sha256":"3737e3564b4eb900c9570154cdd14a34d89182abf6d41ed0bdc40be782380733","fixed_definition":"official defaults length=7, InPhase multiplication=.635, Quadrature multiplication=.338; detrended price is current minus delay7; delayed detrended values and feedback produce InPhase=1.25*(delay4-delay2*.635)+InPhaseDelay3*.635 exactly in LEAN update order","readiness":"outer WarmUpPeriod=length+2=9, while the InPhase functional component requires Samples>length+2; event eligibility therefore requires ready finite InPhase output after that component predicate and a prior eligible finite value","selection_use":"official defaults, recursive update order, readiness, and InPhase zero crossing only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","input":"completed four-hour close from exact 240 coherent BTCUSDT one-minute rows","indicator":"exact stateful LEAN HilbertTransform(7,.635,.338) InPhase component","event":"strict finite zero crossing of consecutive eligible InPhase values; current zero emits no event","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier source-valid four-hour decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"bar aggregation, every Hilbert delay/feedback state, crossing state, and variation history reset after any invalid completed source bar","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"length":7,"in_phase_multiplication_factor":.635,"quadrature_multiplication_factor":.338,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","quadrature_zero_cross","in_phase_quadrature_cross","one_bar_stale_cross","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_hilbert_transform_definition_read":True,"repository_hilbert_in_phase_zero_cross_candidate_found":False,"prior_mama_and_ehlers_cycle_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official default fixed Hilbert real-component zero crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no length, factors, update order, component, crossing, variation, side, hold, clock, subset, threshold, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVHILBERT-I7-24 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
