"""Outcome-blind preregistration for HVCVCSS-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVCVCSS-8";SLUG="high_volatility_cross_venue_cash_shock_sponsorship_relay";DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":f"{SLUG}_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"An own-history five-minute spot quote-turnover shock that is not accompanied by an upper-quartile perpetual turnover state identifies cash-led information sponsorship rather than leverage-driven churn. When completed spot and perpetual returns agree during elevated BTC variation, follow their common direction for eight hours.","side":"common strict sign of completed spot and perpetual five-minute returns","why_distinct":"HVSPSR uses daily spot share of combined turnover; HVCPMR compares first-versus-second-half participation migration; spot-flow leadership uses taker imbalance. HVCVCSS uses an irregular absolute spot turnover shock together with a non-shocked perpetual counterfactual and no flow sign, ticket size, basis, funding, OI, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"causal trailing perpetual twenty-four-hour realized variation must occupy its upper 35 percent","why_low_gross9_overlap_is_plausible":"irregular cash-only participation shocks are absent from Gross9 primitives"},
 "features":{"decision_grid":"every exact UTC five-minute boundary D","bar":"five exact coherent native one-minute BTCUSDT rows [D-5m,D) independently for Binance spot and perpetual","venue_return":"log(last completed close/first completed open), both finite strict nonzero and same sign","venue_turnover":"sum quote_asset_volume, independently finite strict positive","history":"8640 strictly prior source-valid venue observations (30 days), current excluded; minimum 6048","spot_shock_threshold":"numpy-linear strict-prior spot turnover q95","perpetual_quiet_threshold":"numpy-linear strict-prior perpetual turnover q75","cash_only_shock":"spot turnover>=spot q95 and perpetual turnover<perpetual q75","btc_realized_variation":"sqrt(sum squared exact perpetual one-minute log(close/open) returns over [D-24h,D)), finite strict positive","variation_history":"at most 8640 strictly prior source-valid decisions, minimum 6048, current excluded","variation_rank":"strict-prior midrank; rank>=0.65","onset":"full cash-only direction state true now and false at immediately prior exact source-valid five-minute decision; missing prior cannot trigger","no_imputation":True},
 "clock":{"decision":"D after both completed venue bars are available","entry":"exact BTCUSDT perpetual D+5m open","side":"common completed venue return direction","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements only after novelty"},
 "policy":{"history_bars":8640,"minimum_history_bars":6048,"spot_shock_quantile":.95,"perpetual_quiet_quantile":.75,"variation_bars":288,"variation_history_decisions":8640,"minimum_variation_history_decisions":6048,"variation_rank_min":.65,"onset_required":True,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","spot_shock_without_perp_quiet","perp_shock_spot_quiet","one_bar_stale_cash_shock","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"spot":{"table":"bars_binance_spot","symbol":"BTCUSDT"},"perpetual":{"table":"bars_binance","symbol":"BTCUSDT"},"interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"],"window":["2023-05-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration_commit":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_spot_perpetual_participation_outcomes_known":True,"repository_exact_irregular_cash_only_turnover_shock_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent irregular cash-versus-leverage participation shock"},
 "stopping_rule":"terminal first failure; no venue, bar, turnover, history, quantile, quiet counterfactual, agreement, variation, onset, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}) or x!=build():raise RuntimeError("HVCVCSS prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_bytes(b);print(a.output)
