"""Outcome-blind preregistration for HVCAVAC-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVCAVAC-8";SLUG="high_volatility_cross_alt_volume_weighted_auction_consensus_relay";ALTS=("ADAUSDT","BNBUSDT","DOGEUSDT","ETHUSDT","SOLUSDT","XRPUSDT");DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":f"{SLUG}_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"When at least four liquid alt perpetuals complete a volatile eight-hour auction with their closing price beyond their own quote-volume-weighted completed value in one common direction, and the cross-sectional displacement strength enters its causal upper tail, the crypto market has broadly migrated value rather than produced one idiosyncratic spike. Follow the common accepted-value direction in BTC for eight hours.","side":"strict majority sign of alt log(last close / quote-volume-weighted mean close)","why_distinct":"BTC close-VWAP candidates are single-asset mean-reversion rules. Cross-alt close-location uses each bar's high-low geometry; path efficiency uses endpoint displacement over path length; return-turnover concordance ranks returns and turnover separately. HVCAVAC uses six independent block-level quote-volume-weighted value anchors and requires directional cross-sectional continuation consensus; it uses no BTC return direction, flow, funding, OI, premium, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour BTC realized variation must occupy its causal upper 35 percent","why_low_gross9_overlap_is_plausible":"offset broad alt value-area migration onsets are absent from Gross9 primitives"},
 "features":{"decision_grid":"exact 04:00, 12:00, and 20:00 UTC boundaries D","block":"480 exact aligned coherent bars_binance one-minute rows [D-8h,D) per alt","value_anchor":"sum(close*quote_asset_volume)/sum(quote_asset_volume), with finite positive denominator and anchor","value_displacement":"log(last completed close/value_anchor), finite strict nonzero","consensus":"at least four of six displacement signs in one direction and strictly more than the opposite direction","consensus_strength":"median absolute value_displacement among alts in the majority direction","strength_rank":"strict-prior midrank over at most 270 source-valid positive-consensus decisions, minimum 180, current excluded; rank>=0.70","btc_realized_variation":"sqrt(sum squared exact BTC one-minute log(close/open) returns over [D-24h,D)), finite strict positive","variation_rank":"strict-prior midrank over at most 270 source-valid decisions, minimum 180, current excluded; rank>=0.65","onset":"full rule true now and false at immediately prior exact source-valid decision; missing prior cannot trigger","no_imputation":True},
 "clock":{"decision":"D after all completed source paths are available","entry":"exact BTCUSDT perpetual D+5m open","side":"majority accepted-value direction","hold":"8 elapsed hours","reservation":"natural global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements only after novelty"},
 "policy":{"block_minutes":480,"minimum_consensus_breadth":4,"history_decisions":270,"minimum_history_decisions":180,"strength_rank_min":.70,"variation_rank_min":.65,"onset_required":True,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_strength_tail","no_variation_gate","equal_weight_value_anchor","one_block_stale_value","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"table":"bars_binance","symbols":["BTCUSDT",*ALTS],"interval":"1m","columns":["ts","symbol","open","high","low","close","quote_asset_volume"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration_commit":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_cross_alt_and_vwap_outcomes_known":True,"repository_exact_cross_alt_volume_weighted_value_consensus_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cross-sectional volume-weighted auction-value migration"},
 "stopping_rule":"terminal first failure; no universe, block, value anchor, displacement, breadth, rank, variation, onset, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}) or x!=build():raise RuntimeError("HVCAVAC prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_bytes(b);print(a.output)
