"""Outcome-blind preregistration for HVFT-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVFT-24";DEFAULT_OUTPUT=Path("results/high_volatility_fisher_transform_turn_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_fisher_transform_turn_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a canonical ten-period Ehlers Fisher Transform turning-point crossover on completed four-hour BTC auctions maps bounded range location into a near-Gaussian extreme scale and identifies a directional turn; follow the new Fisher slope for twenty-four hours.","side":"long when Fisher crosses strictly above its one-period trigger after being at or below it; short when Fisher crosses strictly below its trigger after being at or above it","why_distinct":"HVFT recursively normalizes median price within its rolling extrema and applies a nonlinear log-odds transform before detecting a slope turn. It is not a raw stochastic threshold, linear band/channel, MACD/EMA state, volume force, OI, funding, premium, or Gross9 primitive.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%; nonlinear tail expansion makes turning points in volatile range extremes explicit","why_low_gross9_overlap_is_plausible":"sparse four-hour nonlinear range-transform turning clocks are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Fisher Transform","fixed_definition":"10-period median-price range normalization; recursive value=0.33*2*(location-0.5)+0.67*prior value clipped to +/-0.999; Fisher=0.5*ln((1+value)/(1-value))+0.5*prior Fisher; trigger=prior Fisher","selection_use":"published period, recursion, clipping, transform, trigger, and crossover direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","median_price":"(high+low)/2","range_location":"(median-current rolling 10-period minimum)/(rolling maximum-minimum) on 10 consecutive valid bars; zero range invalid","recursive_value":"0.33*2*(range_location-0.5)+0.67*prior value, clipped to [-0.999,0.999], reset after gaps","fisher":"0.5*ln((1+value)/(1-value))+0.5*prior Fisher, reset after gaps","trigger":"immediately prior valid Fisher","turn":"strict Fisher/trigger crossover requiring three consecutive valid Fisher states","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"range_periods":10,"value_new_weight":.33,"value_prior_weight":.67,"fisher_prior_weight":.5,"clip_absolute":.999,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","unsmoothed_fisher","one_bar_stale_turn","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_fisher_transform_definition_read":True,"repository_fisher_transform_candidate_found":False,"prior_rsi_cci_stochastic_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical Ehlers Fisher Transform turn under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no range period, recursion, clipping, transform, trigger, crossover, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVFT preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
