"""Outcome-blind preregistration for HVMARU-12."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVMARU-12";DEFAULT_OUTPUT=Path("results/high_volatility_marubozu_acceptance_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_marubozu_acceptance_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a completed four-hour near-wickless Marubozu auction whose real body occupies at least ninety percent of its high-low range represents one-sided price acceptance rather than rejection; follow the body direction for twelve hours.","side":"strict sign of completed close minus open","why_distinct":"HVMARU requires both terminal wicks to be individually no more than five percent of the full range and the directional body to occupy at least ninety percent. It does not require a prior-range breakout, close-location alone, engulfing relation, multi-bar sequence, volume, flow, OI, funding, fitted outcome, reused event, repair, or promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%, so one-sided acceptance is tested specifically in July-like volatile conditions","why_low_gross9_overlap_is_plausible":"sparse four-hour wickless initiative-auction clocks with twelve-hour reservations are absent from Gross9 primitives"},
 external_basis={"origin":"canonical Japanese Marubozu candlestick convention","fixed_definition":"directional real body fills at least 90% of the completed high-low range; each terminal wick is no more than 5% of range; bullish close>open and bearish close<open","selection_use":"published near-wickless geometry and body direction only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","range":"high-low, finite strict positive","body":"abs(close-open)","upper_wick":"high-max(open,close)","lower_wick":"min(open,close)-low","event":"body/range>=0.90 and upper_wick/range<=0.05 and lower_wick/range<=0.05, with strict nonzero body","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","side":"strict completed body direction","hold":"12 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"body_share_min":.90,"upper_wick_share_max":.05,"lower_wick_share_max":.05,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","wick_pressure_side","one_bar_stale_pattern","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_marubozu_definition_read":True,"repository_marubozu_candidate_found":False,"prior_candlestick_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical near-wickless Marubozu acceptance under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no body or wick geometry, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVMARU preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(z.output)
