"""Preregister HVCACJP-6 without opening incidence or outcomes."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVCACJP-6";SLUG="high_volatility_cross_alt_cojump_propagation_relay";DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-11.json");ALTS=("ADAUSDT","BNBUSDT","DOGEUSDT","ETHUSDT","SOLUSDT","XRPUSDT")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_cross_alt_cojump_propagation_relay_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-11","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A same-five-minute same-sign idiosyncratic jump across at least four of six liquid alt perpetuals is a market-wide information event rather than ordinary correlated drift. Cryptocurrency co-jumps document cross-coin jump contagion; during elevated BTC variation, propagate the common alt jump direction into BTC for six elapsed hours.","side":"strict common sign of at least four alt five-minute jump returns; BTC return direction is never an input","why_distinct":"CABUR uses broad four-hour endpoint moves plus BTC magnitude underreaction at three fixed clocks; CABLR uses eight-hour sign disagreement with BTC. HVCARTAR uses a block-level cubic cross-sectional tail statistic. HVCACJP instead date-stamps a simultaneous five-minute own-history jump in each alt, requires no BTC return, and triggers at irregular event times. It reuses no event set or control and uses no range, close location, volume, flow, funding, OI, premium, or fitted outcome.","why_suited_to_volatile_regimes":"a causal trailing BTC variation threshold restricts co-jump contagion to July-like volatile conditions","why_low_gross9_overlap_is_plausible":"irregular simultaneous cross-alt jump timestamps with a six-hour reservation are absent from Gross9 primitives"},
 "external_basis":{"paper":"Bouri, Roubaud and Shahzad (2020), Do Bitcoin and other cryptocurrencies jump together?, Quarterly Review of Economics and Finance 76, 396-409","doi":"10.1016/j.qref.2019.09.003","supported_facts":["jump activity is present across cryptocurrencies","a jump in one cryptocurrency increases the probability of a jump in another","co-jumps are associated with market-wide crypto activity"],"implementation_is_unpublished_adaptation":True,"selection_use":"co-jump contagion mechanism only; five-minute threshold, direction, volatility gate and hold are tested without imported outcomes"},
 "features":{"decision_grid":"every exact five-minute UTC boundary D","source_bar":"five exact coherent one-minute bars per symbol over [D-5m,D)","alt_return":"log(five-minute close/open), finite strict nonzero","jump_history":"at most 8640 strictly prior valid five-minute absolute returns per symbol, minimum 6048, current excluded","jump_threshold":"numpy-linear 0.99 quantile of each symbol's strict-prior absolute-return history","alt_jump":"abs(current alt return)>=its own strict-prior jump threshold","cojump":"at least four of six alt jumps have one common strict return sign; a 3-3 split is ineligible","btc_realized_variation":"sqrt(sum squared exact BTC five-minute open-to-close log returns over the 288 completed bars [D-24h,D)), finite strict positive","variation_history":"at most 8640 strictly prior valid BTC variation observations, minimum 6048, current excluded","variation_threshold":"numpy-linear 0.65 quantile of strict-prior BTC variation history","eligible":"source-valid cojump and BTC variation>=its causal threshold","no_imputation":True},
 "clock":{"decision":"D immediately after all seven five-minute paths complete","entry":"exact BTCUSDT D+5m open","hold":"6 elapsed hours","reservation":"global chronological half-open reservation; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 "policy":{"jump_history_bars":8640,"minimum_jump_history_bars":6048,"jump_quantile":.99,"minimum_cojump_breadth":4,"variation_bars":288,"variation_history_observations":8640,"minimum_variation_history_observations":6048,"variation_quantile":.65,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval and final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","three_of_six_cojump","btc_confirmation","one_bar_stale_cojump","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"table":"bars_binance","symbols":["BTCUSDT",*ALTS],"interval":"1m","columns":["ts","symbol","open","high","low","close"],"query_window":["2023-05-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True,"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"cojump_paper_read":True,"prior_cross_alt_breadth_tail_and_leadership_outcomes_known":True,"repository_simultaneous_cross_alt_own_history_cojump_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published cross-cryptocurrency co-jump contagion mapped once to an irregular high-volatility BTC propagation event"},
 "stopping_rule":"Terminal first failure; no universe, bar size, history, quantile, breadth, variation, side, hold, clock, subset, threshold, or control repair."};return {**core,"manifest_hash":canonical_hash(core)}
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();a.output.parent.mkdir(parents=True,exist_ok=True)
 if a.output.exists() and json.loads(a.output.read_text())!=x:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(json.dumps({"output":str(a.output),"manifest_hash":x["manifest_hash"]}))
if __name__=="__main__":main()
