"""Outcome-blind preregistration for SQCBI-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/stablecoin_quote_count_breadth_impulse_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"stablecoin_quote_count_breadth_impulse_v1","policy_id":"SQCBI-8","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
  "mechanism":{"claim":"A completed eight-hour increase in USDC+FDUSD execution-count share and cross-book count entropy marks a broadening of BTC price discovery beyond the dominant USDT book. When USDC and FDUSD aggressive flows agree during high BTC variation, follow their common direction for eight hours.","side":"common strict sign of completed-block USDC and FDUSD signed taker flow","why_distinct":"CQSTL used signed BTC per execution and USDT ticket subordination and is terminal. Existing stablecoin relays use volume-normalized flow magnitude, ordered diffusion, or quote-volume participation. SQCBI triggers only on execution-count distribution breadth and entropy change; no prior event set or control is reused.","why_suited_to_volatile_regimes":"BTC completed prior-24h realized variation must rank in its causal upper 35%.","why_low_gross9_overlap_is_plausible":"three fixed daily boundaries conditioned on cross-quote execution-count breadth are absent from Gross9 primitives."},
  "features":{"source_panel":"hash-bound official Binance Spot hourly panel for BTCUSDT, BTCUSDC, and BTCFDUSD","block":"exact eight completed consecutive UTC hourly rows [D-8h,D) per symbol at D hour 00, 08, or 16","block_valid":"all 8 rows source_complete, exact consecutive hours, finite signed_taker_flow_btc, integer trade_count, and aggregate trade_count>=80 for each book; no imputation","count_share":"aggregate trade_count for each book divided by all-three-book aggregate trade_count","alternative_count_share":"USDC count_share plus FDUSD count_share","normalized_count_entropy":"-sum(p_i*log(p_i))/log(3), requiring every p_i>0","breadth_impulse":"current alternative_count_share minus immediately prior valid consecutive block alternative_count_share; strict positive","entropy_confirmation":"current normalized_count_entropy minus prior valid consecutive block entropy; strict positive","impulse_rank":"strict-prior midrank of absolute breadth_impulse over at most 90 prior valid consecutive transitions, minimum 60, current excluded; rank>=0.65","flow_consensus":"completed-block USDC and FDUSD signed_taker_flow_btc sums are strict nonzero and same sign","btc_realized_variation":"sqrt(sum squared completed-hour BTC log returns over 24 hours ending at D)","volatility_rank":"strict-prior midrank over at most 90 valid decision blocks, minimum 60, current excluded; rank>=0.65","no_imputation":True},
  "clock":{"decision":"exact D at UTC hour 00, 08, or 16 after all source rows complete","entry":"exact BTCUSDT D+5m open","side":"common strict USDC/FDUSD flow sign","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","funding_oi_premium":"not signal inputs; exact funding only after novelty passes"},
  "policy":{"block_hours":8,"aggregate_trade_count_min":80,"prior_blocks":90,"prior_min_blocks":60,"breadth_impulse_rank_min":.65,"realized_variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "source_plan":{"quote_flow":{"path":"data/binance_stablecoin_quote_flow_btc_2023_2026_aug/BTC_stablecoin_quote_flow_1h_2023-07-01_2026-07-31T23.csv.gz","sha256":"44374b9a2298ae4b64f0c1e7208665b1c08c8221045308694311123deae1c805"},"completed_btc":"hash-bound completed-hour BTC source through 2026-08-01","execution_price":"sealed until source-support and Gross9 novelty pass"},
  "diagnostic_controls":{"names":["no_volatility_gate","no_impulse_tail","no_entropy_confirmation","one_block_stale_breadth","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
  "research_boundary":{"prior_stablecoin_family_outcomes_known":True,"prior_stablecoin_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_sqcbi_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent cross-quote execution-count breadth impulse mechanism"},
  "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no symbols, block, trade floor, breadth, entropy, rank, flow side, hold, clock, volatility, or subset repair."
 };return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2)+"\n");print(a.output)
