"""Outcome-blind preregistration for EMVCR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any

DEFAULT_OUTPUT=Path("results/emerging_market_volatility_confirmation_relay_preregistration_2026-08-09.json")
SOURCES={"VXEEM":"https://cdn.cboe.com/api/global/us_indices/daily_prices/VXEEM_History.csv","VIX":"https://cdn.cboe.com/api/global/us_indices/daily_prices/VIX_History.csv"}
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"emerging_market_volatility_confirmation_relay_v1","policy_id":"EMVCR-8","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
  "mechanism":{"claim":"A large completed daily change in Cboe VXEEM/VIX isolates emerging-market uncertainty relative to broad US equity volatility. When BTC is already in a high realized-variation regime and its completed overnight return confirms the implied risk direction before the next US session, the cross-market move should persist for eight hours.","side":"negative sign of completed delta log(VXEEM/VIX), which must equal the nonzero BTC overnight-return sign","external_support":{"VXEEM":"Cboe Emerging Markets ETF Volatility Index: expected 30-day EEM volatility","VIX":"Cboe Volatility Index: expected 30-day S&P 500 volatility","implementation_is_not_a_published_replication":True,"untested_adaptation":"relative emerging-market volatility plus BTC confirmation is tested as an eight-hour BTC relay"},"why_distinct":"No prior repository alpha uses VXEEM. RVSBR-12 used RVX small-cap volatility without BTC direction confirmation; EMVCR uses emerging-market uncertainty and requires a separate completed BTC overnight path.","why_suited_to_volatile_regimes":"BTC prior-24h realized variation must have a causal rank of at least 0.65","why_low_gross9_overlap_is_plausible":"external daily emerging-market volatility plus next-session 09:35 ET confirmation timing is absent from Gross9 primitives"},
  "features":{"relative_volatility":"log(VXEEM_close/VIX_close) on exact common Cboe source dates","shock":"current relative_volatility minus immediately previous exact common-source observation","shock_z":"(shock-current strict-prior mean)/strict-prior sample std over at most 252 prior finite shocks; minimum 126; current excluded","shock_gate":"absolute shock_z >= 0.75; zero is ineligible","btc_overnight":"log return from source-date 16:00 America/New_York exact 1m open through next exact common-source date 09:30 America/New_York, using the completed 09:29 minute close","confirmation":"sign(btc_overnight) equals negative sign(shock), both nonzero","btc_variation":"sqrt(sum squared log(close/open)) over 1,440 exact BTCUSDT 1m bars ending at, but excluding, next source date 09:30 America/New_York","btc_variation_rank":"strict-prior midrank against at most 252 previous exact source-date variations; minimum 126; current excluded; rank >= 0.65","missing_or_nonpositive":"ineligible; no imputation"},
  "clock":{"decision":"after next exact common Cboe source date 09:30 America/New_York BTC paths are complete","entry":"same source date exact BTCUSDT 09:35 America/New_York 5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium":"not signal inputs; exact funding only after novelty passes","no_imputation":True},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "source_plan":{"cboe":{"urls":SOURCES,"columns":["DATE","CLOSE"],"download_after_preregistration":True},"btc_1m":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","close"],"read_only":True},"execution_price":"sealed until source support and Gross9 novelty pass"},
  "diagnostic_controls":{"names":["no_btc_confirmation","no_btc_volatility_gate","vxeem_change_only","one_session_stale_spread","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
  "research_boundary":{"source_schema_and_transport_checked":True,"source_values_used_to_select_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_rvsbr":False,"promoted_rvsbr_control":False,"selection_basis":"official VXEEM/VIX economic definitions, an independent BTC confirmation path, and the user-required high-volatility regime"},
  "stopping_rule":"terminal first-failure sequence: source support, Gross9 novelty, strict economics; no threshold, confirmation, side, hold, timing, volatility, or subset repair"}
 return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x.get("outcomes_opened") is not False or x.get("source_incidence_opened") is not False:raise RuntimeError("EMVCR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
