"""Outcome-blind preregistration for RBEFR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="RBEFR-8";DEFAULT_OUTPUT=Path("results/range_body_efficiency_fracture_reversal_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"range_body_efficiency_fracture_reversal_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When eight-hour high-low travel becomes extreme relative to realized candle-body movement, the auction has fractured into rejected excursions rather than efficient directional displacement. Fade the completed final two-hour impulse for eight elapsed hours at the onset of that state.","side":"negative strict sign of the final 24 completed five-minute bars' open-to-close return","why_distinct":"RBEFR uses the ratio of summed Parkinson-style intrabar range variance to summed candle-body variance. It is not wick-side imbalance, semivariance direction, bipower jump size, variance-ratio serial dependence, close location, funding, flow, or a fitted model.","volatile_market_target":"large intrabar travel with weak body efficiency is itself a volatile-auction geometry; causal RV20 q90 remains only a later audit","why_low_gross9_overlap_is_plausible":"top-15% strictly-prior fracture crossings with an eight-hour global reservation"},
 "features":{"decision_grid":"every exact 2-hour UTC boundary","window":"exact 96 completed five-minute bars [decision-8h,decision)","range_variance":"sum(log(high/low)^2)/(4*log(2)) over all 96 bars","body_variance":"sum(log(close/open)^2) over all 96 bars; strict positive denominator","fracture":"range_variance/body_variance, finite and strict positive","fracture_rank":"strict-prior midrank over at most 1080 valid decisions, minimum 720, current excluded","onset":"current fracture_rank>=0.85 and immediately preceding exact two-hour decision fracture_rank<0.85","impulse":"log(last close/first open) over final 24 completed bars, strict nonzero","source_valid":"each five-minute aggregate has exactly five unique coherent finite positive-OHLC one-minute rows; no imputation"},
 "rv20_stress_slice":{"rv20":"sqrt(365*mean exact daily returns^2 over t-20 through t-1)","threshold":"numpy linear q90 over 756 strictly prior available RV20 observations","entry_filter":False,"future_use":"only after all sequential full-calendar stages pass"},
 "clock":{"decision":"exact 2-hour UTC boundary after all 96 bars complete","entry":"exact BTCUSDT decision+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact realized funding only after novelty"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","persistent_long_vol_comparator":"same accepted clock and 0.5 gross, side forced long","full_calendar_decomposition":"candidate minus comparator net return","rv20_q90_decomposition":"same decomposition on causal RV20 q90 decisions","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"candidate_specific_q90_residual_positive":True,"comparator_cannot_satisfy_candidate_claim":True},
 "diagnostic_controls":{"definitions":{"raw_range_variance_tail":"strict-prior top-15% raw range-variance crossing, fading the same impulse","inverse_body_variance_tail":"strict-prior top-15% reciprocal body-variance crossing, fading the same impulse","one_decision_stale_fracture":"primary formula shifted by one exact two-hour decision","direction_flip":"positive primary impulse side"},"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"exact_rbefr_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no estimator, rank, history, onset, impulse, side, clock, hold, RV20, subset, comparator, control, or gate repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("RBEFR preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+"\n");print(a.output)
