"""Outcome-blind preregistration for HVDQOFS-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID='HVDQOFS-12';ALTS=('ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','DOGEUSDT','ADAUSDT');DEFAULT_OUTPUT=Path('results/high_volatility_daily_quarter_opening_flow_surprise_relay_preregistration_2026-08-13.json')
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c={'protocol_version':'high_volatility_daily_quarter_opening_flow_surprise_relay_v1','policy_id':POLICY_ID,'as_of_date':'2026-08-13','singleton':True,'outcomes_opened':False,'source_incidence_opened':False,'gross9_rows_opened':False,
 'mechanism':{'claim':'Periodic algorithmic trading concentrates information in the first five minutes of crypto quarter-hours. A completed day in which at least four liquid alt perpetuals share an unusually strong same-direction innovation in quarter-opening flow relative to their own causal daily baselines should transmit to BTC for twelve hours during elevated variation.','side':'strict majority sign of six alt daily quarter-opening normalized-flow innovations; BTC flow and price direction are never inputs','external_basis':{'paper':'The Quarter-Hour Effect: Periodic Algorithmic Trading and Return Predictability in Cryptocurrency Futures','arxiv':'https://arxiv.org/abs/2607.09426','reported_result':'quarter-hour opening order imbalance is informative for four-to-twelve-hour cryptocurrency futures returns','adaptation':'aggregate all 96 completed daily opening windows and remove each alt own strictly-prior 30-day median before cross-alt consensus'},'why_distinct':'HVCAQF treats each individual quarter-hour raw-flow onset as an event and failed Gross9 proximity. HVDCAFC uses the entire UTC-day raw flow level and failed directional balance. CAFAER uses full-day day-over-day flow acceleration plus BTC confirmation and fades. HVDQOFS uses one daily event from only scheduled opening windows, per-alt causal median innovations, no BTC flow/direction, and no reused event or control.','why_suited_to_volatile_regimes':'completed BTC daily variation must occupy its causal upper 35%','why_low_gross9_overlap_is_plausible':'one daily phase-restricted cross-alt flow-surprise clock is absent from Gross9'},
 'features':{'decision_grid':'every exact 00:00 UTC boundary D','opening_minutes':'for every quarter-hour Q in [D-24h,D), use exactly five bars_binance one-minute rows [Q,Q+5m); 96 windows and 480 rows per symbol','daily_opening_flow':'sum(2*taker_buy_quote-quote_asset_volume)/sum(quote_asset_volume) over only those 480 rows per alt; positive denominator and finite','causal_baseline':'median daily_opening_flow over 30 exact source-valid calendar days strictly before current day, minimum 24, separately per alt','flow_innovation':'current daily opening flow minus own causal baseline, finite strict nonzero','consensus':'at least four of six innovation signs share one direction; 3-3 rejects','consensus_strength':'median absolute innovation among only direction-confirming alts, finite strict positive','strength_rank':'strict-prior midrank over at most 180 jointly source-valid days, minimum 120, current excluded; rank>=0.60','btc_variation':'sqrt(sum squared exact BTC one-minute open-to-close returns over completed day), finite strict positive','variation_rank':'strict-prior midrank over at most 180 jointly source-valid days, minimum 120, current excluded; rank>=0.65','no_imputation':True},
 'clock':{'feature_available':'D after all opening windows and BTC path complete','entry':'exact BTCUSDT D+5m open','side':'alt opening-flow innovation consensus sign','hold':'12 elapsed hours','reservation':'global half-open; exit first on equal open','split_crossing_action':'skip','gross_exposure':.5,'funding':'not signal input; exact settlements only after novelty','rv20':'q90 only after unchanged all-stage pass'},
 'policy':{'baseline_days':30,'minimum_baseline_days':24,'history_days':180,'minimum_history_days':120,'minimum_consensus_breadth':4,'strength_rank_min':.60,'variation_rank_min':.65,'entry_delay_minutes':5,'hold_hours':12,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 'stages':{'train':['2023-07-01T00:00:00Z','2024-01-01T00:00:00Z'],'test':['2024-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'eval':['2025-01-01T00:00:00Z','2026-01-01T00:00:00Z'],'final':['2026-01-01T00:00:00Z','2026-08-01T00:00:00Z']},
 'source_support_gates':{'minimum_events':{'train':8,'test':12,'eval':12,'final':8},'minority_side_share_min':.2,'max_month_share':.45},'novelty_gates':{'exact_entry_jaccard_max':.1,'candidate_near_6h_share_max':.35,'occupied_5m_bar_jaccard_max':.25,'absolute_signed_exposure_pearson_max':.35,'must_pass_before_economics':True},
 'economic_gates':{'absolute_return_positive':True,'cagr_to_strict_mdd_min':3.,'strict_mdd_max_pct':15.,'mean_gross_underlying_min_bp':20.,'weekly_signflip_one_sided_p_max':.1,'stress_absolute_return_positive':True,'stress_cagr_to_strict_mdd_min':2.5,'each_calendar_half_positive':True,'stop_on_first_failure':True,'accounting':'fixed quantity, exact funding, 6bp/10bp per notional side, held 5m favorable-then-adverse, global HWM, full-calendar CAGR'},
 'post_stage_volatility_audit':{'prerequisite':'unchanged all-stage pass','rv20_q90_entry_filter':False,'minimum_q90_trades':8,'candidate_q90_absolute_return_positive':True,'identical_clock_forced_long_residual_positive':True},
 'diagnostic_controls':{'names':['no_strength_tail','no_variation_gate','raw_opening_flow_level','one_day_stale_surprise','direction_flip','forced_long'],'cannot_be_promoted':True},
 'source_plan':{'table':'bars_binance','symbols':['BTCUSDT',*ALTS],'interval':'1m','columns':['ts','symbol','open','high','low','close','quote_asset_volume','taker_buy_quote'],'window':['2023-01-01T00:00:00Z','2026-08-01T00:00:00Z'],'read_after_preregistration':True,'execution_prices':'sealed until source and novelty pass'},
 'research_boundary':{'quarter_hour_paper_read':True,'repository_exact_daily_phase_restricted_flow_surprise_found':False,'prior_quarter_daily_level_and_acceleration_outcomes_known':True,'prior_event_sets_or_controls_reused':False,'prior_outcomes_used_to_set_formula_rank_side_hold_or_clock':False,'candidate_incidence_opened':False,'postentry_return_or_pnl_opened':False,'gross9_rows_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False,'promoted_prior_control':False,'selection_basis':'paper-supported periodic order flow expressed as causal daily phase-restricted surprise'},
 'stopping_rule':'terminal first failure; no universe, phase, window, aggregation, baseline, innovation, breadth, strength, history, rank, variation, side, hold, clock, subset, threshold, source, or control repair'};return {**c,'manifest_hash':canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!='manifest_hash'}
 if x.get('manifest_hash')!=canonical_hash(core) or x!=build() or x['outcomes_opened'] or x['source_incidence_opened'] or x['gross9_rows_opened']:raise RuntimeError('HVDQOFS prereg drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+'\n');print(a.output)
