"""Outcome-blind preregistration for HVERF-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVERF-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_reflex_zero_cross_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_reflex_zero_cross_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' published Reflex oscillator crossing zero on completed four-hour BTC auctions identifies a standardized departure from the zero-lag linear path; follow the new curvature direction for twenty-four hours.","side":"long on a strict nonpositive-to-positive Reflex crossing; short on a strict nonnegative-to-negative crossing","why_distinct":"Reflex SuperSmooths close, compares its prior Length observations with the straight line joining current and Length-lag filtered values, averages the path residual, and recursively standardizes it. It is not TrendFlex, a fast/slow crossover, raw return or price level, fixed-threshold reentry, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"Reflex was designed to react promptly to significant reversals and the crossing must occur while completed trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"standardized zero-lag path-residual curvature crossings are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, Reflex: A New Zero-Lag Indicator, TASC February 2020","source":"https://traders.com/Documentation/FEEDbk_docs/2020/02/TradersTips.html","fixed_definition":"Length=20; SuperSmoother critical period=.5*Length; Slope=(Filt[Length]-Filt)/Length; Sum=mean over count 1..Length of (Filt+count*Slope)-Filt[count]; MS=.04*Sum^2+.96*MS[1]; Reflex=Sum/sqrt(MS); zero reference","selection_use":"published default, recursions, normalization, and zero reference only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","reflex":"published period-20 Reflex of completed close","super_smoother":"a1=exp(-1.414*pi/(.5*Length)); b1=2*a1*cos(1.414*pi/(.5*Length)); c2=b1; c3=-a1^2; c1=1-c2-c3; Filt=c1*(Close+Close[1])/2+c2*Filt[1]+c3*Filt[2]","path_residual":"Slope=(Filt[Length]-Filt)/Length; Sum is the mean of (Filt+count*Slope)-Filt[count] for count one through Length","normalization":"MS=.04*Sum^2+.96*prior_MS; Reflex=Sum/sqrt(MS) when MS>0","event":"strict finite Reflex zero crossing relative to the immediately prior valid decision","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"invalid completed four-hour bars reset filter and MS state; initialize the first three filtered values to close and MS to zero; require at least Length+1 uninterrupted observations and finite current/prior Reflex values","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"length":20,"mean_square_current_weight":.04,"mean_square_prior_weight":.96,"warmup_observations":21,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","filtered_slope_zero_cross","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_reflex_definition_read":True,"repository_reflex_candidate_found":False,"prior_trendflex_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published Ehlers period-20 Reflex zero crossing under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no length, recursion, initialization, normalization, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVERF preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
