"""Outcome-blind preregistration for HVSPPE-12."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID='HVSPPE-12';DEFAULT_OUTPUT=Path('results/high_volatility_spot_perpetual_permutation_entropy_leadership_relay_preregistration_2026-08-11.json')
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop('manifest_hash')
 c.update(protocol_version='high_volatility_spot_perpetual_permutation_entropy_leadership_relay_v1',policy_id=POLICY_ID,as_of_date='2026-08-11',
 mechanism={'claim':'During an already volatile BTC block, unusually lower ordinal-path entropy in Binance spot than in the perpetual identifies more structured cash price discovery rather than derivatives noise. When completed spot and perpetual returns agree, follow their common direction for twelve hours at the fresh entropy-leadership onset.','side':'common strict nonzero sign of completed four-hour spot and perpetual returns','why_distinct':'Prior spot sponsorship candidates used quote turnover, execution counts, taker imbalance, or relative return magnitude. The prior ordinal classifier used one perpetual path and fitted outcome labels. HVSPPE uses no flow, volume, trade count, ticket size, fitted model, prior event set, or promoted control: it compares normalized Bandt-Pompe ordinal-pattern entropy across the cash and perpetual paths.','why_suited_to_volatile_regimes':'completed perpetual four-hour realized variation must rank in its causal upper 35%','why_low_gross9_overlap_is_plausible':'fresh cross-market complexity-leadership onsets at four-hour boundaries are absent from Gross9 primitives'},
 external_basis={'origin':'Bandt-Pompe permutation entropy applied to cryptocurrency efficiency','paper':'https://arxiv.org/pdf/1901.04967','paper_sha256':'9fbfdba3c66f3d882ae1d290c7c725d6b474d0f18a36ff5e7dbde17c300a2d13','support':'ordinal-pattern permutation entropy quantifies cryptocurrency price-series efficiency and temporal ordering','selection_use':'fixed dimension-three normalized permutation entropy only; cross-market difference, ranks, direction and holding application are untested; no incidence or outcomes'},
 features={'decision_grid':'every completed four-hour UTC boundary','sources':'240 exact aligned coherent BTCUSDT one-minute rows from bars_binance_spot and bars_binance over [T-4h,T)','five_minute_paths':'48 exact nonoverlapping groups per venue; each close is the fifth constituent minute close','ordinal_patterns':'all 46 consecutive triples of five-minute closes, dimension 3 and delay 1; ties resolve deterministically by earlier temporal index','normalized_permutation_entropy':'negative sum over six pattern probabilities p*log(p), divided by log(6), independently by venue','entropy_leadership':'perpetual entropy minus spot entropy, finite strict nonzero; positive means spot is more ordinally ordered','entropy_leadership_rank':'strict-prior midrank over at most 270 earlier source-valid decisions, minimum 180, current excluded; rank>=0.80','returns':'log(last five-minute close/first five-minute close) independently by venue; both strict nonzero and same sign','perpetual_variation':'sqrt(sum squared 47 perpetual five-minute close-to-close log returns), finite strict positive','variation_rank':'strict-prior 270/180 midrank, current excluded; rank>=0.65','eligible_state':'positive entropy leadership, entropy rank and variation rank pass, and venue return directions agree','onset':'eligible now and immediately prior source-valid decision ineligible; missing prior cannot trigger','no_imputation':True},
 clock={'feature_available':'completed four-hour boundary','entry':'exact BTCUSDT perpetual boundary+5m open','hold':'12 elapsed hours','reservation':'global half-open; exit first on equal open','gross_exposure':.5,'funding':'not a signal input; exact settlements only after novelty passes'},
 policy={'ordinal_dimension':3,'five_minute_bars':48,'entropy_history_decisions':270,'minimum_entropy_history_decisions':180,'entropy_leadership_rank_min':.80,'variation_rank_min':.65,'entry_delay_minutes':5,'hold_hours':12,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 diagnostic_controls={'names':['no_entropy_leadership_gate','no_variation_gate','perpetual_more_ordered','one_bar_stale_onset','direction_flip','forced_long'],'cannot_be_promoted':True},
 source_plan={'spot':{'table':'bars_binance_spot','symbol':'BTCUSDT','interval':'1m','columns':['ts','open','high','low','close']},'perpetual':{'table':'bars_binance','symbol':'BTCUSDT','interval':'1m','columns':['ts','open','high','low','close']},'window':['2023-04-01T00:00:00Z','2026-08-01T00:00:00Z'],'read_after_preregistration':True,'execution_price':'sealed until source support and Gross9 novelty pass'},
 research_boundary={'permutation_entropy_definition_read':True,'repository_cross_market_entropy_candidate_found':False,'prior_spot_sponsorship_and_ordinal_classifier_outcomes_known':True,'prior_event_sets_reused':False,'prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock':False,'candidate_incidence_opened':False,'postentry_return_or_pnl_opened':False,'gross9_rows_opened':False,'candidate_count':1,'grid':False,'repair_of_spot_sponsorship':False,'repair_of_ordinal_classifier':False,'promoted_prior_control':False,'selection_basis':'published cryptocurrency permutation-entropy complexity applied as a cross-market cash-leadership mechanism'},
 stopping_rule='Terminal first failure; no embedding dimension, tie convention, entropy rank, variation rank, direction agreement, onset, side, hold, clock, subset, control, or other repair.')
 return {**c,'manifest_hash':canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!='manifest_hash'}
 if v.get('manifest_hash')!=canonical_hash(core) or v!=build():raise RuntimeError('HVSPPE-12 preregistration drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+'\n');print(a.output)
