"""Outcome-blind preregistration for HVLWRB-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVLWRB-24";DEFAULT_OUTPUT=Path("results/high_volatility_larry_williams_range_breakout_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_larry_williams_range_breakout_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a completed hourly BTC close crossing beyond the current UTC day open plus or minus one half of the fully completed prior UTC day's range identifies a daily volatility breakout; follow the breakout direction for twenty-four hours.","side":"long on the first strict hourly close crossing above day_open+0.5*prior_day_range; short on the first strict crossing below day_open-0.5*prior_day_range","why_distinct":"HVLWRB uses a fixed daily-open anchor and a fully completed prior-day range projected into the current session. It is not a rolling Donchian/channel, retest/reclaim, oscillator, volume/flow, OI, funding, premium, or Gross9 state primitive.","why_suited_to_volatile_regimes":"the exact completed trailing twenty-four-hour minute variation at the hourly decision must rank in its causal upper 35%, targeting active range-expansion sessions","why_low_gross9_overlap_is_plausible":"hourly crossings of daily-open projected prior-range barriers are absent from Gross9 primitives"},
 external_basis={"origin":"Larry Williams daily volatility-breakout convention","fixed_definition":"project a fixed fraction of the completed prior day high-low range from the current day open and trade breakout direction; factor fixed at the common one-half adaptation","selection_use":"published daily-open/prior-range construction and breakout direction only; hourly close confirmation and twenty-four-hour relay are disclosed adaptations; no incidence or outcomes"},
 features={"decision_grid":"each exact UTC hour after a completed current-day hour","source_hour":"exact aggregation of 60 coherent BTCUSDT one-minute rows [T-1h,T)","prior_day":"exact 24 coherent hourly bars for [D-24h,D), where D is current UTC day start","day_open":"open of exact minute D, observed before every eligible decision","barriers":"day_open plus/minus 0.5*(prior_day_high-prior_day_low); strict positive prior range","crossing":"current completed-hour close crosses strictly beyond a barrier from prior current-day hourly close, or from day_open for the first hour","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid hourly decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"exact hourly boundary after completed source hour and all prior-day inputs","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"range_factor":.5,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","prior_day_body_projection","one_hour_stale_crossing","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_williams_breakout_definition_read":True,"repository_williams_breakout_candidate_found":False,"prior_rsi_cci_stochastic_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical prior-day-range daily-open breakout under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no day boundary, range factor, barrier, crossing, variation, variation, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVLWRB preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
