"""Outcome-blind preregistration for RIVSCR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path('results/realized_over_implied_volatility_shock_continuation_relay_preregistration_2026-08-08.json')
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={'protocol_version':'realized_over_implied_volatility_shock_continuation_relay_v1','policy_id':'RIVSCR-6','as_of_date':'2026-08-08','outcomes_opened':False,
 'mechanism':{'claim':'At a fixed eight-hour boundary, unusually large BTC realized variation relative to the jointly observed Binance BVOL and Deribit DVOL level indicates that price discovery is outrunning options repricing. When the final completed hour agrees with the full-block direction, the still-underpriced shock direction should continue for six hours.','side':'common sign of the completed eight-hour return and final-hour return','why_distinct':'RIVSCR uses a causal realized-variation/cross-venue-implied-level ratio. HVDPR used elevated absolute IV levels plus same-direction four-hour halves and path efficiency; CVVIB used joint IV body expansion after price compression; RV20 used a trailing realized-volatility regime with OI/taker-flow shocks.','why_suited_to_volatile_regimes':'the signal activates only when realized variation becomes extreme relative to both crypto implied-volatility venues','why_low_gross9_overlap_is_plausible':'Gross9 contains no realized-to-implied variance-ratio block clock'},
 'clock':{'decision':'exact UTC 00:00/08:00/16:00 boundary D after eight consecutive completed source-valid hours [D-8h,D)','realized_variation':'sqrt(sum of eight squared hourly BTC log returns), zero invalid','implied_level':'sqrt((BVOL close/100)*(DVOL close/100)) observed at D, positive only','ratio':'log(realized_variation/implied_level), strict-prior 270 nonoverlapping block midrank with 252 observations; current excluded','shock_gate':'ratio rank >=0.75','direction_confirmation':'nonzero eight-hour return and final-hour return have the same sign','entry':'exact BTCUSDT D+5m open','side':'common direction','hold':'6 elapsed hours','reservation':'fixed nonoverlapping blocks; global half-open, exit first on equal open','no_imputation':True},
 'policy':{'block_hours':8,'prior_blocks':270,'prior_min_blocks':252,'ratio_rank_min':.75,'entry_delay_minutes':5,'hold_hours':6,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 'stages':{'train':['2023-07-01T00:00:00Z','2024-01-01T00:00:00Z'],'test':['2024-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'eval':['2025-01-01T00:00:00Z','2026-01-01T00:00:00Z'],'final':['2026-01-01T00:00:00Z','2026-08-01T00:00:00Z']},
 'source_support_gates':{'minimum_events':{'train':8,'test':12,'eval':12,'final':8},'minority_side_share_min':.2,'max_month_share':.45},'novelty_gates':{'exact_entry_jaccard_max':.1,'candidate_near_6h_share_max':.35,'occupied_5m_jaccard_max':.25,'absolute_signed_exposure_pearson_max':.35,'must_pass_before_economics':True},
 'economic_gates':{'absolute_return_positive':True,'cagr_to_strict_mdd_min':3.,'strict_mdd_max_pct':15.,'mean_gross_underlying_min_bp':20.,'weekly_signflip_one_sided_p_max':.1,'stress_absolute_return_positive':True,'stress_cagr_to_strict_mdd_min':2.5,'each_calendar_half_positive':True,'stop_on_first_failure':True,'future_can_rank_repair_or_reselect':False,'accounting':'fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR'},
 'diagnostic_controls':{'absolute_realized_variation':'realized-variation rank only','absolute_implied_level':'low implied-level rank plus direction confirmation','no_final_hour_confirmation':'ratio shock plus block direction','one_block_stale_ratio':'ratio rank lagged one fixed block','direction_flip':'same entries opposite side'},
 'source_plan':{'volatility':'hash-bound official completed-hour BVOL/DVOL through 2026-08-01','completed_price_features':'hash-bound BTC completed-hour snapshot; no post-entry prices','execution_price':'sealed until source-support and Gross9 novelty pass'},
 'research_boundary':{'prior_candidate_incidence_known':True,'prior_candidate_outcomes_used_for_rivscr':False,'rivscr_candidate_incidence_opened':False,'rivscr_post_entry_return_or_pnl_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False,'diagnostic_controls_cannot_be_promoted':True}}
 return {**core,'manifest_hash':canonical_hash(core)}
if __name__=='__main__':p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2,ensure_ascii=False)+'\n');print(a.output)
