"""Outcome-blind preregistration for HVSTER-8."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any

DEFAULT_OUTPUT=Path("results/high_volatility_small_ticket_exhaustion_reversal_preregistration_2026-08-09.json")
SOURCE_BINDINGS={"data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz":"a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"}
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={
  "protocol_version":"high_volatility_small_ticket_exhaustion_reversal_v1","policy_id":"HVSTER-8","as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"singleton":True,
  "mechanism":{"claim":"During high BTC range volatility, a six-hour directional move accompanied by unusually many executions but unusually small average quote notional per execution reflects broad late participation rather than a few informed inventory transfers. Fade the completed move for eight hours as small-ticket urgency exhausts.","side":"opposite strict sign of the completed six-hour BTC return","why_distinct":"HVSTER uses the joint block-level geometry of high execution count and low quote-notional-per-execution. HVDVBR used concentration in one maximum-volume bar; STCSR used unavailable spot-versus-perpetual trade-count share; BAFR and MFIC used aggregate-trade aggressor direction and event topology. No prior event, control, threshold, or side is reused.","why_suited_to_volatile_regimes":"the trailing twelve-hour BTC range must be in the source-only upper 35%.","why_low_gross9_overlap_is_plausible":"execution-count/ticket-size participation tails are absent from Gross9 primitives."},
  "features":{"decision":"each completed xx:55 UTC five-minute bar","block":"72 exact consecutive completed five-minute bars ending at decision","range_window":"144 exact consecutive completed bars ending at decision","validity":"finite positive coherent OHLC, finite nonnegative quote volume, finite nonnegative integer trade count, positive block quote volume and trade count; no imputation","block_return":"log(last close/first open) over 72 bars; strict nonzero","execution_count":"sum(number_of_trades) over 72 bars","average_ticket":"sum(quote_asset_volume)/sum(number_of_trades) over 72 bars","range_vol":"max(high)/min(low)-1 over 144 bars","calibration":"2023H1 complete hourly anchors only: execution_count q75, average_ticket q35, abs(block_return) q60, range_vol q65; no candidate incidence or post-entry values","eligibility":"execution_count>=q75, average_ticket<=q35, abs(block_return)>=q60, range_vol>=q65; first row of a consecutive eligible same-side run","grid":False},
  "clock":{"entry":"next exact-hour five-minute open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5},
  "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
  "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
  "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
  "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
  "diagnostic_controls":{"names":["no_volatility_gate","count_tail_only","ticket_tail_only","one_block_stale_participation","direction_flip"],"diagnostic_controls_cannot_be_promoted":True},
  "source_plan":{"historical":"hash-bound five-minute market through 2026-06-01","live_extension":"read-only Postgres completed one-minute bars aggregated exactly through 2026-08-01","execution_prices":"sealed until source support and Gross9 novelty pass"},"source_bindings":SOURCE_BINDINGS,
  "research_boundary":{"prior_microstructure_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_hvster_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent block-level small-ticket participation-exhaustion mechanism"},
  "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no count, ticket, move, volatility, onset, side, hold, clock, or subset repair."
 };return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2)+"\n");print(a.output)
