"""Outcome-blind preregistration for HVPCR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVPCR-8";DEFAULT_OUTPUT=Path("results/high_volatility_premium_catchup_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_premium_catchup_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"When the completed eight-hour Binance BTC premium-index displacement and BTC return have opposite strict signs during elevated BTC variation, derivatives fair-value demand has not been assimilated by price. Trade BTC in the premium displacement direction for eight hours.","side":"strict sign of premium-index last close minus first open, opposite the BTC block-return sign","why_distinct":"PPLAR required a top-quintile one-hour premium impulse, second-hour persistence, bounded BTC under-response and onset logic. HVPCR uses one indivisible fixed eight-hour cross-surface displacement relation, no magnitude tail, no PPLAR event/control clock, and no repair of its unopened economics.","volatile_market_target":"completed BTC eight-hour realized-variation rank at least 0.65","why_low_gross9_overlap_is_plausible":"three conditional premium-price disagreement clocks are absent from Gross9"},
 "features":{"decision_grid":"00:00,08:00,16:00 UTC","source":"480 exact joined BTCUSDT premium-index and perpetual 1m rows","premium_displacement":"last premium close minus first premium open","btc_return":"log(last BTC close/first BTC open)","disagreement":"both strict nonzero and opposite signs","btc_variation":"sqrt(sum squared 1m BTC close-to-close returns)","variation_rank":"strict-prior midrank over at most 270 valid blocks, minimum 180; current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"completed 8h boundary","entry":"decision+5m exact BTCUSDT open","hold":"8 elapsed hours","side":"premium displacement sign","reservation":"fixed nonoverlap; exit first on equal open","gross_exposure":.5,"funding":"exact only after novelty"},
 "policy":{"history_blocks":270,"minimum_history_blocks":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","contemporaneous_agreement","one_block_stale_premium","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"premium":{"table":"bars_binance_premium","symbol":"BTCUSDT","interval":"1m"},"btc":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m"},"read_only":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_premium_outcomes_known":True,"pplar_outcomes_opened":False,"prior_event_sets_or_controls_reused":False,"exact_hvpcr_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent fixed-block premium-price displacement disagreement"},
 "stopping_rule":"terminal first failure; no premium, disagreement, rank, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x["manifest_hash"]!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVPCR drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2)+"\n");print(a.output)
