"""Outcome-blind preregistration for HVCASCE-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVCASCE-8";SLUG="high_volatility_cross_alt_sign_configuration_entropy_relay";ALTS=("ADAUSDT","BNBUSDT","DOGEUSDT","ETHUSDT","SOLUSDT","XRPUSDT");DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":f"{SLUG}_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"A volatile crypto auction whose six-alt directional breadth repeatedly occupies only a few cross-sectional sign configurations has collapsed from fragmented trading into a persistent common market mode. When the last hour confirms one broad direction, follow that mode in BTC for eight elapsed hours.","side":"strict majority sign of the six alts' completed final-hour cumulative returns","why_distinct":"HVSER is BTC-only binary sign entropy. HVCMMI uses continuous return covariance eigenvalues. Cross-alt serial persistence uses each alt's time autocorrelation. HVCASCE instead measures Shannon entropy of the 24 categorical six-alt breadth states {-6,-4,-2,0,2,4,6}; it uses no return magnitude in the entropy, value anchor, order flow, turnover, funding, OI, premium, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour BTC realized variation must occupy its causal upper 35 percent","why_low_gross9_overlap_is_plausible":"irregular half-hour cross-sectional entropy-collapse onsets are absent from Gross9 primitives"},
 "features":{"decision_grid":"every exact UTC half-hour D","window":"24 exact aligned coherent fifteen-minute aggregates from 360 native bars_binance one-minute rows [D-6h,D) for six alts","alt_interval_return":"log(last completed close/first completed open), finite; strict sign with exact zero coded 0","breadth_state":"sum of six signs at each interval, one of {-6,-4,-2,0,2,4,6}","configuration_entropy":"Shannon entropy in bits of the empirical seven-state distribution across the 24 completed intervals","collapse_strength":"negative configuration_entropy","collapse_rank":"strict-prior midrank over at most 2160 source-valid decisions, minimum 1440, current excluded; rank>=0.80","final_hour_direction":"sum each alt's final four interval returns; at least four of six have one common strict sign and strictly outnumber the opposite sign","btc_realized_variation":"sqrt(sum squared exact BTC one-minute log(close/open) returns over [D-24h,D)), finite strict positive","variation_rank":"strict-prior midrank over at most 2160 source-valid decisions, minimum 1440, current excluded; rank>=0.65","onset":"full eligible state true now and false at immediately prior exact source-valid half-hour; missing prior cannot trigger","no_imputation":True},
 "clock":{"decision":"D after all completed source paths are available","entry":"exact BTCUSDT perpetual D+5m open","side":"broad final-hour alt direction","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements only after novelty"},
 "policy":{"window_minutes":360,"interval_minutes":15,"state_observations":24,"minimum_directional_breadth":4,"history_decisions":2160,"minimum_history_decisions":1440,"collapse_rank_min":.80,"variation_rank_min":.65,"onset_required":True,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_collapse_tail","no_variation_gate","btc_binary_sign_entropy","one_hour_stale_entropy","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"table":"bars_binance","symbols":["BTCUSDT",*ALTS],"interval":"1m","columns":["ts","symbol","open","high","low","close"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration_commit":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_entropy_and_cross_alt_outcomes_known":True,"repository_exact_cross_alt_breadth_state_entropy_candidate_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent categorical cross-sectional market-mode entropy collapse"},
 "stopping_rule":"terminal first failure; no universe, interval, window, state alphabet, entropy, rank, variation, confirmation, onset, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}) or x!=build():raise RuntimeError("HVCASCE prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_bytes(b);print(a.output)
