"""Outcome-blind preregistration for HVTSF3-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVTSF3-24";DEFAULT_OUTPUT=Path("results/high_volatility_time_series_forecast_slope_flip_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_time_series_forecast_slope_flip_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated completed realized variation, a sign flip in the canonical three-period Time Series Forecast's one-step-ahead displacement identifies a new local linear trend direction. Follow the forecast direction for twenty-four hours.","side":"long when forecast-minus-current close flips strictly from negative to positive; short on the strict reverse","why_distinct":"Regression Channel uses fitted bands and breakouts; moving-average candidates compare price with smoothed levels or line slopes. HVTSF3 extrapolates a least-squares line one full step beyond the current three-bar window and trades only strict sign flips of that forecast displacement. It uses no volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the forecast transition is admitted only when trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse four-hour extrapolated forecast-direction flips are absent from Gross9 primitives"},
 external_basis={"origin":"QuantConnect LEAN TimeSeriesForecast canonical implementation derived from Tulip Indicators","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/TimeSeriesForecast.cs","definition_source_sha256":"ac1227b24d3d66de04f6b139137efbba564fcb170e3c50bcc315500f9e4297bd","documentation_source":"https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/time-series-forecast","fixed_definition":"ordinary least-squares fit to x=1..3 completed closes, forecast=a+b*4; displacement=forecast-current close","selection_use":"official documented example period 3 and exact forecast formula only; sign-flip trading application is untested; no incidence or outcomes"},
 features={"decision_grid":"every completed four-hour BTCUSDT bar","forecast":"LEAN TimeSeriesForecast(3) over completed closes, reset across gaps","displacement":"forecast-current completed close, finite strict nonzero","flip":"current displacement strict sign differs from immediately prior source-valid strict nonzero displacement","realized_variation":"sqrt(sum squared one-minute log(close/open) returns over trailing completed twenty-four hours), finite strict positive","variation_rank":"strict-prior midrank over at most 270 earlier source-valid decisions, minimum 180, current excluded; rank>=0.65","recursive_reset":"forecast window, prior sign, variation window, and rank history reset after any invalid four-hour bar","no_imputation":True},
 clock={"feature_available":"completed four-hour boundary","entry":"exact BTCUSDT boundary+5m open","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"forecast_periods":3,"variation_hours":24,"variation_history_decisions":270,"minimum_variation_history_decisions":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","forecast_level_side","current_regression_slope_flip","one_bar_stale_flip","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_price":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_time_series_forecast_definition_read":True,"repository_tsf_candidate_found":False,"prior_regression_channel_and_moving_average_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official documented three-period one-step forecast under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no forecast period, formula, side, variation, hold, clock, subset, threshold, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVTSF3-24 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
