"""Outcome-blind preregistration for ACUCR-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="ACUCR-12";DEFAULT_OUTPUT=Path("results/asian_carry_unwind_concordance_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"asian_carry_unwind_concordance_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"During the completed Asian session, simultaneous AUD weakness and JPY strength identify a carry unwind while simultaneous AUD strength and JPY weakness identify carry relief. In a high-variation BTC regime, trade BTC with risk relief and against risk unwind for twelve hours.","side":"short when USDAUD return is positive and USDJPY return is negative; long for the exact symmetric concordance","why_distinct":"SHRR used a standardized three-leg SEK/CHF/JPY European-session median with a magnitude tail; UJCVR used USDJPY alone; dollar-factor candidates measured common USD direction. ACUCR uses raw two-leg Asia-session carry concordance, no magnitude threshold, no reused event set, and no promoted control.","why_suited_to_volatile_regimes":"completed pre-decision 24-hour BTC realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"one weekday 08:05 UTC external carry-concordance clock is absent from Gross9 primitives"},
 "features":{"fx_session":"bars_polygon 1m USDAUD and USDJPY rows with 00:00<=UTC time<08:00 on one weekday","session_valid":"each pair has at least 450 distinct minutes, first<=00:05, last>=07:55, finite positive coherent OHLC; no imputation","returns":"log(session close/session open) independently for USDAUD and USDJPY","risk_pressure":"USDAUD return for AUD weakness and negative USDJPY return for JPY strength","concordance":"both risk-pressure components have the same strict nonzero sign; opposite signs or zero are ineligible","btc_realized_variation":"sqrt(sum squared completed-hour BTC returns over 24 hours ending at decision)","variation_rank":"strict-prior midrank over at most 90 valid weekday decisions, minimum 60, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact weekday D 08:00 UTC after both FX sessions and BTC variation complete","entry":"exact BTCUSDT D 08:05 UTC open","side":"negative concordant risk-pressure sign","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","funding":"not an input; exact funding only after novelty"},
 "policy":{"variation_prior_days":90,"variation_prior_min_days":60,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all stages","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "source_plan":{"fx":{"table":"bars_polygon","symbols":["USDAUD","USDJPY"],"interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"materialize_after_preregistration":True},"completed_btc":"hash-bound completed-hour source through 2026-08-01","execution_price":"sealed until source and novelty pass"},
 "diagnostic_controls":{"names":["no_volatility_gate","aud_leg_only","jpy_leg_only","one_session_stale_concordance","direction_flip","forced_long"],"cannot_be_promoted":True},
 "research_boundary":{"prior_shrr_ujcvr_dollar_factor_evidence_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_acucr_direction_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent Asia-session carry concordance transmission"},
 "stopping_rule":"Terminal first failure; no pair set, concordance, volatility, side, session, clock, hold, subset, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2)+"\n");print(a.output)
