"""Outcome-blind preregistration for HVERI-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVERI-24";DEFAULT_OUTPUT=Path("results/high_volatility_ehlers_reversion_index_crossover_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_ehlers_reversion_index_crossover_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, John Ehlers' published Reversion Index fast Trigger crossing its slower Smooth line on completed four-hour BTC auctions identifies timely peaks and valleys in ranging volatile markets; follow the newly indicated direction for twenty-four hours.","side":"long when period-4 SuperSmoothed Reversion Trigger strictly crosses above period-8 Reversion Smooth; short on the strict cross below","why_distinct":"The raw field is the length-20 signed path displacement divided by total absolute path variation, then two different two-pole SuperSmoothers cross. It is not RSI, a price/range oscillator, raw return sign, moving-average price crossover, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"the 2026 publication explicitly presents the indicator for mean-reversion peaks and valleys and reports the crossover example working well on a volatile stock; the crossing must also occur while trailing twenty-four-hour realized variation ranks in its causal upper 35%","why_low_gross9_overlap_is_plausible":"dual-smoothed signed-path-efficiency turning-point crossings are absent from Gross9 primitives"},
 external_basis={"origin":"John F. Ehlers, The Reversion Index, TASC January 2026","source":"https://traders.com/Documentation/FEEDbk_docs/2026/01/TradersTips.html","fixed_definition":"Length=20; Ratio=sum of Close-previous Close over Length divided by sum absolute changes; Smooth=SuperSmoother(Ratio,8); Trigger=SuperSmoother(Ratio,4); published implementations buy when Trigger crosses above Smooth and sell when it crosses below","selection_use":"published default length, ratio, smoothing periods, crossover, and side only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","ratio":"sum of the last twenty completed close differences divided by their summed absolute values, invalid when denominator is zero","smooth":"published period-8 two-pole SuperSmoother of Ratio","trigger":"published period-4 two-pole SuperSmoother of Ratio","event":"strict finite Trigger-minus-Smooth zero crossing relative to the immediately prior valid decision","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"invalid completed four-hour bars reset both smoothing states; initialize each first three smoother outputs to its current Ratio; require at least 23 uninterrupted observations and finite current/prior fields","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"length":20,"smooth_period":8,"trigger_period":4,"warmup_observations":23,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_variation_gate","raw_ratio_zero_cross","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_ehlers_reversion_index_strategy_read":True,"repository_reversion_index_candidate_found":False,"prior_oscillator_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"published Ehlers length-20 Reversion Index SS4/SS8 crossover under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no length, smoothing, initialization, crossover, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVERI preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(a.output)
