"""Outcome-blind preregistration for HVCAFRU-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID='HVCAFRU-8';SLUG='high_volatility_cross_alt_funding_residual_unwind_relay';ALTS=('ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','DOGEUSDT','ADAUSDT');DEFAULT_OUTPUT=Path(f'results/{SLUG}_preregistration_2026-08-13.json')
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build():
 core={'protocol_version':'high_volatility_cross_alt_funding_residual_unwind_relay_v1','policy_id':POLICY_ID,'slug':SLUG,'as_of_date':'2026-08-13','singleton':True,'outcomes_opened':False,'source_incidence_opened':False,'gross9_rows_opened':False,
 'mechanism':{'claim':'When at least four of six liquid alt perpetuals settle funding materially above or below BTC funding and each relative spread is extreme versus its own causal history, leverage crowding is cross-sectionally concentrated outside BTC. During elevated BTC variation, fade the common relative-funding sign in BTC over the next funding cycle as crowded crypto inventory unwinds.','side':'negative strict common sign of at least four extreme alt-minus-BTC funding spreads','why_distinct':'HVEFR fades BTC funding relative to its own median. HVCAPCR fades continuous alt premium-index levels. Cross-venue funding fracture compares venues. HVCAFRU instead uses six simultaneous realized alt-minus-BTC funding settlement spreads, each normalized only by its own strict-prior distribution, and requires a cross-sectional tail breadth; it uses no price direction, premium, OI, flow, turnover, fitted outcome, prior event set, or promoted control.','why_suited_to_volatile_regimes':'completed prior-24h BTC realized variation must rank in its causal upper 35 percent, selecting July-like volatile states','why_low_gross9_overlap_is_plausible':'irregular cross-alt relative-funding tail onsets at settlement boundaries are absent from Gross9 primitives'},
 'features':{'decision_grid':'actual UTC funding_time values at which BTCUSDT and all six alts have one exact settlement record','funding_spread':'alt funding_rate minus simultaneous BTCUSDT funding_rate, finite strict nonzero','spread_history':'per alt at most 270 strictly prior source-valid common settlements, minimum 180, current excluded','spread_extremity_rank':'strict-prior midrank of absolute funding_spread in that alt history','tail_alt':'spread_extremity_rank>=0.75','consensus':'at least four tail alts have one common strict funding_spread sign; larger breadth wins and equal positive/negative breadth rejects','consensus_strength':'median spread_extremity_rank among selected-side tail alts','btc_realized_variation':'sqrt(sum squared exact BTCUSDT one-minute log(close/open) returns over [funding_time-24h,funding_time)), finite strict positive','variation_rank':'strict-prior midrank over at most 270 earlier source-valid common settlements, minimum 180, current excluded; rank>=0.65','eligible_state':'source-valid funding consensus plus variation gate','onset':'eligible now and immediately previous source-valid common settlement ineligible; missing prior cannot trigger','causal_availability':'funding rates are used only at their actual completed settlement timestamp; BTC path ends strictly before decision','no_imputation':True},
 'clock':{'decision':'actual common funding settlement after all seven rates and prior BTC path complete','entry':'exact BTCUSDT decision+5m open','hold':'8 elapsed hours','reservation':'global chronological half-open; exit first on equal entry','split_crossing_action':'skip','gross_exposure':.5,'funding':'signal settlement is pre-entry; all held-interval exact funding included only after novelty'},
 'policy':{'history_settlements':270,'minimum_history_settlements':180,'spread_extremity_rank_min':.75,'minimum_consensus_breadth':4,'variation_rank_min':.65,'entry_delay_minutes':5,'hold_hours':8,'leverage':.5,'base_cost_per_notional_side':.0006,'stress_cost_per_notional_side':.001},
 'stages':{'train':['2023-07-01T00:00:00Z','2024-01-01T00:00:00Z'],'test':['2024-01-01T00:00:00Z','2025-01-01T00:00:00Z'],'eval':['2025-01-01T00:00:00Z','2026-01-01T00:00:00Z'],'final':['2026-01-01T00:00:00Z','2026-08-01T00:00:00Z']},
 'source_support_gates':{'minimum_events':{'train':8,'test':12,'eval':12,'final':8},'minority_side_share_min':.2,'max_month_share':.45},'novelty_gates':{'exact_entry_jaccard_max':.1,'candidate_near_6h_share_max':.35,'occupied_5m_bar_jaccard_max':.25,'absolute_signed_exposure_pearson_max':.35,'must_pass_before_economics':True},
 'economic_gates':{'absolute_return_positive':True,'cagr_to_strict_mdd_min':3.,'strict_mdd_max_pct':15.,'mean_gross_underlying_min_bp':20.,'weekly_signflip_one_sided_p_max':.1,'stress_absolute_return_positive':True,'stress_cagr_to_strict_mdd_min':2.5,'each_calendar_half_positive':True,'stop_on_first_failure':True,'accounting':'fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR'},
 'post_stage_volatility_audit':{'prerequisite':'unchanged all-stage pass','rv20_q90_entry_filter':False,'minimum_q90_trades':8,'candidate_q90_absolute_return_positive':True,'identical_clock_forced_long_residual_positive':True},
 'diagnostic_controls':{'names':['no_spread_tail','no_variation_gate','raw_alt_funding_consensus','one_settlement_stale_spreads','direction_flip','forced_long'],'cannot_be_promoted':True},
 'source_plan':{'funding':{'table':'funding_rates_binance','symbols':['BTCUSDT',*ALTS],'columns':['funding_time','symbol','funding_rate'],'actual_timestamps':True},'btc_bars':{'table':'bars_binance','symbol':'BTCUSDT','interval':'1m','columns':['ts','open','high','low','close']},'window':['2023-01-01T00:00:00Z','2026-08-01T00:00:00Z'],'read_after_preregistration':True,'execution_prices':'sealed until source and Gross9 novelty pass'},
 'research_boundary':{'database_schema_metadata_only_opened_before_preregistration':True,'prior_btc_funding_and_alt_premium_family_outcomes_known':True,'repository_cross_alt_relative_funding_tail_breadth_candidate_found':False,'prior_event_sets_or_controls_reused':False,'prior_outcomes_used_to_set_formula_rank_side_hold_or_clock':False,'candidate_incidence_opened':False,'postentry_return_or_pnl_opened':False,'gross9_rows_opened':False,'candidate_count':1,'grid':False,'repair_of_prior_candidate':False,'promoted_prior_control':False,'selection_basis':'independent relative leverage-crowding settlement mechanism'},
 'stopping_rule':'terminal first failure; no universe, spread, history, rank, breadth, variation, onset, side, clock, hold, subset, threshold, source, comparator, or control repair'};return {**core,'manifest_hash':canonical_hash(core)}
def validate(x):
 if x.get('manifest_hash')!=canonical_hash({k:v for k,v in x.items() if k!='manifest_hash'}) or x!=build():raise RuntimeError('HVCAFRU prereg drift')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+'\n').encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f'refusing overwrite {a.output}')
 a.output.write_bytes(b);print(a.output)
