"""Outcome-blind preregistration for HVECTR-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_cross_structure_action_vote as gates
POLICY_ID="HVECTR-24";DEFAULT_OUTPUT=Path("results/high_volatility_energy_commodity_transition_relay_preregistration_2026-08-18.json");SOURCE=Path("data/high_volatility_energy_commodity_return_spillover_relay_sources_2022_2026/hvecsp_preentry_features.csv.gz");SOURCE_SHA="320301d01a587de87496bb6610547ee9f9b5b813ba6846036055c5b19c6f0ff2"
def sha256(p:str|Path)->str:return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 g=gates.build();core={"protocol_version":"high_volatility_energy_commodity_transition_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-18","singleton":True,"candidate_family":[POLICY_ID],"candidate_family_size":1,"source_incidence_opened":False,"outcomes_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"A sign transition in the completed natural-gas-minus-oil return impulse changes the energy-to-Bitcoin spillover regime rather than extending an existing score level. During elevated BTC variation, follow the new published gas-positive/oil-negative direction for twenty-four hours.","side":"strict sign of current UNG return minus equal-weight USO/BNO return after opposite prior source-valid sign","why_distinct":"HVECSP trades an absolute z-score tail and failed train. HVECTR trades only raw spillover-score polarity transitions and uses no HVECSP event/control, z threshold, crypto direction, OI, funding, premium, options, fitted outcome, or promoted control.","why_low_gross9_overlap_is_plausible":"irregular actual cash-close energy-regime transitions are absent from Gross9"},
 "features":{"source":{"path":str(SOURCE),"sha256":SOURCE_SHA},"spillover_score":"UNG log(close/open)-0.5*(USO log(close/open)+BNO log(close/open)), finite strict nonzero","previous":"immediately prior source-valid common energy session","transition":"current and previous spillover scores have strict opposite signs","availability":"five minutes after frozen actual NYSE close, including early close","variation_gate":"frozen causal BTC variation_rank>=0.65","no_imputation":True},"policy":{"variation_rank_min":.65,"feature_delay_minutes":5,"entry_delay_minutes_after_feature":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},"clock":{"entry":"actual close+10m exact BTCUSDT open","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal entry","funding":"not signal input; exact settlements after Gross9"},"stages":g["stages"],"source_support_gates":g["source_support_gates"],"gross9_novelty_gates":g["gross9_novelty_gates"],"economic_gates":g["economic_gates"],"diagnostic_controls":{"names":["no_variation_gate","level_not_transition","one_session_stale_transition","previous_side","direction_flip","forced_long"],"cannot_be_promoted":True},"research_boundary":{"prior_HVECSP_train_failure_known":True,"HVECSP_event_set_or_controls_reused":False,"exact_transition_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"classification":"exploratory discovery; not fresh confirmatory evidence","selection_basis":"energy spillover polarity regime transition"},"stopping_rule":"source, Gross9, train/test/eval/final; terminal first failure; no proxies, weighting, score, previous-session law, transition, variation, side, clock, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x!=build():raise RuntimeError("HVECTR prereg drift")
 if sha256(SOURCE)!=SOURCE_SHA:raise RuntimeError("HVECTR source drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
