"""Outcome-blind preregistration for HVKRMR-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVKRMR-24";DEFAULT_OUTPUT=Path("results/high_volatility_kurtosis_regime_momentum_relay_preregistration_2026-08-09.json");MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_kurtosis_regime_momentum_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"An extreme realized-kurtosis completed UTC day during elevated realized variation identifies discontinuous, information-heavy price discovery rather than diffuse noise. Follow the completed BTC day direction for twenty-four elapsed hours.","side":"strict sign of completed UTC-day BTC log return","why_distinct":"No repository alpha uses causal realized kurtosis or quarticity concentration as its primary economic object. Realized-skew reversal, bipower-jump reversal, dominant-bar, entropy, and range candidates use different moments or event geometry.","why_suited_to_volatile_regimes":"published quantile evidence reports a role for lagged Bitcoin realized kurtosis in upper return tails; the candidate separately requires causal elevated BTC variation","why_low_gross9_overlap_is_plausible":"a daily fourth-moment price-discovery clock is absent from Gross9"},
 "features":{"source":"exact completed BTCUSDT 5m OHLC","day":"UTC [D,D+1), exact 288 five-minute bars","returns":"288 close-to-close log returns; first return uses D 00:00 close versus D-1 23:55 close","day_return":"log(D 23:55 close / D 00:00 open), strict nonzero","realized_variation":"sum of squared five-minute returns","realized_kurtosis":"288*sum(r^4)/(sum(r^2)^2), finite with positive variation","kurtosis_rank":"strict-prior midrank over at most 270 valid completed days, minimum 180, current excluded; rank>=0.80","variation_rank":"strict-prior midrank of sqrt(realized_variation) over same policy, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"D+1 00:00 UTC","entry":"decision+5m BTCUSDT open","hold":"24 elapsed hours","side":"completed day return sign","reservation":"daily nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements after novelty"},
 "policy":{"history_days":270,"minimum_history_days":180,"kurtosis_rank_min":.80,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all stages","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"definitions":{"no_kurtosis_tail":"day direction and variation gate without kurtosis rank","no_variation_gate":"day direction and kurtosis tail only","one_day_stale_moments":"prior day moments and direction","direction_flip":"negative primary side","same_clock_forced_long":"side +1 on primary clock"},"cannot_be_promoted":True},
 "source_plan":{"historical_market":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m through 2026-08-01","execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"paper":"Quantile prediction for Bitcoin returns using financial assets' realized measures, Finance Research Letters 55A (2023) 103843","paper_url":"https://doi.org/10.1016/j.frl.2023.103843","prior_price_family_outcomes_known":True,"prior_event_sets_or_controls_reused":False,"exact_hvkrmr_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent realized fourth-moment regime mechanism"},
 "stopping_rule":"terminal first failure; no source, moment, rank, variation, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVKRMR prereg drift")
 if hashlib.sha256(MARKET.read_bytes()).hexdigest()!=MARKET_SHA:raise RuntimeError("HVKRMR market drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
