"""Outcome-blind preregistration for HVRDBR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVRDBR-6";DEFAULT_OUTPUT=Path("results/high_volatility_record_discovery_breadth_relay_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_record_discovery_breadth_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"Within a high-variation completed eight-hour BTC auction, repeated strict running-high discoveries versus running-low discoveries measure which side is actively expanding the accepted range. When that record-discovery breadth is unusually one-sided, follow the dominant discovery direction for six hours.","side":"sign(running-high discovery count minus running-low discovery count)","why_distinct":"HVRTR used only the occurrence order of the single absolute daily high and low plus close location. HVRDBR counts every strict sequential range expansion in fixed eight-hour blocks. Donchian and reclaim candidates test one boundary crossing; confirmation ladders use external block ordering. No prior event set or control is reused.","volatile_market_target":"completed-block realized-variation causal rank must be at least 0.65","why_low_gross9_overlap_is_plausible":"record-discovery breadth at fixed eight-hour boundaries is absent from Gross9"},
 "features":{"decision_grid":"exact UTC 00:00, 08:00, and 16:00 boundaries","block":"96 exact coherent BTCUSDT perpetual five-minute aggregates in [D-8h,D), each from five unique 1m rows","running_high_discovery":"for bars 2..96, bar high strictly exceeds every earlier bar high in the block","running_low_discovery":"for bars 2..96, bar low strictly falls below every earlier bar low in the block","breadth":"high-discovery count minus low-discovery count; strict nonzero","discovery_share":"abs(breadth)/(high count+low count), denominator strict positive","realized_variation":"sqrt(sum squared five-minute log(close/open) returns), strict positive","causal_ranks":"strict-prior midranks of discovery_share and realized_variation over at most 270 earlier source-valid blocks, minimum 252; current excluded","eligibility":"discovery-share rank>=0.65 and variation rank>=0.65","no_imputation":True},
 "clock":{"decision":"exact block boundary after all source bars complete","entry":"exact BTCUSDT decision+5m open","side":"record-discovery breadth sign","hold":"6 elapsed hours","reservation":"fixed blocks and holds are nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding_oi_premium_rv20":"not signal inputs; funding only after novelty; RV20 q90 only after all economics pass"},
 "policy":{"block_hours":8,"bars_5m":96,"history_blocks":270,"minimum_history_blocks":252,"discovery_share_rank_min":.65,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_discovery_share_gate","no_variation_gate","net_block_return_side","one_block_stale_features","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"read_only":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"related_range_path_outcomes_known":True,"record_counts_used_to_select_rule":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent sequential range-expansion breadth mechanism"},
 "stopping_rule":"terminal first failure; no block, discovery definition, rank, history, threshold, side, timing, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVRDBR preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
