"""Outcome-blind preregistration for HVSAUD-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_cross_structure_action_vote as gates
POLICY_ID="HVSAUD-8";DEFAULT_OUTPUT=Path("results/high_volatility_spot_adverse_underwater_duration_relay_preregistration_2026-08-18.json");VARIATION=Path("data/high_volatility_adverse_underwater_duration_sources_2023_2026/states.csv.gz");VARIATION_SHA="50a1cd219dd54d7562a3a4216ef9a0305d349f459a2768cba529d2c2cf1127f6"
def sha256(p:str|Path)->str:return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 g=gates.build();core={"protocol_version":"high_volatility_spot_adverse_underwater_duration_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-18","singleton":True,"candidate_family":[POLICY_ID],"candidate_family_size":1,"source_incidence_opened":False,"outcomes_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"A volatile completed BTC spot move that spends little uninterrupted time away from its running favorable close extreme is repeatedly discovering new cash prices rather than relying on one terminal impulse; when the full spot block and final two hours agree, follow that cash direction for eight hours.","side":"common strict sign of completed spot eight-hour and final-two-hour returns","why_distinct":"HVAUD is perpetual-only. HVSAUD independently computes running-extreme underwater duration on actual spot closes and uses perpetual variation solely as the requested volatile-regime gate. It uses no HVAUD event set, volume, flow, OI, funding, premium, options, fitted outcome, or promoted control.","why_low_gross9_overlap_is_plausible":"spot path-duration onsets are absent from Gross9 primitives"},
 "features":{"variation_source":{"path":str(VARIATION),"sha256":VARIATION_SHA},"decision_grid":"exact 00:00,08:00,16:00 UTC boundaries","spot_block":"480 exact coherent bars_binance_spot BTCUSDT one-minute rows [D-8h,D)","block_return":"log(last close/first open), strict nonzero","late_return":"log(last close/open at D-2h), same strict sign as block return","directional_underwater":"for positive side close strictly below running maximum close; for negative side close strictly above running minimum close","adverse_duration":"longest consecutive directional-underwater run divided by 480","duration_rank":"strict-prior midrank over at most 270 spot-valid blocks, minimum 180, current excluded; rank<=0.25","variation_gate":"frozen causal perpetual variation_rank>=0.65 at same decision","onset":"eligible now and immediately prior exact jointly valid block ineligible; missing prior cannot trigger","no_imputation":True},
 "policy":{"duration_observations":480,"history_blocks":270,"minimum_history_blocks":180,"variation_rank_min":.65,"duration_rank_max":.25,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "clock":{"entry":"decision+5m exact BTCUSDT perpetual open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal entry","funding":"not signal input; exact settlements only after source and Gross9 pass"},"stages":g["stages"],"source_support_gates":g["source_support_gates"],"gross9_novelty_gates":g["gross9_novelty_gates"],"economic_gates":g["economic_gates"],"diagnostic_controls":{"names":["no_duration_tail","no_variation_gate","raw_duration_at_most_half","one_block_stale_geometry","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"table":"bars_binance_spot","symbol":"BTCUSDT","interval":"1m","window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True,"execution_prices":"sealed until source and Gross9 pass"},
 "research_boundary":{"prior_HVAUD_train_ratio_failure_known":True,"HVAUD_event_set_reused":False,"exact_spot_duration_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"classification":"exploratory discovery; not fresh confirmatory evidence","selection_basis":"independent actual-cash running-extreme duration geometry"},
 "stopping_rule":"source, Gross9, train/test/eval/final; terminal first failure; no venue, duration formula, history, rank, variation, return confirmation, side, clock, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x!=build():raise RuntimeError("HVSAUD prereg drift")
 if sha256(VARIATION)!=VARIATION_SHA:raise RuntimeError("HVSAUD variation source drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
