"""Outcome-blind preregistration for HVLDAR-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVLDAR-8";SLUG="high_volatility_leverage_displacement_amplification_reversal";DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-13.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":f"{SLUG}_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-13","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"When BTC spot and perpetual close a five-minute auction in the same direction but the perpetual's absolute return exceeds spot by a causal extreme amount, leverage has amplified rather than discovered the cash move. During elevated BTC variation, fade the common direction for eight hours as the leverage-only displacement mean reverts.","side":"opposite the common strict spot and perpetual return sign","why_distinct":"Spot displacement dominance follows repeated multi-hour cash-over-leverage return dominance. Basis and error-correction use price-level spreads. HVLOWR uses high/low excursion rejection with cash nonconfirmation. HVLDAR uses only the same-direction close-to-open return magnitude excess of the perpetual over spot on one completed five-minute auction and fades leverage amplification. It uses no high/low geometry, volume, flow, basis level, funding, OI, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"causal trailing perpetual 24-hour realized variation must occupy its upper 35 percent","why_low_gross9_overlap_is_plausible":"irregular same-direction cross-market displacement-amplification onsets are absent from Gross9 primitives"},
 "features":{"decision_grid":"every exact UTC five-minute boundary D","market_bars":"five exact coherent native one-minute BTCUSDT perpetual and spot rows [D-5m,D)","perpetual_return":"log(perpetual close/open), strict nonzero","spot_return":"log(spot close/open), strict nonzero","direction_confirmation":"returns share one strict sign","leverage_excess":"absolute perpetual_return minus absolute spot_return","excess_rank":"strict-prior midrank over at most 8640 jointly valid decisions, minimum 6048, current excluded; rank>=0.995","btc_realized_variation":"sqrt(sum squared exact perpetual one-minute log(close/open) returns over [D-24h,D))","variation_rank":"strict-prior midrank over at most 8640 jointly valid decisions, minimum 6048, current excluded; rank>=0.65","onset":"full directional amplification true now and false at immediately prior exact source-valid decision; missing prior cannot trigger","no_imputation":True},
 "clock":{"decision":"D after both completed bars and causal ranks are available","entry":"exact BTCUSDT perpetual D+5m open","side":"opposite common completed return direction","hold":"8 elapsed hours","reservation":"global chronological half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements only after novelty"},
 "policy":{"history_decisions":8640,"minimum_history_decisions":6048,"excess_rank_min":.995,"variation_bars":288,"variation_rank_min":.65,"onset_required":True,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_variation_gate","rank_0_99","cash_displacement_dominance","one_bar_stale_amplification","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"perpetual":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m"},"spot":{"table":"bars_binance_spot","symbol":"BTCUSDT","interval":"1m"},"columns":["ts","open","high","low","close"],"window":["2023-05-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration_commit":True,"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"adjacent_spot_displacement_basis_and_leverage_wick_outcomes_known":True,"repository_exact_same_direction_leverage_close_displacement_tail_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent leverage amplification of confirmed cash displacement"},
 "stopping_rule":"terminal first failure; no market, bar, return, magnitude excess, rank history, rank threshold, confirmation, variation, onset, side, clock, hold, subset, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x):
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}) or x!=build():raise RuntimeError("HVLDAR prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);b=(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n").encode()
 if a.output.exists() and a.output.read_bytes()!=b:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_bytes(b);print(a.output)
