"""Outcome-blind preregistration for HVEPUH-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVEPUH-24";DEFAULT_OUTPUT=Path("results/high_volatility_epu_hedge_relay_preregistration_2026-08-09.json");SOURCE=Path("data/us_daily_epu_1985_2026_aug.csv");MARKET=Path("data/cache_market_ext_5m_wavefull_2020-01-01_2026-06-01.csv.gz");MARKET_SHA="a77cd0ae5b88b3c95e509d8d2610773d34af3afdc9170c63d88564bc3d0b990c";URL="https://www.policyuncertainty.com/media/All_Daily_Policy_Data.csv"
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_epu_hedge_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","singleton":True,"outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,
 "mechanism":{"claim":"A large daily rise or fall in newspaper-based US Economic Policy Uncertainty during elevated BTC variation identifies an extreme uncertainty shock. Consistent with evidence that Bitcoin can hedge uncertainty at distribution tails, follow the EPU change direction for one day.","side":"strict sign of the completed source-day log EPU change","why_distinct":"No existing repository alpha uses the official daily US EPU index. FX, Treasury, Cboe, fear-greed, premium, options, and on-chain candidates use different economic objects and clocks.","why_suited_to_volatile_regimes":"quantile-causality research reports EPU predictive content for Bitcoin returns especially under extreme market conditions, and the candidate additionally requires causal high BTC variation","why_low_gross9_overlap_is_plausible":"a conservatively delayed official news-uncertainty clock is absent from Gross9"},
 "features":{"source":"official Baker-Bloom-Davis US Daily News-Based Economic Policy Uncertainty CSV","source_url":URL,"observation":"positive finite daily_policy_index for calendar day D","availability":"D+2 00:00 UTC, deliberately later than the next-day daily release; no same-day or D+1 use","valid_change":"D and D-1 exact consecutive calendar observations, both positive","epu_change":"log(EPU[D]/EPU[D-1]), strict nonzero","epu_shock_rank":"strict-prior midrank of abs(epu_change) over at most 270 valid changes, minimum 180, current excluded; rank>=0.75","btc_variation":"sqrt(sum squared exact completed 5m BTC log returns over UTC day D+1, ending at decision)","btc_variation_rank":"strict-prior midrank over at most 270 source-valid decisions, minimum 180, current excluded; rank>=0.65","no_imputation":True},
 "clock":{"decision":"D+2 00:00 UTC","entry":"decision+5m BTCUSDT open","hold":"24 elapsed hours","side":"EPU change sign","reservation":"daily nonoverlapping; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not signal input; exact settlements after novelty"},
 "policy":{"epu_history_days":270,"minimum_history_days":180,"epu_shock_rank_min":.75,"btc_variation_rank_min":.65,"publication_delay_days":2,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all stages","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"definitions":{"no_epu_tail":"EPU direction and high BTC variation without shock rank","no_btc_variation_gate":"EPU shock tail without BTC variation rank","one_day_stale_epu":"prior exact EPU change with current BTC variation gate","direction_flip":"negative primary side","same_clock_forced_long":"side +1 on primary clock"},"cannot_be_promoted":True},
 "source_plan":{"epu":{"url":URL,"destination":str(SOURCE),"download_after_preregistration_commit":True,"read_only_snapshot":True},"historical_market":{"path":str(MARKET),"sha256":MARKET_SHA},"live_extension":"read-only Postgres BTCUSDT 1m through 2026-08-01","execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"paper":"When, where, and how economic policy uncertainty predicts Bitcoin returns and volatility? A quantiles-based analysis, Quarterly Review of Economics and Finance 80 (2021) 65-73","paper_url":"https://ideas.repec.org/a/eee/quaeco/v80y2021icp65-73.html","prior_macro_outcomes_known":True,"prior_event_sets_or_controls_reused":False,"exact_hvepuh_incidence_or_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent official daily news uncertainty mechanism"},
 "stopping_rule":"terminal first failure; no source, delay, rank, variation, side, clock, hold, subset, threshold, comparator, or control repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("HVEPUH prereg drift")
 if SOURCE.exists():raise RuntimeError("HVEPUH source must not exist before preregistration freeze")
 if hashlib.sha256(MARKET.read_bytes()).hexdigest()!=MARKET_SHA:raise RuntimeError("HVEPUH market drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
