"""Outcome-blind preregistration for TECC-12."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="TECC-12";DEFAULT_OUTPUT=Path("results/ticket_expansion_concordance_continuation_preregistration_2026-08-09.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"ticket_expansion_concordance_continuation_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-09","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A six-hour move that remains directionally concordant while average executed quote ticket expands in the final two hours is more likely sponsored than churn. Follow the common direction for twelve elapsed hours.","side":"common strict sign of completed early four-hour and late two-hour returns","why_distinct":"TECC uses within-BTC temporal expansion of quote volume per reported trade. It is not cross-asset ticket leadership, spot/perpetual count share, small-ticket exhaustion, taker imbalance, VWAP contradiction, funding, or a volatility threshold.","volatile_market_target":"sponsored ticket expansion should retain direction during volatile auctions; causal RV20 q90 is only a later audit","why_low_gross9_overlap_is_plausible":"strict-prior ticket-expansion tail plus concordance onset creates sparse state-dependent clocks rather than a fixed schedule"},
 "features":{"decision_grid":"every exact 4-hour UTC boundary","window":"exact 360 one-minute bars [decision-6h,decision)","early_block":"first 240 bars [decision-6h,decision-2h)","late_block":"last 120 bars [decision-2h,decision)","early_return":"log(early last close/early first open), strict nonzero","late_return":"log(late last close/late first open), strict nonzero","early_ticket":"sum early quote_asset_volume/sum early number_of_trades","late_ticket":"sum late quote_asset_volume/sum late number_of_trades","ticket_expansion":"log(late_ticket/early_ticket), strict positive","ticket_expansion_rank":"strict-prior midrank over at most 540 prior valid decision observations; minimum 360; current excluded","eligible_state":"ticket expansion rank>=0.80 and early/late returns have the same sign","onset":"eligible state true and immediately preceding 4-hour decision eligible state false","source_valid":"exact unique minute grid, coherent finite positive OHLC, finite nonnegative quote volume, finite nonnegative integer trade counts, positive block quote volume and trade-count denominators; no imputation"},
 "rv20_stress_slice":{"rv20":"sqrt(365*mean exact daily returns^2 over t-20 through t-1)","threshold":"numpy linear q90 over 756 strictly prior available RV20 observations","entry_filter":False,"future_use":"only after all sequential full-calendar stages pass"},
 "clock":{"decision":"exact 4-hour UTC boundary after all source bars complete","entry":"exact BTCUSDT decision+5m open","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact realized funding only after novelty"},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","persistent_long_vol_comparator":"same accepted clock and 0.5 gross, side forced long","full_calendar_decomposition":"candidate minus comparator net return","rv20_q90_decomposition":"same decomposition on causal RV20 q90 decisions","minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"candidate_specific_q90_residual_positive":True,"comparator_cannot_satisfy_candidate_claim":True},
 "diagnostic_controls":{"definitions":{"no_ticket_tail":"same-sign early/late returns with positive raw ticket expansion onset","no_concordance":"ticket-tail onset following the late return side without early/late sign agreement","early_ticket_dominance":"same-sign returns with positive early-over-late ticket expansion in its strictly-prior top quintile onset, following the common return side","direction_flip":"negative primary side"},"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume","number_of_trades"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"exact_tecc_outcomes_known":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False},"stopping_rule":"terminal first failure; no rank, history, onset, block, side, clock, hold, RV20, subset, comparator, control, or gate repair"};return {**core,"manifest_hash":canonical_hash(core)}
def validate(x:dict[str,Any])->None:
 if x.get("manifest_hash")!=canonical_hash({k:v for k,v in x.items() if k!="manifest_hash"}):raise RuntimeError("TECC preregistration drift")
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();validate(r);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+"\n");print(a.output)
