"""Outcome-blind preregistration for CVDTSR-24."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="CVDTSR-24";DEFAULT_OUTPUT=Path("results/cboe_direct_term_slope_rotation_relay_preregistration_2026-08-12.json")
SURFACE=Path("data/cboe_volatility_surface_2021_2026/cboe_volatility_surface_2021-01-01_2026-08-07.csv.gz");SURFACE_SHA="42eb1093f5167aec9c71a4733ab3451e40807c81dc7cb49568a6a0c634267ba0";MANIFEST=Path("data/cboe_volatility_surface_2021_2026/manifest.json");MANIFEST_SHA="ec1dd33efcee29b75c80294fb594969cd1b12a9343fc40f888525db4400bc936"
def chash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build():
 core={"protocol_version":"cboe_direct_term_slope_rotation_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-12","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"An unusually large completed one-session rotation in the direct Cboe VIX9D-to-VIX3M endpoint slope isolates repricing from immediate to quarterly equity volatility. During elevated BTC variation, rising short-end pressure maps short BTC and falling pressure maps long BTC for twenty-four hours after conservative next-session availability.","side":"negative strict sign of delta log(VIX9D/VIX3M)","why_distinct":"CVCIR requires same-sign changes in both VIX9D/VIX and VIX/VIX3M plus elevated VIX; CVACR additionally requires VIX acceleration; static term candidates rank levels. CVDTSR uses only the direct endpoint-ratio first difference, admits internally offsetting component moves, has no VIX level or crypto-vol confirmation, and reuses no event/control.","volatile_market_target":"direct slope rotation and completed prior-24h BTC variation must independently enter causal upper tails","why_low_gross9_overlap_is_plausible":"one delayed official daily external-volatility clock is absent from Gross9"},
 "features":{"surface":"strictly ordered common Cboe observation dates with positive finite VIX9D_close and VIX3M_close","direct_slope":"log(VIX9D_close/VIX3M_close)","slope_rotation":"current direct_slope minus immediately previous source observation direct_slope, strict nonzero","rotation_rank":"strict-prior midrank of abs(slope_rotation) over at most 252 valid observations, minimum 126, current excluded; rank>=0.65","btc_variation":"sum squared BTCUSDT one-minute log(close/open) over exact 24 elapsed hours ending at next source-session 09:30 ET decision","btc_variation_rank":"strict-prior midrank over at most 270 valid decisions, minimum 180, current excluded; rank>=0.65","eligible_state":"both rank gates pass","onset":"eligible now and immediately prior exact valid source decision ineligible","no_imputation":True},
 "clock":{"decision":"next Cboe observation date 09:30 America/New_York after source date","entry":"decision+5m BTCUSDT open","side":"-sign slope_rotation","hold":"24 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not an input; exact settlements only after novelty"},
 "policy":{"rotation_prior":252,"rotation_minimum":126,"rotation_rank_min":.65,"variation_prior":270,"variation_minimum":180,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp/10bp per notional side, held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged all-stage pass","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_rotation_tail","no_btc_variation_gate","one_session_stale_rotation","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"surface":{"path":str(SURFACE),"sha256":SURFACE_SHA,"manifest":str(MANIFEST),"manifest_sha256":MANIFEST_SHA},"btc":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","close"],"read_after_preregistration":True},"execution_prices":"sealed until source and novelty pass"},
 "research_boundary":{"prior_cboe_term_family_outcomes_known":True,"exact_direct_endpoint_rotation_candidate_found":False,"prior_event_sets_or_controls_reused":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"independent direct VIX9D/VIX3M endpoint slope rotation"},
 "stopping_rule":"terminal first failure; no source, slope, delay, rank, side, clock, hold, subset, threshold, or control repair"};return {**core,"manifest_hash":chash(core)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=chash(core) or x!=build():raise RuntimeError("CVDTSR prereg drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
