"""Outcome-blind preregistration for HVZLEMA-C10-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVZLEMA-C10-24"
DEFAULT_OUTPUT=Path("results/high_volatility_zero_lag_exponential_moving_average_price_crossover_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_zero_lag_exponential_moving_average_price_crossover_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
  mechanism={"claim":"During elevated realized variation, a completed four-hour BTC close crossing its documented ten-period Zero Lag Exponential Moving Average identifies a trend change after compensating the input for conventional moving-average lag; follow the new relation for twenty-four hours.","side":"long when close crosses strictly above ZLEMA(10); short when close crosses strictly below it","why_distinct":"ZLEMA first advances close by subtracting its rounded four-bar delayed value, then applies a ten-period EMA. It is not an ordinary EMA/SMA, HMA/ALMA turn, oscillator, channel, range path, volume, flow, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"lag compensation is designed to react to directional changes without waiting for a conventional average, while completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse four-hour price crossings of a lag-compensated recursive trend estimate are absent from Gross9 primitives"},
  external_basis={"origin":"John Ehlers and Ric Way Zero Lag Exponential Moving Average; QuantConnect LEAN canonical implementation","definition_source":"https://github.com/QuantConnect/Lean/blob/master/Indicators/ZeroLagExponentialMovingAverage.cs","documentation_source":"https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators/zero-lag-exponential-moving-average","fixed_definition":"documented period 10; lag=round((10-1)/2)=4 under LEAN/.NET midpoint-to-even rounding; adjusted input=close+(close-close delayed four decisions); EMA(10) with LEAN SMA seed then recursive alpha=2/11; readiness after 15 uninterrupted bars","selection_use":"official formula, documented example period, readiness, and standard price/average crossover only; no incidence or outcomes"},
  features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T)","delayed_close":"completed close four valid decisions earlier","adjusted_close":"2*current close-delayed close","zlema":"LEAN EMA(10) of adjusted close, seeded by the first ten adjusted inputs","event":"current close newly strictly above finite ZLEMA from not above gives +1; newly strictly below from not below gives -1","variation":"sqrt(sum squared completed five-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","recursive_reset":"delay, EMA, and crossover state reset after any invalid completed four-hour bar","no_imputation":True},
  clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
  policy={"period":10,"delay_bars":4,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
  diagnostic_controls={"names":["no_variation_gate","ordinary_ema_crossover","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
  source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
  research_boundary={"canonical_zlema_definition_read":True,"repository_zlema_candidate_found":False,"prior_moving_average_candidate_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"official ZLEMA(10) price crossover under the requested high-variation regime"},
  stopping_rule="Terminal first failure; no period, delay rounding, EMA seed, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVZLEMA-C10-24 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
