"""Outcome-blind preregistration for HVQHOFR-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVQHOFR-8";DEFAULT_OUTPUT=Path("results/high_volatility_quarter_hour_order_flow_relay_preregistration_2026-08-11.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_quarter_hour_order_flow_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"At cryptocurrency quarter-hour openings, concentrated algorithmic activity makes the completed first-five-minute aggressive quote imbalance informative. When its absolute imbalance is causally strong and trailing BTC realized variation is elevated, follow the imbalance direction for eight hours.","side":"strict sign of completed quarter-hour opening aggressive quote imbalance","why_distinct":"Existing fixed eight-hour flow candidates aggregate long blocks or compare halves; hour-of-week candidates use calendar means; trade-arrival candidates ignore quarter-hour phase. HVQHOFR uses 96 daily quarter-hour openings, a completed five-minute flow window, causal strength and volatility ranks, and an onset/reservation clock, without fitted returns, prior events, or promoted controls.","why_suited_to_volatile_regimes":"trailing completed 24-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"entry minutes :10/:25/:40/:55 and quarter-hour onset reservation are absent from Gross9 primitives"},
 external_basis={"paper":"The Quarter-Hour Effect: Periodic Algorithmic Trading and Return Predictability in Cryptocurrency Futures","authors":"Chan Kim and Peter Reinhard Hansen","published":"2026-07-10","url":"https://arxiv.org/abs/2607.09426","reported_horizon":"opening order imbalance forecasts four-to-twelve-hour futures returns","selection_use":"mechanism and fixed eight-hour horizon only; no repository incidence or outcome opened"},
 features={"quarter_anchor":"every exact UTC :00/:15/:30/:45 boundary A","opening_window":"five exact completed BTCUSDT one-minute rows [A,A+5m)","feature_available_time":"A+5m","opening_imbalance":"(2*sum(taker_buy_quote)-sum(quote_asset_volume))/sum(quote_asset_volume), positive denominator and strict nonzero","imbalance_strength":"absolute opening imbalance","trailing_variation":"sqrt(sum squared log(close/open) over 1,440 exact completed one-minute rows [A-24h,A)), finite strict positive","prior_ranks":"strict-prior midranks over at most 2,688 earlier source-valid quarter windows, minimum 1,920, current excluded","strength_gate":"imbalance-strength rank>=0.75","variation_gate":"trailing-variation rank>=0.65","onset":"eligible now and immediately preceding exact source-valid quarter window ineligible; missing prior cannot trigger","no_imputation":True},
 clock={"decision":"A+5m after opening window completes","entry":"exact BTCUSDT A+10m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_windows":2688,"minimum_history_windows":1920,"imbalance_strength_rank_min":.75,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_imbalance_strength","no_variation_gate","no_onset_requirement","one_window_stale_features","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume","taker_buy_quote"],"window":["2023-05-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"external_primary_mechanism_read":True,"repository_quarter_hour_order_flow_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"paper-supported quarter-hour periodic order-flow predictability with fixed causal ranks"},
 stopping_rule="Terminal first failure; no quarter phase, opening window, rank history, strength, variation, onset, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVQHOFR preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
