"""Outcome-blind preregistration for HVDPR-6."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
DEFAULT_OUTPUT=Path("results/high_volatility_directional_persistence_relay_preregistration_2026-08-08.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_directional_persistence_relay_v1","policy_id":"HVDPR-6","as_of_date":"2026-08-08","outcomes_opened":False,"mechanism":{"claim":"In an already elevated BVOL-and-DVOL regime, a fixed eight-hour BTC move whose first and second four-hour returns agree and whose total displacement and close-path efficiency are both unusually high represents persistent price discovery rather than a transient shock; the direction should relay for six hours.","side":"sign of the completed eight-hour BTC return","why_distinct":"HVDPR is a persistent-trend state: same-direction block halves plus high total displacement and high path efficiency. It is not HVCRR's inefficient chop/range escape, CVVIB's volatility ignition, intrahour absorption, funding direction, or a control promotion.","why_low_gross9_overlap_is_plausible":"signals occur only at fixed eight-hour boundaries and require dual implied-volatility levels plus multi-hour directional persistence absent from Gross9"},
 "clock":{"decision":"exact UTC 00:00/08:00/16:00 boundary D after eight consecutive completed valid hours [D-8h,D)","volatile_regime":"BVOL close and DVOL close at D each >= own strict-prior 720h q60 with 672 observations","directional_persistence":"nonzero first-four-hour and second-four-hour BTC returns have the same sign","large_move":"absolute eight-hour return >= strict-prior 270-block q60 with 252 observations","path_efficiency":"absolute eight-hour return divided by sum of eight absolute hourly returns >= strict-prior 270-block q60 with 252 observations; zero denominator invalid","entry":"exact BTCUSDT D+5m open","side":"sign of eight-hour return","hold":"6 elapsed hours","reservation":"fixed blocks are nonoverlapping; global half-open, exit first on equal open","funding":"not a signal input; exact settlements only for later PnL","oi":"not a signal input","no_imputation":True},
 "policy":{"block_hours":8,"half_hours":4,"prior_blocks":270,"prior_min_blocks":252,"absolute_return_quantile":.60,"path_efficiency_quantile":.60,"volatility_level_prior_hours":720,"volatility_level_min_hours":672,"volatility_level_quantile":.60,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},"stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},"source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},"novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},"economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"future_can_rank_repair_or_reselect":False,"accounting":"fixed quantity, exact funding marks, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},"source_plan":{"volatility":"reuse hash-bound OCDR-12C BVOL/DVOL snapshot through 2026-08-01","completed_price_path":"reuse hash-bound OLIAH completed-hour intrahour snapshot through 2026-08-01","execution_price":"sealed until source-support and Gross9 novelty pass"},"research_boundary":{"prior_candidate_incidence_known":True,"prior_candidate_outcomes_used_for_hvdpr":False,"hvdpr_candidate_incidence_opened":False,"hvdpr_post_entry_return_or_pnl_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False}}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();a.output.write_text(json.dumps(build(),indent=2,ensure_ascii=False)+"\n");print(a.output)
