"""Outcome-blind preregistration for HVHVS-8."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVHVS-8";DEFAULT_OUTPUT=Path("results/high_volatility_har_variation_surprise_relay_preregistration_2026-08-10.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_har_variation_surprise_relay_v1","policy_id":POLICY_ID,"as_of_date":"2026-08-10","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"A completed eight-hour BTC block whose realized path variation greatly exceeds a fixed heterogeneous multi-scale forecast is a volatility innovation. When the block and its final two hours agree directionally and the full path converts variation into displacement efficiently, the innovation represents directional price discovery rather than two-way churn and should continue for eight hours.","side":"common strict sign of completed eight-hour and final-two-hour returns","why_distinct":"HVHVS uses a fixed HAR-style forecast from lagged block, daily, and weekly variation scales and ranks the current forecast innovation. Variance-acceleration candidates compare adjacent halves; temporal ignition uses within-block concentration; directional-persistence candidates use implied-volatility levels. HVHVS uses no implied volatility, flow, volume, funding, OI, cross-assets, prior event rows, or controls.","why_suited_to_volatile_regimes":"a top-quartile positive realized-variation forecast surprise directly identifies an unexpectedly volatile regime","why_low_gross9_overlap_is_plausible":"three fixed UTC forecast-innovation onsets with an eight-hour reservation are absent from Gross9 primitives"},
 "features":{"decision_grid":"exact 00:00/08:00/16:00 UTC boundaries","block":"480 exact coherent BTCUSDT bars_binance interval=1m rows [D-8h,D)","realized_variation":"sqrt(sum squared one-minute close-to-close log returns), strict positive","har_forecast":"arithmetic mean of prior block RV, mean of three strictly prior block RVs, and mean of twenty-one strictly prior block RVs; all 21 prior exact valid blocks required; current excluded","variation_surprise":"log(current realized variation / HAR forecast), strict positive","surprise_rank":"strict-prior midrank over at most 270 valid positive surprises, minimum 180, current excluded; rank>=0.75","block_return":"log(last close/first open) over eight hours","late_return":"log(last close/open at D-2h) over final two hours","path_efficiency":"abs(block_return)/sum absolute one-minute close-to-close returns, strict positive","efficiency_rank":"strict-prior midrank over at most 270 valid blocks, minimum 180, current excluded; rank>=0.60","direction_confirmation":"block and late returns have one strict nonzero sign","onset":"eligible now and immediately prior exact valid block ineligible; missing prior opportunity cannot trigger","no_imputation":True},
 "clock":{"decision":"completed eight-hour boundary","entry":"exact BTCUSDT perpetual D+5m open","side":"common completed-return sign","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","funding":"not a signal input; exact settlements only after novelty passes"},
 "policy":{"har_block_lags":1,"har_daily_blocks":3,"har_weekly_blocks":21,"history_blocks":270,"minimum_history_blocks":180,"surprise_rank_min":.75,"efficiency_rank_min":.60,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.20,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.10,"candidate_near_6h_share_max":.35,"occupied_5m_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.10,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes train, test, eval, final","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_surprise_tail","no_efficiency_gate","raw_positive_surprise","one_block_stale_geometry","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"prior_variance_and_trend_family_outcomes_known":True,"repository_har_forecast_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_hvhvs_formula_ranks_direction_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"fixed heterogeneous multi-scale realized-variation forecast innovation"},
 "stopping_rule":"Terminal first-failure sequence: source support, Gross9 novelty, strict economics; no formula, rank, side, hold, clock, subset, or control repair."}
 return {**core,"manifest_hash":canonical_hash(core)}
if __name__=="__main__":p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();r=build();a.output.write_text(json.dumps(r,indent=2)+"\n");print(a.output)
