"""Outcome-blind preregistration for HVDHSVPR-8."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVDHSVPR-8";DEFAULT_OUTPUT=Path("results/high_volatility_dual_half_signed_volume_persistence_relay_preregistration_2026-08-10.json")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_dual_half_signed_volume_persistence_relay_v1",policy_id=POLICY_ID,
 mechanism={"claim":"When quote turnover attached to up versus down minute candles has the same strong polarity in both halves of a volatile completed BTC block, participation is persistently sponsoring one direction rather than reflecting one isolated shock. Follow that direction for eight hours.","side":"common strict sign of first-half and second-half signed quote-turnover balances","why_distinct":"Aggressive-flow candidates use taker fields; range-participation weights signed range energy; return-volume covariance uses continuous return magnitude; dominant-volume candidates select one bar. HVDHSVPR uses candle-sign-assigned quote turnover separately in two fixed halves, ranks the weaker half, and uses no taker flow, endpoint return, range weight, funding, OI, cross-asset, prior event, fitted outcome, or control.","why_suited_to_volatile_regimes":"completed realized variation must rank in its causal upper 35% while both halves independently show same-side turnover sponsorship","why_low_gross9_overlap_is_plausible":"offset three-daily dual-half signed-volume clocks are absent from Gross9 primitives"},
 features={"decision_grid":"exact 02:00/10:00/18:00 UTC boundaries","block":"480 exact coherent bars_binance BTCUSDT one-minute rows [D-8h,D)","minute_return":"log(close/open), finite; sign zero retained with zero signed contribution","half_balance":"for each fixed 240-minute half, sum(quote_asset_volume*sign(minute_return))/sum(quote_asset_volume), requiring finite nonnegative turnover and strict positive denominator","dual_half_persistence":"both balances strict nonzero with the same sign","weak_half_strength":"minimum absolute half balance","strength_rank":"strict-prior midrank of weak_half_strength over at most 270 earlier source-valid blocks, minimum 180, current excluded; rank>=0.55","realized_variation":"sqrt(sum squared minute returns), finite strict positive","variation_rank":"strict-prior 270/180 midrank, current excluded; rank>=0.65","eligible_state":"dual-half persistence plus strength and variation gates","event_clock":"every eligible fixed boundary; no onset filter","no_imputation":True},
 clock={"decision":"completed eight-hour boundary","entry":"exact BTCUSDT D+5m open","hold":"8 elapsed hours","reservation":"global half-open; exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"history_blocks":270,"minimum_history_blocks":180,"strength_rank_min":.55,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":8,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_weak_half_rank","no_variation_gate","full_block_signed_volume","equal_weight_half_sign_breadth","one_block_stale_participation","direction_flip","same_clock_forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume"],"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"prior_aggressive_flow_range_participation_volume_covariance_and_dominant_volume_outcomes_known":True,"repository_dual_half_signed_volume_persistence_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_rank_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"same-side quote-turnover sponsorship in both fixed halves"},
 stopping_rule="Terminal first failure; no volume field, half split, sign rule, rank, side, hold, clock, subset, threshold, or control repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x):
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVDHSVPR preregistration drift")
if __name__=="__main__":
 a=argparse.ArgumentParser();a.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);z=a.parse_args();x=build();validate(x);z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(x,indent=2,allow_nan=False)+"\n");print(z.output)
