"""Outcome-blind preregistration for HVCVD-24."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVCVD-24";DEFAULT_OUTPUT=Path("results/high_volatility_cumulative_volume_delta_signal_crossover_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_cumulative_volume_delta_signal_crossover_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a completed four-hour Cumulative Volume Delta crossover of its fixed twenty-period exponential signal identifies a reversal in persistent aggressive buyer-versus-seller pressure; follow the new relation for twenty-four hours.","side":"long when CVD crosses strictly above its EMA(20); short on the strict reverse crossover","why_distinct":"CVD accumulates directly observed taker-buy quote notional minus inferred taker-sell quote notional. It is not OBV, price-volume trend, normalized same-day intrinsic flow, close-location weighting, rolling money flow, raw price momentum, prior candidate repair, OI, funding, fitted outcome, reused event set, or promoted control.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse continuous aggressive-notional path reversals are absent from Gross9 primitives"},
 external_basis={"origin":"canonical Cumulative Volume Delta convention","fixed_definition":"bar delta=taker buy volume-taker sell volume; CVD is its causal cumulative sum; fixed causal EMA(20) signal crossover","selection_use":"published aggressive-volume delta construction and one preregistered twenty-period signal only; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T), including quote_asset_volume and taker_buy_quote","aggressive_quote_delta":"sum(2*taker_buy_quote-quote_asset_volume) over the completed block, finite; each source row requires 0<=taker_buy_quote<=quote_asset_volume","cvd":"causal cumulative aggressive_quote_delta, reset across source gaps","signal":"causal EMA(20) of CVD with alpha=2/21, emitted after full warmup","event":"current finite nonzero CVD-signal sign differs from immediately prior finite nonzero sign","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","hold":"24 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":0.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"signal_periods":20,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":0.65,"entry_delay_minutes":5,"hold_hours":24,"leverage":0.5,"base_cost_per_notional_side":0.0006,"stress_cost_per_notional_side":0.001},
 diagnostic_controls={"names":["no_variation_gate","delta_zero_cross","one_bar_stale_cross","direction_flip"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","quote_asset_volume","taker_buy_quote"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_cvd_definition_read":True,"repository_continuous_cvd_signal_candidate_found":False,"prior_intrinsic_daily_cumulative_flow_candidates_known":True,"prior_volume_indicator_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical continuous CVD with preregistered EMA(20) signal crossover under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no signal period, CVD formula, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVCVD preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
