"""Outcome-blind preregistration for HVLZCTR-6."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVLZCTR-6";DEFAULT_OUTPUT=Path("results/high_volatility_last_zero_crossing_trend_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_last_zero_crossing_trend_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"In a volatile completed BTC path, an unusually early final visit to the opening level or the side opposite the terminal return means the terminal direction was established early rather than only at the endpoint. Follow that accepted direction for six hours.","side":"strict sign of completed twelve-hour log return","why_distinct":"Price-level occupation counts all time on each side; excursion area integrates distance; opening-drive hold imposes a first-hour range; directional timing uses squared-return centroids. HVLZCTR retains only the final passage time across the opening anchor and uses no area, count, range, volume, flow, funding, OI, fitted outcome, prior event set, or promoted control.","why_suited_to_volatile_regimes":"completed twelve-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"two daily early-last-passage clocks are absent from Gross9 primitives"},
 external_basis={"mathematical_source":"https://www.mi.uni-koeln.de/~moerters/book/book.pdf","source_sha256":"e850e30e824d33494e40c63faba0e23e364c8ccd80f58cee0d85732277071681","finance_source":"https://doi.org/10.1016/j.jfineco.2011.11.003","support":"Lévy's second arcsine law characterizes the last zero of a Brownian path, while time-series momentum research documents directional persistence and particularly strong performance in extreme markets","selection_use":"fixed last-passage statistic and terminal direction only; block clock, causal rank, volatility gate and six-hour BTC application are untested; no incidence or outcomes"},
 features={"decision_grid":"exact 00:00 and 12:00 UTC boundaries","block":"720 exact coherent bars_binance BTCUSDT one-minute rows [D-12h,D)","opening_anchor":"first one-minute open","minute_displacement":"log(each minute close/opening_anchor), finite","terminal_return":"log(last minute close/opening_anchor), strict nonzero; terminal_side is its sign","opposite_or_zero":"minute_displacement*terminal_side<=0","last_passage_fraction":"(one plus the last zero-based opposite_or_zero index)/720; zero if no such minute; finite in [0,1]","last_passage_rank":"strict-prior midrank over at most 180 earlier source-valid blocks, minimum 120, current excluded; rank<=0.30","realized_variation":"sqrt(sum squared one-minute log(close/open) returns), finite strict positive","variation_rank":"strict-prior 180/120 midrank, current excluded; rank>=0.65","eligible":"source valid and both frozen rank gates pass","no_imputation":True},
 clock={"feature_available":"completed twelve-hour boundary","entry":"exact BTCUSDT perpetual D+5m open","side":"terminal_side","hold":"6 elapsed hours","reservation":"fixed decisions do not overlap; global half-open, exit first on equal open","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"block_minutes":720,"history_blocks":180,"minimum_history_blocks":120,"last_passage_rank_max":.30,"variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":6,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 diagnostic_controls={"names":["no_last_passage_gate","no_variation_gate","occupation_share","one_block_stale_state","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"perpetual":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close"]},"window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True,"execution_price":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"arcsine_last_zero_and_time_series_momentum_sources_read":True,"repository_exact_last_zero_crossing_candidate_found":False,"prior_occupation_area_opening_drive_and_timing_outcomes_known":True,"prior_event_sets_reused":False,"prior_outcomes_used_to_set_formula_rank_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_path_candidate":False,"promoted_prior_control":False,"selection_basis":"last-passage topology of the completed price path combined with independently documented extreme-market trend persistence"},
 stopping_rule="Terminal first failure; no anchor, passage definition, block, rank, variation gate, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(v):
 core={k:x for k,x in v.items() if k!="manifest_hash"}
 if v.get("manifest_hash")!=canonical_hash(core) or v!=build():raise RuntimeError("HVLZCTR-6 preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();v=build();validate(v);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
