"""Preregister HVCARER-12 without opening incidence or outcomes."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
POLICY_ID="HVCARER-12";SLUG="high_volatility_cross_alt_range_expansion_confirmation_relay";DEFAULT_OUTPUT=Path(f"results/{SLUG}_preregistration_2026-08-11.json")
ALTS=("ADAUSDT","BNBUSDT","DOGEUSDT","ETHUSDT","SOLUSDT","XRPUSDT")
def canonical_hash(x:Any)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 core={"protocol_version":"high_volatility_cross_alt_range_expansion_confirmation_relay_v1","policy_id":POLICY_ID,"slug":SLUG,"as_of_date":"2026-08-11","outcomes_opened":False,"source_incidence_opened":False,"gross9_rows_opened":False,"singleton":True,
 "mechanism":{"claim":"When at least four of six liquid alt perpetuals simultaneously enter their own causal upper-quartile completed daily high-low ranges, volatility expansion is market-wide rather than BTC-local. If BTC also has elevated realized variation, follow its completed daily displacement for twelve hours.","side":"strict sign of the completed BTC twenty-four-hour return","why_distinct":"Cross-alt price candidates use return signs, residuals, rank persistence, tails, turnover, or close locations. Alt-variation compression compares cross-sectional dispersion across two intraday halves. HVCARER ignores every alt return direction and instead counts symbol-specific upper-tail full-auction range expansions as confirmation for an independently signed BTC displacement. It reuses no event set or control and uses no volume, flow, funding, OI, premium, or fitted outcome.","why_suited_to_volatile_regimes":"both broad alt range expansion and BTC completed realized-variation rank>=0.65 directly target July-like market-wide volatility","why_low_gross9_overlap_is_plausible":"one conditional 03:05 UTC market-wide range-expansion confirmation clock per day is absent from Gross9 primitives"},
 "features":{"decision_grid":"one exact daily 03:00 UTC decision D","symbols":list(ALTS),"source_window":"1440 exact coherent bars_binance one-minute rows per symbol over [D-24h,D)","alt_range":"log(max(high)/min(low)), finite strict positive","alt_range_rank":"per-symbol strict-prior midrank over at most 90 earlier source-valid daily decisions, minimum 60, current excluded","range_expansion":"alt_range_rank>=0.75","expansion_breadth":"at least four of six alts are in range expansion; alt return signs are never computed or used","btc_return":"log(final close/first open) over the same completed window, strict nonzero","btc_realized_variation":"sum squared one-minute log(close/open) returns, finite strict positive","btc_variation_rank":"strict-prior midrank over at most 90 earlier source-valid daily decisions, minimum 60, current excluded; rank>=0.65","eligible":"source-valid, expansion breadth>=4, BTC variation rank>=0.65, and BTC return strict nonzero","no_imputation":True},
 "clock":{"decision":"exact daily 03:00 UTC after all seven completed paths are available","entry":"exact BTCUSDT D+5m open","hold":"12 elapsed hours","reservation":"global half-open; exit first on equal open","split_crossing_action":"skip","gross_exposure":.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 "policy":{"history_days":90,"minimum_history_days":60,"alt_range_rank_min":.75,"minimum_expansion_breadth":4,"btc_variation_rank_min":.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":.5,"base_cost_per_notional_side":.0006,"stress_cost_per_notional_side":.001},
 "stages":{"train":["2023-07-01T00:00:00Z","2024-01-01T00:00:00Z"],"test":["2024-01-01T00:00:00Z","2025-01-01T00:00:00Z"],"eval":["2025-01-01T00:00:00Z","2026-01-01T00:00:00Z"],"final":["2026-01-01T00:00:00Z","2026-08-01T00:00:00Z"]},
 "source_support_gates":{"minimum_events":{"train":8,"test":12,"eval":12,"final":8},"minority_side_share_min":.2,"max_month_share":.45},
 "novelty_gates":{"exact_entry_jaccard_max":.1,"candidate_near_6h_share_max":.35,"occupied_5m_bar_jaccard_max":.25,"absolute_signed_exposure_pearson_max":.35,"must_pass_before_economics":True},
 "economic_gates":{"absolute_return_positive":True,"cagr_to_strict_mdd_min":3.,"strict_mdd_max_pct":15.,"mean_gross_underlying_min_bp":20.,"weekly_signflip_one_sided_p_max":.1,"stress_absolute_return_positive":True,"stress_cagr_to_strict_mdd_min":2.5,"each_calendar_half_positive":True,"stop_on_first_failure":True,"accounting":"fixed quantity, exact funding, 6bp base and 10bp stress per notional side, every held 5m favorable then adverse, global HWM, full-calendar CAGR"},
 "post_stage_volatility_audit":{"prerequisite":"unchanged candidate passes all four stages","rv20_q90_entry_filter":False,"minimum_q90_trades":8,"candidate_q90_absolute_return_positive":True,"identical_clock_forced_long_residual_positive":True},
 "diagnostic_controls":{"names":["no_btc_variation_gate","three_of_six_breadth","median_alt_range_level","one_day_stale_breadth","direction_flip","forced_long"],"cannot_be_promoted":True},
 "source_plan":{"table":"bars_binance","symbols":["BTCUSDT",*ALTS],"interval":"1m","columns":["ts","symbol","open","high","low","close"],"query_window":["2023-04-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True,"execution_prices":"sealed until source support and Gross9 novelty pass"},
 "research_boundary":{"prior_cross_alt_range_return_and_volatility_outcomes_known":True,"repository_cross_alt_range_expansion_breadth_candidate_found":False,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"market-wide symbol-specific range-expansion breadth confirming BTC displacement"},
 "stopping_rule":"Terminal first failure; no symbol basket, range, history, rank, breadth, variation, side, hold, clock, subset, threshold, or control repair."};return {**core,"manifest_hash":canonical_hash(core)}
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();a.output.parent.mkdir(parents=True,exist_ok=True)
 if a.output.exists() and json.loads(a.output.read_text())!=x:raise RuntimeError(f"refusing overwrite {a.output}")
 a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(json.dumps({"output":str(a.output),"manifest_hash":x["manifest_hash"]}))
if __name__=="__main__":main()
