"""Outcome-blind preregistration for HVPVO-12."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
from training import preregister_high_volatility_ticket_elasticity_sponsorship_relay as template
POLICY_ID="HVPVO-12";DEFAULT_OUTPUT=Path("results/high_volatility_percentage_volume_oscillator_ignition_relay_preregistration_2026-08-11.json")
def canonical_hash(v:Any)->str:return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False,allow_nan=False).encode()).hexdigest()
def build()->dict[str,Any]:
 c=copy.deepcopy(template.build());c.pop("manifest_hash")
 c.update(protocol_version="high_volatility_percentage_volume_oscillator_ignition_relay_v1",policy_id=POLICY_ID,as_of_date="2026-08-11",
 mechanism={"claim":"During elevated realized variation, a completed four-hour canonical Percentage Volume Oscillator crossing above its signal identifies fresh participation acceleration; follow the completed four-hour price direction for twelve hours.","side":"strict sign of the completed four-hour close/open log return at a bullish PVO-signal crossover","why_distinct":"PVO divides the EMA(12)-EMA(26) base-volume spread by the positive slow volume EMA, then compares that scale-free participation rate with its EMA(9). It supplies no price direction itself and is distinct from price PPO, raw relative volume, ticket expansion, cumulative flow, PVT, OBV, OI, funding, fitted outcomes, reused event sets, and promoted controls.","why_suited_to_volatile_regimes":"completed trailing twenty-four-hour realized variation must rank in its causal upper 35%","why_low_gross9_overlap_is_plausible":"sparse four-hour volume-acceleration ignition clocks are absent from Gross9 primitives"},
 external_basis={"origin":"canonical Percentage Volume Oscillator convention","fixed_definition":"EMA(12) of volume minus EMA(26), divided by EMA(26) and multiplied by 100; EMA(9) signal; strict upward line crossover","selection_use":"published defaults 12,26,9, percentage normalization, and upward signal crossover only; BTC direction and holding application are untested; no incidence or outcomes"},
 features={"decision_grid":"every exact four-hour UTC boundary","source_bar":"exact aggregation of 240 coherent BTCUSDT one-minute rows [T-4h,T), including finite nonnegative base volume with strict positive completed sum","fast_ema":"causal EMA(12) of completed base volume using alpha=2/13, reset across gaps","slow_ema":"causal EMA(26) of completed base volume using alpha=2/27 and required strictly positive","pvo":"100*(fast volume EMA-slow volume EMA)/slow volume EMA","signal":"causal EMA(9) of PVO using alpha=2/10","event":"current PVO-signal is strictly positive and immediately prior finite PVO-signal is <=0","terminal_return":"log(completed four-hour close/open), finite strict nonzero","variation":"sqrt(sum squared completed one-minute open-to-close log returns over [T-24h,T)), finite strict positive","variation_rank":"strict-prior midrank over at most 180 earlier valid decisions, minimum 120, current excluded; rank>=0.65","no_imputation":True},
 clock={"feature_available":"four-hour boundary after completed source bar","entry":"exact BTCUSDT open five elapsed minutes later","side":"terminal_return sign","hold":"12 elapsed hours","reservation":"global half-open first-eligible reservation; exit first on equal open","gross_exposure":0.5,"funding":"not a signal input; exact settlements only after novelty passes"},
 policy={"fast_periods":12,"slow_periods":26,"signal_periods":9,"variation_hours":24,"variation_history_decisions":180,"minimum_variation_history_decisions":120,"variation_rank_min":0.65,"entry_delay_minutes":5,"hold_hours":12,"leverage":0.5,"base_cost_per_notional_side":0.0006,"stress_cost_per_notional_side":0.001},
 diagnostic_controls={"names":["no_variation_gate","zero_line_ignition","one_bar_stale_cross","direction_flip","forced_long"],"cannot_be_promoted":True},
 source_plan={"bars":{"table":"bars_binance","symbol":"BTCUSDT","interval":"1m","columns":["ts","open","high","low","close","volume"],"window":["2020-01-01T00:00:00Z","2026-08-01T00:00:00Z"],"read_after_preregistration":True},"execution_prices":"sealed until source support and Gross9 novelty pass"},
 research_boundary={"canonical_pvo_definition_read":True,"repository_pvo_candidate_found":False,"prior_price_and_volume_indicator_outcomes_known":True,"prior_event_sets_reused":False,"prior_candidate_outcomes_used_to_set_formula_side_hold_or_clock":False,"candidate_incidence_opened":False,"postentry_return_or_pnl_opened":False,"gross9_rows_opened":False,"candidate_count":1,"grid":False,"repair_of_prior_candidate":False,"promoted_prior_control":False,"selection_basis":"canonical PVO(12,26,9) upward signal crossover under the requested high-variation regime"},
 stopping_rule="Terminal first failure; no periods, smoothing convention, scaling, crossing, variation, side, hold, clock, subset, control, or other repair.")
 return {**c,"manifest_hash":canonical_hash(c)}
def validate(x:dict[str,Any])->None:
 core={k:v for k,v in x.items() if k!="manifest_hash"}
 if x.get("manifest_hash")!=canonical_hash(core) or x!=build():raise RuntimeError("HVPVO preregistration drift")
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);a=p.parse_args();x=build();validate(x);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+"\n");print(a.output)
